#define TORTENDLG                   150
#define IDCB_TORTENTYPEN            151
#define IDB_TORTENHILFE             153
#define IDCB_FEATURECODE            152
#define IDCB_OFFSET                 157
#define IDCB_SHOWVALUES             158
#define IDR_RELVALUES               160
#define IDR_ABSVALUES               161
#define IDB_COLORS                  163
#define IDB_FARBENHILFE             165
#define COLORSELDLG                 166
#define IDFT_COLOR1                 170
#define IDFT_COLOR2                 171
#define IDFT_COLOR3                 172
#define IDFT_COLOR4                 173
#define IDFT_COLOR5                 174
#define IDFT_COLOR6                 175
#define IDFT_COLOR7                 176
#define IDFT_COLOR8                 177
#define IDFT_COLOR9                 178
#define IDFT_COLOR10                179
#define IDFT_COLOR11                180
#define IDFT_COLOR12                181
#define IDFT_COLOR13                182
#define IDFT_COLOR14                183
#define IDFT_COLOR15                184
#define IDFT_COLOR16                185
#define IDB_SELECTOTHER             167
#define IDB_RESETCOLORS             168
#define IDT_TORTENPREVIEW           154
#define IDT_HELPTEXT                155
#define IDCB_COLORPALETTE           156
#define IDE_PALETTENAME             186
#define IDE_NUMDIGITS               169
#define IDCB_ENABLEROUNDING         187
#define IDT_PERCENTS                188
#define IDT_NUMDIGITS               189
#define IDE_DREHWINKEL              191
#define IDT_DREHWINKEL              390
