// Dispatch declarations for OGC interfaces
	[ uuid(9FCB86E0-D616-4C36-8916-76BE6B1FD7E7) ]
	dispinterface DGeometry 
	{ 
		interface IGeometry; 
	};

	[ uuid(9FCB86E1-D616-4C36-8916-76BE6B1FD7E7) ]
	dispinterface DPoint 
	{ 
		interface IPoint; 
	};

	[ uuid(9FCB86E2-D616-4C36-8916-76BE6B1FD7E7) ]
	dispinterface DPointZ 
	{ 
		interface IPointZ; 
	};

	[ uuid(9FCB86E3-D616-4C36-8916-76BE6B1FD7E7) ]
	dispinterface DCurve 
	{ 
		interface ICurve; 
	};

	[ uuid(9FCB86E4-D616-4C36-8916-76BE6B1FD7E7) ]
	dispinterface DLineString 
	{ 
		interface ILineString; 
	};

	[ uuid(9FCB86E5-D616-4C36-8916-76BE6B1FD7E7) ]
	dispinterface DLinearRing 
	{ 
		interface ILinearRing; 
	};

	[ uuid(9FCB86E6-D616-4C36-8916-76BE6B1FD7E7) ]
	dispinterface DSurface 
	{ 
		interface ISurface; 
	};

	[ uuid(9FCB86E7-D616-4C36-8916-76BE6B1FD7E7) ]
	dispinterface DPolygon 
	{ 
		interface IPolygon; 
	};

	[ uuid(9FCB86E8-D616-4C36-8916-76BE6B1FD7E7) ]
	dispinterface DGeometryCollection 
	{ 
		interface IGeometryCollection; 
	};

	[ uuid(9FCB86E9-D616-4C36-8916-76BE6B1FD7E7) ]
	dispinterface DMultiSurface 
	{ 
		interface IMultiSurface; 
	};

	[ uuid(9FCB86EA-D616-4C36-8916-76BE6B1FD7E7) ]
	dispinterface DMultiCurve 
	{ 
		interface IMultiCurve; 
	};

	[ uuid(9FCB86EB-D616-4C36-8916-76BE6B1FD7E7) ]
	dispinterface DMultiPoint 
	{ 
		interface IMultiPoint; 
	};

	[ uuid(9FCB86EC-D616-4C36-8916-76BE6B1FD7E7) ]
	dispinterface DSpatialRelation 
	{ 
		interface ISpatialRelation; 
	};

	[ uuid(9FCB86ED-D616-4C36-8916-76BE6B1FD7E7) ]
	dispinterface DSpatialRelation2 
	{ 
		interface ISpatialRelation2; 
	};

	[ uuid(9FCB86EE-D616-4C36-8916-76BE6B1FD7E7) ]
	dispinterface DSpatialOperator 
	{ 
		interface ISpatialOperator; 
	};

	[ uuid(9FCB86EF-D616-4C36-8916-76BE6B1FD7E7) ]
	dispinterface DWks 
	{ 
		interface IWks; 
	};
