//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Trias32.RC
//
#define IDB_PRINTERSELECTION            3
#define IDB_DETAILS                     3
#define IDHELP                          9
#define DBD050E                         12
#define IDI_INTERTRIASBLUE              47
#define IDI_INTERTRIASBLACK             48
#define LEGENDEDROPDOWNMENU             101
#define IDM_LEGENTRYEDITTEXT            102
#define IDM_LEGENTRYSHOWENTRY           103
#define IDB_SELECTVIEWHELP              103
#define LEGENTRYTEXTDLG                 104
#define IDM_SHOWALLENTRIES              105
#define IDD_EDITHEADER                  105
#define IDT_REGNUMBER                   105
#define IDM_LEGENTRYVISPARAMS           106
#define IDD_MANAGEEXT                   106
#define IDM_CANCELMENU                  106
#define IDM_LEGENTRYRESETTEXT           107
#define IDC_DROPSCALEUPPER              107
#define IDM_LEGENDRESET                 108
#define IDC_DROPSCALELOWER              108
#define IDB_INVPATTERN                  109
#define IDD_PRIORITY_SELECT             109
#define IDM_LEGENTRYMOVEUP              110
#define IDD_REGISTRYPROGRESS            110
#define IDM_LEGENTRYMOVEDOWN            111
#define BUCHICON                        111
#define IDD_COPYVISINFODLG              111
#define IDM_LEGENTRYREMOVEENTRY         112
#define LUPEICON                        112
#define IDD_PRINTLAYOUT                 112
#define IDM_LEGENDSAVE                  113
#define BUCHICON1                       113
#define IDM_ENTERSPACELINE              114
#define IDI_REFRESH_REGISTRY            114
#define IDM_REMOVESPACELINE             115
#define IDM_ADDTOLEGEND                 116
#define FILEOPEN40SUBDLG                116
#define IDM_REBUILD                     117
#define EXPORTFMT40SUBDLG               117
#define IDM_KOMPLOBJECTS                118
#define DELETEIDENTSDLG                 119
#define IDB_BITMAP_15_SW                119
#define IDM_DEFAULTVIEW                 120
#define IDB_BITMAP_20_SW                120
#define IDB_BITMAP_32_SW                121
#define IDM_LEGENDE_ANAUSSCHNITTANPASSEN 121
#define IDM_UNDO                        122
#define IDM_REDO                        123
#define IDM_SAVEAS                      124
#define IDM_PRINTPREVIEW                125
#define IDR_BMPOFFSETS15                126
#define IDM_OBJPROPERTIES               126
#define IDR_BMPOFFSETS23                127
#define IDM_COORDMODE                   127
#define IDR_BMPOFFSETS32                128
#define IDM_SELECTVIEWS                 128
#define IDR_PUNKTIDTABLE                129
#define IDM_SAVECOPYAS                  129
#define IDM_NEWENTRY                    131
#define IDM_FINDENTRY                   132
#define QUERYEXTENSIONNAME              133
#define IDM_DELETEENTRY                 133
#define UNDOREDOLIST                    134
#define IDM_RENAMEENTRY                 134
#define IDD_LICENSE                     135
#define IDM_COLLAPSE                    135
#define IDD_SELECTRECT                  136
#define IDM_EXPAND                      136
#define IDD_SELECTVIEW                  137
#define IDM_TOGGLERO                    137
#define IDC_TEXTSHIFTCURSOR             138
#define IDM_TEXTSEARCH_PP               138
#define ID_OBJMENU_COPY                 139
#define IDC_TEXTCOPYCURSOR              140
#define ID_OBJMENU_CUT                  140
#define ID_OBJMENU_PASTE                141
#define IDB_HEADERSTRIP                 143
#define ID_OBJMENU_SELECTALL            143
#define IDR_EDITHDRMENU                 144
#define ID_OBJMENU_REVERSESELECTION     144
#define IDB_PLFT                        147
#define IDM_OBJMENU_SEARCH              147
#define IDB_UP                          148
#define IDM_SIZESLIKESCALING            148
#define IDB_UP_SEL                      149
#define IDB_UP_FOCUS                    150
#define ID_OVERVIEW_RESETRECT           150
#define IDB_UP_DISABLED                 151
#define ID_OVERVIEW_ACTVIEW             151
#define IDB_DOWN                        152
#define ID_OVERVIEW_HIDE                152
#define IDB_DOWN_SEL                    153
#define IDB_DOWN_FOCUS                  154
#define IDM_GENTEXTOBJECTS              154
#define IDB_DOWN_DISABLED               155
#define IDM_COPYOBJECTS                 155
#define IDB_CATID_TOOLBITMAP            160
#define IDB_CATID_PLUGIN                161
#define IDR_OBJMENUACCEL                166
#define IDR_LEGMENUACCEL                167
#define IDR_OVERVIEW_DROPDOWN           169
#define IDR_AVI_REGISTER                170
#define DBD0510                         173
#define ID_GEOVIEW_PREVENT_REPAINT      206
#define IDM_RESTOREVIEWCONTAINER        221
#define IDE_LEGENTRYEDITTEXT            1000
#define IDSND_QUACK                     1002
#define IDBMP_STARTUP_T                 1003
#define IDB_ALLCLASSES                  1005
#define IDL_DELETEIDENTSLIST            1006
#define IDS_HEADERCAP                   1007
#define IDR_RECHRES_ONR                 1009
#define IDR_RECHRES_OTYP                1010
#define IDR_RECHRES_IDENT               1011
#define IDR_RECHRES_OBJPROP             1012
#define IDL_SHOWIDENTSLIST              1013
#define IDB_RECHRES_SELALL              1014
#define IDE_DESCRIPTION                 1015
#define IDC_BKCONTURE                   1019
#define IDB_INSTALL                     1020
#define IDB_REMOVE                      1022
#define IDE_EXTNAME                     1024
#define IDT_QUERYTEXT                   1025
#define IDR_EXPORTACTVIEW               1026
#define IDR_EXPORTALLOBJECTS            1027
#define IDE_ROTATION                    1027
#define IDC_IMPORTGEOMETRY              1028
#define IDCC_ROTATION                   1028
#define IDC_IMPORTFEATURES              1029
#define IDC_IMPORTRELATIONS             1030
#define IDS_SHORTCAPTION                1030
#define IDS_NORMALEXTENSIONS            1030
#define IDC_IMPORTVISUALISATION         1031
#define IDS_NONAME                      1031
#define IDB_CONFIG                      1032
#define IDS_COLUMNHEADER                1032
#define IDC_SHOWALL                     1033
#define IDL_UNDOREDOLIST                1034
#define IDR_VIEWNAME                    1035
#define IDS_POSTEXTATBASELINE           1035
#define IDR_DEFAULTVIEW                 1036
#define IDS_CATID_EXTENSION             1036
#define IDCB_VIEWNAMES                  1037
#define IDS_CATID_IMPORTFILTER          1037
#define IDS_CATID_GEOCOMPONENT          1038
#define IDC_IMPORTANSIOEM               1039
#define IDL_OBJPROPIDENTSLIST           1041
#define IDC_LICENSEKEY                  1042
#define IDS_NOWIN40                     1042
#define IDC_LICENSETEXT                 1043
#define IDS_LAYOUTPAGECAP               1043
#define IDS_ONPRINTERPORT               1044
#define IDS_CANTDOTHAT                  1045
#define IDC_LEGENDONLY                  1046
#define IDS_SEARCHCAP                   1046
#define IDC_SELECTVIEWLIST              1047
#define IDS_OBJNAMEKTEXT                1047
#define IDT_SELECTVIEW                  1048
#define IDS_OBJNAMELTEXT                1048
#define IDC_OPTIONS                     1049
#define IDS_OBJCLASSMCODE               1049
#define IDC_OBJPROPDESTWINDOW           1050
#define IDC_COLOR1                      1051
#define IDC_COLOR2                      1052
#define IDT_FARBAUSWAHL                 1054
#define IDS_OBJCLASSDESC_KT             1054
#define IDT_LINEWIDTH                   1055
#define IDS_OBJPROPINTERACTIVE          1055
#define IDT_CONTOURWIDTH                1056
#define IDT_PREVIEW                     1057
#define IDC_HEADERKEYS                  1058
#define IDC_HEADERENTRY                 1059
#define IDC_BUTTON1                     1060
#define IDC_NEWKEY                      1060
#define IDC_COORDSYS                    1060
#define IDC_TEST                        1060
#define IDC_COPYTOCLIPBOARD             1060
#define IDC_BUTTON2                     1061
#define IDC_DELETEKEY                   1061
#define IDC_READONLY                    1064
#define IDC_DEFINE                      1065
#define IDC_SETSCALE                    1066
#define IDC_SETSCALE_UPPER              1066
#define IDC_SETSCALE_LOWER              1067
#define IDC_UP                          1074
#define IDC_DOWN                        1075
#define IDC_PRIORITY                    1076
#define IDC_MOVEPRIO                    1078
#define IDC_SELECTDEST                  1079
#define IDC_RGBHSB_GROUP                1080
#define IDC_PROGRESS                    1081
#define IDC_SCALE_GROUP                 1081
#define IDC_REGISTERTEXT1               1082
#define IDC_REGISTERTEXT2               1084
#define IDC_REGISTERENDTEXT             1085
#define IDMS_PRINTFORMAT_X              1087
#define IDC_ACTFILENAME                 1088
#define IDC_UNDOREDODETAILS             1090
#define IDC_ANIMATE_GLOBE               1092
#define IDC_REGISTERTEXT                1093
#define IDS_EXPDESCEX                   1101
#define IDS_SEARCHCAP_OR                1107
#define IDS_UNDOOBJPROPFEATURE          1109
#define IDS_PROJECTEXTENSIONS           1129
#define IDS_SYSTEMEXTENSIONS            1131
#define IDS_COMPATIBILITY_16BIT         1133
#define IDS_OPENPROJECTCAP              1142
#define IDS_CATID_SELFREGISTER          1149
#define IDS_NOPROJECTEXTENSIONS         1150
#define IDS_NOSYSTEMEXTENSIONS          1151
#define IDS_LOADEXTERROR                1152
#define IDS_VIEWCOMMENT                 1184
#define IDS_ALLOBJECTS                  1203
#define IDS_OVERVIEW_RESETRECT          1204
#define IDS_OVERVIEW_ACTVIEW            1205
#define IDS_OVERVIEW_HIDE               1206
#define IDS_PROJECTISCOMPATIBEL         1207
#define IDS_UPPERSCALE                  1231
#define IDS_LOWERSCALE                  1232
#define IDS_P_SCALEVIEWMCODE            1233
#define IDS_OBJPROPPUNKTOBJ2            1251
#define IDS_L_SCALEVIEWMCODE            1256
#define IDS_A_SCALEVIEWMCODE            1262
#define IDS_T_SCALEVIEWMCODE            1264
#define IDS_P_SCALEVIEWMCODE_KT         1265
#define IDS_L_SCALEVIEWMCODE_KT         1266
#define IDS_A_SCALEVIEWMCODE_KT         1267
#define IDS_T_SCALEVIEWMCODE_KT         1268
#define IDS_NOSCALELIMIT                1269
#define IDS_OBJECTGUIDHDR               1270
#define IDS_OBJECTGUIDMCODE             1271
#define IDS_T_SCALEVIEWMCODELTEXT       1339
#define IDS_OBJPROPGUID                 1339
#define IDS_VIEWLEGINFOKURZTEXT         1353
#define IDS_VIEWLEGINFOLANGTEXT         1354
#define IDS_LEGENTRYSHOW                1355
#define IDS_LEGENTRYSHOWENTRY           1356
#define IDS_LEGENTRYREMOVE              1357
#define IDS_LEGENTRYREMOVEENTRY         1358
#define IDS_LEGENDRESET                 1359
#define IDS_LEGENDSAVE                  1360
#define IDS_ENTERSPACELINE              1361
#define IDS_REMOVESPACELINE             1362
#define IDS_NOVIEWNAME                  1363
#define IDS_READONLYPROJECT             1364
#define IDS_COMPLOBJINFO                1365
#define IDS_CAPTIONMCODE                1367
#define IDS_CAPTIONMCODEKTEXT           1368
#define IDS_CAPTIONMCODELTEXT           1369
#define IDS_DEFAULTVIEWCAP              1370
#define IDS_LEGENDCLIPBOARDFMT          1371
#define IDS_USEOLDPOINTSTYLE            1372
#define IDS_USENEWPOINTSTYLE            1373
#define IDS_REGEXEICON                  1374
#define IDS_EXPORTFMTDLGCAP             1375
#define IDS_HDRUNKNOWNIDENT             1376
#define IDS_KTUNKNOWNIDENT              1377
#define IDS_LTUNKNOWNIDENT              1378
#define IDS_LEGENDOFFSET                1379
#define IDS_PRNTLAYOUTCAPTION           1380
#define IDS_LEGENDAREAMODE              1381
#define IDS_AREAMODEKTEXT               1382
#define IDS_AREAMODELTEXT               1383
#define IDS_EXTENSIONTEMPLATE           1384
#define IDS_OBJPROPGUIDHELP             1384
#define IDS_LOADEXTCAPTION              1385
#define IDS_IMPORTFMTDLGCAP             1386
#define IDS_NOIMPORTFILTERS             1387
#define IDS_DELETEEXT                   1388
#define IDS_DELETEEXTCAP                1389
#define IDS_UNDONOTHING                 1390
#define IDS_REDONOTHING                 1391
#define IDS_UNDOTEMPL                   1392
#define IDS_REDOTEMPL                   1393
#define IDS_UNDOUNKNOWN                 1394
#define IDS_REDOUNKNOWN                 1395
#define IDS_UNDOEDITFEATURES            1396
#define IDS_REDOCAPTION                 1397
#define IDS_UNDOCAPTION                 1398
#define IDS_ONEACTION                   1399
#define IDS_ACTIONS                     1400
#define IDS_UNDODELETETEXT              1401
#define IDS_UNDOCREATETEXT              1402
#define IDS_UNDODELETEOBJECT            1403
#define IDS_LISTOUTOFSPACECAP           1404
#define IDS_LISTOUTOFSPACE              1405
#define IDS_EDITOUTOFSPACE              1406
#define IDS_BADREGISTRATION_CAP         1407
#define IDS_CTFTOSTRINGEX               1408
#define IDS_CTFTOVALUEEX                1409
#define IDS_SHORTCUTDESCTEMPLATE        1410
#define IDS_LICENSING                   1411
#define IDS_NOTLICENSED                 1412
#define IDS_STAND                       1413
#define IDS_OBJPROPPUNKTOBJSH           1413
#define IDS_OBJPROPKANTENOBJSH          1414
#define IDS_OBJPROPFLAECHENOBJSH        1415
#define IDS_OBJPROPTEXTOBJSH            1416
#define IDS_OBJPROPKOMPLEXOBJSH         1417
#define IDS_OBJPROPUNKNOWNOBJSH         1418
#define IDS_OBJPROPOBJTYPSHORT          1419
#define IDS_OBJPROPTYPHELPSHORT         1420
#define IDS_PRINTLAYOUTLEGENDEONLY      1421
#define IDM_MCODEFORMAT                 1422
#define IDS_IMPORTNOMULTISEL            1423
#define IDS_PROJECTCLOSEPAINTING        1424
#define IDS_MOREVIEWS                   1425
#define IDS_OBJPROPCAP                  1426
#define IDS_OBJPROPSTATUS               1427
#define IDS_EXPORTCAP                   1428
#define IDS_EXPORTSTATUS                1429
#define IDS_EXPORTOBJEKT                1430
#define IDS_INTERNOPROPGROUP            1431
#define IDS_SYSTEMPROPGROUP             1432
#define IDS_UNDOMODIFYTEXT              1433
#define IDS_UNDOMODIFYTEXTPOINT         1434
#define IDS_CTFDISTANCEEX               1435
#define IDS_BACKGROUNDCOLOR             1436
#define IDS_DBSAVEASTEMPLATE            1437
#define IDS_SAVEASDBCAPTION             1438
#define IDS_EMPTYMRU                    1439
#define IDS_DOCPROPS                    1440
#define IDS_PROJECTENTRIES              1441
#define IDS_SYSTEMENTRIES               1442
#define IDS_NOENTRIESAVAIL              1443
#define IDS_NEWENTRY                    1444
#define IDS_EXPAND                      1445
#define IDS_DUPHDRENTRIES_CAP           1446
#define IDS_DUPHDRENTRIES               1447
#define IDS_PROJECTISCOPY               1448
#define IDS_SHOWGKCOORDS                1449
#define IDS_TKINFO                      1450
#define IDS_REGISTEREDMSG               1451
#define IDS_UNREGISTEREDMSG             1452
#define IDS_COORDCANTCONFIG             1453
#define IDS_USEDBYOTHERS                1454
#define IDS_ISREADONLY                  1455
#define IDS_SAVEPROJECTCAP              1456
#define IDS_CHANGEDBYOTHERS             1457
#define IDS_SAVEDBASCOPYCAPTION         1458
#define IDS_CUSTOMIZE                   1459
#define IDS_CUSTEXTSCAP                 1460
#define IDS_VISPARAMCAP                 1461
#define IDS_VISDEFINE                   1462
#define IDS_VISDEFINENEW                1463
#define IDS_UNDOPRIORITY                1464
#define IDS_UNDOVISINFOPUNKT            1465
#define IDS_UNDOVISINFOLINIE            1466
#define IDS_UNDOVISINFOFLAECHE          1467
#define IDS_UNDOVISINFOTEXT             1468
#define IDS_UNDOVISINFODEFAULT          1469
#define IDS_UNDOMODIDENTS               1470
#define IDS_MODIDENTCAP                 1471
#define IDS_COORDFMTDLGCAP              1472
#define IDS_REGNR                       1473
#define IDS_NOTREGISTEREDVERSION        1474
#define IDS_NOTFORWIN32                 1475
#define IDS_UNDOCLIPSELENTRIES          1476
#define IDS_UNDOADDOBJECTS              1477
#define IDS_UNDODRAGDROPOBJECTS         1478
#define IDS_MODIDENTCAP_OR              1479
#define IDS_PRNTLAYOUTCAPTION_NOPRINTER 1481
#define IDS_OBJDELSTATUS                1482
#define IDS_UNDODELETEOBJ               1483
#define IDS_BADREGISTRATION             1484
#define IDS_OBJPROPOKSHELP              1485
#define IDS_TKMCODE                     1486
#define IDS_TKVCODE                     1487
#define IDS_ALLOWLEADINGZEROS           1488
#define IDS_EDITPROMPT                  1489
#define IDS_GENERATETEXT                1490
#define IDS_GENERATETEXT_OR             1491
#define IDS_OLDUNIQUEIDENT              1492
#define IDS_OLDUNIQUEIDENTKTEXT         1493
#define IDS_OLDUNIQUEIDENTLTEXT         1494
#define IDS_COPYOBJECTSCAP              1495
#define IDS_COPYOBJECTSCAP_OR           1496
#define EXPORTFMTDLG                    1537
#define PUNKTFARBSELEKTION_NEU          1538
#define MANAGEEXTENSIONS                1539
#define EXPORTFMT40SUBDLGOBJ            1540
#define IMPORTFMT40SUBDLG               1541
#define IMPORTFMTDLG                    1542
#define COPYVISINFODLG                  1543
#define OBJPROPIDENTDLG                 1544
#define OBJEKTE40                       1545
#define VISPARAMCTRLPAGE                1546
#define IDD_TRIAS_PROPPAGE_MEDIUM       1547
#define IDD_VISPARAMCTRLPAGE            1548
#define IDD_PRIORITY_SELECT_WIN32S      1549
#define IDD_OBJPROPIDENTDLG             1550
#define IDD_SELECTIDENTSDLG             1551
#define IDD_DELETEIDENTSDLG             1552
#define IDD_MODIFYIDENTSDLG             1553
#define IDD_REGISTRYPROGRESSEND         1554
#define IDD_UNDOREDODETAILS             1555
#define IDD_REGISTRYPROGRESS_AVI        1556
#define IDT_EDITTEXTPROMPT              2000
#define IDMS_PRINTFORMAT_Y              2654
#define BLINKEL                         3000
#define IDB_UNDOREDO_DETAILS            3001
#define IDB_CATID_SELFREGISTER          3002
#define IDS_ACCESSVIOLATION             4000
#define IDR_EDITHDRENTRYMENU            4001
#define IDS_DATATYPEMISALIGNMENT        4001
#define IDS_ARRAYBOUNDSEXCEEDED         4002
#define IDS_FLTDENORMALOPERAND          4003
#define IDS_FLTDIVIDEBYZERO             4004
#define IDS_FLTINEXACTRESULT            4005
#define IDS_FLTINVALIDOPERATION         4006
#define IDS_FLTOVERFLOW                 4007
#define IDS_FLTSTACKCHECK               4008
#define IDS_FLTUNDERFLOW                4009
#define IDS_INTDIVIDEBYZERO             4010
#define IDS_INTOVERFLOW                 4011
#define IDS_PRIVINSTRUCTION             4012
#define IDS_UNHANDLEDEXCEPTION          4013
#define IDS_UNHANDLEDEXCEPTION_CAPTION  4014
#define IDM_MRUDEFAULT                  7999
#define ID_ANZEIGE_STATUSLEISTE         40012
#define ID_ANZEIGE_SYMBOLLEISTEN        40013
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        176
#define _APS_NEXT_COMMAND_VALUE         156
#define _APS_NEXT_CONTROL_VALUE         1094
#define _APS_NEXT_SYMED_VALUE           110
#endif
#endif
