// $Header: $
// Copyright© 1998-2000 TRiAS GmbH Potsdam, All rights reserved
// Created: 25.02.2000 11:15:18 
//
// This file was generated by the TRiASDB Data Server Wizard V1.01.076 (#HK000225)
//
// @doc
// @module Strings.cpp | Definition of global string constants

#include "stdafx.h"
#include "strings.h"

///////////////////////////////////////////////////////////////////////////////
// sonstiges
const TCHAR g_cbNil[] = _T("");
const TCHAR g_cbRim[] = _T("rim");

///////////////////////////////////////////////////////////////////////////////
// Properties
const OLECHAR g_cbTRiASCSService[] = L"TRiASCSService";
const OLECHAR g_cbTRiASCSTransform[] = L"TRiASCSTransform";
const OLECHAR g_cbObjectsCursor[] = L"ObjectsCursor";
const OLECHAR g_cbObjectCursor[] = L"ObjectCursor";
const OLECHAR g_cbFeatureCursor[] = L"FeatureCursor";
const OLECHAR g_cbCSSGuid[] = L"CSSGuid";
const OLECHAR g_cbDatabaseEnvelope[] = L"DatabaseEnvelope";
const OLECHAR g_cbObjectMap[] = L"ObjectMap";
const OLECHAR g_cbObjectsMap[] = L"ObjectsMap";
const OLECHAR g_cbFeatureMap[] = L"FeatureMap";
const OLECHAR g_cbGenericMap[] = L"GenericMap";

/////////////////////////////////////////////////////////////////////////////
// SuchPattern für Objektklassenschlüssel
const TCHAR g_cbOKS[] = 
TEXT("\\[\\([[:xdigit:]]+\\)\\]" "\\|"							// [OKS]
	 "\\(\\([[:xdigit:]]+\\)[[:punct:][:blank:]].*\\)" "\\|"	// OKS:irgend was
	 "\\[\\([[:xdigit:]]+\\)\\]\\(.*\\)"  "\\|"					// [OKS]irgend was
	 "!\\(.*\\):\\[\\([[:xdigit:]]+\\)\\]\\(.*\\)"				// irgendwas![OKS]irgendwas (Monikerformat)
	);

/////////////////////////////////////////////////////////////////////////////
// Standardnamen für diverse Objekteigenschaften
const char g_cbGeometry[] = "Geometry";
const char g_cbObjektname[] = "Objektname";

///////////////////////////////////////////////////////////////////////////////
// Monikersupport
const TCHAR g_cbMkObjectsDef[] = TEXT("MkObjectsDef");
const TCHAR g_cbMkObjectDef[] = TEXT("MkObjectDef");
const TCHAR g_cbMkConnection[] = TEXT("MkConnection");
const TCHAR g_cbMkProject[] = TEXT("MkProject");
const TCHAR g_cbMkFeature[] = TEXT("MkFeature");
const OLECHAR g_cbMkDel[] =  L"!";
const OLECHAR g_cbMkWild[] = L"\\";

///////////////////////////////////////////////////////////////////////////////
// Datenbankzugriffe
const char g_cbVersion[] = "Version";

///////////////////////////////////////////////////////////////////////////////
// Globale Zeichenketten (nicht konstant)
TCHAR g_cbProjects[_MAX_PATH];

