#
# HISTORY
# 	Add uio calls: readv, writev.
# 	Make libdownhill installable.
# 	Put include guards around stdlib.h.
# 	[1997/05/21  07:35:46  tbartley]

DATAFILES	= in.h

INCLUDES	= ${DATAFILES}

EXPDIR		= /usr/include/netinet/
ILIST		= ${INCLUDES}
IDIR		= /include/netinet/

.include <${RULES_MK}>
