//
// Copyright (c) 1995, 1996 - Jon Seymour
//
// views.h - top level header file
//
// Permission to use, copy, modify, distribute and sell this software
// and its documentation for any purpose is hereby granted without fee,
// provided that this notice appears unmodified in all derivative
// works.
//
// The author makes no representations about the suitability of 
// this software for any purpose.  It is provided "as is" 
// without express or implied warranty.
//
// For more information about this software, refer to:
//
//   http://www.zeta.org.au/~jon/STL/views/doc/views.html
//
// Please send comments about this software to:
//
//   Jon Seymour (jon@zeta.org.au)
//

#ifndef _views_h
#define _views_h

#include <ospace\views\view.h>
#include <ospace\views\domain.h>
// #include <ospace\views\downcast.h>
#include <ospace\views\transform.h>
#include <ospace\views\predicate.h>
#include <ospace\views\mapview.h> 

#endif
