; Moduldefinitionsdatei fÅr PBD-Handling

DESCRIPTION	'TRIAS(R)-Erweiterung zur Anzeige diverser statistischer Informationen V@A.@B.@C, (C) #@D'

EXPORTS
        DllGetClassObject       = _DllGetClassObject@12         @1
        DllCanUnloadNow         = _DllCanUnloadNow@0            @2
        DllRegisterServer       = _DllRegisterServer@0          @3
        DllUnregisterServer     = _DllUnregisterServer@0        @4
