// $Header: $
// Copyright© 1999-2002 Geopunkt GmbH & Co. KG, NL Potsdam, All rights reserved
// Created: 20.03.2002 12:30:27 
//
// DO NOT EDIT -- this file is ALWAYS GENERATED !
//
// @doc
// @module OleAuto.hh | Declaration of the helpcontext constants for TRiAS

#if !defined(_OLEAUTO_HH__INCLUDED_)
#define _OLEAUTO_HH__INCLUDED_

#if _MSC_VER >= 1000
#pragma once
#endif // _MSC_VER >= 1000

// Header include diagnostics
#if defined(_TRIAS_DBG_HEADER_DIAGNOSTICS)
#pragma message(__TIME__": include " __FILE__ )
#endif

#define Application_obj 1
#define CREATEOBJECTWIN_enum 2
#define DApplication_ActiveDocument_prop 3
#define DApplication_AddObjectProperty_meth 4
#define DApplication_AddToolbar_meth 5
#define DApplication_Advise_meth 6
#define DApplication_Caption_prop 7
#define DApplication_CreateInstance_meth 8
#define DApplication_DefaultFilePath_prop 9
#define DApplication_Documents_prop 10
#define DApplication_FullName_prop 11
#define DApplication_GetDocument_meth 12
#define DApplication_GetExtension_meth 13
#define DApplication_GetToolBar_meth 14
#define DApplication_Height_prop 15
#define DApplication_int 16
#define DApplication_Interactive_prop 17
#define DApplication_Left_prop 18
#define DApplication_LoadExtension_meth 19
#define DApplication_Name_prop 20
#define DApplication_NewDocument_meth 21
#define DApplication_OpenDocument_meth 22
#define DApplication_Quit_meth 23
#define DApplication_RemoveObjectProperty_meth 24
#define DApplication_RemoveToolbar_meth 25
#define DApplication_RunScript_meth 26
#define DApplication_StartupPath_prop 27
#define DApplication_StatusBar_prop 28
#define DApplication_StopScript_meth 29
#define DApplication_Tag_prop 30
#define DApplication_Toolbars_prop 31
#define DApplication_Top_prop 32
#define DApplication_UnAdvise_meth 33
#define DApplication_UnloadExtension_meth 34
#define DApplication_Value_prop 35
#define DApplication_Version_prop 36
#define DApplication_VersionLong_prop 37
#define DApplication_Visible_prop 38
#define DApplication_Width_prop 39
#define DDocument_ActiveViewName_prop 40
#define DDocument_AddClass_meth 41
#define DDocument_AddObject_meth 42
#define DDocument_Author_prop 43
#define DDocument_ClassCount_prop 44
#define DDocument_CloseIt_meth 45
#define DDocument_Comments_prop 46
#define DDocument_Connections_prop 47
#define DDocument_CreateGeoObjectsCollection_meth 48
#define DDocument_FullName_prop 49
#define DDocument_GetClass_meth 50
#define DDocument_GetClasses_meth 51
#define DDocument_GetClassEx_meth 52
#define DDocument_GetGeoObjectWin_meth 53
#define DDocument_GetGeoObjectWins_meth 54
#define DDocument_GetHeaderEntry_meth 55
#define DDocument_GetHeaderEntry2_meth 56
#define DDocument_GetHeaderEntryEx_meth 57
#define DDocument_GetHeaderEntryEx2_meth 58
#define DDocument_GetObject_meth 59
#define DDocument_GetObjects_meth 60
#define DDocument_GetView_meth 61
#define DDocument_GetViewRect_meth 62
#define DDocument_GetViews_meth 63
#define DDocument_int 64
#define DDocument_IsDirty_prop 65
#define DDocument_Keywords_prop 66
#define DDocument_Name_prop 67
#define DDocument_ObjectCount_prop 68
#define DDocument_Path_prop 69
#define DDocument_PreventRepaint_prop 70
#define DDocument_ReadOnly_prop 71
#define DDocument_ReBuild_meth 72
#define DDocument_RefScale_prop 73
#define DDocument_Render_meth 74
#define DDocument_RePaint_meth 75
#define DDocument_RevertToSaved_meth 76
#define DDocument_Save_meth 77
#define DDocument_SaveAs_meth 78
#define DDocument_Saved_prop 79
#define DDocument_SetHeaderEntry_meth 80
#define DDocument_SetHeaderEntry2_meth 81
#define DDocument_SetHeaderEntryEx_meth 82
#define DDocument_SetHeaderEntryEx2_meth 83
#define DDocument_SetViewRect_meth 84
#define DDocument_Subject_prop 85
#define DDocument_Tag_prop 86
#define DDocument_Title_prop 87
#define DDocument_Value_prop 88
#define DDocument_ViewCount_prop 89
#define DDocuments_int 90
#define DGeoClass_Code_prop 91
#define DGeoClass_Connection_prop 92
#define DGeoClass_FullName_prop 93
#define DGeoClass_GetFeature_meth 94
#define DGeoClass_GetFeatures_meth 95
#define DGeoClass_GetObject_meth 96
#define DGeoClass_GetObjectFeature_meth 97
#define DGeoClass_GetObjectFeatures_meth 98
#define DGeoClass_GetObjects_meth 99
#define DGeoClass_GetObjectsInRect_meth 100
#define DGeoClass_GetViews_meth 101
#define DGeoClass_GetVisInfo_meth 102
#define DGeoClass_int 103
#define DGeoClass_IsQueryDef_prop 104
#define DGeoClass_Name_prop 105
#define DGeoClass_ResetVisInfo_meth 106
#define DGeoClass_SetVisInfo_meth 107
#define DGeoClass_Updatable_prop 108
#define DGeoClass_Value_prop 109
#define DGeoClasses_int 110
#define DGeoDocument_QueryObjects_meth 111
#define DGeoFeature_ConfigData_prop 112
#define DGeoFeature_Feature_prop 113
#define DGeoFeature_Flags_prop 114
#define DGeoFeature_FullName_prop 115
#define DGeoFeature_GetClasses_meth 116
#define DGeoFeature_GetObjects_meth 117
#define DGeoFeature_GetViews_meth 118
#define DGeoFeature_int 119
#define DGeoFeature_Name_prop 120
#define DGeoFeature_Value_prop 121
#define DGeoFeatures_int 122
#define DGeoObject_Activated_prop 123
#define DGeoObject_AddFeature_meth 124
#define DGeoObject_AnalyzeGeometry_meth 125
#define DGeoObject_AnalyzeGeometryObject_meth 126
#define DGeoObject_ClassDistance_meth 127
#define DGeoObject_CloneObject_meth 128
#define DGeoObject_Connection_prop 129
#define DGeoObject_CreateObjectRelation_meth 130
#define DGeoObject_Feature_prop 131
#define DGeoObject_GeometryIntersection_meth 132
#define DGeoObject_GeometryUnion_meth 133
#define DGeoObject_GeometryXOR_meth 134
#define DGeoObject_GetBufferObjectEx_meth 135
#define DGeoObject_GetBufferObjects_meth 136
#define DGeoObject_GetCircleBufferObjects_meth 137
#define DGeoObject_GetCommonContourObjects_meth 138
#define DGeoObject_GetFeature_meth 139
#define DGeoObject_GetFeatures_meth 140
#define DGeoObject_GetGeometry_meth 141
#define DGeoObject_GetGeometryCS_meth 142
#define DGeoObject_GetGeometryPt_meth 143
#define DGeoObject_GetGeometryPtCS_meth 144
#define DGeoObject_GetGeometryRect_meth 145
#define DGeoObject_GetGeometryRectCS_meth 146
#define DGeoObject_GetIntersectObjects_meth 147
#define DGeoObject_GetIntersectObjectsClass_meth 148
#define DGeoObject_GetIntersectObjectsCollection_meth 149
#define DGeoObject_GetRelatedObject_meth 150
#define DGeoObject_GetText_meth 151
#define DGeoObject_GetTopRelationObjects_meth 152
#define DGeoObject_GetVisInfo_meth 153
#define DGeoObject_Guid_prop 154
#define DGeoObject_Hilight_meth 155
#define DGeoObject_int 156
#define DGeoObject_MakeRectangular_meth 157
#define DGeoObject_Name_prop 158
#define DGeoObject_ObjClass_prop 159
#define DGeoObject_ObjDistance_meth 160
#define DGeoObject_ObjType_prop 161
#define DGeoObject_OldUniqueID_prop 162
#define DGeoObject_PutGeometry_meth 163
#define DGeoObject_PutGeometryCS_meth 164
#define DGeoObject_PutGeometryPt_meth 165
#define DGeoObject_PutGeometryPtCS_meth 166
#define DGeoObject_PutText_meth 167
#define DGeoObject_RemoveFeature_meth 168
#define DGeoObject_RemoveObjectRelation_meth 169
#define DGeoObject_RePaint_meth 170
#define DGeoObject_ResetVisInfo_meth 171
#define DGeoObject_Selected_prop 172
#define DGeoObject_SetVisInfo_meth 173
#define DGeoObject_ShiftGeometrySegment_meth 174
#define DGeoObject_TopRelation_meth 175
#define DGeoObject_UnHilight_meth 176
#define DGeoObject_UniqueID_prop 177
#define DGeoObject_Value_prop 178
#define DGeoObject_Visible_prop 179
#define DGeoObjects__GeometryLinesUnion_meth 180
#define DGeoObjects_CreateGeoObjectWin_meth 181
#define DGeoObjects_Difference_meth 182
#define DGeoObjects_GeometryIntersection_meth 183
#define DGeoObjects_GeometryUnion_meth 184
#define DGeoObjects_GetObjectsInRect_meth 185
#define DGeoObjects_int 186
#define DGeoObjects_Intersection_meth 187
#define DGeoObjects_MakeGeoClass_meth 188
#define DGeoObjects_SymmetricDifference_meth 189
#define DGeoObjects_Union_meth 190
#define DGeoObjectWin_int 191
#define DGeoObjectWins_ActGeoObjectWin_prop 192
#define DGeoObjectWins_int 193
#define DObjectProperty_int 194
#define DOCMODE_enum 195
#define DSearchAbleObjectProperty_int 196
#define DTRiASBaseClass_Application_prop 197
#define DTRiASBaseClass_int 198
#define DTRiASBaseClass_isA_prop 199
#define DTRiASBaseClass_Parent_prop 200
#define DTRiASCollection_Add_meth 201
#define DTRiASCollection_Count_prop 202
#define DTRiASCollection_int 203
#define DTRiASCollection_Item_meth 204
#define DTRiASCollection_Refresh_meth 205
#define DTRiASCollection_Remove_meth 206
#define DView_Description_prop 207
#define DView_GetActRect_meth 208
#define DView_GetClass_meth 209
#define DView_GetClasses_meth 210
#define DView_GetClipObject_meth 211
#define DView_GetConstraintRect_meth 212
#define DView_GetFeature_meth 213
#define DView_GetFeatures_meth 214
#define DView_GetObject_meth 215
#define DView_GetObjects_meth 216
#define DView_GetObjectsInRect_meth 217
#define DView_int 218
#define DView_Name_prop 219
#define DView_RefScale_prop 220
#define DView_ResetClipObject_meth 221
#define DView_Scale_prop 222
#define DView_SetActRect_meth 223
#define DView_SetClipObject_meth 224
#define DView_SetConstraintRect_meth 225
#define DView_Value_prop 226
#define DViews_int 227
#define DWriteAbleObjectProperty_int 228
#define FEATUREMODE_enum 229
#define FEATURESEARCHMODE_enum 230
#define FEATURESEARCHQUALIFIER_enum 231
#define GeoClass_obj 232
#define GeoClasses_obj 233
#define GEOCLASSMODE_enum 234
#define GeoDocument_obj 235
#define GeoDocuments_obj 236
#define GeoFeature_obj 237
#define GeoFeatures_obj 238
#define GeoObject_obj 239
#define GEOOBJECTMODE_enum 240
#define GeoObjects_obj 241
#define GeoObjectWin_obj 242
#define GeoObjectWins_obj 243
#define GEOOBJWINMODE_enum 244
#define GeoView_obj 245
#define GeoViews_obj 246
#define HEADERFLAG_enum 247
#define IGeoComponent_BeginAction_meth 248
#define IGeoComponent_Callback_prop 249
#define IGeoComponent_DoAction_meth 250
#define IGeoComponent_EndAction_meth 251
#define IGeoComponent_HasDataOut_prop 252
#define IGeoComponent_InitFromData_meth 253
#define IGeoComponent_int 254
#define IGeoComponent_PageCount_prop 255
#define IGeoComponent_PageProgId_prop 256
#define IGeoComponent_PreConfigAction_meth 257
#define IGeoComponent_ReadProperties_meth 258
#define IGeoComponent_WriteProperties_meth 259
#define IGeoComponentCallback_ContextData_prop 260
#define IGeoComponentCallback_int 261
#define IGeoComponentCallback_IsSequence_prop 262
#define IGeoComponentUI_AllowNextPage_prop 263
#define IGeoComponentUI_Callback_prop 264
#define IGeoComponentUI_int 265
#define IGeoComponentUI_OnActivate_meth 266
#define IGeoComponentUI_OnBack_meth 267
#define IGeoComponentUI_OnNext_meth 268
#define IGeoComponentUI_TranslateAccelerator_meth 269
#define IGeoComponentUICallback_int 270
#define IGeoComponentUICallback_OnStatusChange_meth 271
#define IGeoComponentUICallback_TranslateAccelerator_meth 272
#define IProgressIndicator2_Canceled_prop 273
#define IProgressIndicator2_ChangeText_meth 274
#define IProgressIndicator2_Flags_prop 275
#define IProgressIndicator2_Hide_meth 276
#define IProgressIndicator2_IncrementPosition_meth 277
#define IProgressIndicator2_InitNew_meth 278
#define IProgressIndicator2_IsCanceled_meth 279
#define IProgressIndicator2_Restart_meth 280
#define IProgressIndicator2_RetrieveRange_meth 281
#define IProgressIndicator2_RetrieveText_meth 282
#define IProgressIndicator2_SetPosition_meth 283
#define IProgressIndicator2_Show_meth 284
#define IPropertySequenceService_ContextData_prop 285
#define IPropertySequenceService_ResourceModule_prop 286
#define IPropertySequenceService_RunActionSequence_meth 287
#define IPropertySequenceService_RunActionSequenceFromFile_meth 288
#define MODGEOMETRYMODE_enum 289
#define OBJECTTYPE_enum 290
#define OBJOPERMODE_enum 291
#define OPENMODE_enum 292
#define PROPERTYCAPS_enum 293
#define RTTI_enum 294
#define TOPRELATION_enum 295
#define VIEWMODE_enum 296

#endif // !defined(_OLEAUTO_HH__INCLUDED_)
