// $Header: $
// Copyright© 1998-$$year$$ $$company$$, All rights reserved
// Created: $$date_n_time$$
//
// This file was generated by the TRiASDB Data Server Wizard $$this_version$$
//
$$IF(EMIT_WARRANTIES)
// THIS CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT WARRANTY OF ANY 
// KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
// IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A PARTICULAR 
// PURPOSE.
//
$$ENDIF // EMIT_WARRANTIES
// @doc 
// @module $$root$$Engine.h | Databaseengine für TRiASDB Data Server $$root$$

#if !defined(_$$SAFE_ROOT$$DBENGINE_H__$$GUID_DBENGINE_H$$__INCLUDED_)
#define _$$SAFE_ROOT$$DBENGINE_H__$$GUID_DBENGINE_H$$__INCLUDED_

#if _MSC_VER >= 1000
#pragma once
#endif // _MSC_VER >= 1000

// Header include diagnostics
#if defined(_TRIAS_DBG_HEADER_DIAGNOSTICS)
#pragma message(__TIME__": include " __FILE__ )
#endif

#include "resource.h"       // main symbols
#include "CP$$safe_root$$DBEngineEvents.h"

/////////////////////////////////////////////////////////////////////////////
// C$$safe_root$$DBEngine
class ATL_NO_VTABLE C$$safe_root$$DBEngine : 
	public CComObjectRootEx<CComObjectThreadModel>,
	public CErrSupport<C$$safe_root$$DBEngine, &IID_ITRiASDBEngine>,
	public CComCoClass<C$$safe_root$$DBEngine, &CLSID_$$safe_root$$DBEngine>,
	public IConnectionPointContainerImpl<C$$safe_root$$DBEngine>,
	public CProxyITRiASDBEngineEvents<C$$safe_root$$DBEngine>,
	public IDispatchImpl<ITRiASDBEngine, &IID_ITRiASDBEngine, &LIBID_TRiASDB,
		TYPELIB_TRiASDB_VERSION_MAJOR, TYPELIB_TRiASDB_VERSION_MINOR>
{
public:
	C$$safe_root$$DBEngine()
		: m_fIsStarted(false),
		  m_bstrUserName(g_cbNil), m_bstrPassword(g_cbNil)
	{
	}

$$IF(EMIT_OBJECTCOUNT_DEBUG)
	_ATLX_DEBUG_OBJECTCOUNT_IMPL(C$$safe_root$$DBEngine)
$$ENDIF // IF(EMIT_OBJECTCOUNT_DEBUG)

	DECLARE_REGISTRY_RESOURCEID(IDR_$$SAFE_ROOT$$DBENGINE_RGS)
	DECLARE_PROTECT_FINAL_CONSTRUCT()
	DECLARE_CLASSFACTORY_SINGLETON(C$$safe_root$$DBEngine)	// DBEngines existieren nur einmal

	BEGIN_COM_MAP(C$$safe_root$$DBEngine)
		COM_INTERFACE_ENTRY(ITRiASDBEngine)
		COM_INTERFACE_ENTRY(ISupportErrorInfo)
		COM_INTERFACE_ENTRY(IDispatch)
	END_COM_MAP()

	BEGIN_CONNECTION_POINT_MAP(C$$safe_root$$DBEngine)
		CONNECTION_POINT_ENTRY(IID_ITRiASDBEngineEvents)
	END_CONNECTION_POINT_MAP()

	HRESULT FinalConstruct();
	void FinalRelease();

// ISupportsErrorInfo
	STDMETHOD(InterfaceSupportsErrorInfo)(REFIID riid);

// ITRiASDBEngine
public:
	STDMETHOD(get_Version)(BSTR *pVal);
	STDMETHOD(put_Password)(BSTR bstrPwd);
	STDMETHOD(put_UserName)(BSTR bstrUser);
	STDMETHOD(get_Description)(BSTR *pVal);

	STDMETHOD(Start)(STARTMODE Mode);
	STDMETHOD(EnumDataBaseTypes)(IUnknown **ppIEnum);
	STDMETHOD(Stop)();

public:
// Konvertieren Blob <--> _DGMGeometry
	HRESULT StorageToGeometry (const VARIANT &Blob, GEOMETRYTYPE *prgType, IDispatch **ppIGeometry) throw(_com_error &)
	{
		_ASSERTE(m_Service.IsValid());
		return m_Service -> StorageToGeometry (Blob, prgType, ppIGeometry);
	}
	HRESULT GeometryToStorage (GEOMETRYTYPE rgType, IDispatch *pIGeometry, VARIANT *pBlob) throw(_com_error &)
	{
		_ASSERTE(m_Service.IsValid());
		return m_Service -> GeometryToStorage (rgType, pIGeometry, pBlob);
	}

private:
	bool m_fIsStarted;			// Engine wurde gestartet
	CComBSTR m_bstrUserName;	// Nutzername (optional)
	CComBSTR m_bstrPassword;	// Paßword (optional)

	WTRiASCSStorageService m_Service;	// Service für Geometrieoperationen
};

/////////////////////////////////////////////////////////////////////////////
// globale Instanz der DBEngine
extern C$$safe_root$$DBEngine *g_pDBEngine;
extern STARTMODE g_rgStartMode;

#endif // !defined(_$$SAFE_ROOT$$DBENGINE_H__$$GUID_DBENGINE_H$$__INCLUDED_)
