// $Header: $
// Copyright© 1998-$$year$$ $$company$$, All rights reserved
// Created: $$date_n_time$$ 
//
// This file was generated by the TRiASDB Data Server Wizard $$this_version$$
//
$$IF(EMIT_WARRANTIES)
// THIS CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT WARRANTY OF ANY 
// KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
// IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A PARTICULAR 
// PURPOSE.
//
$$ENDIF // EMIT_WARRANTIES
// @doc
// @module $$root$$SmartIFs.cpp | Definition of required smart interface classes

#if !defined(_$$SAFE_ROOT$$SMARTIFS_H__$$GUID_SMARTIFS_H$$__INCLUDED_)
#define _$$SAFE_ROOT$$SMARTIFS_H__$$GUID_SMARTIFS_H$$__INCLUDED_

#if _MSC_VER >= 1000
#pragma once
#endif // _MSC_VER >= 1000

///////////////////////////////////////////////////////////////////////////////
// SmartIF's

DefineSmartInterface(Dispatch);
DefineSmartInterface(PersistStreamInit);
DefineSmartInterface(Moniker);
DefineSmartInterface(ObjectWithSite);

DefineSmartInterface(TRiASConnection);
DefineSmartInterface(TRiASPropertyBase);
DefineSmartInterface(TRiASProperties);
DefineSmartInterface(TRiASProperty);
DefineSmartInterface(TRiASPropertyCallback);
DefineSmartInterface(TRiASDatabase);
DefineSmartInterface(TRiASObjectsCollection);
DefineSmartInterface(TRiASObjects);
DefineSmartInterface(TRiASObject);
DefineSmartInterface(TRiASObjectHandleMap);
DefineSmartInterface(TRiASFeatures);
DefineSmartInterface(TRiASFeature);

DefineSmartInterface(TRiASCS);
DefineSmartInterface(TRiASCSGCS);
DefineSmartInterface(TRiASCSDatumTransformation);
DefineSmartInterface(TRiASCSStorageService);
DefineSmartInterface(TRiASCSTransform);
DefineSmartInterface(TRiASCSGeometryProperties);
DefineSmartInterface(TRiASTransformGeometry);
DefineSmartInterface(TRiASCloneGeometry);		

DefineSmartInterface(TRiASSimpleRectangle);

$$IF(EMIT_SAMPLE_CODE)
$$IF(READ_WRITE)
// BEGIN_SAMPLE_CODE
DefineSmartInterface(TRiASPropertyMapHandler);
// END_SAMPLE_CODE
$$ENDIF // $$IF(READ_WRITE)
$$ENDIF // $$IF(EMIT_SAMPLE_CODE)

#endif // defined(_$$SAFE_ROOT$$SMARTIFS_H__$$GUID_SMARTIFS_H$$__INCLUDED_)



