// $Header: $
// Copyright© 1998-$$year$$ $$company$$, All rights reserved
// Created: $$date_n_time$$
//
// This file was generated by the TRiASDB Data Server Wizard $$this_version$$
//
$$IF(EMIT_WARRANTIES)
// THIS CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT WARRANTY OF ANY 
// KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
// IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A PARTICULAR 
// PURPOSE.
//
$$ENDIF // EMIT_WARRANTIES
// @doc
// @module StdAfx.h | include file for standard system include files,
// or project specific include files that are used frequently,
// but are changed infrequently

#if !defined(_STDAFX_H__$$GUID_STDAFX_H$$__INCLUDED_)
#define _STDAFX_H__$$GUID_STDAFX_H$$__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000

#include "$$root$$Config.h"
#include <TRiASConfig.h>

#if defined(__MFC_USED__)
#include <afxwin.h>
#include <afxdisp.h>
#endif // defined(__MFC_USED__)

///////////////////////////////////////////////////////////////////////////////
// ospace-STL specific stuff
namespace ospace { namespace std { namespace rel_ops {} } }
using namespace ospace::std;
using namespace ospace::std::rel_ops;

#include <ospace/std/string>
typedef os_string string;

#include <ospace/std/list>
#include <ospace/std/map>

///////////////////////////////////////////////////////////////////////////////
// ATL-related stuff 
#include <atlbase.h>
//You may derive a class from CComModule and use it if you want to override
//something, but do not change the name of _Module
extern CComModule _Module;
#include <atlcom.h>
#include <atlctl.h>

#include <Atl/Ciid.h>
#include <Atl/AtlAggregate.h>
$$IF(EMIT_OBJECTCOUNT_DEBUG)
#include <Atl/DebugObjectCount.h>	// count objects in debug builds
$$ENDIF // IF(EMIT_OBJECTCOUNT_DEBUG)

///////////////////////////////////////////////////////////////////////////////
// Interfacewrapper und Fehlerbehandlung
#include <Com/Iterenum.h>
#include <Com/ComErrorMacros.h>
#include <Com/ErrorMacros2.h>

///////////////////////////////////////////////////////////////////////////////
// Fehlercodes
#include <DBMsg.hmc>
#include "DBUtil.h"

///////////////////////////////////////////////////////////////////////////////
// diverse Objekte/Interfaces, auf die Bezug genommen wird
#include <GMObjects/PBasic.tlh>		// GeoMedia-Geometrieobjekte

#pragma warning (disable: 4192)		// automatically excluding 'symbol' while importing type library
#import "tlb/TRiASDB.tlb" raw_interfaces_only, raw_native_types, no_namespace, named_guids
#import "tlb/TRiASCS.tlb" raw_interfaces_only, raw_native_types, no_namespace, named_guids
#import "tlb/TDBGeo.tlb" raw_interfaces_only, raw_native_types, no_namespace, named_guids

#include <TRiASDBModuleStrings.h>
#include <TRiASDBGuids.h>

///////////////////////////////////////////////////////////////////////////////
// sonstiges
#include <Com/PropertyHelper.h>
#include <Com/SafeArray.h>

$$IF(EMIT_SAMPLE_CODE)
// BEGIN_SAMPLE_DATA
#include "SampleDataTypes.h"
// END_SAMPLE_DATA
$$ENDIF

// Smart interface classes
#include "$$root$$SmartIFs.h"

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(_STDAFX_H__$$GUID_STDAFX_H$$__INCLUDED)
