// $Header: $
// Copyright© 1998-$$year$$ $$company$$, All rights reserved
// Created: $$date_n_time$$
//
// This file was generated by the TRiASDB Data Server Wizard $$this_version$$
//
$$IF(EMIT_WARRANTIES)
// THIS CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT WARRANTY OF ANY 
// KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
// IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A PARTICULAR 
// PURPOSE.
//
$$ENDIF // EMIT_WARRANTIES
// @doc
// @module Version.h | Versionen dieses Modules

#if !defined(_VERSION_H__$$GUID_VERSION_H$$__INCLUDED_)
#define _VERSION_H__$$GUID_VERSION_H$$__INCLUDED_

#if _MSC_VER >= 1000
#pragma once
#endif // _MSC_VER >= 1000

// VersionsInfo des DataServers
#define $$SAFE_ROOT$$_VERSION	"@A"
#define $$SAFE_ROOT$$_RELEASE	"@B"
#define $$SAFE_ROOT$$_BUILD		"@C"

// VersionsInfo der $$safe_root$$Database
#define $$SAFE_ROOT$$_VERSION_MAJOR	@A
#define $$SAFE_ROOT$$_VERSION_MINOR	@B

#endif // !defined(_VERSION_H__$$GUID_VERSION_H$$__INCLUDED_)
