/*----------------------------------------------------------------------------+
| LEADTOOLS for Windows -                                                     |
| Copyright (c) 1991-2000 LEAD Technologies, Inc.                             |
| All Rights Reserved.                                                        |
|-----------------------------------------------------------------------------|
| PROJECT   : LEAD wrappers                                                   |
| FILE NAME : tcprnt.h                                                        |
| DESC      :                                                                 |
+----------------------------------------------------------------------------*/

#ifndef  _LEAD_WRAPPER_ENUMS_H_
#define  _LEAD_WRAPPER_ENUMS_H_

/*----------------------------------------------------------------------------+
| ENUMS                                                                       |
+----------------------------------------------------------------------------*/

//--LBITMAP CHANGE NOTIFICATIONS-----------------------------------------------
typedef enum tagCHANGENOTIFICATIONS
{
   NC_RECTS_SRC_RECT=1,
   NC_RECTS_CLIPSRC_RECT,
   NC_RECTS_DST_RECT,
   NC_RECTS_CLIPDST_RECT,
   NC_BITMAP_BITMAPHANDLE,
   NC_BITMAP_ALLOC,
   NC_BITMAP_COPY,
   NC_BITMAP_DATA,
   NC_BITMAP_COPYHANDLE,
   NC_BITMAP_CREATE,
   NC_BITMAP_SET_DATA_POINTER,
   NC_BITMAP_CREATEALPHA,
   NC_BITMAP_INITIALIZE,
   NC_BITMAP_COLOR_MERGE,
   NC_BITMAP_TOGGLE_COMPRESSION,
   NC_REGION_FREE_REGION,
   NC_REGION_OFFSET_REGION,
   NC_REGION_SET_REGION,
   NC_REGION_RESIZE_REGION,
   NC_FREE_FREE,
   NC_FREE_CHANGE_TO_DIB,
   NC_FREE_CHANGE_TO_DDB,
   NC_ACCESS_ACCESS,
   NC_ACCESS_RELEASE,
   NC_EDIT_CLEAR,
   NC_EDIT_COMBINE,
   NC_EDIT_COMBINEWARP,
   NC_EDIT_COPYRECT,
   NC_EDIT_PUTROW,
   NC_EDIT_PUTROWCOL,
   NC_EDIT_PUTROWCOMP,
   NC_EDIT_PUTROWCOLCOMP,
   NC_EDIT_GRAY,
   NC_EDIT_PUTCOLORS,
   NC_EDIT_PIXELCOLOR,
   NC_EDIT_SETALPHA,
   NC_EDIT_COLORRES,
   NC_EDIT_FILL,
   NC_EDIT_UNDERLAY,
   NC_EDIT_REMAP_INTENSITY,
   NC_EDIT_PICTURIZE,
   NC_EDIT_WINDOW_LEVEL,
   NC_EDIT_CLEAR_NEGATIVE_PIXELS,
   NC_EDIT_WINDOW_LEVEL_BITMAP,
   NC_EDIT_SET_PAINT_CONTRAST,
   NC_EDIT_SET_PAINT_INTENSITY,
   NC_EDIT_SET_PAINT_GAMMA,
   NC_EDIT_GRAY_EXT,
   NC_EDIT_COLORED_GRAY,
   NC_EDIT_BALANCE_COLORS,
   NC_EDIT_SWAP_COLORS,
   NC_EDIT_ADD,
   NC_EDIT_REMOVE_REDEYE,
   NC_EDIT_ALPHA_BLEND,
   NC_EDIT_FEATHER_ALPHA_BLEND,
   NC_EDIT_ADD_BORDER,
   NC_EDIT_ADD_FRAME,
   NC_EDIT_PIXELDATA,
   NC_EDIT_SIGNED_TO_UNSIGNED,
   NC_EDIT_CHANGE_COMPRESSION,
   NC_TRANSFORM_ROTATE_VIEW_PERSPECTIVE,
   NC_TRANSFORM_VIEW_PERSPECTIVE,
   NC_TRANSFORM_FLIP,
   NC_TRANSFORM_REVERSE,
   NC_TRANSFORM_ROTATE,
   NC_TRANSFORM_SHEAR,
   NC_TRANSFORM_TRANSLATE,
   NC_TRANSFORM_SCALE,
   NC_DIM_HEIGHT,
   NC_DIM_TRIM,
   NC_DIM_SIZE,
   NC_DIM_RESAMPLE,
   NC_DITHERING_START_DITHERING,
   NC_DITHERING_DITHERING,
   NC_DITHERING_STOP_DITHERING,
   NC_FILTER_AUTOTRIM,
   NC_FILTER_HALFTONE,
   NC_FILTER_ADDNOISE,
   NC_FILTER_AVERAGE,
   NC_FILTER_BINARY,
   NC_FILTER_CONTRAST,
   NC_FILTER_HUE,
   NC_FILTER_INTENSITY,
   NC_FILTER_SATURATION,
   NC_FILTER_DESKEW,
   NC_FILTER_DESPECKLE,
   NC_FILTER_SMOOTH,
   NC_FILTER_LINEREMOVE,
   NC_FILTER_DOTREMOVE,
   NC_FILTER_INVERTEDTEXT,
   NC_FILTER_BORDERREMOVE,
   NC_FILTER_HOLEPUNCHREMOVE,
   NC_FILTER_EMBOSS,
   NC_FILTER_GAMMA_CORRECT,
   NC_FILTER_INVERT,
   NC_FILTER_HISTO_CONTRAST,
   NC_FILTER_HISTO_EQUALIZE,
   NC_FILTER_INTENSITY_DETECT,
   NC_FILTER_MAX,
   NC_FILTER_MEDIAN,
   NC_FILTER_MIN,
   NC_FILTER_OILIFY,
   NC_FILTER_POSTERIZE,
   NC_FILTER_SOLARIZE,
   NC_FILTER_SPATIAL,
   NC_FILTER_STRETCH_INTENSITY,
   NC_FILTER_GRADIENT,
   NC_FILTER_LAPLACIAN,
   NC_FILTER_SOBEL,       
   NC_FILTER_PREWITT ,
   NC_FILTER_SHIFTDIFF,
   NC_FILTER_LINESEG,
   NC_FILTER_EROSION,
   NC_FILTER_DILATION,
   NC_FILTER_SHARPEN,
   NC_FILTER_BRIGHTNESS,
   NC_FILTER_MOSAIC,
   NC_FILTER_CONTOUR,
   NC_FILTER_GAUSSIAN,
   NC_FILTER_UNSHARP_MASK,
   NC_FILTER_ANTI_ALIAS,
   NC_FILTER_EDGE_DETECTOR,
   NC_FILTER_MOTION_BLUR,
   NC_DIALOG_OPENFILE,
   NC_DIALOG_GETDIR,
   NC_DIALOG_GETCONTOUR,
   NC_DIALOG_GETANGLE,
   NC_DIALOG_GETSIZE,
   NC_DIALOG_GETFILTER,
   NC_DIALOG_GETGHANGE,
   NC_DIALOG_GETGAMMA,
   NC_DIALOG_GETNOISE,
   NC_DIALOG_GETEMBOSS,
   NC_DIALOG_GETRANGE,
   NC_DIALOG_COLORRES,
   NC_DIALOG_FILESAVE,
   NC_DIALOG_WINDOWLEVEL,
   NC_DIALOG_GETEFFECT,
   NC_DIALOG_GETSHAPE,
   NC_DIALOG_GETTEXT,
   NC_DIALOG_GETGRADIENT,
   NC_DIALOG_GETTRANSITION,
   NC_DIALOG_GETHALFTONE,
   NC_VECTOR_VECTORHANDLE,
   NC_VECTOR_COPY,
   NC_VECTOR_INITIALIZE,
   NC_VECTOR_DIALOG_ROTATE,
   NC_VECTOR_DIALOG_SCALE,
   NC_VECTOR_DIALOG_TRANSLATE,
   NC_VECTOR_DIALOG_3DOPTIONS,
   NC_VECTOR_DIALOG_CAMERA,
   NC_VECTOR_DIALOG_RENDER,
   NC_VECTOR_DIALOG_VIEW_MODE,
   NC_VECTOR_DIALOG_HIT_TEST,
   NC_VECTOR_DIALOG_EDIT_ALL_LAYERS,
   NC_VECTOR_DIALOG_NEW_LAYER,
   NC_VECTOR_DIALOG_EDIT_LAYER,   
   NC_VECTOR_DIALOG_EDIT_ALL_GROUPS,
   NC_VECTOR_DIALOG_NEW_GROUP,
   NC_VECTOR_DIALOG_EDIT_GROUP,
   NC_VECTOR_DIALOG_NEW_OBJECT,
   NC_VECTOR_DIALOG_EDIT_OBJECT,
   NC_VECTOR_ROTATE,
   NC_VECTOR_SCALE,
   NC_VECTOR_TRANSLATE,
   NC_VECTOR_CAMERA,
   NC_VECTOR_FREE,
   NC_VECTOR_EMPTY,
   NC_VECTOR_BACKCOLOR,
   NC_VECTOR_PALETTE,
   NC_VECTOR_VIEW_MODE,
   NC_VECTOR_VIEW_PORT,
   NC_VECTOR_PAN,
   NC_VECTOR_BIND_VERTICES,
   NC_VECTOR_REALIZE,
   NC_VECTOR_LOCKED,
   
   NC_VECTOR_ORIGIN,
   NC_VECTOR_TRANSFORM,
   NC_VECTOR_ZOOMRECT,
   NC_VECTOR_PARALLELOGRAM,
   NC_VECTOR_MARKER,
   NC_VECTOR_HIT_TEST,
   
   NC_VECTOR_GET_ENGINE,
   NC_VECTOR_ATTACH,
   NC_VECTOR_ADD_OBJECT,
   NC_VECTOR_COPY_OBJECT,
   NC_VECTOR_DELETE_OBJECT,
   NC_VECTOR_SELECT_OBJECT,
   NC_VECTOR_EXPLODE_OBJECT,
   NC_VECTOR_SET_OBJECT,
   NC_VECTOR_SET_OBJECT_ATTRIBUTES,
   NC_VECTOR_LOCK_OBJECT,
   
   NC_VECTOR_POLYGON_MODE,
   NC_VECTOR_USE_LIGHTS,
   NC_VECTOR_AMBIENT_COLOR,
   NC_VECTOR_COPY_FROM_CLIPBOARD,
   //NC_FREE_CHANGE_TO_EMF,
   //NC_FREE_CHANGE_TO_WMF,
   NC_VECTOR_METAFILE,

   NC_VECTOR_ADD_LAYER,
   NC_VECTOR_DELETE_LAYER,
   NC_VECTOR_EMPTY_LAYER,
   NC_VECTOR_COPY_LAYER,
   NC_VECTOR_SET_ACTIVE_LAYER,
   NC_VECTOR_SET_LAYER,
   NC_VECTOR_REPAINT,
   NC_VECTOR_LOAD_FILE,
   NC_VECTOR_ADD_GROUP,
   NC_VECTOR_DELETE_GROUP,
   NC_VECTOR_DELETE_GROUP_CLONES,
   NC_VECTOR_EMPTY_GROUP,
   NC_VECTOR_COPY_GROUP,
   NC_VECTOR_SET_GROUP
   
}  CHANGENOTIFICATIONS;

//--LBITMAP CHANGE NOTIFICATIONS CATIGORY--------------------------------------
typedef enum tagCHANGENOTIFICATIONSCATIGORY
{
   NCAT_RECTS=1,
   NCAT_BITMAP,
   NCAT_FREE,
   NCAT_ACCESS,
   NCAT_DIM,
   NCAT_EDIT,
   NCAT_TRANSFORM,
   NCAT_FILTER,
   NCAT_AUTOPROCESS,
   NCAT_DITHERING,
   NCAT_REGION,
   NCAT_DIALOG,
   NCAT_VECTOR,
   NCAT_VECTOR_DIALOG
}  CHANGENOTIFICATIONSCATIGORY;

//--LWRAPPER OBJECT TYPE-------------------------------------------------------
typedef enum tagLWRAPPEROBJECTTYPE
{
   LEAD_OBJECT_LFILE=0,
   LEAD_OBJECT_LISIS,                                
   LEAD_OBJECT_LTWAIN,                               
   LEAD_OBJECT_LPRINT,                               
   LEAD_OBJECT_LPAINT,                               
   LEAD_OBJECT_LDIALOG,                              
   LEAD_OBJECT_LBITMAPRGN,                           
   LEAD_OBJECT_LMEMORYFILE,                          
   LEAD_OBJECT_LPAINTEFFECT,
   LEAD_OBJECT_LSCREENCAPTURE,
   LEAD_OBJECT_LVECTORDIALOG, 
   LEAD_OBJECT_LVECTORFILE,   
   LEAD_OBJECT_LVECTORMEMORYFILE,
   LEAD_OBJECT_LVECTORLAYER,
   LEAD_OBJECT_LVECTOROBJECT,
   LEAD_OBJECT_LBARCODE,
   LEAD_OBJECT_LAST,
}  LWRAPPEROBJECTTYPE;
//--LWRAPPER OBJECT TYPE-------------------------------------------------------
typedef enum tagLWRAPPERBITMAPMEMBER
{
   BITMAP_MEMBER_PLAYBACK=0,
   BITMAP_MEMBER_BITMAPLIST
}LWRAPPERBITMAPMEMBER;

//--LWRAPPER OBJECT TYPE-------------------------------------------------------
typedef enum tagBITMAPWNDTOOL
{
   TOOL_USERMODE,
   TOOL_PANIMAGE,
   TOOL_ZOOMRECT,
   TOOL_REGION,
   TOOL_ZOOM_ON_MOUSECLICK,
   TOOL_MAGGLASS,
}BITMAPWNDTOOL;

//--LWRAPPER OBJECT TYPE-------------------------------------------------------
typedef enum tagVECTORWNDTOOL
{
   TOOL_VECTOR_USERMODE,
   TOOL_VECTOR_PANIMAGE,
   //TOOL_VECTOR_ZOOMRECT,
   //TOOL_VECTOR_ZOOM_ON_MOUSECLICK,
   TOOL_VECTOR_SELECT,
   TOOL_VECTOR_ROTATE,
}VECTORWNDTOOL;

//--LWRAPPER KEYMODE TYPE -----------------------------------------------------
typedef enum tagVECTORWNDKEYMODE
{
   KEY_MODE_ZOOM,
   KEY_MODE_SCALE,
}VECTORWNDKEYMODE;

//--LWRAPPER OBJECT TYPE-------------------------------------------------------
typedef enum tagBITMAPWNDZOOMMODE
{
   ZOOM_FIT,
   ZOOM_STRETCH,
   ZOOM_NORMAL,
   ZOOM_FITWIDTH,
   ZOOM_FITHEIGHT,
   ZOOM_FACTOR
}BITMAPWNDZOOMMODE;

//--LWRAPPER OBJECT TYPE-------------------------------------------------------
typedef enum tagBITMAPWNDFRAMRGN
{
   RGNFRAME_STATIC,
   RGNFRAME_ANIMATED,
   RGNFRAME_NONE
}BITMAPWNDFRAMRGN;
//--LWRAPPER OBJECT TYPE-------------------------------------------------------
typedef enum tagBITMAPWNDRGNTYPE
{
   REGION_TYPE_POLYGON,
   REGION_TYPE_RECT,
   REGION_TYPE_ELIPSE,
   REGION_TYPE_ROUNDRECT,
   REGION_TYPE_TRIANGLE,
   REGION_TYPE_FREE_HAND,
   REGION_TYPE_CURVE,
   REGION_TYPE_BEZIER
}BITMAPWNDRGNTYPE;

//--LWRAPPER EFFECT TYPE-------------------------------------------------------
typedef enum tagEFXPAINTTYPE
{
   EFX_NOTIFY_TRANSSITON, 
   EFX_NOTIFY_IMAGE,
}EFXPAINTTYPE;

//--LWRAPPER REGION ACTIONS----------------------------------------------------
typedef enum tagREGIONACTION
{
   REGION_CREATED,
   REGION_DESTROYED,
   REGION_MODIFIED,
}REGIONACTION;

//--possible values for nEvent in ANIMATTIONEVENTDATA ----------------------------------------------------
typedef enum tagANIMATE_EVENT
{
   EVENT_MOVE_FIRST,
   EVENT_MOVE_LAST,
   EVENT_MOVE_NEXT,
   EVENT_MOVE_PREV,
   EVENT_MOVE_TO,
   EVENT_PLAYSTATE_START,
   EVENT_PLAYSTATE_END,
   EVENT_PLAYSTATE_PRECLEAR,
   EVENT_PLAYSTATE_POSTCLEAR,
   EVENT_PLAYSTATE_PRERENDER,
   EVENT_PLAYSTATE_RENDER    ,
   EVENT_PLAYSTATE_POSTRENDER,
   EVENT_PLAYSTATE_WAITINPUT,
   EVENT_PLAYSTATE_WAITDELAY , 
   EVENT_PLAYSTATE_WAITINPUTDELAY,
   EVENT_PLAYSTATE_PREDISPOSE   , 
   EVENT_PLAYSTATE_POSTDISPOSE,
   EVENT_PLAYSTATE_LOOP
} ANIMATE_EVENT;
//--possible values for LAnimationWindow::SetDisposalMethod----------------------------------------------------

typedef enum tagANIMATION_DISPOSAL
{
      DISPOSAL_NONE,
      DISPOSAL_LEAVE,
      DISPOSAL_RESTOREBACKGROUND,
      DISPOSAL_RESTOREPREVIOUS
} ANIMATION_DISPOSAL;

//--BITMAP WINDOW MESSAGES-----------------------------------------------------
typedef enum tagBITMAPWINDOWMESSAGES
{
   /*Bitmap Window (LBitmapWindow) Messages*/
   LBW_LBUTTONDOWN=WM_LEAD+0,
   LBW_LBUTTONUP,
   LBW_RBUTTONDOWN,
   LBW_RBUTTONUP,
   LBW_LBUTTONCLICKED,
   LBW_RBUTTONCLICKED,
   LBW_LBUTTONDBLCLK,
   LBW_RBUTTONDBLCLK,
   LBW_MOUSEMOVE,
   LBW_KEYDOWN,
   LBW_KEYUP,
   LBW_KEYPRESS,
   LBW_SIZECHANGED,
   LBW_FILEDRAGDROP,
   LBW_PAINTEFFECTS,
   LBW_PANWINDOW,
   LBW_ZOOM,
   LBW_SETFOCUS,
   LBW_KILLFOCUS,
   LBW_ENABLED,
   LBW_DISABLED,
   LBW_SCROLLED,
   LBW_BITMAPCHANGED,
   LBW_PAINTED,
   LBW_RGNCHANGED,
   /*Annotation Window (LAnnotationWindow) Messages*/
   LBAW_SELECTED,
   LBAW_HYPERLINK,
   LBAW_HYPERLINKMENU,
   LBAW_CHANGED,
   LBAW_DESTROYED,
   LBAW_DRAWN,
   LBAW_LOCKED,
   LBAW_UNLOCKED,
   LBAW_CLICKED,
   LBAW_CREATED,
   /*Animation Window (LAnimationWindow) Messages*/
   LAM_MOVE_FIRST,
   LAM_MOVE_LAST,
   LAM_MOVE_NEXT,
   LAM_MOVE_PREV,
   LAM_MOVE_TO,
   LAM_PLAYBACK_EVENT,
   /*Vector Window (LVectorWindow) specific Messages*/
   LVW_SCALE,
   LVW_VECTOR_CHANGED
} BITMAPWINDOWMESSAGES;

//--BAR CODE Major Types-------------------------------------------------------
typedef enum tagBARCODETYPE
{
   BARCODE_LINEAR =0,
   BARCODE_CODEONE,
   BARCODE_PDF,
   BARCODE_DATAMATRIX
} BARCODETYPE;

#endif //_LEAD_WRAPPER_ENUMS_H_
/*================================================================= EOF =====*/
