/*----------------------------------------------------------------------------+
| LEADTOOLS for Windows -                                                     |
| Copyright(c) 1991-2000 LEAD Technologies, Inc.                              |
| All Rights Reserved.                                                        |
|-----------------------------------------------------------------------------|
| PROJECT   : LEAD wrappers                                                   |
| FILE NAME : tcFncID.h                                                       |
| DESC      :                                                                 |
+----------------------------------------------------------------------------*/

#ifndef  _LEAD_FUNCTIONS_ID_H_
#define  _LEAD_FUNCTIONS_ID_H_

/*----------------------------------------------------------------------------+
| MACROS                                                                      |
+----------------------------------------------------------------------------*/
#ifdef USE_POINTERS_TO_LEAD_FUNCTIONS

//-----------------------------------------------------------------------------
//--LTKRN.H FUNCTIONS MACROS---------------------------------------------------
//-----------------------------------------------------------------------------


#define IDF_L_AccessBitmap                   MAKEINTRESOURCE(100)
#define IDF_L_AllocateBitmap                 MAKEINTRESOURCE(101)
#define IDF_L_ChangeBitmapHeight             MAKEINTRESOURCE(102)
#define IDF_L_FreeDuplicateBitmap            MAKEINTRESOURCE(103)
#define IDF_L_ChangeFromDIB                  MAKEINTRESOURCE(104)
#define IDF_L_SQRT                           MAKEINTRESOURCE(105)
#define IDF_L_ChangeToDIB                    MAKEINTRESOURCE(106)
#define IDF_L_ClearBitmap                    MAKEINTRESOURCE(107)
#define IDF_L_ColorResBitmap                 MAKEINTRESOURCE(108)
#define IDF_L_ConvertBuffer                  MAKEINTRESOURCE(109)
#define IDF_L_ConvertFromDIB                 MAKEINTRESOURCE(110)
#define IDF_L_ConvertToDIB                   MAKEINTRESOURCE(111)
#define IDF_L_CopyBitmap                     MAKEINTRESOURCE(112)
#define IDF_L_CopyBitmapData                 MAKEINTRESOURCE(113)
#define IDF_L_CopyBitmapHandle               MAKEINTRESOURCE(114)
#define IDF_L_CopyBitmapRect                 MAKEINTRESOURCE(115)
#define IDF_L_CreateBitmap                   MAKEINTRESOURCE(116)
#define IDF_L_CreateLeadDC                   MAKEINTRESOURCE(117)
#define IDF_L_CreateUserMatchTable           MAKEINTRESOURCE(118)
#define IDF_L_DefaultDithering               MAKEINTRESOURCE(119)
#define IDF_L_DeleteLeadDC                   MAKEINTRESOURCE(120)
#define IDF_L_DitherLine                     MAKEINTRESOURCE(121)
#define IDF_L_DupPalette                     MAKEINTRESOURCE(122)
#define IDF_L_FillBitmap                     MAKEINTRESOURCE(123)
#define IDF_L_FlipBitmap                     MAKEINTRESOURCE(124)
#define IDF_L_FreeBitmap                     MAKEINTRESOURCE(125)
#define IDF_L_FreeImage                      MAKEINTRESOURCE(126)
#define IDF_L_FreeUserMatchTable             MAKEINTRESOURCE(127)
#define IDF_L_GetBitmapColors                MAKEINTRESOURCE(128)
#define IDF_L_GetBitmapRow                   MAKEINTRESOURCE(129)
#define IDF_L_GetBitmapRowCol                MAKEINTRESOURCE(130)
#define IDF_L_GetFixedPalette                MAKEINTRESOURCE(131)
#define IDF_L_GetPixelColor                  MAKEINTRESOURCE(132)
#define IDF_L_GrayScaleBitmap                MAKEINTRESOURCE(133)
#define IDF_L_InitBitmap                     MAKEINTRESOURCE(134)
#define IDF_L_IsGrayScaleBitmap              MAKEINTRESOURCE(135)
#define IDF_L_PutBitmapColors                MAKEINTRESOURCE(136)
#define IDF_L_PutBitmapRow                   MAKEINTRESOURCE(137)
#define IDF_L_PutBitmapRowCol                MAKEINTRESOURCE(138)
#define IDF_L_PutPixelColor                  MAKEINTRESOURCE(139)
#define IDF_L_RedirectIO                     MAKEINTRESOURCE(140)
#define IDF_L_ReleaseBitmap                  MAKEINTRESOURCE(141)
#define IDF_L_Resize                         MAKEINTRESOURCE(142)
#define IDF_L_ResizeBitmap                   MAKEINTRESOURCE(143)
#define IDF_L_ReverseBitmap                  MAKEINTRESOURCE(144)
#define IDF_L_RotateBitmap                   MAKEINTRESOURCE(145)
#define IDF_L_GetChangeViewPerspectiveParams MAKEINTRESOURCE(146)
#define IDF_L_RotateBuffer90                 MAKEINTRESOURCE(147)
#define IDF_L_SetStatusCallBack              MAKEINTRESOURCE(148)
#define IDF_L_SetUserMatchTable              MAKEINTRESOURCE(149)
#define IDF_L_ShearBitmap                    MAKEINTRESOURCE(150)
#define IDF_L_SizeBitmap                     MAKEINTRESOURCE(151)
#define IDF_L_StartDithering                 MAKEINTRESOURCE(152)
#define IDF_L_StartResize                    MAKEINTRESOURCE(153)
#define IDF_L_StopDithering                  MAKEINTRESOURCE(154)
#define IDF_L_StopResize                     MAKEINTRESOURCE(155)
#define IDF_L_UnlockBitmap                   MAKEINTRESOURCE(156)
#define IDF_L_VersionInfo                    MAKEINTRESOURCE(157)
#define IDF_L_CalcConvertSize                MAKEINTRESOURCE(158)
#define IDF_L_CompareHandleToPalette         MAKEINTRESOURCE(159)
#define IDF_L_CreateBitmapFixedPalette       MAKEINTRESOURCE(160)
#define IDF_L_CreateFixedPalette             MAKEINTRESOURCE(161)
#define IDF_L_CreateGrayPalette              MAKEINTRESOURCE(162)
#define IDF_L_CreatePalette                  MAKEINTRESOURCE(163)
#define IDF_L_CreateSystemPalette            MAKEINTRESOURCE(164)
#define IDF_L_DupBitmapNewDim                MAKEINTRESOURCE(165)
#define IDF_L_Get1BitOnTable                 MAKEINTRESOURCE(166)
#define IDF_L_GetDefaultXResolution          MAKEINTRESOURCE(167)
#define IDF_L_GetDefaultYResolution          MAKEINTRESOURCE(168)
#define IDF_L_GetPaletteEntries              MAKEINTRESOURCE(169)
#define IDF_L_GetPaletteSize                 MAKEINTRESOURCE(170)
#define IDF_L_GetStatusCallBack              MAKEINTRESOURCE(171)
#define IDF_L_IntRotateBitmap                MAKEINTRESOURCE(172)
#define IDF_L_LockBitmap                     MAKEINTRESOURCE(173)
#define IDF_L_OsAlloc                        MAKEINTRESOURCE(174)
#define IDF_L_OsAllocInit                    MAKEINTRESOURCE(175)
#define IDF_L_OsClose                        MAKEINTRESOURCE(176)
#define IDF_L_OsCreat                        MAKEINTRESOURCE(177)
#define IDF_L_OsDelete                       MAKEINTRESOURCE(178)
#define IDF_L_OsFree                         MAKEINTRESOURCE(179)
#define IDF_L_OsGetTempName                  MAKEINTRESOURCE(180)
#define IDF_L_OsOpen                         MAKEINTRESOURCE(181)
#define IDF_L_OsRead                         MAKEINTRESOURCE(182)
#define IDF_L_OsReAlloc                      MAKEINTRESOURCE(183)
#define IDF_L_OsSeek                         MAKEINTRESOURCE(184)
#define IDF_L_OsWrite                        MAKEINTRESOURCE(185)
#define IDF_L_SetDefaultXResolution          MAKEINTRESOURCE(186)
#define IDF_L_SetDefaultYResolution          MAKEINTRESOURCE(187)
#define IDF_L_RedirectedClose                MAKEINTRESOURCE(188)
#define IDF_L_RedirectedOpen                 MAKEINTRESOURCE(189)
#define IDF_L_RedirectedRead                 MAKEINTRESOURCE(190)
#define IDF_L_RedirectedSeek                 MAKEINTRESOURCE(191)
#define IDF_L_RedirectedWrite                MAKEINTRESOURCE(192)
#define IDF_L_IntGetFixedPalette             MAKEINTRESOURCE(193)
#define IDF_L_FilterIO                       MAKEINTRESOURCE(194)
#define IDF_L_SetPaletteEntries              MAKEINTRESOURCE(195)
#define IDF_L_IsSupportLocked                MAKEINTRESOURCE(196)
#define IDF_L_UnlockSupport                  MAKEINTRESOURCE(197)
#define IDF_L_ChangeRectViewPerspective      MAKEINTRESOURCE(198)
#define IDF_L_PutBitmapRowSegments           MAKEINTRESOURCE(199)
#define IDF_L_DeleteLeadRgn                  MAKEINTRESOURCE(200)
#define IDF_L_GetDisDispatch                 MAKEINTRESOURCE(201)
#define IDF_L_SetDisDispatch                 MAKEINTRESOURCE(202)
#define IDF_L_CopyPlaybackParms              MAKEINTRESOURCE(203)
#define IDF_L_ColorResBitmapList             MAKEINTRESOURCE(204)
#define IDF_L_TranslateBitmapColor           MAKEINTRESOURCE(205)
#define IDF_L_GetBitmapAlpha                 MAKEINTRESOURCE(206)
#define IDF_L_SetBitmapAlpha                 MAKEINTRESOURCE(207)
#define IDF_L_GetBitmapRowColCompressed      MAKEINTRESOURCE(208)
#define IDF_L_PutBitmapRowColCompressed      MAKEINTRESOURCE(209)
#define IDF_L_ExpandRow                      MAKEINTRESOURCE(210)
#define IDF_L_CompressRow                    MAKEINTRESOURCE(211)
#define IDF_L_FindPaletteIndex               MAKEINTRESOURCE(212)
#define IDF_L_TrimBitmap                     MAKEINTRESOURCE(213)
#define IDF_L_GetBitmapRowCompressed         MAKEINTRESOURCE(214)
#define IDF_L_PutBitmapRowCompressed         MAKEINTRESOURCE(215)
#define IDF_L_PointFromBitmap                MAKEINTRESOURCE(216)
#define IDF_L_PointToBitmap                  MAKEINTRESOURCE(217)
#define IDF_L_RectFromBitmap                 MAKEINTRESOURCE(218)
#define IDF_L_RectToBitmap                   MAKEINTRESOURCE(219)
#define IDF_L_RotateBitmapViewPerspective    MAKEINTRESOURCE(220)
#define IDF_L_ChangeBitmapViewPerspective    MAKEINTRESOURCE(221)
#define IDF_L_IntChangeBitmapViewPerspective MAKEINTRESOURCE(222)
#define IDF_L_MirrorLine                     MAKEINTRESOURCE(223)
#define IDF_L_FlipCompressedBuffer           MAKEINTRESOURCE(224)
#define IDF_L_MirrorCompressedBuffer         MAKEINTRESOURCE(225)
#define IDF_L_ExpandRows                     MAKEINTRESOURCE(226)
#define IDF_L_CompressRows                   MAKEINTRESOURCE(227)
#define IDF_L_CosValue                       MAKEINTRESOURCE(228)
#define IDF_L_SinValue                       MAKEINTRESOURCE(229)
#define IDF_L_TrimBitmapHeap                 MAKEINTRESOURCE(230)
#define IDF_L_GrowBitmapHeap                 MAKEINTRESOURCE(231)
#define IDF_L_CreateBitmapList               MAKEINTRESOURCE(232)
#define IDF_L_RemoveBitmapListItem           MAKEINTRESOURCE(233)
#define IDF_L_InsertBitmapListItem           MAKEINTRESOURCE(234)
#define IDF_L_DeleteBitmapListItems          MAKEINTRESOURCE(235)
#define IDF_L_DestroyBitmapList              MAKEINTRESOURCE(236)
#define IDF_L_GetBitmapListCount             MAKEINTRESOURCE(237)
#define IDF_L_GetBitmapListItem              MAKEINTRESOURCE(238)
#define IDF_L_SetBitmapListItem              MAKEINTRESOURCE(239)
#define IDF_L_CopyBitmapListItems            MAKEINTRESOURCE(240)
#define IDF_L_CombineBitmap                  MAKEINTRESOURCE(241)
#define IDF_L_ClearNegativePixels            MAKEINTRESOURCE(242)
#define IDF_L_ConvertBufferExt               MAKEINTRESOURCE(243)
#define IDF_L_GetGrayParams                  MAKEINTRESOURCE(244)
#define IDF_L_MirrorFromDIB                  MAKEINTRESOURCE(245)
#define IDF_L_InitGrayParams                 MAKEINTRESOURCE(246)
#define IDF_L_CopyGrayParams                 MAKEINTRESOURCE(247)
#define IDF_L_SetHotKeyCallback              MAKEINTRESOURCE(250)
#define IDF_L_StartDitheringExt              MAKEINTRESOURCE(251)
#define IDF_L_GetBitmapColorCountExt         MAKEINTRESOURCE(252)
#define IDF_L_OsReAllocInit                  MAKEINTRESOURCE(253)
#define IDF_L_SetBitmapDataPointer           MAKEINTRESOURCE(254)
#define IDF_L_ToggleBitmapCompression        MAKEINTRESOURCE(255)
#define IDF_L_ChangeBitmapCompression        MAKEINTRESOURCE(256)
#define IDF_L_GetPixelData                   MAKEINTRESOURCE(257)
#define IDF_L_PutPixelData                   MAKEINTRESOURCE(258)
#define IDF_L_GetFilterIOData                MAKEINTRESOURCE(259)
#define IDF_L_RotateBuffer180                MAKEINTRESOURCE(260)
#define IDF_L_ReverseGetResizedScanLine      MAKEINTRESOURCE(261)
#define IDF_L_GetResizedScanLine             MAKEINTRESOURCE(262)
#define IDF_L_FlipBitmapViewPerspective      MAKEINTRESOURCE(263)
#define IDF_L_ReverseBitmapViewPerspective   MAKEINTRESOURCE(264)
#define IDF_L_StartResizeBitmap              MAKEINTRESOURCE(265)
#define IDF_L_GetResizedRowCol               MAKEINTRESOURCE(266)
#define IDF_L_StopResizeBitmap               MAKEINTRESOURCE(267)
#define IDF_L_IsGrayScalePalette             MAKEINTRESOURCE(268)
#define IDF_L_MoveBitmapListItems            MAKEINTRESOURCE(269)
#define IDF_L_RotateBitmap90                 MAKEINTRESOURCE(270)
#define IDF_L_CombineBitmapWarp              MAKEINTRESOURCE(288)

#define IDF_L_CreateBitmapListOptPal         MAKEINTRESOURCE(286)
#define IDF_L_DupBitmapPalette               MAKEINTRESOURCE(309)
#define IDF_L_SetBitmapPalette               MAKEINTRESOURCE(324)

//-----------------------------------------------------------------------------
//--LTIMG.H FUNCTIONS MACROS---------------------------------------------------
//-----------------------------------------------------------------------------
#define IDF_L_AddBitmapNoise                MAKEINTRESOURCE(100)
#define IDF_L_AverageFilterBitmap           MAKEINTRESOURCE(101)
#define IDF_L_BinaryFilterBitmap            MAKEINTRESOURCE(102)
#define IDF_L_ChangeBitmapContrast          MAKEINTRESOURCE(103)
#define IDF_L_ChangeBitmapHue               MAKEINTRESOURCE(104)
#define IDF_L_ChangeBitmapIntensity         MAKEINTRESOURCE(105)
#define IDF_L_ChangeBitmapSaturation        MAKEINTRESOURCE(106)
#define IDF_L_ColorMergeBitmap              MAKEINTRESOURCE(107)
#define IDF_L_ColorSeparateBitmap           MAKEINTRESOURCE(108)
#define IDF_L_DeskewBitmap                  MAKEINTRESOURCE(109)
#define IDF_L_DespeckleBitmap               MAKEINTRESOURCE(110)
#define IDF_L_EmbossBitmap                  MAKEINTRESOURCE(111)
#define IDF_L_GammaCorrectBitmap            MAKEINTRESOURCE(112)
#define IDF_L_GetBitmapHistogram            MAKEINTRESOURCE(113)
#define IDF_L_HistoContrastBitmap           MAKEINTRESOURCE(114)
#define IDF_L_IntensityDetectBitmap         MAKEINTRESOURCE(116)
#define IDF_L_InvertBitmap                  MAKEINTRESOURCE(117)
#define IDF_L_MedianFilterBitmap            MAKEINTRESOURCE(118)
#define IDF_L_MosaicBitmap                  MAKEINTRESOURCE(119)
#define IDF_L_PosterizeBitmap               MAKEINTRESOURCE(120)
#define IDF_L_RemapBitmapIntensity          MAKEINTRESOURCE(121)
#define IDF_L_SharpenBitmap                 MAKEINTRESOURCE(122)
#define IDF_L_SpatialFilterBitmap           MAKEINTRESOURCE(123)
#define IDF_L_StretchBitmapIntensity        MAKEINTRESOURCE(124)
#define IDF_L_GetBitmapColorCount           MAKEINTRESOURCE(125)
#define IDF_L_GetAutoTrimRect               MAKEINTRESOURCE(126)
#define IDF_L_AutoTrimBitmap                MAKEINTRESOURCE(127)
#define IDF_L_SolarizeBitmap                MAKEINTRESOURCE(128)
#define IDF_L_OilifyBitmap                  MAKEINTRESOURCE(129)
#define IDF_L_MinFilterBitmap               MAKEINTRESOURCE(130)
#define IDF_L_MaxFilterBitmap               MAKEINTRESOURCE(131)
#define IDF_L_WindowLevelBitmap             MAKEINTRESOURCE(132)
#define IDF_L_GetMinMaxVal                  MAKEINTRESOURCE(133)
#define IDF_L_GetMinMaxBits                 MAKEINTRESOURCE(134)
#define IDF_L_PicturizeBitmap               MAKEINTRESOURCE(135)
#define IDF_L_ContourFilterBitmap           MAKEINTRESOURCE(136)
#define IDF_L_SmoothBitmap                  MAKEINTRESOURCE(137)
#define IDF_L_LineRemoveBitmap              MAKEINTRESOURCE(138)
#define IDF_L_BorderRemoveBitmap            MAKEINTRESOURCE(139)
#define IDF_L_InvertedTextBitmap            MAKEINTRESOURCE(140)
#define IDF_L_DotRemoveBitmap               MAKEINTRESOURCE(141)
#define IDF_L_HolePunchRemoveBitmap         MAKEINTRESOURCE(142)
#define IDF_L_StapleRemoveBitmap            MAKEINTRESOURCE(143)
#define IDF_L_GaussianFilterBitmap          MAKEINTRESOURCE(148)
#define IDF_L_UnsharpMaskBitmap             MAKEINTRESOURCE(149)
#define IDF_L_GrayScaleBitmapExt            MAKEINTRESOURCE(151)
#define IDF_L_ConvertToColoredGray          MAKEINTRESOURCE(154)
#define IDF_L_BalanceColors                 MAKEINTRESOURCE(153)
#define IDF_L_SwapColors                    MAKEINTRESOURCE(152)
#define IDF_L_LineProfile                   MAKEINTRESOURCE(150)
#define IDF_L_HistoEqualizeBitmap           MAKEINTRESOURCE(115)
#define IDF_L_AddBitmaps                    MAKEINTRESOURCE(161)
#define IDF_L_AntiAliasBitmap               MAKEINTRESOURCE(162)
#define IDF_L_EdgeDetectorBitmap            MAKEINTRESOURCE(163)
#define IDF_L_RemoveRedeyeBitmap            MAKEINTRESOURCE(155)
#define IDF_L_ResizeBitmapRgn               MAKEINTRESOURCE(156)
#define IDF_L_AlphaBlendBitmap              MAKEINTRESOURCE(159)
#define IDF_L_FeatherAlphaBlendBitmap       MAKEINTRESOURCE(158)
#define IDF_L_CreateFadedMask               MAKEINTRESOURCE(157)
#define IDF_L_MotionBlurBitmap              MAKEINTRESOURCE(164)
#define IDF_L_PicturizeBitmapList           MAKEINTRESOURCE(165)
#define IDF_L_PicturizeBitmapSingle         MAKEINTRESOURCE(169)
#define IDF_L_HalfToneBitmap                MAKEINTRESOURCE(168)
#define IDF_L_GetFunctionalLookupTable      MAKEINTRESOURCE(167)
#define IDF_L_GetUserLookUpTable            MAKEINTRESOURCE(166)
#define IDF_L_CombineBitmapExt              MAKEINTRESOURCE(160)
#define IDF_L_AddBorder                     MAKEINTRESOURCE(171)
#define IDF_L_AddFrame                      MAKEINTRESOURCE(172)
#define IDF_L_ConvertBitmapSignedToUnsigned MAKEINTRESOURCE(170)


//-----------------------------------------------------------------------------
//--LTDIS.H FUNCTIONS MACROS---------------------------------------------------
//-----------------------------------------------------------------------------


#define IDF_L_CreateMaskFromBitmapRgn        MAKEINTRESOURCE(100)
#define IDF_L_SetBitmapRgnFromMask           MAKEINTRESOURCE(101)
#define IDF_L_IsPtInBitmapRgn                MAKEINTRESOURCE(102)
#define IDF_L_SetBitmapRgnRect               MAKEINTRESOURCE(105)
#define IDF_L_SetBitmapRgnEllipse            MAKEINTRESOURCE(106)
#define IDF_L_SetBitmapRgnPolygon            MAKEINTRESOURCE(107)
#define IDF_L_SetBitmapRgnRoundRect          MAKEINTRESOURCE(108)
#define IDF_L_OffsetBitmapRgn                MAKEINTRESOURCE(109)
#define IDF_L_GetBitmapRgnArea               MAKEINTRESOURCE(110)
#define IDF_L_PaintRgnDC                     MAKEINTRESOURCE(111)
#define IDF_L_PaintRgnDCBuffer               MAKEINTRESOURCE(112)
#define IDF_L_SetBitmapRgnColor              MAKEINTRESOURCE(113)
#define IDF_L_FrameBitmapRgn                 MAKEINTRESOURCE(114)
#define IDF_L_FreeBitmapRgn                  MAKEINTRESOURCE(115)
#define IDF_L_BitmapHasRgn                   MAKEINTRESOURCE(116)
#define IDF_L_GetBitmapRgnBounds             MAKEINTRESOURCE(117)
#define IDF_L_GetBitmapRgnHandle             MAKEINTRESOURCE(118)
#define IDF_L_SetBitmapRgnHandle             MAKEINTRESOURCE(119)
#define IDF_L_ChangeFromDDB                  MAKEINTRESOURCE(120)
#define IDF_L_ChangeToDDB                    MAKEINTRESOURCE(121)
#define IDF_L_CreatePaintPalette             MAKEINTRESOURCE(122)
#define IDF_L_ClipboardReady                 MAKEINTRESOURCE(123)
#define IDF_L_ConvertFromDDB                 MAKEINTRESOURCE(124)
#define IDF_L_ConvertToDDB                   MAKEINTRESOURCE(125)
#define IDF_L_CopyFromClipboard              MAKEINTRESOURCE(126)
#define IDF_L_CopyToClipboard                MAKEINTRESOURCE(127)
#define IDF_L_CopyToClipboardExt             MAKEINTRESOURCE(128)
#define IDF_L_GetDisplayMode                 MAKEINTRESOURCE(129)
#define IDF_L_PaintDC                        MAKEINTRESOURCE(132)
#define IDF_L_PaintDCBuffer                  MAKEINTRESOURCE(133)
#define IDF_L_PrintBitmap                    MAKEINTRESOURCE(134)
#define IDF_L_PrintBitmapExt                 MAKEINTRESOURCE(135)
#define IDF_L_PrintBitmapFast                MAKEINTRESOURCE(136)
#define IDF_L_ScreenCaptureBitmap            MAKEINTRESOURCE(137)
#define IDF_L_SetDisplayMode                 MAKEINTRESOURCE(138)
#define IDF_L_UnderlayBitmap                 MAKEINTRESOURCE(139)
#define IDF_L_CreatePlayback                 MAKEINTRESOURCE(140)
#define IDF_L_CancelPlaybackWait             MAKEINTRESOURCE(141)
#define IDF_L_GetPlaybackState               MAKEINTRESOURCE(142)
#define IDF_L_ProcessPlayback                MAKEINTRESOURCE(143)
#define IDF_L_GetPlaybackUpdateRect          MAKEINTRESOURCE(144)
#define IDF_L_ClearPlaybackUpdateRect        MAKEINTRESOURCE(145)
#define IDF_L_DestroyPlayback                MAKEINTRESOURCE(146)
#define IDF_L_GetPlaybackIndex               MAKEINTRESOURCE(147)
#define IDF_L_SetPlaybackIndex               MAKEINTRESOURCE(148)
#define IDF_L_AppendPlayback                 MAKEINTRESOURCE(149)
#define IDF_L_ValidatePlaybackLines          MAKEINTRESOURCE(150)
#define IDF_L_GetPlaybackDelay               MAKEINTRESOURCE(151)
#define IDF_L_SetPaintIntensity              MAKEINTRESOURCE(152)
#define IDF_L_GetPaintIntensity              MAKEINTRESOURCE(153)
#define IDF_L_SetPaintContrast               MAKEINTRESOURCE(154)
#define IDF_L_GetPaintContrast               MAKEINTRESOURCE(155)
#define IDF_L_SetPaintGamma                  MAKEINTRESOURCE(156)
#define IDF_L_GetPaintGamma                  MAKEINTRESOURCE(157)
#define IDF_L_IntGetBitmapRgnHandle          MAKEINTRESOURCE(158)
#define IDF_L_ConvertColorSpace              MAKEINTRESOURCE(159)
#define IDF_L_WindowLevel                    MAKEINTRESOURCE(160)
#define IDF_L_CreatePanWindow                MAKEINTRESOURCE(161)
#define IDF_L_UpdatePanWindow                MAKEINTRESOURCE(162)
#define IDF_L_DestroyPanWindow               MAKEINTRESOURCE(163)
#define IDF_L_WindowLevelFillLUT             MAKEINTRESOURCE(164)
#define IDF_L_CopyMetaBitmap                 MAKEINTRESOURCE(165)
#define IDF_L_DeleteMetaBitmap               MAKEINTRESOURCE(166)
#define IDF_L_GetMetafileInfo                MAKEINTRESOURCE(167)
#define IDF_L_PaintMetaBitmap                MAKEINTRESOURCE(168)
#define IDF_L_AllocateMetaBitmapBits         MAKEINTRESOURCE(169)
#define IDF_L_LoadMetaBitmap                 MAKEINTRESOURCE(170)
#define IDF_L_ParseMetaBits                  MAKEINTRESOURCE(171)
#define IDF_L_ConvertToMetafile              MAKEINTRESOURCE(172)
#define IDF_L_ConvertFromMetafile            MAKEINTRESOURCE(173)
#define IDF_L_ChangeToMetafile               MAKEINTRESOURCE(174)
#define IDF_L_ChangeFromMetafile             MAKEINTRESOURCE(175)
#define IDF_L_ConvertFromWMF                 MAKEINTRESOURCE(176)
#define IDF_L_ChangeFromWMF                  MAKEINTRESOURCE(177)
#define IDF_L_ConvertToWMF                   MAKEINTRESOURCE(178)
#define IDF_L_ChangeToWMF                    MAKEINTRESOURCE(179)
#define IDF_L_ConvertFromEMF                 MAKEINTRESOURCE(180)
#define IDF_L_ChangeFromEMF                  MAKEINTRESOURCE(181)
#define IDF_L_ConvertToEMF                   MAKEINTRESOURCE(182)
#define IDF_L_ChangeToEMF                    MAKEINTRESOURCE(183)
#define IDF_L_GetResizedRgnHandle            MAKEINTRESOURCE(184)
#define IDF_L_StartMagGlass                  MAKEINTRESOURCE(185)
#define IDF_L_StopMagGlass                   MAKEINTRESOURCE(186)
#define IDF_L_SetBitmapRgnMagicWand          MAKEINTRESOURCE(187)
#define IDF_L_ColorBitmapRgn                 MAKEINTRESOURCE(188)
#define IDF_L_CopyLeadRgn                    MAKEINTRESOURCE(189)
#define IDF_L_UpdateMagGlassRect             MAKEINTRESOURCE(190)
#define IDF_L_WindowHasMagGlass              MAKEINTRESOURCE(199)
#define IDF_L_SetBitmapRgnCurve              MAKEINTRESOURCE(200)
#define IDF_L_CurveToBezier                  MAKEINTRESOURCE(201)
#define IDF_L_GetBitmapClipSegments          MAKEINTRESOURCE(104)
#define IDF_L_GetBitmapClipSegmentsMax       MAKEINTRESOURCE(103)

//-----------------------------------------------------------------------------
//--LTFIL.H FUNCTIONS MACROS---------------------------------------------------
//-----------------------------------------------------------------------------

#define IDF_L_FileInfo                       MAKEINTRESOURCE(100)
#define IDF_L_LoadBitmap                     MAKEINTRESOURCE(101)
#define IDF_L_LoadFile                       MAKEINTRESOURCE(102)
#define IDF_L_SaveBitmap                     MAKEINTRESOURCE(103)
#define IDF_L_SaveFile                       MAKEINTRESOURCE(104)
#define IDF_L_GetDefaultLoadFileOption       MAKEINTRESOURCE(105)
#define IDF_L_GetDefaultSaveFileOption       MAKEINTRESOURCE(106)
#define IDF_L_SetLoadInfoCallback            MAKEINTRESOURCE(107)
#define IDF_L_GetComment                     MAKEINTRESOURCE(108)
#define IDF_L_SetComment                     MAKEINTRESOURCE(109)
#define IDF_L_ReadFileComment                MAKEINTRESOURCE(110)
#define IDF_L_FileConvert                    MAKEINTRESOURCE(111)
#define IDF_L_SaveFileOffset                 MAKEINTRESOURCE(112)
#define IDF_L_LoadFileOffset                 MAKEINTRESOURCE(113)
#define IDF_L_GetPCDResolution               MAKEINTRESOURCE(114)
#define IDF_L_SetPCDResolution               MAKEINTRESOURCE(115)
#define IDF_L_SaveBitmapMemory               MAKEINTRESOURCE(116)
#define IDF_L_FileInfoMemory                 MAKEINTRESOURCE(117)
#define IDF_L_LoadBitmapMemory               MAKEINTRESOURCE(118)
#define IDF_L_LoadMemory                     MAKEINTRESOURCE(119)
#define IDF_L_StartFeedLoad                  MAKEINTRESOURCE(120)
#define IDF_L_FeedLoad                       MAKEINTRESOURCE(121)
#define IDF_L_StopFeedLoad                   MAKEINTRESOURCE(122)
#define IDF_L_DocLoadFile                    MAKEINTRESOURCE(123)
#define IDF_L_DocLoadMemory                  MAKEINTRESOURCE(124)
#define IDF_L_DocStartFeedLoad               MAKEINTRESOURCE(125)
#define IDF_L_DocFeedLoad                    MAKEINTRESOURCE(126)
#define IDF_L_StartCompressBuffer            MAKEINTRESOURCE(127)
#define IDF_L_CompressBuffer                 MAKEINTRESOURCE(128)
#define IDF_L_EndCompressBuffer              MAKEINTRESOURCE(129)
#define IDF_L_GetWMFResolution               MAKEINTRESOURCE(130)
#define IDF_L_SetWMFResolution               MAKEINTRESOURCE(131)
#define IDF_L_LoadBitmapList                 MAKEINTRESOURCE(132)
#define IDF_L_SaveBitmapList                 MAKEINTRESOURCE(133)
#define IDF_L_ReadLoadResolutions            MAKEINTRESOURCE(134)
#define IDF_L_SetLoadResolution              MAKEINTRESOURCE(135)
#define IDF_L_GetLoadResolution              MAKEINTRESOURCE(136)
#define IDF_L_ReadFileCommentMemory          MAKEINTRESOURCE(137)
#define IDF_L_GetTag                         MAKEINTRESOURCE(138)
#define IDF_L_SetTag                         MAKEINTRESOURCE(139)
#define IDF_L_ReadFileTag                    MAKEINTRESOURCE(140)
#define IDF_L_ReadFileTagMemory              MAKEINTRESOURCE(141)
#define IDF_L_GetFileCommentSize             MAKEINTRESOURCE(142)
#define IDF_L_ReadFileCommentExt             MAKEINTRESOURCE(143)
#define IDF_L_WriteFileCommentExt            MAKEINTRESOURCE(144)
#define IDF_L_ReadFileStamp                  MAKEINTRESOURCE(145)
#define IDF_L_WriteFileStamp                 MAKEINTRESOURCE(146)
#define IDF_L_ReadFileTransforms             MAKEINTRESOURCE(147)
#define IDF_L_WriteFileTransforms            MAKEINTRESOURCE(148)
#define IDF_L_LoadFileTile                   MAKEINTRESOURCE(149)
#define IDF_L_SaveFileTile                   MAKEINTRESOURCE(150)
#define IDF_L_PreLoadFilters                 MAKEINTRESOURCE(151)
#define IDF_L_IgnoreFilters                  MAKEINTRESOURCE(152)
#define IDF_L_StartSaveData                  MAKEINTRESOURCE(153)
#define IDF_L_SaveData                       MAKEINTRESOURCE(154)
#define IDF_L_StopSaveData                   MAKEINTRESOURCE(155)
#define IDF_L_DeletePage                     MAKEINTRESOURCE(156)
#define IDF_L_SaveFileMemory                 MAKEINTRESOURCE(157)
#define IDF_L_GetSaveResolution              MAKEINTRESOURCE(158)
#define IDF_L_SetSaveResolution              MAKEINTRESOURCE(159)
#define IDF_L_2DSetViewport                  MAKEINTRESOURCE(160)
#define IDF_L_2DGetViewport                  MAKEINTRESOURCE(161)
#define IDF_L_2DSetViewMode                  MAKEINTRESOURCE(162)
#define IDF_L_2DGetViewMode                  MAKEINTRESOURCE(163)
#define IDF_L_VecLoadFile                    MAKEINTRESOURCE(164)
#define IDF_L_VecLoadMemory                  MAKEINTRESOURCE(165)
#define IDF_L_VecStartFeedLoad               MAKEINTRESOURCE(166)
#define IDF_L_VecFeedLoad                    MAKEINTRESOURCE(167)
#define IDF_L_VecStopFeedLoad                MAKEINTRESOURCE(168)
#define IDF_L_VecSaveFile                    MAKEINTRESOURCE(169)
#define IDF_L_VecSaveMemory                  MAKEINTRESOURCE(170)
#define IDF_L_WriteFileTag                   MAKEINTRESOURCE(171)
#define IDF_L_WriteFileComment               MAKEINTRESOURCE(172)
#define IDF_L_DocStopFeedLoad                MAKEINTRESOURCE(173)
#define IDF_L_DocSaveFile                    MAKEINTRESOURCE(174)
#define IDF_L_DocSaveMemory                  MAKEINTRESOURCE(175)
#define IDF_L_StartRedirectMemory            MAKEINTRESOURCE(176)
#define IDF_L_StopRedirectMemory             MAKEINTRESOURCE(177)
#define IDF_L_StartSaveRedirectMemory        MAKEINTRESOURCE(178)
#define IDF_L_StartRedirectOffset            MAKEINTRESOURCE(179)
#define IDF_L_StopRedirectOffset             MAKEINTRESOURCE(180)
#define IDF_L_GetJ2KOptions                  MAKEINTRESOURCE(189)
#define IDF_L_SetJ2KOptions                  MAKEINTRESOURCE(190)
#define IDF_L_GetDefaultJ2KOptions           MAKEINTRESOURCE(191)
#define IDF_L_LoadBitmapResize               MAKEINTRESOURCE(194)
#define IDF_L_SaveBitmapBuffer               MAKEINTRESOURCE(195)
#define IDF_L_SaveFileBuffer                 MAKEINTRESOURCE(196)
#define IDF_L_LoadLayer                      MAKEINTRESOURCE(198)
#define IDF_L_SaveBitmapWithLayers           MAKEINTRESOURCE(199)
#define IDF_L_ReadFileExtensions             MAKEINTRESOURCE(200)
#define IDF_L_FreeExtensions                 MAKEINTRESOURCE(201)
#define IDF_L_LoadExtensionStamp             MAKEINTRESOURCE(202)
#define IDF_L_GetExtensionAudio              MAKEINTRESOURCE(203)
#define IDF_L_TransformFile                  MAKEINTRESOURCE(197)

//-----------------------------------------------------------------------------
//--LTEFX.H FUNCTIONS MACROS---------------------------------------------------
//-----------------------------------------------------------------------------
#define IDF_L_EfxPaintBitmap                MAKEINTRESOURCE(100)
#define IDF_L_EfxPaintTransition            MAKEINTRESOURCE(101)
#define IDF_L_EfxDrawFrame                  MAKEINTRESOURCE(102)
#define IDF_L_EfxGradientFillRect           MAKEINTRESOURCE(103)
#define IDF_L_EfxPatternFillRect            MAKEINTRESOURCE(104)
#define IDF_L_EfxDraw3dText                 MAKEINTRESOURCE(106)
#define IDF_L_EfxDrawRotated3dText          MAKEINTRESOURCE(107)
#define IDF_L_EfxDraw3dShape                MAKEINTRESOURCE(108)
#define IDF_L_EfxEffectBlt                  MAKEINTRESOURCE(109)
#define IDF_L_PaintDCEffect                 MAKEINTRESOURCE(110)
#define IDF_L_PaintRgnDCEffect              MAKEINTRESOURCE(111)

//-----------------------------------------------------------------------------
//--LTISI.H FUNCTIONS MACROS---------------------------------------------------
//-----------------------------------------------------------------------------
#define IDF_L_IsISISAvailable          MAKEINTRESOURCE(3)
#define IDF_L_ISISAcquire              MAKEINTRESOURCE(100)
#define IDF_L_ISISAcquireMulti         MAKEINTRESOURCE(101)
#define IDF_L_ISISSelect               MAKEINTRESOURCE(102)
#define IDF_L_ISISSetTagLong           MAKEINTRESOURCE(103)
#define IDF_L_ISISGetTagLong           MAKEINTRESOURCE(104)
#define IDF_L_ISISSetTagShort          MAKEINTRESOURCE(105)
#define IDF_L_ISISGetTagShort          MAKEINTRESOURCE(106)
#define IDF_L_ISISLoadDriver           MAKEINTRESOURCE(107)
#define IDF_L_ISISUnloadDriver         MAKEINTRESOURCE(108)
#define IDF_L_ISISSetScanOptions       MAKEINTRESOURCE(109)
#define IDF_L_ISISSetTagASCII          MAKEINTRESOURCE(110)
#define IDF_L_ISISGetTagASCII          MAKEINTRESOURCE(111)
#define IDF_L_ISISGetTagASCIIChoice    MAKEINTRESOURCE(112)
#define IDF_L_ISISGetTagLongChoice     MAKEINTRESOURCE(113)
#define IDF_L_ISISGetTagShortChoice    MAKEINTRESOURCE(114)

//-----------------------------------------------------------------------------
//--LTTWN.H FUNCTIONS MACROS---------------------------------------------------
//-----------------------------------------------------------------------------
#define IDF_L_TwainAcquire          MAKEINTRESOURCE(100)
#define IDF_L_TwainAcquireExt       MAKEINTRESOURCE(101)
#define IDF_L_TwainEnumSources      MAKEINTRESOURCE(102)
#define IDF_L_TwainSelect           MAKEINTRESOURCE(103)
#define IDF_L_TwainSetProps         MAKEINTRESOURCE(104)
#define IDF_L_TwainGetProps         MAKEINTRESOURCE(105)
#define IDF_L_IsTwainAvailable      MAKEINTRESOURCE(106)
#define IDF_L_TwainCloseSession     MAKEINTRESOURCE(107)

//-----------------------------------------------------------------------------
//--LTANN.H FUNCTIONS MACROS---------------------------------------------------
//-----------------------------------------------------------------------------
#define IDF_L_AnnCreate                      MAKEINTRESOURCE(100)
#define IDF_L_AnnDraw                        MAKEINTRESOURCE(101)
#define IDF_L_AnnDestroy                     MAKEINTRESOURCE(102)
#define IDF_L_AnnRemove                      MAKEINTRESOURCE(103)
#define IDF_L_AnnInsert                      MAKEINTRESOURCE(104)
#define IDF_L_AnnSetVisible                  MAKEINTRESOURCE(105)
#define IDF_L_AnnGetVisible                  MAKEINTRESOURCE(106)
#define IDF_L_AnnSetSelected                 MAKEINTRESOURCE(107)
#define IDF_L_AnnGetSelected                 MAKEINTRESOURCE(108)
#define IDF_L_AnnSetFontUnderline            MAKEINTRESOURCE(109)
#define IDF_L_AnnGetFontUnderline            MAKEINTRESOURCE(110)
#define IDF_L_AnnSetFontStrikeThrough        MAKEINTRESOURCE(111)
#define IDF_L_AnnGetFontStrikeThrough        MAKEINTRESOURCE(112)
#define IDF_L_AnnSetFontItalic               MAKEINTRESOURCE(113)
#define IDF_L_AnnGetFontItalic               MAKEINTRESOURCE(114)
#define IDF_L_AnnSetFontBold                 MAKEINTRESOURCE(115)
#define IDF_L_AnnGetFontBold                 MAKEINTRESOURCE(116)
#define IDF_L_AnnSetForeColor                MAKEINTRESOURCE(117)
#define IDF_L_AnnGetForeColor                MAKEINTRESOURCE(118)
#define IDF_L_AnnSetBackColor                MAKEINTRESOURCE(119)
#define IDF_L_AnnGetBackColor                MAKEINTRESOURCE(120)
#define IDF_L_AnnSetLineWidth                MAKEINTRESOURCE(121)
#define IDF_L_AnnGetLineWidth                MAKEINTRESOURCE(122)
#define IDF_L_AnnSetLineStyle                MAKEINTRESOURCE(123)
#define IDF_L_AnnGetLineStyle                MAKEINTRESOURCE(124)
#define IDF_L_AnnSetFillPattern              MAKEINTRESOURCE(125)
#define IDF_L_AnnGetFillPattern              MAKEINTRESOURCE(126)
#define IDF_L_AnnSetFillMode                 MAKEINTRESOURCE(127)
#define IDF_L_AnnGetFillMode                 MAKEINTRESOURCE(128)
#define IDF_L_AnnSetFontSize                 MAKEINTRESOURCE(129)
#define IDF_L_AnnGetFontSize                 MAKEINTRESOURCE(130)
#define IDF_L_AnnSetWnd                      MAKEINTRESOURCE(131)
#define IDF_L_AnnGetWnd                      MAKEINTRESOURCE(132)
#define IDF_L_AnnBringToFront                MAKEINTRESOURCE(133)
#define IDF_L_AnnSendToBack                  MAKEINTRESOURCE(134)
#define IDF_L_AnnSetPoints                   MAKEINTRESOURCE(135)
#define IDF_L_AnnGetType                     MAKEINTRESOURCE(136)
#define IDF_L_AnnSetTag                      MAKEINTRESOURCE(137)
#define IDF_L_AnnGetTag                      MAKEINTRESOURCE(138)
#define IDF_L_AnnGetContainer                MAKEINTRESOURCE(139)
#define IDF_L_AnnSetRect                     MAKEINTRESOURCE(140)
#define IDF_L_AnnGetRect                     MAKEINTRESOURCE(141)
#define IDF_L_AnnCreateContainer             MAKEINTRESOURCE(142)
#define IDF_L_AnnCreateItem                  MAKEINTRESOURCE(143)
#define IDF_L_AnnEnumerate                   MAKEINTRESOURCE(144)
#define IDF_L_AnnSetText                     MAKEINTRESOURCE(145)
#define IDF_L_AnnGetText                     MAKEINTRESOURCE(146)
#define IDF_L_AnnGetTextLen                  MAKEINTRESOURCE(147)
#define IDF_L_AnnDefine                      MAKEINTRESOURCE(148)
#define IDF_L_AnnSetActiveState              MAKEINTRESOURCE(149)
#define IDF_L_AnnGetActiveState              MAKEINTRESOURCE(150)
#define IDF_L_AnnSetBitmap                   MAKEINTRESOURCE(151)
#define IDF_L_AnnGetBitmap                   MAKEINTRESOURCE(152)
#define IDF_L_AnnSetFontName                 MAKEINTRESOURCE(153)
#define IDF_L_AnnGetFontName                 MAKEINTRESOURCE(154)
#define IDF_L_AnnGetFontNameLen              MAKEINTRESOURCE(155)
#define IDF_L_AnnSetUserMode                 MAKEINTRESOURCE(156)
#define IDF_L_AnnGetUserMode                 MAKEINTRESOURCE(157)
#define IDF_L_AnnHitTest                     MAKEINTRESOURCE(158)
#define IDF_L_AnnSave                        MAKEINTRESOURCE(159)
#define IDF_L_AnnLoad                        MAKEINTRESOURCE(160)
#define IDF_L_AnnFlip                        MAKEINTRESOURCE(161)
#define IDF_L_AnnReverse                     MAKEINTRESOURCE(162)
#define IDF_L_AnnRotate                      MAKEINTRESOURCE(163)
#define IDF_L_AnnGetTopContainer             MAKEINTRESOURCE(164)
#define IDF_L_AnnSelectPoint                 MAKEINTRESOURCE(165)
#define IDF_L_AnnSelectRect                  MAKEINTRESOURCE(166)
#define IDF_L_AnnToolBarWndProc              MAKEINTRESOURCE(167)
#define IDF_L_AnnCreateToolBar               MAKEINTRESOURCE(168)
#define IDF_L_AnnGetToolBarChecked           MAKEINTRESOURCE(169)
#define IDF_L_AnnSetToolBarChecked           MAKEINTRESOURCE(170)
#define IDF_L_AnnSetScalarX                  MAKEINTRESOURCE(171)
#define IDF_L_AnnSetScalarY                  MAKEINTRESOURCE(172)
#define IDF_L_AnnSetOffsetX                  MAKEINTRESOURCE(173)
#define IDF_L_AnnSetOffsetY                  MAKEINTRESOURCE(174)
#define IDF_L_AnnGetScalarX                  MAKEINTRESOURCE(175)
#define IDF_L_AnnGetScalarY                  MAKEINTRESOURCE(176)
#define IDF_L_AnnGetOffsetX                  MAKEINTRESOURCE(177)
#define IDF_L_AnnGetOffsetY                  MAKEINTRESOURCE(178)
#define IDF_L_AnnPrint                       MAKEINTRESOURCE(179)
#define IDF_L_AnnRealize                     MAKEINTRESOURCE(180)
#define IDF_L_AnnSetPolyFillMode             MAKEINTRESOURCE(181)
#define IDF_L_AnnGetPolyFillMode             MAKEINTRESOURCE(182)
#define IDF_L_AnnResize                      MAKEINTRESOURCE(183)
#define IDF_L_AnnMove                        MAKEINTRESOURCE(184)
#define IDF_L_AnnAutoWndProc                 MAKEINTRESOURCE(185)
#define IDF_L_AnnGetBoundingRect             MAKEINTRESOURCE(186)
#define IDF_L_AnnCopyFromClipboard           MAKEINTRESOURCE(187)
#define IDF_L_AnnClipboardReady              MAKEINTRESOURCE(188)
#define IDF_L_AnnSaveMemory                  MAKEINTRESOURCE(189)
#define IDF_L_AnnSaveOffset                  MAKEINTRESOURCE(190)
#define IDF_L_AnnLoadOffset                  MAKEINTRESOURCE(191)
#define IDF_L_AnnLoadMemory                  MAKEINTRESOURCE(192)
#define IDF_L_AnnCopyToClipboard             MAKEINTRESOURCE(193)
#define IDF_L_AnnGetSelectCount              MAKEINTRESOURCE(194)
#define IDF_L_AnnSetTool                     MAKEINTRESOURCE(195)
#define IDF_L_AnnGetTool                     MAKEINTRESOURCE(196)
#define IDF_L_AnnSetAutoContainer            MAKEINTRESOURCE(197)
#define IDF_L_AnnGetAutoContainer            MAKEINTRESOURCE(198)
#define IDF_L_AnnFillDlgProc                 MAKEINTRESOURCE(199)
#define IDF_L_AnnLineDlgProc                 MAKEINTRESOURCE(200)
#define IDF_L_AnnTextDlgProc                 MAKEINTRESOURCE(201)
#define IDF_L_AnnCutToClipboard              MAKEINTRESOURCE(202)
#define IDF_L_AnnGetSelectRect               MAKEINTRESOURCE(203    )
#define IDF_L_AnnSetDpiX                     MAKEINTRESOURCE(204)
#define IDF_L_AnnSetDpiY                     MAKEINTRESOURCE(205)
#define IDF_L_AnnGetDpiX                     MAKEINTRESOURCE(206)
#define IDF_L_AnnGetDpiY                     MAKEINTRESOURCE(207)
#define IDF_L_AnnCopy                        MAKEINTRESOURCE(208)
#define IDF_L_AnnUndo                        MAKEINTRESOURCE(209)
#define IDF_L_AnnSetUndoDepth                MAKEINTRESOURCE(210)
#define IDF_L_AnnGetItem                     MAKEINTRESOURCE(211)
#define IDF_L_AnnSetAutoText                 MAKEINTRESOURCE(212)
#define IDF_L_AnnGetAutoText                 MAKEINTRESOURCE(213)
#define IDF_L_AnnGetAutoTextLen              MAKEINTRESOURCE(214)
#define IDF_L_AnnGetToolBarButtonVisible     MAKEINTRESOURCE(215)
#define IDF_L_AnnSetToolBarButtonVisible     MAKEINTRESOURCE(216)
#define IDF_L_AnnSetAutoMenuEnable           MAKEINTRESOURCE(217)
#define IDF_L_AnnGetAutoMenuEnable           MAKEINTRESOURCE(218)
#define IDF_L_AnnSetAutoDrawEnable           MAKEINTRESOURCE(219)
#define IDF_L_AnnGetAutoDrawEnable           MAKEINTRESOURCE(220)
#define IDF_L_AnnGetPoints                   MAKEINTRESOURCE(221)
#define IDF_L_AnnGetPointCount               MAKEINTRESOURCE(222)
#define IDF_L_AnnGetSelectItems              MAKEINTRESOURCE(223)
#define IDF_L_AnnGetROP2                     MAKEINTRESOURCE(224)
#define IDF_L_AnnSetROP2                     MAKEINTRESOURCE(225)
#define IDF_L_AnnROP2DlgProc                 MAKEINTRESOURCE(226)
#define IDF_L_AnnGetTransparent              MAKEINTRESOURCE(227)
#define IDF_L_AnnSetTransparent              MAKEINTRESOURCE(228)
#define IDF_L_AnnLock                        MAKEINTRESOURCE(229)
#define IDF_L_AnnUnlock                      MAKEINTRESOURCE(230)
#define IDF_L_AnnShowLockedIcon              MAKEINTRESOURCE(231)
#define IDF_L_AnnGetLocked                   MAKEINTRESOURCE(232)
#define IDF_L_AnnUnrealize                   MAKEINTRESOURCE(233)
#define IDF_L_AnnPasswordDlgProc             MAKEINTRESOURCE(234)
#define IDF_L_AnnSetHyperlink                MAKEINTRESOURCE(235)
#define IDF_L_AnnGetHyperlink                MAKEINTRESOURCE(236)
#define IDF_L_AnnGetHyperlinkLen             MAKEINTRESOURCE(237)
#define IDF_L_AnnSetHyperlinkMenuEnable      MAKEINTRESOURCE(238)
#define IDF_L_AnnGetHyperlinkMenuEnable      MAKEINTRESOURCE(239)
#define IDF_L_AnnSaveTag                     MAKEINTRESOURCE(240)
#define IDF_L_AnnSetBitmapDpiX               MAKEINTRESOURCE(241)
#define IDF_L_AnnSetBitmapDpiY               MAKEINTRESOURCE(242)
#define IDF_L_AnnGetBitmapDpiX               MAKEINTRESOURCE(243)
#define IDF_L_AnnGetBitmapDpiY               MAKEINTRESOURCE(244)
#define IDF_L_AnnSetUnit                     MAKEINTRESOURCE(245)
#define IDF_L_AnnGetUnit                     MAKEINTRESOURCE(246)
#define IDF_L_AnnGetUnitLen                  MAKEINTRESOURCE(247)
#define IDF_L_AnnGetDistance                 MAKEINTRESOURCE(248)
#define IDF_L_AnnSetGaugeLength              MAKEINTRESOURCE(249)
#define IDF_L_AnnGetGaugeLength              MAKEINTRESOURCE(250)
#define IDF_L_AnnSetNodes                    MAKEINTRESOURCE(251)
#define IDF_L_AnnGetNodes                    MAKEINTRESOURCE(252)
#define IDF_L_AnnSetProtractorOptions        MAKEINTRESOURCE(253)
#define IDF_L_AnnGetProtractorOptions        MAKEINTRESOURCE(254)
#define IDF_L_AnnSetName                     MAKEINTRESOURCE(255)
#define IDF_L_AnnGetName                     MAKEINTRESOURCE(256)
#define IDF_L_AnnSetShowFlags                MAKEINTRESOURCE(257)
#define IDF_L_AnnGetShowFlags                MAKEINTRESOURCE(258)
#define IDF_L_AnnGetAngle                    MAKEINTRESOURCE(259)
#define IDF_L_AnnSetMetafile                 MAKEINTRESOURCE(260)
#define IDF_L_AnnGetMetafile                 MAKEINTRESOURCE(261)
#define IDF_L_AnnSetPredefinedMetafile       MAKEINTRESOURCE(262)
#define IDF_L_AnnGetPredefinedMetafile       MAKEINTRESOURCE(263)
#define IDF_L_AnnSetSecondaryBitmap          MAKEINTRESOURCE(264)
#define IDF_L_AnnGetSecondaryBitmap          MAKEINTRESOURCE(265)
#define IDF_L_AnnSetAutoMenuItemEnable       MAKEINTRESOURCE(266)
#define IDF_L_AnnGetAutoMenuItemEnable       MAKEINTRESOURCE(267)
#define IDF_L_AnnSetAutoMenuState            MAKEINTRESOURCE(268)
#define IDF_L_AnnGetAutoMenuState            MAKEINTRESOURCE(269)
#define IDF_L_AnnSetUser                     MAKEINTRESOURCE(270)
#define IDF_L_AnnSetToolBarButtons           MAKEINTRESOURCE(271)
#define IDF_L_AnnGetToolBarButtons           MAKEINTRESOURCE(272)
#define IDF_L_AnnFreeToolBarButtons          MAKEINTRESOURCE(273)
#define IDF_L_AnnGetToolBarInfo              MAKEINTRESOURCE(274)
#define IDF_L_AnnSetAutoDefaults             MAKEINTRESOURCE(275)
#define IDF_L_AnnSetTransparentColor         MAKEINTRESOURCE(276)
#define IDF_L_AnnGetTransparentColor         MAKEINTRESOURCE(277)
#define IDF_L_AnnSetToolBarColumns           MAKEINTRESOURCE(278)
#define IDF_L_AnnSetToolBarRows              MAKEINTRESOURCE(279)
#define IDF_L_AnnInitLibrary                 MAKEINTRESOURCE(280)
#define IDF_L_AnnGetUndoDepth                MAKEINTRESOURCE(281)
#define IDF_L_AnnGroup                       MAKEINTRESOURCE(282)
#define IDF_L_AnnUngroup                     MAKEINTRESOURCE(283)
#define IDF_L_AnnSetAutoOptions              MAKEINTRESOURCE(284)
#define IDF_L_AnnGetAutoOptions              MAKEINTRESOURCE(285)
#define IDF_L_AnnGetObjectFromTag            MAKEINTRESOURCE(286)
#define IDF_L_AnnGetRgnHandle                MAKEINTRESOURCE(287)
#define IDF_L_AnnGetArea                     MAKEINTRESOURCE(288)
#define IDF_L_AnnTermLibrary                 MAKEINTRESOURCE(289)
#define IDF_L_AnnSetAutoDialogFontSize       MAKEINTRESOURCE(290)
#define IDF_L_AnnGetAutoDialogFontSize       MAKEINTRESOURCE(291)
#define IDF_L_AnnSetGrouping                 MAKEINTRESOURCE(292)
#define IDF_L_AnnGetGrouping                 MAKEINTRESOURCE(293)
#define IDF_L_AnnSetAutoBackColor            MAKEINTRESOURCE(294)
#define IDF_L_AnnGetAutoBackColor            MAKEINTRESOURCE(295)
#define IDF_L_AnnAddUndoNode                 MAKEINTRESOURCE(296)
#define IDF_L_AnnSetAutoUndoEnable           MAKEINTRESOURCE(297)
#define IDF_L_AnnGetAutoUndoEnable           MAKEINTRESOURCE(298)
#define IDF_L_AnnSetToolBarParent            MAKEINTRESOURCE(299)
#define IDF_L_AnnFileInfo                    MAKEINTRESOURCE(300)
#define IDF_L_AnnFileInfoOffset              MAKEINTRESOURCE(301)
#define IDF_L_AnnFileInfoMemory              MAKEINTRESOURCE(302)
#define IDF_L_AnnDeletePage                  MAKEINTRESOURCE(303)
#define IDF_L_AnnDeletePageOffset            MAKEINTRESOURCE(304)
#define IDF_L_AnnDeletePageMemory            MAKEINTRESOURCE(305)

//-----------------------------------------------------------------------------
//--LTSCR.H FUNCTIONS MACROS---------------------------------------------------
//-----------------------------------------------------------------------------
#define IDF_L_SetCaptureOption          MAKEINTRESOURCE(100)
#define IDF_L_GetCaptureOption          MAKEINTRESOURCE(101)
#define IDF_L_CaptureWindow             MAKEINTRESOURCE(102)
#define IDF_L_CaptureActiveWindow       MAKEINTRESOURCE(103)
#define IDF_L_CaptureActiveClient       MAKEINTRESOURCE(104)
#define IDF_L_CaptureWallPaper          MAKEINTRESOURCE(105)
#define IDF_L_CaptureFullScreen         MAKEINTRESOURCE(106)
#define IDF_L_CaptureMenuUnderCursor    MAKEINTRESOURCE(107)
#define IDF_L_CaptureWindowUnderCursor  MAKEINTRESOURCE(108)
#define IDF_L_CaptureSelectedObject     MAKEINTRESOURCE(109)
#define IDF_L_CaptureArea               MAKEINTRESOURCE(110)
#define IDF_L_CaptureMouseCursor        MAKEINTRESOURCE(111)
#define IDF_L_CaptureSetHotKeyCallback  MAKEINTRESOURCE(112)
#define IDF_L_SetCaptureOptionDlg       MAKEINTRESOURCE(113)
#define IDF_L_CaptureAreaOptionDlg      MAKEINTRESOURCE(114)
#define IDF_L_CaptureObjectOptionDlg    MAKEINTRESOURCE(115)
#define IDF_L_GetDefaultAreaOption      MAKEINTRESOURCE(116)
#define IDF_L_GetDefaultObjectOption    MAKEINTRESOURCE(117)
#define IDF_L_StopCapture               MAKEINTRESOURCE(118)
#define IDF_L_CaptureFromExeDlg         MAKEINTRESOURCE(119)
#define IDF_L_CaptureFromExe            MAKEINTRESOURCE(120)
#define IDF_L_CaptureGetResCount        MAKEINTRESOURCE(121)
#define IDF_L_IsCaptureActive           MAKEINTRESOURCE(122)

//-----------------------------------------------------------------------------
//--LTNET.H FUNCTIONS MACROS---------------------------------------------------
//-----------------------------------------------------------------------------
#define IDF_L_InetConnect              MAKEINTRESOURCE(100)
#define IDF_L_InetClose                MAKEINTRESOURCE(101)
#define IDF_L_InetServerInit           MAKEINTRESOURCE(102)
#define IDF_L_InetSendData             MAKEINTRESOURCE(103)
#define IDF_L_InetReadData             MAKEINTRESOURCE(104)
#define IDF_L_InetUUencode             MAKEINTRESOURCE(105)
#define IDF_L_InetUUdecode             MAKEINTRESOURCE(106)
#define IDF_L_InetGetHostName          MAKEINTRESOURCE(107)
#define IDF_L_InetAcceptConnect        MAKEINTRESOURCE(108)
#define IDF_L_InetSendBitmap           MAKEINTRESOURCE(109)
#define IDF_L_InetSendMMData           MAKEINTRESOURCE(110)
#define IDF_L_InetAutoProcess          MAKEINTRESOURCE(111)
#define IDF_L_InetSendRawData          MAKEINTRESOURCE(112)
#define IDF_L_InetGetQueueSize         MAKEINTRESOURCE(113)
#define IDF_L_InetClearQueue           MAKEINTRESOURCE(114)
#define IDF_L_InetStartUp              MAKEINTRESOURCE(115)
#define IDF_L_InetShutDown             MAKEINTRESOURCE(116)
#define IDF_L_InetSendSound            MAKEINTRESOURCE(117)
#define IDF_L_InetCloseSockets         MAKEINTRESOURCE(118)
#define IDF_L_InetAttachToSocket       MAKEINTRESOURCE(119)
#define IDF_L_InetDetachFromSocket     MAKEINTRESOURCE(120)
#define IDF_L_InetCreatePacket         MAKEINTRESOURCE(121)
#define IDF_L_InetFreePacket           MAKEINTRESOURCE(122)
#define IDF_L_InetSendCmd              MAKEINTRESOURCE(123)
#define IDF_L_InetSendRsp              MAKEINTRESOURCE(124)
#define IDF_L_InetSendSaveRsp          MAKEINTRESOURCE(125)
#define IDF_L_InetSendLoadCmd          MAKEINTRESOURCE(126)
#define IDF_L_InetSendLoadRsp          MAKEINTRESOURCE(127)
#define IDF_L_InetSendCloseWinCmd      MAKEINTRESOURCE(128)
#define IDF_L_InetSendCloseWinRsp      MAKEINTRESOURCE(129)
#define IDF_L_InetSendSaveCmd          MAKEINTRESOURCE(130)
#define IDF_L_InetSendCreateWinCmd     MAKEINTRESOURCE(131)
#define IDF_L_InetSendCreateWinRsp     MAKEINTRESOURCE(132)
#define IDF_L_InetSendSizeWinCmd       MAKEINTRESOURCE(133)
#define IDF_L_InetSendSizeWinRsp       MAKEINTRESOURCE(134)
#define IDF_L_InetSendAttachBitmapCmd  MAKEINTRESOURCE(135)
#define IDF_L_InetSendAttachBitmapRsp  MAKEINTRESOURCE(136)
#define IDF_L_InetSetCommandCallback   MAKEINTRESOURCE(137)
#define IDF_L_InetSetResponseCallback  MAKEINTRESOURCE(138)
#define IDF_L_InetSendFreeBitmapCmd    MAKEINTRESOURCE(139)
#define IDF_L_InetSendFreeBitmapRsp    MAKEINTRESOURCE(140)
#define IDF_L_InetSendShowWinCmd       MAKEINTRESOURCE(141)
#define IDF_L_InetSendShowWinRsp       MAKEINTRESOURCE(142)
#define IDF_L_InetSendSetRectCmd       MAKEINTRESOURCE(143)
#define IDF_L_InetSendSetRectRsp       MAKEINTRESOURCE(144)
#define IDF_L_InetSetCallback          MAKEINTRESOURCE(145)
#define IDF_L_InetGetCallback          MAKEINTRESOURCE(146)
#define IDF_L_InetCreatePacketFromParams MAKEINTRESOURCE(147)
#define IDF_L_InetGetParameters        MAKEINTRESOURCE(148)
#define IDF_L_InetCopyParameters       MAKEINTRESOURCE(149)
#define IDF_L_InetFreeParameters       MAKEINTRESOURCE(150)


//-----------------------------------------------------------------------------
//--LTWEB.H FUNCTIONS MACROS---------------------------------------------------
//-----------------------------------------------------------------------------

#define IDF_L_InetHttpConnect          MAKEINTRESOURCE(100)
#define IDF_L_InetHttpDisconnect       MAKEINTRESOURCE(101)
#define IDF_L_InetHttpOpenRequest      MAKEINTRESOURCE(102)
#define IDF_L_InetHttpCloseRequest     MAKEINTRESOURCE(103)
#define IDF_L_InetHttpSendBitmap       MAKEINTRESOURCE(104)
#define IDF_L_InetHttpSendData         MAKEINTRESOURCE(105)
#define IDF_L_InetHttpSendForm         MAKEINTRESOURCE(106)
#define IDF_L_InetHttpSendRequest      MAKEINTRESOURCE(107)
#define IDF_L_InetHttpGetResponse      MAKEINTRESOURCE(108)
#define IDF_L_InetHttpGetServerStatus  MAKEINTRESOURCE(109)
#define IDF_L_InetFtpConnect           MAKEINTRESOURCE(110)
#define IDF_L_InetFtpDisconnect        MAKEINTRESOURCE(111)
#define IDF_L_InetFtpSendFile          MAKEINTRESOURCE(112)
#define IDF_L_InetFtpGetFile           MAKEINTRESOURCE(113)
#define IDF_L_InetFtpRenameFile        MAKEINTRESOURCE(114)
#define IDF_L_InetFtpDeleteFile        MAKEINTRESOURCE(115)
#define IDF_L_InetFtpCreateDir         MAKEINTRESOURCE(116)
#define IDF_L_InetFtpDeleteDir         MAKEINTRESOURCE(117)
#define IDF_L_InetFtpGetCurrentDir     MAKEINTRESOURCE(118)
#define IDF_L_InetFtpBrowseDir         MAKEINTRESOURCE(119)
#define IDF_L_InetFtpChangeDir         MAKEINTRESOURCE(120)
#define IDF_L_InetFtpSendBitmap        MAKEINTRESOURCE(121)

//-----------------------------------------------------------------------------
//--LTDLG.H FUNCTIONS MACROS---------------------------------------------------
//-----------------------------------------------------------------------------
#define IDF_L_DlgFileOpen            MAKEINTRESOURCE(106)
#define IDF_L_DlgGetAngle            MAKEINTRESOURCE(114)
#define IDF_L_DlgGetSize             MAKEINTRESOURCE(116)
#define IDF_L_DlgGetFilter           MAKEINTRESOURCE(126)
#define IDF_L_DlgGetChange           MAKEINTRESOURCE(109)
#define IDF_L_DlgGetGamma            MAKEINTRESOURCE(127)
#define IDF_L_DlgGetNoise            MAKEINTRESOURCE(108)
#define IDF_L_DlgGetEmboss           MAKEINTRESOURCE(125)
#define IDF_L_DlgGetRange            MAKEINTRESOURCE(128)
#define IDF_L_DlgColorRes            MAKEINTRESOURCE(112)
#define IDF_L_DlgFileSave            MAKEINTRESOURCE(107)
#define IDF_L_DlgWindowLevel         MAKEINTRESOURCE(140)
#define IDF_L_DlgGetEffect           MAKEINTRESOURCE(136)
#define IDF_L_DlgGetShape            MAKEINTRESOURCE(134)
#define IDF_L_DlgGetText             MAKEINTRESOURCE(139)
#define IDF_L_DlgGetGradient         MAKEINTRESOURCE(138)
#define IDF_L_DlgGetTransition       MAKEINTRESOURCE(137)
#define IDF_L_DlgGetDirectory        MAKEINTRESOURCE(135)
#define IDF_L_DlgContourFilter       MAKEINTRESOURCE(129)
#define IDF_L_DlgGetStringLen        MAKEINTRESOURCE(101)
#define IDF_L_DlgGetString           MAKEINTRESOURCE(103)
#define IDF_L_DlgSetString           MAKEINTRESOURCE(102)
#define IDF_L_DlgSetFont             MAKEINTRESOURCE(100)
#define IDF_L_DlgHalftone            MAKEINTRESOURCE(110)

//-----------------------------------------------------------------------------
//--LTTMB.H FUNCTIONS MACROS---------------------------------------------------
//-----------------------------------------------------------------------------
#define IDF_L_BrowseDir              MAKEINTRESOURCE(100)

//-----------------------------------------------------------------------------
//--LTLST.H FUNCTIONS MACROS---------------------------------------------------
//-----------------------------------------------------------------------------
#define IDF_L_CreateImageListControl MAKEINTRESOURCE(100)
#define IDF_L_UseImageListControl    MAKEINTRESOURCE(101)

//-----------------------------------------------------------------------------
//--LVKRN.H FUNCTIONS MACROS---------------------------------------------------
//-----------------------------------------------------------------------------
#define IDF_L_VecDuplicateObjectDescriptor   MAKEINTRESOURCE(1220)
//Do not remove above

#define     IDF_L_VecInit                        MAKEINTRESOURCE( 100 )
#define     IDF_L_VecFree                        MAKEINTRESOURCE( 101 )
#define     IDF_L_VecEmpty                       MAKEINTRESOURCE( 102 )
#define     IDF_L_VecIsEmpty                     MAKEINTRESOURCE( 103 )
#define     IDF_L_VecCopy                        MAKEINTRESOURCE( 104 )
#define     IDF_L_VecSetViewport                 MAKEINTRESOURCE( 105 )
#define     IDF_L_VecGetViewport                 MAKEINTRESOURCE( 106 )
#define     IDF_L_VecSetPan                      MAKEINTRESOURCE( 107 )
#define     IDF_L_VecGetPan                      MAKEINTRESOURCE( 108 )
#define     IDF_L_VecPaint                       MAKEINTRESOURCE( 109 )
#define     IDF_L_VecRealize                     MAKEINTRESOURCE( 110 )
#define     IDF_L_VecIs3D                        MAKEINTRESOURCE( 111 )
#define     IDF_L_VecIsLocked                    MAKEINTRESOURCE( 112 )
#define     IDF_L_VecSetLocked                   MAKEINTRESOURCE( 113 )
#define     IDF_L_VecSetBackgroundColor          MAKEINTRESOURCE( 114 )
#define     IDF_L_VecGetBackgroundColor          MAKEINTRESOURCE( 115 )
#define     IDF_L_VecLogicalToPhysical           MAKEINTRESOURCE( 116 )
#define     IDF_L_VecPhysicalToLogical           MAKEINTRESOURCE( 117 )
#define     IDF_L_VecSetPalette                  MAKEINTRESOURCE( 118 )
#define     IDF_L_VecGetPalette                  MAKEINTRESOURCE( 119 )
#define     IDF_L_VecSetViewMode                 MAKEINTRESOURCE( 120 )
#define     IDF_L_VecGetViewMode                 MAKEINTRESOURCE( 121 )
#define     IDF_L_VecGetSize                     MAKEINTRESOURCE( 122 )
#define     IDF_L_VecIsDirtyTransformAndCamera   MAKEINTRESOURCE( 123 )
#define     IDF_L_VecPaintDC                     MAKEINTRESOURCE( 124 )
#define     IDF_L_VecSetDisplayOptions           MAKEINTRESOURCE( 125 )
#define     IDF_L_VecGetDisplayOptions           MAKEINTRESOURCE( 126 )
#define     IDF_L_VecInvertColors                MAKEINTRESOURCE( 127 )
#define     IDF_L_VecSetTranslation              MAKEINTRESOURCE( 200 )
#define     IDF_L_VecGetTranslation              MAKEINTRESOURCE( 201 )
#define     IDF_L_VecSetRotation                 MAKEINTRESOURCE( 202 )
#define     IDF_L_VecGetRotation                 MAKEINTRESOURCE( 203 )
#define     IDF_L_VecSetScale                    MAKEINTRESOURCE( 204 )
#define     IDF_L_VecGetScale                    MAKEINTRESOURCE( 205 )
#define     IDF_L_VecSetOrigin                   MAKEINTRESOURCE( 206 )
#define     IDF_L_VecGetOrigin                   MAKEINTRESOURCE( 207 )
#define     IDF_L_VecApplyTransformation         MAKEINTRESOURCE( 208 )
#define     IDF_L_VecZoomRect                    MAKEINTRESOURCE( 209 )
#define     IDF_L_VecSetBindVerticesMode         MAKEINTRESOURCE( 300 )
#define     IDF_L_VecGetBindVerticesMode         MAKEINTRESOURCE( 301 )
#define     IDF_L_VecSetParallelogram            MAKEINTRESOURCE( 302 )
#define     IDF_L_VecGetParallelogram            MAKEINTRESOURCE( 303 )
#define     IDF_L_VecEnumVertices                MAKEINTRESOURCE( 304 )
#define     IDF_L_VecSetCamera                   MAKEINTRESOURCE( 400 )
#define     IDF_L_VecGetCamera                   MAKEINTRESOURCE( 401 )
#define     IDF_L_VecConvertToWMF                MAKEINTRESOURCE( 500 )
#define     IDF_L_VecConvertFromWMF              MAKEINTRESOURCE( 501 )
#define     IDF_L_VecConvertToEMF                MAKEINTRESOURCE( 502 )
#define     IDF_L_VecConvertFromEMF              MAKEINTRESOURCE( 503 )
#define     IDF_L_VecGetEngine                   MAKEINTRESOURCE( 600 )
#define     IDF_L_VecAttachToWindow              MAKEINTRESOURCE( 601 )
#define     IDF_L_VecSetMarker                   MAKEINTRESOURCE( 700 )
#define     IDF_L_VecGetMarker                   MAKEINTRESOURCE( 701 )
#define     IDF_L_VecSetUnit                     MAKEINTRESOURCE( 750 )
#define     IDF_L_VecGetUnit                     MAKEINTRESOURCE( 751 )
#define     IDF_L_VecConvertPointToUnits         MAKEINTRESOURCE( 752 )
#define     IDF_L_VecConvertPointFromUnits       MAKEINTRESOURCE( 753 )
#define     IDF_L_VecSetHitTest                  MAKEINTRESOURCE( 800 )
#define     IDF_L_VecGetHitTest                  MAKEINTRESOURCE( 801 )
#define     IDF_L_VecHitTest                     MAKEINTRESOURCE( 802 )
#define     IDF_L_VecSetPolygonMode              MAKEINTRESOURCE( 900 )
#define     IDF_L_VecGetPolygonMode              MAKEINTRESOURCE( 901 )
#define     IDF_L_VecSetUseLights                MAKEINTRESOURCE( 902 )
#define     IDF_L_VecGetUseLights                MAKEINTRESOURCE( 903 )
#define     IDF_L_VecSetAmbientColor             MAKEINTRESOURCE( 904 )
#define     IDF_L_VecGetAmbientColor             MAKEINTRESOURCE( 905 )
#define     IDF_L_VecClipboardReady              MAKEINTRESOURCE( 1000 )
#define     IDF_L_VecCopyToClipboard             MAKEINTRESOURCE( 1001 )
#define     IDF_L_VecCopyFromClipboard           MAKEINTRESOURCE( 1002 )
#define     IDF_L_VecAddLayer                    MAKEINTRESOURCE( 1100 )
#define     IDF_L_VecDeleteLayer                 MAKEINTRESOURCE( 1101 )
#define     IDF_L_VecEmptyLayer                  MAKEINTRESOURCE( 1102 )
#define     IDF_L_VecCopyLayer                   MAKEINTRESOURCE( 1103 )
#define     IDF_L_VecGetLayerByName              MAKEINTRESOURCE( 1104 )
#define     IDF_L_VecGetLayerCount               MAKEINTRESOURCE( 1105 )
#define     IDF_L_VecGetLayerByIndex             MAKEINTRESOURCE( 1106 )
#define     IDF_L_VecGetLayer                    MAKEINTRESOURCE( 1107 )
#define     IDF_L_VecFreeLayer                   MAKEINTRESOURCE( 1108 )
#define     IDF_L_VecSetLayer                    MAKEINTRESOURCE( 1109 )
#define     IDF_L_VecSetActiveLayer              MAKEINTRESOURCE( 1110 )
#define     IDF_L_VecGetActiveLayer              MAKEINTRESOURCE( 1111 )
#define     IDF_L_VecEnumLayers                  MAKEINTRESOURCE( 1112 )
#define     IDF_L_VecAddGroup                    MAKEINTRESOURCE( 1300 )
#define     IDF_L_VecDeleteGroup                 MAKEINTRESOURCE( 1301 )
#define     IDF_L_VecDeleteGroupClones           MAKEINTRESOURCE( 1302 )
#define     IDF_L_VecEmptyGroup                  MAKEINTRESOURCE( 1303 )
#define     IDF_L_VecCopyGroup                   MAKEINTRESOURCE( 1304 )
#define     IDF_L_VecGetGroupByName              MAKEINTRESOURCE( 1305 )
#define     IDF_L_VecGetGroupCount               MAKEINTRESOURCE( 1306 )
#define     IDF_L_VecGetGroupByIndex             MAKEINTRESOURCE( 1307 )
#define     IDF_L_VecGetGroup                    MAKEINTRESOURCE( 1308 )
#define     IDF_L_VecFreeGroup                   MAKEINTRESOURCE( 1309 )
#define     IDF_L_VecSetGroup                    MAKEINTRESOURCE( 1310 )
#define     IDF_L_VecEnumGroups                  MAKEINTRESOURCE( 1311 )
#define     IDF_L_VecInitObject                  MAKEINTRESOURCE( 1200 )
#define     IDF_L_VecAddObject                   MAKEINTRESOURCE( 1201 )
#define     IDF_L_VecDeleteObject                MAKEINTRESOURCE( 1202 )
#define     IDF_L_VecCopyObject                  MAKEINTRESOURCE( 1203 )
#define     IDF_L_VecGetObject                   MAKEINTRESOURCE( 1205 )
#define     IDF_L_VecFreeObject                  MAKEINTRESOURCE( 1206 )
#define     IDF_L_VecSetObject                   MAKEINTRESOURCE( 1207 )
#define     IDF_L_VecExplodeObject               MAKEINTRESOURCE( 1208 )
#define     IDF_L_VecGetObjectParallelogram      MAKEINTRESOURCE( 1209 )
#define     IDF_L_VecGetObjectRect               MAKEINTRESOURCE( 1210 )
#define     IDF_L_VecIsObjectInsideParallelogram MAKEINTRESOURCE( 1211 )
#define     IDF_L_VecIsObjectInsideRect          MAKEINTRESOURCE( 1212 )
#define     IDF_L_VecSelectObject                MAKEINTRESOURCE( 1213 )
#define     IDF_L_VecIsObjectSelected            MAKEINTRESOURCE( 1214 )
#define     IDF_L_VecEnumObjects                 MAKEINTRESOURCE( 1215 )
#define     IDF_L_VecEnumObjectsInLayer          MAKEINTRESOURCE( 1216 )
#define     IDF_L_VecObjectGetPolyPoint          MAKEINTRESOURCE( 1217 )
#define     IDF_L_VecCalculateTextParallelogram  MAKEINTRESOURCE( 1218 )
#define     IDF_L_VecIsObjectValidForAdding      MAKEINTRESOURCE( 1219 )
//#define     IDF_L_VecDuplicateObjectDescriptor   MAKEINTRESOURCE( 1220 )
#define     IDF_L_VecSetObjectAttributes         MAKEINTRESOURCE( 1221 )
#define     IDF_L_VecGetObjectAttributes         MAKEINTRESOURCE( 1222 )
#define     IDF_L_VecAddObjectToGroup            MAKEINTRESOURCE( 1223 )
#define     IDF_L_VecEnumObjectsInGroup          MAKEINTRESOURCE( 1224 )
#define     IDF_L_VecHideObject                  MAKEINTRESOURCE( 1225 )
#define     IDF_L_VecIsObjectHidden              MAKEINTRESOURCE( 1226 )
#define     IDF_L_VecEnumObjectsRaw              MAKEINTRESOURCE( 1227 )
#define     IDF_L_VecCreatePolyPoint             MAKEINTRESOURCE( 1228 )
#define     IDF_L_VecFreePolyPoint               MAKEINTRESOURCE( 1229 )
#define     IDF_L_VecSetObjectTooltip            MAKEINTRESOURCE( 1500 )
#define     IDF_L_VecGetObjectTooltip            MAKEINTRESOURCE( 1501 )
#define     IDF_L_VecShowObjectTooltip           MAKEINTRESOURCE( 1502 )
#define     IDF_L_VecHideObjectTooltip           MAKEINTRESOURCE( 1503 )
#define     IDF_L_VecAddHyperlink                MAKEINTRESOURCE( 1504 )
#define     IDF_L_VecSetHyperlink                MAKEINTRESOURCE( 1505 )
#define     IDF_L_VecGetHyperlink                MAKEINTRESOURCE( 1506 )
#define     IDF_L_VecGetHyperlinkCount           MAKEINTRESOURCE( 1507 )
#define     IDF_L_VecGotoHyperlink               MAKEINTRESOURCE( 1508 )
#define     IDF_L_VecSetObjectDescription        MAKEINTRESOURCE( 1509 )
#define     IDF_L_VecGetObjectDescription        MAKEINTRESOURCE( 1510 )
#define     IDF_L_VecSetObjectViewContext        MAKEINTRESOURCE( 1511 )
#define     IDF_L_VecGetObjectViewContext        MAKEINTRESOURCE( 1512 )
#define     IDF_L_VecRemoveObjectViewContext     MAKEINTRESOURCE( 1513 )
#define     IDF_L_VecArrayReset                  MAKEINTRESOURCE( 2000 )
#define     IDF_L_VecArrayFree                   MAKEINTRESOURCE( 2001 )
#define     IDF_L_VecArrayCopy                   MAKEINTRESOURCE( 2002 )
#define     IDF_L_VecArrayAdd                    MAKEINTRESOURCE( 2003 )
#define     IDF_L_VecArrayReplace                MAKEINTRESOURCE( 2004 )
#define     IDF_L_VecArrayGet                    MAKEINTRESOURCE( 2005 )
#define     IDF_L_VecArrayRemove                 MAKEINTRESOURCE( 2006 )
#define     IDF_L_VecArrayRemoveAll              MAKEINTRESOURCE( 2007 )
#define     IDF_L_VecArrayDumpSave               MAKEINTRESOURCE( 2008 )
#define     IDF_L_VecArrayAddFast                MAKEINTRESOURCE( 2009 )
#define     IDF_L_VecPointReset                  MAKEINTRESOURCE( 2100 )
#define     IDF_L_VecPointCopy                   MAKEINTRESOURCE( 2101 )
#define     IDF_L_VecPointIsEqual                MAKEINTRESOURCE( 2102 )
#define     IDF_L_VecPointMin                    MAKEINTRESOURCE( 2103 )
#define     IDF_L_VecPointMax                    MAKEINTRESOURCE( 2104 )
#define     IDF_L_VecPointMagnitude              MAKEINTRESOURCE( 2105 )
#define     IDF_L_VecPointSubtract               MAKEINTRESOURCE( 2106 )
#define     IDF_L_VecPointAdd                    MAKEINTRESOURCE( 2107 )
#define     IDF_L_VecPointDot                    MAKEINTRESOURCE( 2108 )
#define     IDF_L_VecPointCross                  MAKEINTRESOURCE( 2109 )
#define     IDF_L_VecPointFindAngle              MAKEINTRESOURCE( 2110 )
#define     IDF_L_VecPointNormalize              MAKEINTRESOURCE( 2111 )
#define     IDF_L_VecMatrixReset                 MAKEINTRESOURCE( 2200 )
#define     IDF_L_VecMatrixSet                   MAKEINTRESOURCE( 2201 )
#define     IDF_L_VecMatrixCopy                  MAKEINTRESOURCE( 2202 )
#define     IDF_L_VecMatrixIdentity              MAKEINTRESOURCE( 2203 )
#define     IDF_L_VecMatrixScale                 MAKEINTRESOURCE( 2204 )
#define     IDF_L_VecMatrixMultiply              MAKEINTRESOURCE( 2205 )
#define     IDF_L_VecMatrixMulByPoint            MAKEINTRESOURCE( 2206 )
#define     IDF_L_VecMatrixInverse               MAKEINTRESOURCE( 2207 )
#define     IDF_L_VecMatrixRotation              MAKEINTRESOURCE( 2208 )
#define     IDF_L_VecRenderDC                    MAKEINTRESOURCE( 2300 )
#define     IDF_L_VecWriterReset                 MAKEINTRESOURCE( 2400 )
#define     IDF_L_VecWriterOpen                  MAKEINTRESOURCE( 2401 )
#define     IDF_L_VecWriterClose                 MAKEINTRESOURCE( 2402 )
#define     IDF_L_VecWriterAdd                   MAKEINTRESOURCE( 2403 )
#define     IDF_L_VecDumpLoad                    MAKEINTRESOURCE( 2500 )
#define     IDF_L_VecDumpSave                    MAKEINTRESOURCE( 2501 )
#define     IDF_L_VecDumpLoadVector              MAKEINTRESOURCE( 2502 )
#define     IDF_L_VecDumpSaveVector              MAKEINTRESOURCE( 2503 )
#define     IDF_L_VecDumpLoadRaster              MAKEINTRESOURCE( 2504 )
#define     IDF_L_VecDumpSaveRaster              MAKEINTRESOURCE( 2505 )
#define     IDF_L_VecSetEventCallback            MAKEINTRESOURCE( 2600 )
#define     IDF_L_VecEvent                       MAKEINTRESOURCE( 2601 )

//-----------------------------------------------------------------------------
//--LVDLG.H FUNCTIONS MACROS---------------------------------------------------
//-----------------------------------------------------------------------------
#define     IDF_L_VecDlgRotate                   MAKEINTRESOURCE( 100 )
#define     IDF_L_VecDlgScale                    MAKEINTRESOURCE( 101 )
#define     IDF_L_VecDlgTranslate                MAKEINTRESOURCE( 102 )

#define     IDF_L_VecDlgCamera                   MAKEINTRESOURCE( 103 )
#define     IDF_L_VecDlgRender                   MAKEINTRESOURCE( 104 )
#define     IDF_L_VecDlgViewMode                 MAKEINTRESOURCE( 105 )
#define     IDF_L_VecDlgHitTest                  MAKEINTRESOURCE( 106 )

#define     IDF_L_VecDlgEditAllLayers            MAKEINTRESOURCE( 200 )
#define     IDF_L_VecDlgNewLayer                 MAKEINTRESOURCE( 201 )
#define     IDF_L_VecDlgEditLayer                MAKEINTRESOURCE( 202 )

#define     IDF_L_VecDlgEditAllGroups            MAKEINTRESOURCE( 250 )
#define     IDF_L_VecDlgNewGroup                 MAKEINTRESOURCE( 251 )
#define     IDF_L_VecDlgEditGroup                MAKEINTRESOURCE( 252 )

#define     IDF_L_VecDlgNewObject                MAKEINTRESOURCE( 300 )
#define     IDF_L_VecDlgEditObject               MAKEINTRESOURCE( 301 )
#define     IDF_L_VecDlgObjectAttributes         MAKEINTRESOURCE( 302 )

#define     IDF_L_VecDlgGetStringLen             MAKEINTRESOURCE( 2000 )
#define     IDF_L_VecDlgGetString                MAKEINTRESOURCE( 2001 )
#define     IDF_L_VecDlgSetString                MAKEINTRESOURCE( 2002 )
#define     IDF_L_VecDlgSetFont                  MAKEINTRESOURCE( 2003 )

//-----------------------------------------------------------------------------
//--LTBAR.H FUNCTIONS MACROS---------------------------------------------------
//-----------------------------------------------------------------------------
#define IDF_L_BarCodeInit                 MAKEINTRESOURCE(100)
#define IDF_L_BarCodeExit                 MAKEINTRESOURCE(101)
#define IDF_L_BarCodeRead                 MAKEINTRESOURCE(102)
#define IDF_L_BarCodeWrite                MAKEINTRESOURCE(103)
#define IDF_L_BarCodeFree                 MAKEINTRESOURCE(104)
#define IDF_L_BarCodeIsDuplicated         MAKEINTRESOURCE(105)
#define IDF_L_BarCodeGetDuplicated        MAKEINTRESOURCE(106)
#define IDF_L_BarCodeGetNextDuplicated    MAKEINTRESOURCE(107)
#define IDF_L_BarCodeGetFirstDuplicated   MAKEINTRESOURCE(108)
#define IDF_L_BarCodeVersionInfo          MAKEINTRESOURCE(109)
#define IDF_L_BarCodeWriteExt             MAKEINTRESOURCE(110)

//-----------------------------------------------------------------------------
//--LTAUT.H FUNCTIONS MACROS---------------------------------------------------
//-----------------------------------------------------------------------------
#define IDF_L_AutIsValid               MAKEINTRESOURCE(301)
#define IDF_L_AutInit                  MAKEINTRESOURCE(302)
#define IDF_L_AutCreate                MAKEINTRESOURCE(303)
#define IDF_L_AutFree                  MAKEINTRESOURCE(304)
#define IDF_L_AutSetUndoLevel          MAKEINTRESOURCE(307)
#define IDF_L_AutGetUndoLevel          MAKEINTRESOURCE(308)
#define IDF_L_AutCanUndo               MAKEINTRESOURCE(309)
#define IDF_L_AutCanRedo               MAKEINTRESOURCE(310)
#define IDF_L_AutUndo                  MAKEINTRESOURCE(311)
#define IDF_L_AutRedo                  MAKEINTRESOURCE(312)
#define IDF_L_AutSetUndoEnabled        MAKEINTRESOURCE(801)
#define IDF_L_AutAddUndoNode           MAKEINTRESOURCE(802)
#define IDF_L_AutClipboardDataReady    MAKEINTRESOURCE(313)
#define IDF_L_AutCut                   MAKEINTRESOURCE(314)
#define IDF_L_AutCopy                  MAKEINTRESOURCE(315)
#define IDF_L_AutPaste                 MAKEINTRESOURCE(316)
#define IDF_L_AutDelete                MAKEINTRESOURCE(317)
#define IDF_L_AutPrint                 MAKEINTRESOURCE(318)
#define IDF_L_AutSelect                MAKEINTRESOURCE(319)
#define IDF_L_AutSetCurrentTool        MAKEINTRESOURCE(320)
#define IDF_L_AutGetCurrentTool        MAKEINTRESOURCE(321)
#define IDF_L_AutAddContainer          MAKEINTRESOURCE(401)
#define IDF_L_AutRemoveContainer       MAKEINTRESOURCE(402)
#define IDF_L_AutSetActiveContainer    MAKEINTRESOURCE(403)
#define IDF_L_AutGetActiveContainer    MAKEINTRESOURCE(404)
#define IDF_L_AutEnumContainers        MAKEINTRESOURCE(405)
#define IDF_L_AutSetToolbar            MAKEINTRESOURCE(501)
#define IDF_L_AutGetToolbar            MAKEINTRESOURCE(502)
#define IDF_L_AutSetPaintProperty      MAKEINTRESOURCE(601)
#define IDF_L_AutGetPaintProperty      MAKEINTRESOURCE(602)
#define IDF_L_AutSetPaintBkColor       MAKEINTRESOURCE(604)
#define IDF_L_AutGetPaintBkColor       MAKEINTRESOURCE(605)
#define IDF_L_AutSetVectorProperty     MAKEINTRESOURCE(701)
#define IDF_L_AutGetVectorProperty     MAKEINTRESOURCE(702)
#define IDF_L_AutEditVectorObject      MAKEINTRESOURCE(703)


//-----------------------------------------------------------------------------
//--LTCON.H FUNCTIONS MACROS---------------------------------------------------
//-----------------------------------------------------------------------------
#define IDF_L_ContainerIsValid               MAKEINTRESOURCE(100)
#define IDF_L_ContainerInit                  MAKEINTRESOURCE(101)
#define IDF_L_ContainerFree                  MAKEINTRESOURCE(102)
#define IDF_L_ContainerCreate                MAKEINTRESOURCE(103)
#define IDF_L_ContainerUpdate                MAKEINTRESOURCE(104)
#define IDF_L_ContainerReset                 MAKEINTRESOURCE(105)
#define IDF_L_ContainerEditObject            MAKEINTRESOURCE(106)

#define IDF_L_ContainerSetOwner              MAKEINTRESOURCE(107)
#define IDF_L_ContainerSetMetrics            MAKEINTRESOURCE(108)
#define IDF_L_ContainerSetOffset             MAKEINTRESOURCE(109)
#define IDF_L_ContainerSetScalar             MAKEINTRESOURCE(110)
#define IDF_L_ContainerSetObjectType         MAKEINTRESOURCE(111)
#define IDF_L_ContainerSetObjectCursor       MAKEINTRESOURCE(112)
#define IDF_L_ContainerSetEnabled            MAKEINTRESOURCE(113)
#define IDF_L_ContainerSetCallback           MAKEINTRESOURCE(114)
#define IDF_L_ContainerSetOwnerDraw          MAKEINTRESOURCE(115)

#define IDF_L_ContainerGetOwner              MAKEINTRESOURCE(116)
#define IDF_L_ContainerGetMetrics            MAKEINTRESOURCE(117)
#define IDF_L_ContainerGetOffset             MAKEINTRESOURCE(118)
#define IDF_L_ContainerGetScalar             MAKEINTRESOURCE(119)
#define IDF_L_ContainerGetObjectType         MAKEINTRESOURCE(120)
#define IDF_L_ContainerGetObjectCursor       MAKEINTRESOURCE(121)
#define IDF_L_ContainerGetCallback           MAKEINTRESOURCE(122)

#define IDF_L_ContainerIsEnabled             MAKEINTRESOURCE(123)
#define IDF_L_ContainerIsOwnerDraw           MAKEINTRESOURCE(124)

#define IDF_L_ContainerSetAutomationCallback MAKEINTRESOURCE(201)
#define IDF_L_ScreenToContainer              MAKEINTRESOURCE(202)
#define IDF_L_ContainerToScreen              MAKEINTRESOURCE(203)
#define IDF_L_ContainerEnableUpdate          MAKEINTRESOURCE(204)



//-----------------------------------------------------------------------------
//--LTPNT.H FUNCTIONS MACROS---------------------------------------------------
//-----------------------------------------------------------------------------
#define IDF_L_PntIsValid                  MAKEINTRESOURCE(101)
#define IDF_L_PntInit                     MAKEINTRESOURCE(102)
#define IDF_L_PntFree                     MAKEINTRESOURCE(103)
#define IDF_L_PntSetProperty              MAKEINTRESOURCE(104)
#define IDF_L_PntGetProperty              MAKEINTRESOURCE(105)
#define IDF_L_PntSetMetrics               MAKEINTRESOURCE(106)
#define IDF_L_PntSetTransformation        MAKEINTRESOURCE(107)
#define IDF_L_PntGetTransformation        MAKEINTRESOURCE(108)
#define IDF_L_PntSetDCExtents             MAKEINTRESOURCE(109)
#define IDF_L_PntGetDCExtents             MAKEINTRESOURCE(110)
#define IDF_L_PntSetClipRgn               MAKEINTRESOURCE(111)
#define IDF_L_PntGetClipRgn               MAKEINTRESOURCE(112)
#define IDF_L_PntOffsetClipRgn            MAKEINTRESOURCE(113)
                  
#define IDF_L_PntBrushMoveTo              MAKEINTRESOURCE(114)
#define IDF_L_PntBrushLineTo              MAKEINTRESOURCE(115)
                                          
#define IDF_L_PntDrawShapeLine            MAKEINTRESOURCE(117)
#define IDF_L_PntDrawShapeRectangle       MAKEINTRESOURCE(118)
#define IDF_L_PntDrawShapeRoundRect       MAKEINTRESOURCE(119)
#define IDF_L_PntDrawShapeEllipse         MAKEINTRESOURCE(120)
#define IDF_L_PntDrawShapePolygon         MAKEINTRESOURCE(121)
#define IDF_L_PntDrawShapePolyBezier      MAKEINTRESOURCE(122)
                                          
#define IDF_L_PntRegionRect               MAKEINTRESOURCE(123)
#define IDF_L_PntRegionRoundRect          MAKEINTRESOURCE(124)
#define IDF_L_PntRegionEllipse            MAKEINTRESOURCE(125)
#define IDF_L_PntRegionPolygon            MAKEINTRESOURCE(126)
#define IDF_L_PntRegionSurface            MAKEINTRESOURCE(127)
#define IDF_L_PntRegionBorder             MAKEINTRESOURCE(128)
#define IDF_L_PntRegionColor              MAKEINTRESOURCE(129)
#define IDF_L_PntRegionTranslate          MAKEINTRESOURCE(130)
#define IDF_L_PntRegionScale              MAKEINTRESOURCE(131 )
                                          
#define IDF_L_PntFillSurface              MAKEINTRESOURCE(132 )
#define IDF_L_PntFillBorder               MAKEINTRESOURCE(133 )
#define IDF_L_PntFillColorReplace         MAKEINTRESOURCE(134)
                                          
#define IDF_L_PntApplyText                MAKEINTRESOURCE(135)
                  
#define IDF_L_PntPickColor                MAKEINTRESOURCE(136)

//-----------------------------------------------------------------------------
//--LTTLB.H FUNCTIONS MACROS---------------------------------------------------
//-----------------------------------------------------------------------------
#define IDF_L_TBIsValid                MAKEINTRESOURCE(101)
#define IDF_L_TBInit                   MAKEINTRESOURCE(102)
#define IDF_L_TBFree                   MAKEINTRESOURCE(103)
#define IDF_L_TBCreate                 MAKEINTRESOURCE(104)
#define IDF_L_TBFreeToolbarInfo        MAKEINTRESOURCE(105)

#define IDF_L_TBIsVisible              MAKEINTRESOURCE(106)
#define IDF_L_TBIsButtonEnabled        MAKEINTRESOURCE(107)
#define IDF_L_TBIsButtonVisible        MAKEINTRESOURCE(108)

#define IDF_L_TBSetVisible             MAKEINTRESOURCE(109)
#define IDF_L_TBSetPosition            MAKEINTRESOURCE(110)
#define IDF_L_TBSetRows                MAKEINTRESOURCE(111)
#define IDF_L_TBSetButtonChecked       MAKEINTRESOURCE(112)
#define IDF_L_TBSetButtonEnabled       MAKEINTRESOURCE(113 )
#define IDF_L_TBSetButtonVisible       MAKEINTRESOURCE(114 )
#define IDF_L_TBSetToolbarInfo         MAKEINTRESOURCE(115)
#define IDF_L_TBSetCallback            MAKEINTRESOURCE(116)

#define IDF_L_TBGetPosition            MAKEINTRESOURCE(117)
#define IDF_L_TBGetRows                MAKEINTRESOURCE(118)
#define IDF_L_TBGetButtonChecked       MAKEINTRESOURCE(119)
#define IDF_L_TBGetToolbarInfo         MAKEINTRESOURCE(120)
#define IDF_L_TBGetCallback            MAKEINTRESOURCE(121)

#define IDF_L_TBSetAutomationCallback  MAKEINTRESOURCE(201)

#define IDF_L_TBAddButton              MAKEINTRESOURCE(301)
#define IDF_L_TBRemoveButton           MAKEINTRESOURCE(302)
#define IDF_L_TBGetButtonInfo          MAKEINTRESOURCE(303)
#define IDF_L_TBSetButtonInfo          MAKEINTRESOURCE(304)

//-----------------------------------------------------------------------------
//--LTPDG.H FUNCTIONS MACROS---------------------------------------------------
//-----------------------------------------------------------------------------
#define IDF_L_PntDlgBrush              MAKEINTRESOURCE(500)
#define IDF_L_PntDlgShape              MAKEINTRESOURCE(501)
#define IDF_L_PntDlgRegion             MAKEINTRESOURCE(502)
#define IDF_L_PntDlgFill               MAKEINTRESOURCE(503)
#define IDF_L_PntDlgText               MAKEINTRESOURCE(504)

//-----------------------------------------------------------------------------
//--LTSGM.H FUNCTIONS MACROS---------------------------------------------------
//-----------------------------------------------------------------------------
#define IDF_L_MrcStartBitmapSegmentation MAKEINTRESOURCE(101)
#define IDF_L_MrcEndBitmapSegmentation   MAKEINTRESOURCE(102)
#define IDF_L_MrcSegmentBitmap           MAKEINTRESOURCE(107)
#define IDF_L_MrcSetNewStripe            MAKEINTRESOURCE(103)
#define IDF_L_MrcSetStripeSegment        MAKEINTRESOURCE(104)
#define IDF_L_MrcSetStripeMaxHeight      MAKEINTRESOURCE(106)
#define IDF_L_MrcEnumSegments            MAKEINTRESOURCE(112)
#define IDF_L_MrcUpdateSegmentData       MAKEINTRESOURCE(113)
#define IDF_L_MrcDeleteSegment           MAKEINTRESOURCE(114)
#define IDF_L_MrcSaveBitmap              MAKEINTRESOURCE(108)
#define IDF_L_MrcSaveBitmapT44           MAKEINTRESOURCE(111)
#define IDF_L_MrcLoadBitmap              MAKEINTRESOURCE(109)
#define IDF_L_MrcGetPagesCount           MAKEINTRESOURCE(110)

#endif //USE_POINTERS_TO_LEAD_FUNCTIONS
#endif //_LEAD_FUNCTIONS_ID_H_
/*================================================================= EOF =====*/
