// Precompiled Header für LOL -------------------------------------------------
// File: LOLPRE.H

#if !defined(_LOLPRE_H)
#define _LOLPRE_H

#if !defined(WIN32) || defined(PRECOMPILE)

#include <windows.h>

#include "yy_ansi.h"
#include "yy_stdio.h"
#include "yy_stdlb.h"
#include "yy_strng.h"
#include "yy_trace.h"
#include "yy_asrt.h"
#include "yy_bool.h"
#include "yy_err.h"
#include "yy_inp.h"
#include "yy_lex.h"
#include "yy_psr.h"

#endif // PRECOMPILE

#endif _LOLPRE_H
