//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by KOMPOBJ.RC
//
#define VER_DEBUG                       0
#define IDS_LONGCLASSNAME               1
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        100
#define _APS_NEXT_COMMAND_VALUE         100
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           100
#endif
#endif
