# Genrieren der Versionsinfo's für FAKEMFC.EXT

!include <triasver.mak>

# Generierungsdatum (yymmdd) und Version
DATE = 050104
VERSION = 2
RELEASE = 20
BUILD = 707		# 400: 15. Juni 2000
				# 500: 6. Februar 2001, 09:58 Uhr
                # 2.20.600: 7. Juni 2002, 12:34 Uhr
				# 2.20.700: 6. Mai 2004, 18:43 Uhr

COPYRIGHT = HK$(DATE)

PNAME = $(TRIAS_PNAME)
PADDRESS = $(TRIAS_PADDRESS)

STUB = rights
RIGHTS = $(STUB).exe
REPLACE = ersetz
NAME = fakemfc
DEF = $(NAME).def

ASM = masm
ASMF = /D?PLM=0 /D?WIN=1
LINK = link16.exe

# Alles neubilden
all:	formake 

$(STUB).exe:	$(STUB).asm
	$(ASM) $(ASMF) $(STUB) 
	$(LINK) /NOLOGO /KNOWEAS $(STUB);

# -----------------------------------------------------------------------------
# CopyrightEintraege Generieren 
new:
	@del $(NAME).rcv
	@del $(DEF)
	@del versio32.h
#	@del $(STUB).asm

formake:	$(DEF) $(NAME).rcv versio32.h	# $(STUB).exe 

$(STUB).asm:	$(STUB).tpl makefile
	$(REPLACE) \
		$(VERSION) \
		$(RELEASE) \
		$(BUILD) \
		$(COPYRIGHT) \
		$(REPLACE) \
		$(COMPANYNAME) \
			$(STUB).tpl $(STUB).asm

# Personalisierungsinformation
$(NAME).rcv:	$(NAME)v.tpl makefile
	$(REPLACE) \
		$(VERSION) \
		$(RELEASE) \
		$(BUILD) \
		$(COPYRIGHT) \
		$(PNAME) \
		$(PADDRESS) \
		$(TRIAS_VERSION) \
		$(TRIAS_RELEASE) \
		$(COMPANYNAME) \
			$(NAME)v.tpl $(NAME).rcv

$(DEF):		$(NAME).tpl makefile
	$(REPLACE) $(VERSION) $(RELEASE) $(BUILD) $(COPYRIGHT) $(NAME).tpl $(DEF)

versio32.h:	versio32.tpl makefile
	$(REPLACE) \
		$(VERSION) \
		$(RELEASE) \
		$(COMPANYNAME) \
		$(TRIAS_VERSION) \
		$(TRIAS_RELEASE) \
		$(TRIAS_BUILD) \
		$(TRIAS_BUILDSTRING) \
		$(TRIAS_COPYRIGHT) \
			versio32.tpl versio32.h
