DESCRIPTION     'TRIAS® Containerbibliothek, Copyright(C) 1991 - 1997 uve GmbH Fernerkundungszentrum Potsdam'

EXPORTS
	??0CAccessViolation@@QAE@ABV0@@Z                            	@334	NONAME
	??0CAccessViolation@@QAE@PBD@Z                              	@335	NONAME
	??0CArrayBoundsExceeded@@QAE@ABV0@@Z                        	@336	NONAME
	??0CArrayBoundsExceeded@@QAE@PBD@Z                          	@337	NONAME
	??0CArrayContainer@@QAE@ABV0@@Z                             	@1	NONAME
	??0CArrayContainer@@QAE@IW4tagCONTFLAGS@@@Z                 	@2	NONAME
	??0CArrayNode@@QAE@ABV0@@Z                                  	@3	NONAME
	??0CArrayNode@@QAE@PAX@Z                                    	@4	NONAME
	??0CArrayNode@@QAE@XZ                                       	@5	NONAME
	??0CBinaryNode@@QAE@AAVCTree@@@Z                            	@6	NONAME
	??0CBinaryNode@@QAE@ABV0@@Z                                 	@7	NONAME
	??0CBinaryNode@@QAE@PAXAAVCTree@@PAV0@@Z                    	@8	NONAME
	??0CBinaryNode@@QAE@XZ                                      	@9	NONAME
	??0CBreakPoint@@QAE@ABV0@@Z                                 	@338	NONAME
	??0CBreakPoint@@QAE@PBD@Z                                   	@339	NONAME
	??0CContainer@@QAE@ABV0@@Z                                  	@10	NONAME
	??0CContainer@@QAE@W4tagCONTFLAGS@@@Z                       	@11	NONAME
	??0CCreator@@QAE@AAVCContainer@@@Z                          	@12	NONAME
	??0CDCreator@@QAE@AAVCContainer@@0@Z                        	@13	NONAME
	??0CDatatypeMisalignment@@QAE@ABV0@@Z                       	@340	NONAME
	??0CDatatypeMisalignment@@QAE@PBD@Z                         	@341	NONAME
	??0CFltDenormalOperand@@QAE@ABV0@@Z                         	@342	NONAME
	??0CFltDenormalOperand@@QAE@PBD@Z                           	@343	NONAME
	??0CFltDivideByZero@@QAE@ABV0@@Z                            	@344	NONAME
	??0CFltDivideByZero@@QAE@PBD@Z                              	@345	NONAME
	??0CFltException@@QAE@ABV0@@Z                               	@346	NONAME
	??0CFltException@@QAE@PBD@Z                                 	@347	NONAME
	??0CFltInexactResult@@QAE@ABV0@@Z                           	@348	NONAME
	??0CFltInexactResult@@QAE@PBD@Z                             	@349	NONAME
	??0CFltInvalidOperation@@QAE@ABV0@@Z                        	@350	NONAME
	??0CFltInvalidOperation@@QAE@PBD@Z                          	@351	NONAME
	??0CFltOverflow@@QAE@ABV0@@Z                                	@352	NONAME
	??0CFltOverflow@@QAE@PBD@Z                                  	@353	NONAME
	??0CFltStackCheck@@QAE@ABV0@@Z                              	@354	NONAME
	??0CFltStackCheck@@QAE@PBD@Z                                	@355	NONAME
	??0CFltUnderflow@@QAE@ABV0@@Z                               	@356	NONAME
	??0CFltUnderflow@@QAE@PBD@Z                                 	@357	NONAME
	??0CHListNode@@QAE@AAVCHashTable@@@Z                        	@14	NONAME
	??0CHListNode@@QAE@ABV0@@Z                                  	@15	NONAME
	??0CHListNode@@QAE@PAXAAVCHashTable@@@Z                     	@16	NONAME
	??0CHListNode@@QAE@XZ                                       	@17	NONAME
	??0CHashNode@@QAE@AAVCHashTable@@I@Z                        	@18	NONAME
	??0CHashNode@@QAE@ABV0@@Z                                   	@19	NONAME
	??0CHashNode@@QAE@XZ                                        	@20	NONAME
	??0CHashTable@@QAE@ABV0@@Z                                  	@21	NONAME
	??0CHashTable@@QAE@P6APAXPAX@ZP6AH00@ZP6AI0@ZIW4tagCONTFLAGS@@@Z	@22	NONAME
	??0CHashTable@@QAE@W4tagCONTFLAGS@@@Z                       	@23	NONAME
	??0CIntDivideByZero@@QAE@ABV0@@Z                            	@358	NONAME
	??0CIntDivideByZero@@QAE@PBD@Z                              	@359	NONAME
	??0CIntException@@QAE@ABV0@@Z                               	@360	NONAME
	??0CIntException@@QAE@PBD@Z                                 	@361	NONAME
	??0CIntOverflow@@QAE@ABV0@@Z                                	@362	NONAME
	??0CIntOverflow@@QAE@PBD@Z                                  	@363	NONAME
	??0CKeyContainer@@QAE@ABV0@@Z                               	@24	NONAME
	??0CKeyContainer@@QAE@P6APAXPAX@ZP6AH00@ZW4tagCONTFLAGS@@@Z 	@25	NONAME
	??0CKeyContainer@@QAE@W4tagCONTFLAGS@@@Z                    	@26	NONAME
	??0CKeyNode@@QAE@AAVCKeyContainer@@@Z                       	@27	NONAME
	??0CKeyNode@@QAE@ABV0@@Z                                    	@28	NONAME
	??0CKeyNode@@QAE@PAXAAVCKeyContainer@@@Z                    	@29	NONAME
	??0CKeyNode@@QAE@XZ                                         	@30	NONAME
	??0CListContainer@@QAE@ABV0@@Z                              	@31	NONAME
	??0CListContainer@@QAE@W4tagCONTFLAGS@@@Z                   	@32	NONAME
	??0CListNode@@QAE@ABV0@@Z                                   	@33	NONAME
	??0CListNode@@QAE@PAX@Z                                     	@34	NONAME
	??0CListNode@@QAE@XZ                                        	@35	NONAME
	??0CLock@@IAE@AAVCNavigator@@@Z                             	@36	NONAME
	??0CLock@@IAE@PAX@Z                                         	@37	NONAME
	??0CMathException@@QAE@ABV0@@Z                              	@364	NONAME
	??0CMathException@@QAE@PBD@Z                                	@365	NONAME
	??0CMutex@@QAE@H@Z                                          	@38	NONAME
	??0CNakedLock@@QAE@PAX@Z                                    	@39	NONAME
	??0CNavigator@@IAE@AAV0@@Z                                  	@40	NONAME
	??0CNavigator@@IAE@AAVCContainer@@@Z                        	@41	NONAME
	??0CNode@@QAE@ABV0@@Z                                       	@42	NONAME
	??0CNode@@QAE@PAX@Z                                         	@43	NONAME
	??0CNode@@QAE@XZ                                            	@44	NONAME
	??0CNoncontinueableException@@QAE@ABV0@@Z                   	@366	NONAME
	??0CNoncontinueableException@@QAE@PBD@Z                     	@367	NONAME
	??0COptTree@@QAE@ABV0@@Z                                    	@506	NONAME
	??0COptTree@@QAE@P6APAXPAX@ZP6AH00@ZW4tagCONTFLAGS@@J@Z     	@507	NONAME
	??0COptTree@@QAE@W4tagCONTFLAGS@@J@Z                        	@508	NONAME
	??0CPrivInstruction@@QAE@ABV0@@Z                            	@368	NONAME
	??0CPrivInstruction@@QAE@PBD@Z                              	@369	NONAME
	??0CRing@@QAE@AAV0@@Z                                       	@45	NONAME
	??0CRing@@QAE@AAVCSeqContainer@@@Z                          	@46	NONAME
	??0CSeqContainer@@QAE@ABV0@@Z                               	@47	NONAME
	??0CSeqContainer@@QAE@W4tagCONTFLAGS@@@Z                    	@48	NONAME
	??0CSeqNode@@QAE@ABV0@@Z                                    	@49	NONAME
	??0CSeqNode@@QAE@PAX@Z                                      	@50	NONAME
	??0CSeqNode@@QAE@XZ                                         	@51	NONAME
	??0CSingleStep@@QAE@ABV0@@Z                                 	@370	NONAME
	??0CSingleStep@@QAE@PBD@Z                                   	@371	NONAME
	??0CSyncMonitor@@IAE@H@Z                                    	@52	NONAME
	??0CTable@@QAE@AAV0@@Z                                      	@53	NONAME
	??0CTable@@QAE@AAVCKeyContainer@@@Z                         	@54	NONAME
	??0CTree@@QAE@ABV0@@Z                                       	@55	NONAME
	??0CTree@@QAE@P6APAXPAX@ZP6AH00@ZW4tagCONTFLAGS@@@Z         	@56	NONAME
	??0CTree@@QAE@W4tagCONTFLAGS@@@Z                            	@57	NONAME
	??0CWin32Exception@@QAE@ABV0@@Z                             	@372	NONAME
	??0CWin32Exception@@QAE@PBD@Z                               	@373	NONAME
	??0CWin32UserException@@QAE@ABV0@@Z                         	@374	NONAME
	??0CWin32UserException@@QAE@IPBD@Z                          	@375	NONAME
	??0DelTree@@QAE@ABV0@@Z                                     	@58	NONAME
	??0DelTree@@QAE@P6APAXPAX@ZP6AH00@ZW4tagCONTFLAGS@@@Z       	@59	NONAME
	??0P5_Ticker@@QAE@ABV0@@Z                                   	@516	NONAME
	??0P5_Ticker@@QAE@XZ                                        	@517	NONAME
	??0UniqueTree@@QAE@ABV0@@Z                                  	@60	NONAME
	??0UniqueTree@@QAE@P6APAXPAX@ZP6AH00@ZW4tagCONTFLAGS@@@Z    	@61	NONAME
	??1CAccessViolation@@UAE@XZ                                 	@376	NONAME
	??1CArrayBoundsExceeded@@UAE@XZ                             	@377	NONAME
	??1CArrayContainer@@UAE@XZ                                  	@62	NONAME
	??1CBreakPoint@@UAE@XZ                                      	@378	NONAME
	??1CContainer@@UAE@XZ                                       	@63	NONAME
	??1CCreator@@QAE@XZ                                         	@64	NONAME
	??1CDCreator@@QAE@XZ                                        	@65	NONAME
	??1CDatatypeMisalignment@@UAE@XZ                            	@379	NONAME
	??1CFltDenormalOperand@@UAE@XZ                              	@380	NONAME
	??1CFltDivideByZero@@UAE@XZ                                 	@381	NONAME
	??1CFltException@@UAE@XZ                                    	@382	NONAME
	??1CFltInexactResult@@UAE@XZ                                	@383	NONAME
	??1CFltInvalidOperation@@UAE@XZ                             	@384	NONAME
	??1CFltOverflow@@UAE@XZ                                     	@385	NONAME
	??1CFltStackCheck@@UAE@XZ                                   	@386	NONAME
	??1CFltUnderflow@@UAE@XZ                                    	@387	NONAME
	??1CHashNode@@QAE@XZ                                        	@66	NONAME
	??1CHashTable@@UAE@XZ                                       	@67	NONAME
	??1CIntDivideByZero@@UAE@XZ                                 	@388	NONAME
	??1CIntException@@UAE@XZ                                    	@389	NONAME
	??1CIntOverflow@@UAE@XZ                                     	@390	NONAME
	??1CKeyContainer@@UAE@XZ                                    	@68	NONAME
	??1CListContainer@@UAE@XZ                                   	@69	NONAME
	??1CLock@@QAE@XZ                                            	@70	NONAME
	??1CMathException@@UAE@XZ                                   	@391	NONAME
	??1CMutex@@QAE@XZ                                           	@71	NONAME
	??1CNakedLock@@QAE@XZ                                       	@72	NONAME
	??1CNavigator@@QAE@XZ                                       	@73	NONAME
	??1CNoncontinueableException@@UAE@XZ                        	@392	NONAME
	??1COptTree@@UAE@XZ                                         	@509	NONAME
	??1CPrivInstruction@@UAE@XZ                                 	@393	NONAME
	??1CRing@@QAE@XZ                                            	@74	NONAME
	??1CSeqContainer@@UAE@XZ                                    	@75	NONAME
	??1CSingleStep@@UAE@XZ                                      	@394	NONAME
	??1CSyncMonitor@@QAE@XZ                                     	@76	NONAME
	??1CTable@@QAE@XZ                                           	@77	NONAME
	??1CTree@@UAE@XZ                                            	@78	NONAME
	??1CWin32Exception@@UAE@XZ                                  	@395	NONAME
	??1CWin32UserException@@UAE@XZ                              	@396	NONAME
	??1DelTree@@UAE@XZ                                          	@79	NONAME
	??1P5_Ticker@@QAE@XZ                                        	@518	NONAME
	??1UniqueTree@@UAE@XZ                                       	@80	NONAME
	??4CAccessViolation@@QAEAAV0@ABV0@@Z                        	@397	NONAME
	??4CArrayBoundsExceeded@@QAEAAV0@ABV0@@Z                    	@398	NONAME
	??4CArrayContainer@@QAEAAV0@ABV0@@Z                         	@81	NONAME
	??4CArrayNode@@QAEAAV0@AAV0@@Z                              	@82	NONAME
	??4CBinaryNode@@QAEAAV0@AAV0@@Z                             	@83	NONAME
	??4CBreakPoint@@QAEAAV0@ABV0@@Z                             	@399	NONAME
	??4CContainer@@QAEAAV0@ABV0@@Z                              	@84	NONAME
	??4CDatatypeMisalignment@@QAEAAV0@ABV0@@Z                   	@400	NONAME
	??4CFltDenormalOperand@@QAEAAV0@ABV0@@Z                     	@401	NONAME
	??4CFltDivideByZero@@QAEAAV0@ABV0@@Z                        	@402	NONAME
	??4CFltException@@QAEAAV0@ABV0@@Z                           	@403	NONAME
	??4CFltInexactResult@@QAEAAV0@ABV0@@Z                       	@404	NONAME
	??4CFltInvalidOperation@@QAEAAV0@ABV0@@Z                    	@405	NONAME
	??4CFltOverflow@@QAEAAV0@ABV0@@Z                            	@406	NONAME
	??4CFltStackCheck@@QAEAAV0@ABV0@@Z                          	@407	NONAME
	??4CFltUnderflow@@QAEAAV0@ABV0@@Z                           	@408	NONAME
	??4CHListNode@@QAEAAV0@AAV0@@Z                              	@85	NONAME
	??4CHashNode@@QAEAAV0@AAV0@@Z                               	@86	NONAME
	??4CHashTable@@QAEAAV0@ABV0@@Z                              	@87	NONAME
	??4CIntDivideByZero@@QAEAAV0@ABV0@@Z                        	@409	NONAME
	??4CIntException@@QAEAAV0@ABV0@@Z                           	@410	NONAME
	??4CIntOverflow@@QAEAAV0@ABV0@@Z                            	@411	NONAME
	??4CKeyContainer@@QAEAAV0@ABV0@@Z                           	@88	NONAME
	??4CKeyNode@@QAEAAV0@AAV0@@Z                                	@89	NONAME
	??4CListContainer@@QAEAAV0@ABV0@@Z                          	@90	NONAME
	??4CListNode@@QAEAAV0@AAV0@@Z                               	@91	NONAME
	??4CLock@@QAEAAV0@ABV0@@Z                                   	@92	NONAME
	??4CMathException@@QAEAAV0@ABV0@@Z                          	@412	NONAME
	??4CMutex@@QAEAAV0@ABV0@@Z                                  	@93	NONAME
	??4CNakedLock@@QAEAAV0@ABV0@@Z                              	@94	NONAME
	??4CNode@@QAEAAV0@AAV0@@Z                                   	@95	NONAME
	??4CNoncontinueableException@@QAEAAV0@ABV0@@Z               	@413	NONAME
	??4COptTree@@QAEAAV0@ABV0@@Z                                	@510	NONAME
	??4CPrivInstruction@@QAEAAV0@ABV0@@Z                        	@414	NONAME
	??4CSeqContainer@@QAEAAV0@ABV0@@Z                           	@96	NONAME
	??4CSeqNode@@QAEAAV0@AAV0@@Z                                	@97	NONAME
	??4CSingleStep@@QAEAAV0@ABV0@@Z                             	@415	NONAME
	??4CSyncMonitor@@QAEAAV0@ABV0@@Z                            	@98	NONAME
	??4CTree@@QAEAAV0@ABV0@@Z                                   	@99	NONAME
	??4CWin32Exception@@QAEAAV0@ABV0@@Z                         	@416	NONAME
	??4CWin32UserException@@QAEAAV0@ABV0@@Z                     	@417	NONAME
	??4DelTree@@QAEAAV0@ABV0@@Z                                 	@100	NONAME
	??4P5_Ticker@@QAEAAV0@ABT_ULARGE_INTEGER@@@Z                	@519	NONAME
	??4P5_Ticker@@QAEAAV0@ABV0@@Z                               	@520	NONAME
	??4UniqueTree@@QAEAAV0@ABV0@@Z                              	@101	NONAME
	??BCMutex@@QAEHXZ                                           	@102	NONAME
	??GP5_Ticker@@QBE?AV0@ABV0@@Z                               	@521	NONAME
	??HP5_Ticker@@QBE?AV0@ABV0@@Z                               	@522	NONAME
	??_7CAccessViolation@@6B@                                   	@418	NONAME
	??_7CArrayBoundsExceeded@@6B@                               	@419	NONAME
	??_7CArrayContainer@@6B@                                    	@103	NONAME
	??_7CArrayNode@@6B@                                         	@104	NONAME
	??_7CBinaryNode@@6B@                                        	@105	NONAME
	??_7CBreakPoint@@6B@                                        	@420	NONAME
	??_7CContainer@@6B@                                         	@106	NONAME
	??_7CDatatypeMisalignment@@6B@                              	@421	NONAME
	??_7CFltDenormalOperand@@6B@                                	@422	NONAME
	??_7CFltDivideByZero@@6B@                                   	@423	NONAME
	??_7CFltException@@6B@                                      	@424	NONAME
	??_7CFltInexactResult@@6B@                                  	@425	NONAME
	??_7CFltInvalidOperation@@6B@                               	@426	NONAME
	??_7CFltOverflow@@6B@                                       	@427	NONAME
	??_7CFltStackCheck@@6B@                                     	@428	NONAME
	??_7CFltUnderflow@@6B@                                      	@429	NONAME
	??_7CHListNode@@6B@                                         	@107	NONAME
	??_7CHashNode@@6B@                                          	@108	NONAME
	??_7CHashTable@@6B@                                         	@109	NONAME
	??_7CIntDivideByZero@@6B@                                   	@430	NONAME
	??_7CIntException@@6B@                                      	@431	NONAME
	??_7CIntOverflow@@6B@                                       	@432	NONAME
	??_7CKeyContainer@@6B@                                      	@110	NONAME
	??_7CKeyNode@@6B@                                           	@111	NONAME
	??_7CListContainer@@6B@                                     	@112	NONAME
	??_7CListNode@@6B@                                          	@113	NONAME
	??_7CMathException@@6B@                                     	@433	NONAME
	??_7CNode@@6B@                                              	@114	NONAME
	??_7CNoncontinueableException@@6B@                          	@434	NONAME
	??_7COptTree@@6B@                                           	@511	NONAME
	??_7CPrivInstruction@@6B@                                   	@435	NONAME
	??_7CSeqContainer@@6B@                                      	@115	NONAME
	??_7CSeqNode@@6B@                                           	@116	NONAME
	??_7CSingleStep@@6B@                                        	@436	NONAME
	??_7CTree@@6B@                                              	@117	NONAME
	??_7CWin32Exception@@6B@                                    	@437	NONAME
	??_7CWin32UserException@@6B@                                	@438	NONAME
	??_7DelTree@@6B@                                            	@118	NONAME
	??_7UniqueTree@@6B@                                         	@119	NONAME
	??_ECAccessViolation@@UAEPAXI@Z                             	@439	NONAME
	??_ECArrayBoundsExceeded@@UAEPAXI@Z                         	@440	NONAME
	??_ECArrayContainer@@UAEPAXI@Z                              	@120	NONAME
	??_ECBreakPoint@@UAEPAXI@Z                                  	@441	NONAME
	??_ECContainer@@UAEPAXI@Z                                   	@121	NONAME
	??_ECCreator@@QAEPAXI@Z                                     	@122	NONAME
	??_ECDCreator@@QAEPAXI@Z                                    	@123	NONAME
	??_ECDatatypeMisalignment@@UAEPAXI@Z                        	@442	NONAME
	??_ECFltDenormalOperand@@UAEPAXI@Z                          	@443	NONAME
	??_ECFltDivideByZero@@UAEPAXI@Z                             	@444	NONAME
	??_ECFltException@@UAEPAXI@Z                                	@445	NONAME
	??_ECFltInexactResult@@UAEPAXI@Z                            	@446	NONAME
	??_ECFltInvalidOperation@@UAEPAXI@Z                         	@447	NONAME
	??_ECFltOverflow@@UAEPAXI@Z                                 	@448	NONAME
	??_ECFltStackCheck@@UAEPAXI@Z                               	@449	NONAME
	??_ECFltUnderflow@@UAEPAXI@Z                                	@450	NONAME
	??_ECHashNode@@QAEPAXI@Z                                    	@124	NONAME
	??_ECHashTable@@UAEPAXI@Z                                   	@125	NONAME
	??_ECIntDivideByZero@@UAEPAXI@Z                             	@451	NONAME
	??_ECIntException@@UAEPAXI@Z                                	@452	NONAME
	??_ECIntOverflow@@UAEPAXI@Z                                 	@453	NONAME
	??_ECKeyContainer@@UAEPAXI@Z                                	@126	NONAME
	??_ECListContainer@@UAEPAXI@Z                               	@127	NONAME
	??_ECLock@@QAEPAXI@Z                                        	@128	NONAME
	??_ECMathException@@UAEPAXI@Z                               	@454	NONAME
	??_ECMutex@@QAEPAXI@Z                                       	@129	NONAME
	??_ECNakedLock@@QAEPAXI@Z                                   	@130	NONAME
	??_ECNavigator@@QAEPAXI@Z                                   	@131	NONAME
	??_ECNoncontinueableException@@UAEPAXI@Z                    	@455	NONAME
	??_ECOptTree@@UAEPAXI@Z                                     	@512	NONAME
	??_ECPrivInstruction@@UAEPAXI@Z                             	@456	NONAME
	??_ECRing@@QAEPAXI@Z                                        	@132	NONAME
	??_ECSeqContainer@@UAEPAXI@Z                                	@133	NONAME
	??_ECSingleStep@@UAEPAXI@Z                                  	@457	NONAME
	??_ECSyncMonitor@@QAEPAXI@Z                                 	@134	NONAME
	??_ECTable@@QAEPAXI@Z                                       	@135	NONAME
	??_ECTree@@UAEPAXI@Z                                        	@136	NONAME
	??_ECWin32Exception@@UAEPAXI@Z                              	@458	NONAME
	??_ECWin32UserException@@UAEPAXI@Z                          	@459	NONAME
	??_EDelTree@@UAEPAXI@Z                                      	@137	NONAME
	??_EP5_Ticker@@QAEPAXI@Z                                    	@523	NONAME
	??_EUniqueTree@@UAEPAXI@Z                                   	@138	NONAME
	??_FCAccessViolation@@QAEXXZ                                	@489	NONAME
	??_FCArrayBoundsExceeded@@QAEXXZ                            	@490	NONAME
	??_FCArrayContainer@@QAEXXZ                                 	@139	NONAME
	??_FCBreakPoint@@QAEXXZ                                     	@491	NONAME
	??_FCContainer@@QAEXXZ                                      	@140	NONAME
	??_FCDatatypeMisalignment@@QAEXXZ                           	@492	NONAME
	??_FCFltDenormalOperand@@QAEXXZ                             	@493	NONAME
	??_FCFltDivideByZero@@QAEXXZ                                	@494	NONAME
	??_FCFltInexactResult@@QAEXXZ                               	@495	NONAME
	??_FCFltInvalidOperation@@QAEXXZ                            	@496	NONAME
	??_FCFltOverflow@@QAEXXZ                                    	@497	NONAME
	??_FCFltStackCheck@@QAEXXZ                                  	@498	NONAME
	??_FCFltUnderflow@@QAEXXZ                                   	@499	NONAME
	??_FCHashTable@@QAEXXZ                                      	@141	NONAME
	??_FCIntDivideByZero@@QAEXXZ                                	@500	NONAME
	??_FCIntOverflow@@QAEXXZ                                    	@501	NONAME
	??_FCKeyContainer@@QAEXXZ                                   	@142	NONAME
	??_FCListContainer@@QAEXXZ                                  	@143	NONAME
	??_FCMutex@@QAEXXZ                                          	@144	NONAME
	??_FCNoncontinueableException@@QAEXXZ                       	@502	NONAME
	??_FCOptTree@@QAEXXZ                                        	@513	NONAME
	??_FCPrivInstruction@@QAEXXZ                                	@503	NONAME
	??_FCSeqContainer@@QAEXXZ                                   	@145	NONAME
	??_FCSingleStep@@QAEXXZ                                     	@504	NONAME
	??_FCSyncMonitor@@QAEXXZ                                    	@146	NONAME
	??_FCTree@@QAEXXZ                                           	@147	NONAME
	??_GCAccessViolation@@UAEPAXI@Z                             	@460	NONAME
	??_GCArrayBoundsExceeded@@UAEPAXI@Z                         	@461	NONAME
	??_GCArrayContainer@@UAEPAXI@Z                              	@148	NONAME
	??_GCBreakPoint@@UAEPAXI@Z                                  	@462	NONAME
	??_GCContainer@@UAEPAXI@Z                                   	@149	NONAME
	??_GCCreator@@QAEPAXI@Z                                     	@150	NONAME
	??_GCDCreator@@QAEPAXI@Z                                    	@151	NONAME
	??_GCDatatypeMisalignment@@UAEPAXI@Z                        	@463	NONAME
	??_GCFltDenormalOperand@@UAEPAXI@Z                          	@464	NONAME
	??_GCFltDivideByZero@@UAEPAXI@Z                             	@465	NONAME
	??_GCFltException@@UAEPAXI@Z                                	@466	NONAME
	??_GCFltInexactResult@@UAEPAXI@Z                            	@467	NONAME
	??_GCFltInvalidOperation@@UAEPAXI@Z                         	@468	NONAME
	??_GCFltOverflow@@UAEPAXI@Z                                 	@469	NONAME
	??_GCFltStackCheck@@UAEPAXI@Z                               	@470	NONAME
	??_GCFltUnderflow@@UAEPAXI@Z                                	@471	NONAME
	??_GCHashNode@@QAEPAXI@Z                                    	@152	NONAME
	??_GCHashTable@@UAEPAXI@Z                                   	@153	NONAME
	??_GCIntDivideByZero@@UAEPAXI@Z                             	@472	NONAME
	??_GCIntException@@UAEPAXI@Z                                	@473	NONAME
	??_GCIntOverflow@@UAEPAXI@Z                                 	@474	NONAME
	??_GCKeyContainer@@UAEPAXI@Z                                	@154	NONAME
	??_GCListContainer@@UAEPAXI@Z                               	@155	NONAME
	??_GCLock@@QAEPAXI@Z                                        	@156	NONAME
	??_GCMathException@@UAEPAXI@Z                               	@475	NONAME
	??_GCMutex@@QAEPAXI@Z                                       	@157	NONAME
	??_GCNakedLock@@QAEPAXI@Z                                   	@158	NONAME
	??_GCNavigator@@QAEPAXI@Z                                   	@159	NONAME
	??_GCNoncontinueableException@@UAEPAXI@Z                    	@476	NONAME
	??_GCOptTree@@UAEPAXI@Z                                     	@514	NONAME
	??_GCPrivInstruction@@UAEPAXI@Z                             	@477	NONAME
	??_GCRing@@QAEPAXI@Z                                        	@160	NONAME
	??_GCSeqContainer@@UAEPAXI@Z                                	@161	NONAME
	??_GCSingleStep@@UAEPAXI@Z                                  	@478	NONAME
	??_GCSyncMonitor@@QAEPAXI@Z                                 	@162	NONAME
	??_GCTable@@QAEPAXI@Z                                       	@163	NONAME
	??_GCTree@@UAEPAXI@Z                                        	@164	NONAME
	??_GCWin32Exception@@UAEPAXI@Z                              	@479	NONAME
	??_GCWin32UserException@@UAEPAXI@Z                          	@480	NONAME
	??_GDelTree@@UAEPAXI@Z                                      	@165	NONAME
	??_GP5_Ticker@@QAEPAXI@Z                                    	@524	NONAME
	??_GUniqueTree@@UAEPAXI@Z                                   	@166	NONAME
	?Alloc@CCreator@@QAEPAXI@Z                                  	@167	NONAME
	?Alloc@CDCreator@@QAEPAXI@Z                                 	@168	NONAME
	?Append@CHListNode@@QAEXPAV1@@Z                             	@169	NONAME
	?Append@CListNode@@QAEXPAV1@@Z                              	@170	NONAME
	?AverageCompares@CHashTable@@QBEIXZ                         	@171	NONAME
	?AverageCompares@CTree@@QBEIXZ                              	@172	NONAME
	?Branch@CTree@@AAEPAVCBinaryNode@@PAV2@W4Richtung@@@Z       	@173	NONAME
	?BucketsOfLength@CHashTable@@QBEII@Z                        	@174	NONAME
	?Check_Has_RDTSC@P5_Ticker@@ABEHXZ                          	@525	NONAME
	?Compare@CKeyNode@@QBEHPAX@Z                                	@175	NONAME
	?ContFlags@CContainer@@QAEGW4tagCONTFLAGS@@@Z               	@176	NONAME
	?CorrectParents@CTree@@AAEXXZ                               	@177	NONAME
	?Count@CContainer@@QBEKXZ                                   	@178	NONAME
	?CurrentAfterDelete@CArrayNode@@UAEPAVCNode@@PAV2@@Z        	@179	NONAME
	?CurrentAfterDelete@CHashNode@@UAEPAVCNode@@PAV2@@Z         	@180	NONAME
	?CurrentAfterDelete@CKeyNode@@UAEPAVCNode@@PAV2@@Z          	@181	NONAME
	?CurrentAfterDelete@CListNode@@UAEPAVCNode@@PAV2@@Z         	@182	NONAME
	?CurrentAfterDelete@CNode@@UAEPAV1@PAV1@@Z                  	@183	NONAME
	?DataStructure@CArrayContainer@@MBEPAVCNode@@XZ             	@184	NONAME
	?DataStructure@CContainer@@MBEPAVCNode@@XZ                  	@185	NONAME
	?DataStructure@CHashTable@@MBEPAVCNode@@XZ                  	@186	NONAME
	?DataStructure@CListContainer@@MBEPAVCNode@@XZ              	@187	NONAME
	?DataStructure@CTree@@MBEPAVCNode@@XZ                       	@188	NONAME
	?Delete@CArrayContainer@@MAEHPAVCNode@@@Z                   	@189	NONAME
	?Delete@CContainer@@MAEHPAVCNode@@@Z                        	@190	NONAME
	?Delete@CHashTable@@MAEHPAVCNode@@@Z                        	@191	NONAME
	?Delete@CListContainer@@MAEHPAVCNode@@@Z                    	@192	NONAME
	?Delete@CNavigator@@QAEHXZ                                  	@193	NONAME
	?Delete@CTree@@MAEHPAVCNode@@@Z                             	@194	NONAME
	?DeleteNotify@CNavigator@@AAEXPAVCNode@@@Z                  	@195	NONAME
	?Depth@CTree@@AAEJPAVCBinaryNode@@W4Richtung@@@Z            	@196	NONAME
	?EmptyBuckets@CHashTable@@QBEIXZ                            	@197	NONAME
	?Every@CContainer@@UAEHP6AHPAX0@Z0@Z                        	@198	NONAME
	?Every@CContainer@@UAEXP6AXPAX@Z@Z                          	@199	NONAME
	?Every@CHashTable@@UAEHP6AHPAX0@Z0@Z                        	@200	NONAME
	?Every@CHashTable@@UAEXP6AXPAX@Z@Z                          	@201	NONAME
	?Every@CSeqContainer@@UAEHP6AHPAX0@Z0@Z                     	@202	NONAME
	?Every@CSeqContainer@@UAEXP6AXPAX@Z@Z                       	@203	NONAME
	?Every@CTree@@UAEHP6AHPAX0@Z0@Z                             	@204	NONAME
	?Every@CTree@@UAEXP6AXPAX@Z@Z                               	@205	NONAME
	?EveryDelete@CContainer@@UAEHXZ                             	@206	NONAME
	?ExtTrace@@YAXPBDZZ                                         	@207	NONAME
	?Find@CBinaryNode@@UBEPAVCKeyNode@@PAX@Z                    	@208	NONAME
	?Find@CHListNode@@UBEPAVCKeyNode@@PAX@Z                     	@209	NONAME
	?Find@CHashNode@@UBEPAVCKeyNode@@PAX@Z                      	@210	NONAME
	?Find@CKeyNode@@UBEPAV1@PAX@Z                               	@211	NONAME
	?Find@CTable@@QAEHPAX@Z                                     	@212	NONAME
	?FindFirst@CKeyNode@@QBEPAV1@PAX@Z                          	@213	NONAME
	?FindFirst@CTable@@QAEHPAX@Z                                	@214	NONAME
	?FindNext@CHListNode@@UBEPAVCKeyNode@@PAX@Z                 	@215	NONAME
	?FindNext@CKeyNode@@UBEPAV1@PAX@Z                           	@216	NONAME
	?FindNext@CTable@@QAEHPAX@Z                                 	@217	NONAME
	?FindPrev@CHListNode@@UBEPAVCKeyNode@@PAX@Z                 	@218	NONAME
	?FindPrev@CKeyNode@@UBEPAV1@PAX@Z                           	@219	NONAME
	?FindPrev@CTable@@QAEHPAX@Z                                 	@220	NONAME
	?First@CNavigator@@QAEHXZ                                   	@221	NONAME
	?First@CRing@@QAEHXZ                                        	@222	NONAME
	?FirstNode@CContainer@@MBEPAVCNode@@XZ                      	@223	NONAME
	?FirstNode@CHashTable@@MBEPAVCNode@@XZ                      	@224	NONAME
	?FirstNode@CTree@@MBEPAVCNode@@XZ                           	@225	NONAME
	?Fold@CTree@@AAEPAVCBinaryNode@@PAV2@W4Richtung@@@Z         	@226	NONAME
	?GetContainer@CKeyNode@@QBEAAVCKeyContainer@@XZ             	@227	NONAME
	?GetContainer@CNavigator@@IBEAAVCContainer@@XZ              	@228	NONAME
	?GetHandle@CLock@@IAEAAPAXXZ                                	@229	NONAME
	?GetHandle@CNavigator@@IBEPAXXZ                             	@230	NONAME
	?GetHandle@CNode@@QBEPAXXZ                                  	@231	NONAME
	?GetNext@CHListNode@@QBEPAV1@XZ                             	@232	NONAME
	?GetNext@CListNode@@QBEPAV1@XZ                              	@233	NONAME
	?GetNode@CHashNode@@QBEPAVCHListNode@@I@Z                   	@234	NONAME
	?GetPrev@CHListNode@@QBEPAV1@XZ                             	@235	NONAME
	?GetPrev@CListNode@@QBEPAV1@XZ                              	@236	NONAME
	?GetRank@CRing@@QBEKXZ                                      	@237	NONAME
	?Get_Frequency@P5_Ticker@@QBENAANKI@Z                       	@526	NONAME
	?Get_Time@P5_Ticker@@QAEAAV1@XZ                             	@527	NONAME
	?Goto@CRing@@QAEHK@Z                                        	@238	NONAME
	?Graft@CBinaryNode@@QAEXPAV1@0@Z                            	@239	NONAME
	?Handle@CMutex@@QBEPAXXZ                                    	@240	NONAME
	?Has_RDTSC@P5_Ticker@@0HA                                   	@528	NONAME
	?InOrder@CTree@@AAEHPAVCBinaryNode@@P6AHPAX1@Z1@Z           	@241	NONAME
	?InOrder@CTree@@AAEXPAVCBinaryNode@@P6AXPAX@Z@Z             	@242	NONAME
	?Insert@CArrayContainer@@MAEHPAX0@Z                         	@243	NONAME
	?Insert@CContainer@@MAEHPAX0@Z                              	@244	NONAME
	?Insert@CCreator@@QAEXXZ                                    	@245	NONAME
	?Insert@CDCreator@@QAEHXZ                                   	@246	NONAME
	?Insert@CHListNode@@QAEXPAV1@@Z                             	@247	NONAME
	?Insert@CHashTable@@MAEHPAX0@Z                              	@248	NONAME
	?Insert@CListContainer@@MAEHPAX0@Z                          	@249	NONAME
	?Insert@COptTree@@UAEHPAX0@Z                                	@515	NONAME
	?Insert@CTree@@MAEHPAX0@Z                                   	@250	NONAME
	?InsertPointer@CCreator@@QAEPAXPAX@Z                        	@251	NONAME
	?IntCmp@@YAHPAX0@Z                                          	@252	NONAME
	?IntHash@@YAIPAX@Z                                          	@253	NONAME
	?IsWin31@@YGHXZ                                             	@254	NONAME
	?IsWin32s@@YGHXZ                                            	@255	NONAME
	?IsWin40@@YGHXZ                                             	@256	NONAME
	?IsWin41@@YGHXZ                                             	@505	NONAME
	?IsWinNT@@YGHXZ                                             	@257	NONAME
	?Last@CNavigator@@QAEHXZ                                    	@258	NONAME
	?Last@CRing@@QAEHXZ                                         	@259	NONAME
	?LastNode@CArrayContainer@@MBEPAVCNode@@XZ                  	@260	NONAME
	?LastNode@CContainer@@MBEPAVCNode@@XZ                       	@261	NONAME
	?LastNode@CHashTable@@MBEPAVCNode@@XZ                       	@262	NONAME
	?LastNode@CListContainer@@MBEPAVCNode@@XZ                   	@263	NONAME
	?LastNode@CTree@@MBEPAVCNode@@XZ                            	@264	NONAME
	?Left@CBinaryNode@@QBEPAV1@XZ                               	@265	NONAME
	?LeftMost@CBinaryNode@@QBEPAV1@XZ                           	@266	NONAME
	?LeftMostOrRight@CBinaryNode@@QBEPAV1@XZ                    	@267	NONAME
	?Linear@CTree@@AAEPAVCBinaryNode@@XZ                        	@268	NONAME
	?Lock@CNode@@QAEXXZ                                         	@269	NONAME
	?Locked@CNode@@QBEHXZ                                       	@270	NONAME
	?Next@CArrayNode@@UBEPAVCSeqNode@@K@Z                       	@271	NONAME
	?Next@CBinaryNode@@UBEPAVCKeyNode@@XZ                       	@272	NONAME
	?Next@CHListNode@@UBEPAVCKeyNode@@XZ                        	@273	NONAME
	?Next@CHashNode@@UBEPAVCKeyNode@@XZ                         	@274	NONAME
	?Next@CKeyNode@@UBEPAV1@XZ                                  	@275	NONAME
	?Next@CListNode@@UBEPAVCSeqNode@@K@Z                        	@276	NONAME
	?Next@CRing@@QAEHXZ                                         	@277	NONAME
	?Next@CSeqNode@@UBEPAV1@K@Z                                 	@278	NONAME
	?Next@CTable@@QAEHXZ                                        	@279	NONAME
	?Optimize@CTree@@QAEXXZ                                     	@280	NONAME
	?P5_Ticker_Available@P5_Ticker@@QBEHXZ                      	@529	NONAME
	?P@CLock@@IAEPAXXZ                                          	@281	NONAME
	?P@CNakedLock@@QAEPAXXZ                                     	@282	NONAME
	?Parent@CBinaryNode@@QBEPAV1@XZ                             	@283	NONAME
	?PostOrder@CTree@@AAEXPAVCBinaryNode@@P6AXPAX@Z@Z           	@284	NONAME
	?PreOrder@CTree@@AAEXPAVCBinaryNode@@P6AXPAX@Z@Z            	@285	NONAME
	?Prev@CArrayNode@@UBEPAVCSeqNode@@K@Z                       	@286	NONAME
	?Prev@CBinaryNode@@UBEPAVCKeyNode@@XZ                       	@287	NONAME
	?Prev@CHListNode@@UBEPAVCKeyNode@@XZ                        	@288	NONAME
	?Prev@CHashNode@@UBEPAVCKeyNode@@XZ                         	@289	NONAME
	?Prev@CKeyNode@@UBEPAV1@XZ                                  	@290	NONAME
	?Prev@CListNode@@UBEPAVCSeqNode@@K@Z                        	@291	NONAME
	?Prev@CRing@@QAEHXZ                                         	@292	NONAME
	?Prev@CSeqNode@@UBEPAV1@K@Z                                 	@293	NONAME
	?Prev@CTable@@QAEHXZ                                        	@294	NONAME
	?ReInsert@CTable@@QAEHPAXG@Z                                	@295	NONAME
	?ReInsert@CTree@@QAEPAVCNode@@PAVCBinaryNode@@PAXG@Z        	@296	NONAME
	?ReSize@CHashNode@@IAEXI@Z                                  	@297	NONAME
	?Register@CContainer@@AAEXPAVCNavigator@@@Z                 	@298	NONAME
	?Remove@CHListNode@@QAEXXZ                                  	@299	NONAME
	?Remove@CListNode@@QAEXXZ                                   	@300	NONAME
	?Reset@CNavigator@@QAEXXZ                                   	@301	NONAME
	?ResetTranslator@CWin32Exception@@SAHXZ                     	@481	NONAME
	?Resize@CArrayContainer@@QAEHI@Z                            	@302	NONAME
	?Revoke@CCreator@@QAEXXZ                                    	@303	NONAME
	?Right@CBinaryNode@@QBEPAV1@XZ                              	@304	NONAME
	?RightMost@CBinaryNode@@QBEPAV1@XZ                          	@305	NONAME
	?SetContainer@CKeyNode@@QAEXPAVCKeyContainer@@@Z            	@306	NONAME
	?SetHandle@CNode@@QAEXPAX@Z                                 	@307	NONAME
	?SetLeft@CBinaryNode@@QAEXPAV1@@Z                           	@308	NONAME
	?SetNext@CHListNode@@QAEXPAV1@@Z                            	@309	NONAME
	?SetNext@CListNode@@QAEXPAV1@@Z                             	@310	NONAME
	?SetNode@CHashNode@@QAEXIPAVCHListNode@@@Z                  	@311	NONAME
	?SetParent@CBinaryNode@@QAEXPAV1@@Z                         	@312	NONAME
	?SetPrev@CHListNode@@QAEXPAV1@@Z                            	@313	NONAME
	?SetPrev@CListNode@@QAEXPAV1@@Z                             	@314	NONAME
	?SetRight@CBinaryNode@@QAEXPAV1@@Z                          	@315	NONAME
	?SetTranslator@CWin32Exception@@SAHXZ                       	@482	NONAME
	?Size@CArrayContainer@@QBEIXZ                               	@316	NONAME
	?Size@CHashNode@@QBEIXZ                                     	@317	NONAME
	?Size@CHashTable@@QBEIXZ                                    	@318	NONAME
	?Special@CTree@@AAEPAVCBinaryNode@@PAV2@W4Richtung@@@Z      	@319	NONAME
	?StrCmp@@YAHPAX0@Z                                          	@320	NONAME
	?StrHash@@YAIPAX@Z                                          	@321	NONAME
	?TIsValidAddress@@YGHPBXIH@Z                                	@322	NONAME
	?TIsValidIUnknown@@YGHPBX@Z                                 	@323	NONAME
	?TIsValidString@@YGHPBDH@Z                                  	@324	NONAME
	?To_Ticks@P5_Ticker@@QBE?AT_ULARGE_INTEGER@@XZ              	@530	NONAME
	?Translate@CWin32Exception@@SAIII@Z                         	@483	NONAME
	?Translator@CWin32Exception@@SAXIPAU_EXCEPTION_POINTERS@@@Z 	@484	NONAME
	?Unlock@CLock@@IAEXXZ                                       	@325	NONAME
	?Unlock@CNode@@QAEXXZ                                       	@326	NONAME
	?Unregister@CContainer@@AAEXPAVCNavigator@@@Z               	@327	NONAME
	?UserDelete@CContainer@@MAEXPAX@Z                           	@328	NONAME
	?UserDelete@DelTree@@MAEXPAX@Z                              	@329	NONAME
	?Valid@CLock@@QAEHXZ                                        	@330	NONAME
	?Valid@CNavigator@@QBEHXZ                                   	@331	NONAME
	?ValidateTree@CTree@@AAEHPAVCBinaryNode@@@Z                 	@332	NONAME
	?_exception_code@CWin32UserException@@QBEIXZ                	@485	NONAME
	?lock@CLock@@IAEXXZ                                         	@333	NONAME
	?m_fInstalled@CWin32Exception@@0HA                          	@486	NONAME
	?m_fP5TickerAvailable@COptTree@@1HA                         	@531	NONAME
	?m_pNextProc@CWin32Exception@@0P6AXIPAU_EXCEPTION_POINTERS@@@ZA	@487	NONAME
	?m_uiTranslated@CWin32Exception@@0IA                        	@488	NONAME
