///////////////////////////////////////////////////////////////////////////
// @doc 
// @module Array.h | Wrapperklasse für ein eindimensionales SAFEARRAY's

#if !defined(_ARRAY_H__4BAB20A4_A922_11D1_8588_00600875138A__INCLUDED_)
#define _ARRAY_H__4BAB20A4_A922_11D1_8588_00600875138A__INCLUDED_

#if _MSC_VER >= 1000
#pragma once
#endif // _MSC_VER >= 1000

// die Klasse ist jetzt hier definiert:
#include <Com/SafeArray.h>

#endif // !defined(_ARRAY_H__4BAB20A4_A922_11D1_8588_00600875138A__INCLUDED_)
