/* This header file machine-generated by mktyplib.exe */
/* Interface to type library: VisInfoLib */

#ifndef _VisInfoLib_H_
#define _VisInfoLib_H_

DEFINE_GUID(LIBID_VisInfoLib,0x0796385CL,0x3123,0x101C,0xBB,0x62,0x00,0xAA,0x00,0x18,0x49,0x7C);

typedef long TRIASCOLOR;

DEFINE_GUID(IID_IVisInfo,0x07963865L,0x3123,0x101C,0xBB,0x62,0x00,0xAA,0x00,0x18,0x49,0x7C);

/* Definition of interface: IVisInfo */
#undef INTERFACE
#define INTERFACE IVisInfo

DECLARE_INTERFACE_(IVisInfo, IUnknown)
{
#ifndef NO_BASEINTERFACE_FUNCS

    /* IUnknown methods */
    STDMETHOD(QueryInterface)(THIS_ REFIID riid, LPVOID FAR* ppvObj) PURE;
    STDMETHOD_(ULONG, AddRef)(THIS) PURE;
    STDMETHOD_(ULONG, Release)(THIS) PURE;
#endif

    /* IVisInfo methods */
    STDMETHOD(get_isA)(THIS_ long FAR* plRTTI) PURE;
    STDMETHOD(get_Parent)(THIS_ IDispatch * FAR* ppIBase) PURE;
    STDMETHOD(put_Parent)(THIS_ IDispatch * pIBase) PURE;
    STDMETHOD(get_Application)(THIS_ IDispatch * FAR* ppIApp) PURE;
    STDMETHOD(put_Application)(THIS_ IDispatch * pIApp) PURE;
    STDMETHOD(get_Style)(THIS_ int FAR* piStyle) PURE;
    STDMETHOD(put_Style)(THIS_ int iStyle) PURE;
    STDMETHOD(get_Priority)(THIS_ int FAR* piPrio) PURE;
    STDMETHOD(put_Priority)(THIS_ int iPrio) PURE;
    STDMETHOD(get_Name)(THIS_ BSTR FAR* pbstrDesc) PURE;
    STDMETHOD(put_Name)(THIS_ BSTR bstrDesc) PURE;
    STDMETHOD(get_MainColor)(THIS_ TRIASCOLOR FAR* pocMain) PURE;
    STDMETHOD(put_MainColor)(THIS_ TRIASCOLOR ocMain) PURE;
};

DEFINE_GUID(IID_IUpdateVisInfo,0x07963866L,0x3123,0x101C,0xBB,0x62,0x00,0xAA,0x00,0x18,0x49,0x7C);

/* Definition of interface: IUpdateVisInfo */
#undef INTERFACE
#define INTERFACE IUpdateVisInfo

DECLARE_INTERFACE_(IUpdateVisInfo, IUnknown)
{
#ifndef NO_BASEINTERFACE_FUNCS

    /* IUnknown methods */
    STDMETHOD(QueryInterface)(THIS_ REFIID riid, LPVOID FAR* ppvObj) PURE;
    STDMETHOD_(ULONG, AddRef)(THIS) PURE;
    STDMETHOD_(ULONG, Release)(THIS) PURE;
#endif

    /* IUpdateVisInfo methods */
    STDMETHOD(FromObject)(THIS_ long lONr, VARIANT bstrView) PURE;
    STDMETHOD(UpdateObject)(THIS_ long lONr, VARIANT bstrView) PURE;
    STDMETHOD(FromClass)(THIS_ long lIdent, VARIANT bstrView) PURE;
    STDMETHOD(UpdateClass)(THIS_ long lIdent, VARIANT bstrView) PURE;
};

DEFINE_GUID(IID_IPointVisInfo,0x0796385EL,0x3123,0x101C,0xBB,0x62,0x00,0xAA,0x00,0x18,0x49,0x7C);

/* Definition of interface: IPointVisInfo */
#undef INTERFACE
#define INTERFACE IPointVisInfo

DECLARE_INTERFACE_(IPointVisInfo, IVisInfo)
{
#ifndef NO_BASEINTERFACE_FUNCS

    /* IUnknown methods */
    STDMETHOD(QueryInterface)(THIS_ REFIID riid, LPVOID FAR* ppvObj) PURE;
    STDMETHOD_(ULONG, AddRef)(THIS) PURE;
    STDMETHOD_(ULONG, Release)(THIS) PURE;

    /* IVisInfo methods */
    STDMETHOD(get_isA)(THIS_ long FAR* plRTTI) PURE;
    STDMETHOD(get_Parent)(THIS_ IDispatch * FAR* ppIBase) PURE;
    STDMETHOD(put_Parent)(THIS_ IDispatch * pIBase) PURE;
    STDMETHOD(get_Application)(THIS_ IDispatch * FAR* ppIApp) PURE;
    STDMETHOD(put_Application)(THIS_ IDispatch * pIApp) PURE;
    STDMETHOD(get_Style)(THIS_ int FAR* piStyle) PURE;
    STDMETHOD(put_Style)(THIS_ int iStyle) PURE;
    STDMETHOD(get_Priority)(THIS_ int FAR* piPrio) PURE;
    STDMETHOD(put_Priority)(THIS_ int iPrio) PURE;
    STDMETHOD(get_Name)(THIS_ BSTR FAR* pbstrDesc) PURE;
    STDMETHOD(put_Name)(THIS_ BSTR bstrDesc) PURE;
    STDMETHOD(get_MainColor)(THIS_ TRIASCOLOR FAR* pocMain) PURE;
    STDMETHOD(put_MainColor)(THIS_ TRIASCOLOR ocMain) PURE;
#endif

    /* IPointVisInfo methods */
    STDMETHOD(get_SizeX)(THIS_ int FAR* piX) PURE;
    STDMETHOD(put_SizeX)(THIS_ int iX) PURE;
    STDMETHOD(get_SizeY)(THIS_ int FAR* piY) PURE;
    STDMETHOD(put_SizeY)(THIS_ int iY) PURE;
    STDMETHOD(get_Rotate)(THIS_ int FAR* piRot) PURE;
    STDMETHOD(put_Rotate)(THIS_ int iRot) PURE;
    STDMETHOD(get_BkColor)(THIS_ TRIASCOLOR FAR* pocBack) PURE;
    STDMETHOD(put_BkColor)(THIS_ TRIASCOLOR ocBack) PURE;
};

DEFINE_GUID(IID_ILineVisInfo,0x07963860L,0x3123,0x101C,0xBB,0x62,0x00,0xAA,0x00,0x18,0x49,0x7C);

/* Definition of interface: ILineVisInfo */
#undef INTERFACE
#define INTERFACE ILineVisInfo

DECLARE_INTERFACE_(ILineVisInfo, IVisInfo)
{
#ifndef NO_BASEINTERFACE_FUNCS

    /* IUnknown methods */
    STDMETHOD(QueryInterface)(THIS_ REFIID riid, LPVOID FAR* ppvObj) PURE;
    STDMETHOD_(ULONG, AddRef)(THIS) PURE;
    STDMETHOD_(ULONG, Release)(THIS) PURE;

    /* IVisInfo methods */
    STDMETHOD(get_isA)(THIS_ long FAR* plRTTI) PURE;
    STDMETHOD(get_Parent)(THIS_ IDispatch * FAR* ppIBase) PURE;
    STDMETHOD(put_Parent)(THIS_ IDispatch * pIBase) PURE;
    STDMETHOD(get_Application)(THIS_ IDispatch * FAR* ppIApp) PURE;
    STDMETHOD(put_Application)(THIS_ IDispatch * pIApp) PURE;
    STDMETHOD(get_Style)(THIS_ int FAR* piStyle) PURE;
    STDMETHOD(put_Style)(THIS_ int iStyle) PURE;
    STDMETHOD(get_Priority)(THIS_ int FAR* piPrio) PURE;
    STDMETHOD(put_Priority)(THIS_ int iPrio) PURE;
    STDMETHOD(get_Name)(THIS_ BSTR FAR* pbstrDesc) PURE;
    STDMETHOD(put_Name)(THIS_ BSTR bstrDesc) PURE;
    STDMETHOD(get_MainColor)(THIS_ TRIASCOLOR FAR* pocMain) PURE;
    STDMETHOD(put_MainColor)(THIS_ TRIASCOLOR ocMain) PURE;
#endif

    /* ILineVisInfo methods */
    STDMETHOD(get_Width)(THIS_ int FAR* piWidth) PURE;
    STDMETHOD(put_Width)(THIS_ int iWidth) PURE;
};

DEFINE_GUID(IID_IAreaVisInfo,0x07963862L,0x3123,0x101C,0xBB,0x62,0x00,0xAA,0x00,0x18,0x49,0x7C);

/* Definition of interface: IAreaVisInfo */
#undef INTERFACE
#define INTERFACE IAreaVisInfo

DECLARE_INTERFACE_(IAreaVisInfo, IVisInfo)
{
#ifndef NO_BASEINTERFACE_FUNCS

    /* IUnknown methods */
    STDMETHOD(QueryInterface)(THIS_ REFIID riid, LPVOID FAR* ppvObj) PURE;
    STDMETHOD_(ULONG, AddRef)(THIS) PURE;
    STDMETHOD_(ULONG, Release)(THIS) PURE;

    /* IVisInfo methods */
    STDMETHOD(get_isA)(THIS_ long FAR* plRTTI) PURE;
    STDMETHOD(get_Parent)(THIS_ IDispatch * FAR* ppIBase) PURE;
    STDMETHOD(put_Parent)(THIS_ IDispatch * pIBase) PURE;
    STDMETHOD(get_Application)(THIS_ IDispatch * FAR* ppIApp) PURE;
    STDMETHOD(put_Application)(THIS_ IDispatch * pIApp) PURE;
    STDMETHOD(get_Style)(THIS_ int FAR* piStyle) PURE;
    STDMETHOD(put_Style)(THIS_ int iStyle) PURE;
    STDMETHOD(get_Priority)(THIS_ int FAR* piPrio) PURE;
    STDMETHOD(put_Priority)(THIS_ int iPrio) PURE;
    STDMETHOD(get_Name)(THIS_ BSTR FAR* pbstrDesc) PURE;
    STDMETHOD(put_Name)(THIS_ BSTR bstrDesc) PURE;
    STDMETHOD(get_MainColor)(THIS_ TRIASCOLOR FAR* pocMain) PURE;
    STDMETHOD(put_MainColor)(THIS_ TRIASCOLOR ocMain) PURE;
#endif

    /* IAreaVisInfo methods */
    STDMETHOD(get_Width)(THIS_ int FAR* piWidth) PURE;
    STDMETHOD(put_Width)(THIS_ int iWidth) PURE;
    STDMETHOD(get_Opaque)(THIS_ int FAR* pfOpaque) PURE;
    STDMETHOD(put_Opaque)(THIS_ int fOpaque) PURE;
    STDMETHOD(get_BkContour)(THIS_ int FAR* pfBkContour) PURE;
    STDMETHOD(put_BkContour)(THIS_ int fBkContour) PURE;
    STDMETHOD(get_BkColor)(THIS_ TRIASCOLOR FAR* pocBack) PURE;
    STDMETHOD(put_BkColor)(THIS_ TRIASCOLOR ocBack) PURE;
};

typedef enum tagALIGNSTYLE {
    ALIGNSTYLE_Left = 0,
    ALIGNSTYLE_Centre = 1,
    ALIGNSTYLE_Right = 2,
    ALIGNSTYLE_Full = 3
} ALIGNSTYLE;

typedef enum tagFRAMESTYLE {
    FRAMESTYLE_NoFrame = 0,
    FRAMESTYLE_SimpleFrame = 1,
    FRAMESTYLE_Rounded = 2,
    FRAMESTYLE_TargetColor = 4
} FRAMESTYLE;

DEFINE_GUID(IID_ITextVisInfo,0x07963864L,0x3123,0x101C,0xBB,0x62,0x00,0xAA,0x00,0x18,0x49,0x7C);

/* Definition of interface: ITextVisInfo */
#undef INTERFACE
#define INTERFACE ITextVisInfo

DECLARE_INTERFACE_(ITextVisInfo, IVisInfo)
{
#ifndef NO_BASEINTERFACE_FUNCS

    /* IUnknown methods */
    STDMETHOD(QueryInterface)(THIS_ REFIID riid, LPVOID FAR* ppvObj) PURE;
    STDMETHOD_(ULONG, AddRef)(THIS) PURE;
    STDMETHOD_(ULONG, Release)(THIS) PURE;

    /* IVisInfo methods */
    STDMETHOD(get_isA)(THIS_ long FAR* plRTTI) PURE;
    STDMETHOD(get_Parent)(THIS_ IDispatch * FAR* ppIBase) PURE;
    STDMETHOD(put_Parent)(THIS_ IDispatch * pIBase) PURE;
    STDMETHOD(get_Application)(THIS_ IDispatch * FAR* ppIApp) PURE;
    STDMETHOD(put_Application)(THIS_ IDispatch * pIApp) PURE;
    STDMETHOD(get_Style)(THIS_ int FAR* piStyle) PURE;
    STDMETHOD(put_Style)(THIS_ int iStyle) PURE;
    STDMETHOD(get_Priority)(THIS_ int FAR* piPrio) PURE;
    STDMETHOD(put_Priority)(THIS_ int iPrio) PURE;
    STDMETHOD(get_Name)(THIS_ BSTR FAR* pbstrDesc) PURE;
    STDMETHOD(put_Name)(THIS_ BSTR bstrDesc) PURE;
    STDMETHOD(get_MainColor)(THIS_ TRIASCOLOR FAR* pocMain) PURE;
    STDMETHOD(put_MainColor)(THIS_ TRIASCOLOR ocMain) PURE;
#endif

    /* ITextVisInfo methods */
    STDMETHOD(get_SizeX)(THIS_ int FAR* piX) PURE;
    STDMETHOD(put_SizeX)(THIS_ int iX) PURE;
    STDMETHOD(get_SizeY)(THIS_ int FAR* piY) PURE;
    STDMETHOD(put_SizeY)(THIS_ int iY) PURE;
    STDMETHOD(get_Bold)(THIS_ int FAR* pfBold) PURE;
    STDMETHOD(put_Bold)(THIS_ int fBold) PURE;
    STDMETHOD(get_Italic)(THIS_ int FAR* pfItalic) PURE;
    STDMETHOD(put_Italic)(THIS_ int fItalic) PURE;
    STDMETHOD(get_Underline)(THIS_ int FAR* pfUnderline) PURE;
    STDMETHOD(put_Underline)(THIS_ int fUnderline) PURE;
    STDMETHOD(get_StrikeThrough)(THIS_ int FAR* pfStrikeThrough) PURE;
    STDMETHOD(put_StrikeThrough)(THIS_ int fStrikeThrough) PURE;
    STDMETHOD(get_FrameStyle)(THIS_ FRAMESTYLE FAR* prgFrameStyle) PURE;
    STDMETHOD(put_FrameStyle)(THIS_ FRAMESTYLE rgFrameStyle) PURE;
    STDMETHOD(get_AlignStyle)(THIS_ ALIGNSTYLE FAR* prgAlign) PURE;
    STDMETHOD(put_AlignStyle)(THIS_ ALIGNSTYLE rgAlign) PURE;
    STDMETHOD(get_Rotate)(THIS_ int FAR* piRot) PURE;
    STDMETHOD(put_Rotate)(THIS_ int iRot) PURE;
    STDMETHOD(get_Slant)(THIS_ int FAR* piSlant) PURE;
    STDMETHOD(put_Slant)(THIS_ int iSlant) PURE;
};

DEFINE_GUID(IID_DVisInfo,0x0796386BL,0x3123,0x101C,0xBB,0x62,0x00,0xAA,0x00,0x18,0x49,0x7C);

/* Definition of interface: DVisInfo */
#undef INTERFACE
#define INTERFACE DVisInfo

DECLARE_INTERFACE_(DVisInfo, IDispatch)
{
#ifndef NO_BASEINTERFACE_FUNCS

    /* IUnknown methods */
    STDMETHOD(QueryInterface)(THIS_ REFIID riid, LPVOID FAR* ppvObj) PURE;
    STDMETHOD_(ULONG, AddRef)(THIS) PURE;
    STDMETHOD_(ULONG, Release)(THIS) PURE;

    /* IDispatch methods */
    STDMETHOD(GetTypeInfoCount)(THIS_ UINT FAR* pctinfo) PURE;

    STDMETHOD(GetTypeInfo)(
      THIS_
      UINT itinfo,
      LCID lcid,
      ITypeInfo FAR* FAR* pptinfo) PURE;

    STDMETHOD(GetIDsOfNames)(
      THIS_
      REFIID riid,
      OLECHAR FAR* FAR* rgszNames,
      UINT cNames,
      LCID lcid,
      DISPID FAR* rgdispid) PURE;

    STDMETHOD(Invoke)(
      THIS_
      DISPID dispidMember,
      REFIID riid,
      LCID lcid,
      WORD wFlags,
      DISPPARAMS FAR* pdispparams,
      VARIANT FAR* pvarResult,
      EXCEPINFO FAR* pexcepinfo,
      UINT FAR* puArgErr) PURE;
#endif

    /* DVisInfo methods */
    STDMETHOD(get_isA)(THIS_ long FAR* plRTTI) PURE;
    STDMETHOD(get_Parent)(THIS_ IDispatch * FAR* ppIBase) PURE;
    STDMETHOD(put_Parent)(THIS_ IDispatch * pIBase) PURE;
    STDMETHOD(get_Application)(THIS_ IDispatch * FAR* ppIApp) PURE;
    STDMETHOD(put_Application)(THIS_ IDispatch * pIApp) PURE;
    STDMETHOD(get_Style)(THIS_ int FAR* piStyle) PURE;
    STDMETHOD(put_Style)(THIS_ int iStyle) PURE;
    STDMETHOD(get_Priority)(THIS_ int FAR* piPrio) PURE;
    STDMETHOD(put_Priority)(THIS_ int iPrio) PURE;
    STDMETHOD(get_Name)(THIS_ BSTR FAR* pbstrDesc) PURE;
    STDMETHOD(put_Name)(THIS_ BSTR bstrDesc) PURE;
    STDMETHOD(get_MainColor)(THIS_ TRIASCOLOR FAR* pocMain) PURE;
    STDMETHOD(put_MainColor)(THIS_ TRIASCOLOR ocMain) PURE;
};

DEFINE_GUID(IID_DPointVisInfo,0x07963867L,0x3123,0x101C,0xBB,0x62,0x00,0xAA,0x00,0x18,0x49,0x7C);

/* Definition of interface: DPointVisInfo */
#undef INTERFACE
#define INTERFACE DPointVisInfo

DECLARE_INTERFACE_(DPointVisInfo, DVisInfo)
{
#ifndef NO_BASEINTERFACE_FUNCS

    /* IUnknown methods */
    STDMETHOD(QueryInterface)(THIS_ REFIID riid, LPVOID FAR* ppvObj) PURE;
    STDMETHOD_(ULONG, AddRef)(THIS) PURE;
    STDMETHOD_(ULONG, Release)(THIS) PURE;

    /* IDispatch methods */
    STDMETHOD(GetTypeInfoCount)(THIS_ UINT FAR* pctinfo) PURE;

    STDMETHOD(GetTypeInfo)(
      THIS_
      UINT itinfo,
      LCID lcid,
      ITypeInfo FAR* FAR* pptinfo) PURE;

    STDMETHOD(GetIDsOfNames)(
      THIS_
      REFIID riid,
      OLECHAR FAR* FAR* rgszNames,
      UINT cNames,
      LCID lcid,
      DISPID FAR* rgdispid) PURE;

    STDMETHOD(Invoke)(
      THIS_
      DISPID dispidMember,
      REFIID riid,
      LCID lcid,
      WORD wFlags,
      DISPPARAMS FAR* pdispparams,
      VARIANT FAR* pvarResult,
      EXCEPINFO FAR* pexcepinfo,
      UINT FAR* puArgErr) PURE;

    /* DVisInfo methods */
    STDMETHOD(get_isA)(THIS_ long FAR* plRTTI) PURE;
    STDMETHOD(get_Parent)(THIS_ IDispatch * FAR* ppIBase) PURE;
    STDMETHOD(put_Parent)(THIS_ IDispatch * pIBase) PURE;
    STDMETHOD(get_Application)(THIS_ IDispatch * FAR* ppIApp) PURE;
    STDMETHOD(put_Application)(THIS_ IDispatch * pIApp) PURE;
    STDMETHOD(get_Style)(THIS_ int FAR* piStyle) PURE;
    STDMETHOD(put_Style)(THIS_ int iStyle) PURE;
    STDMETHOD(get_Priority)(THIS_ int FAR* piPrio) PURE;
    STDMETHOD(put_Priority)(THIS_ int iPrio) PURE;
    STDMETHOD(get_Name)(THIS_ BSTR FAR* pbstrDesc) PURE;
    STDMETHOD(put_Name)(THIS_ BSTR bstrDesc) PURE;
    STDMETHOD(get_MainColor)(THIS_ TRIASCOLOR FAR* pocMain) PURE;
    STDMETHOD(put_MainColor)(THIS_ TRIASCOLOR ocMain) PURE;
#endif

    /* DPointVisInfo methods */
    STDMETHOD(get_SizeX)(THIS_ int FAR* piX) PURE;
    STDMETHOD(put_SizeX)(THIS_ int iX) PURE;
    STDMETHOD(get_SizeY)(THIS_ int FAR* piY) PURE;
    STDMETHOD(put_SizeY)(THIS_ int iY) PURE;
    STDMETHOD(get_Rotate)(THIS_ int FAR* piRot) PURE;
    STDMETHOD(put_Rotate)(THIS_ int iRot) PURE;
    STDMETHOD(get_BkColor)(THIS_ TRIASCOLOR FAR* pocBack) PURE;
    STDMETHOD(put_BkColor)(THIS_ TRIASCOLOR ocBack) PURE;
};

DEFINE_GUID(IID_DLineVisInfo,0x07963868L,0x3123,0x101C,0xBB,0x62,0x00,0xAA,0x00,0x18,0x49,0x7C);

/* Definition of interface: DLineVisInfo */
#undef INTERFACE
#define INTERFACE DLineVisInfo

DECLARE_INTERFACE_(DLineVisInfo, DVisInfo)
{
#ifndef NO_BASEINTERFACE_FUNCS

    /* IUnknown methods */
    STDMETHOD(QueryInterface)(THIS_ REFIID riid, LPVOID FAR* ppvObj) PURE;
    STDMETHOD_(ULONG, AddRef)(THIS) PURE;
    STDMETHOD_(ULONG, Release)(THIS) PURE;

    /* IDispatch methods */
    STDMETHOD(GetTypeInfoCount)(THIS_ UINT FAR* pctinfo) PURE;

    STDMETHOD(GetTypeInfo)(
      THIS_
      UINT itinfo,
      LCID lcid,
      ITypeInfo FAR* FAR* pptinfo) PURE;

    STDMETHOD(GetIDsOfNames)(
      THIS_
      REFIID riid,
      OLECHAR FAR* FAR* rgszNames,
      UINT cNames,
      LCID lcid,
      DISPID FAR* rgdispid) PURE;

    STDMETHOD(Invoke)(
      THIS_
      DISPID dispidMember,
      REFIID riid,
      LCID lcid,
      WORD wFlags,
      DISPPARAMS FAR* pdispparams,
      VARIANT FAR* pvarResult,
      EXCEPINFO FAR* pexcepinfo,
      UINT FAR* puArgErr) PURE;

    /* DVisInfo methods */
    STDMETHOD(get_isA)(THIS_ long FAR* plRTTI) PURE;
    STDMETHOD(get_Parent)(THIS_ IDispatch * FAR* ppIBase) PURE;
    STDMETHOD(put_Parent)(THIS_ IDispatch * pIBase) PURE;
    STDMETHOD(get_Application)(THIS_ IDispatch * FAR* ppIApp) PURE;
    STDMETHOD(put_Application)(THIS_ IDispatch * pIApp) PURE;
    STDMETHOD(get_Style)(THIS_ int FAR* piStyle) PURE;
    STDMETHOD(put_Style)(THIS_ int iStyle) PURE;
    STDMETHOD(get_Priority)(THIS_ int FAR* piPrio) PURE;
    STDMETHOD(put_Priority)(THIS_ int iPrio) PURE;
    STDMETHOD(get_Name)(THIS_ BSTR FAR* pbstrDesc) PURE;
    STDMETHOD(put_Name)(THIS_ BSTR bstrDesc) PURE;
    STDMETHOD(get_MainColor)(THIS_ TRIASCOLOR FAR* pocMain) PURE;
    STDMETHOD(put_MainColor)(THIS_ TRIASCOLOR ocMain) PURE;
#endif

    /* DLineVisInfo methods */
    STDMETHOD(get_Width)(THIS_ int FAR* piWidth) PURE;
    STDMETHOD(put_Width)(THIS_ int iWidth) PURE;
};

DEFINE_GUID(IID_DAreaVisInfo,0x07963869L,0x3123,0x101C,0xBB,0x62,0x00,0xAA,0x00,0x18,0x49,0x7C);

/* Definition of interface: DAreaVisInfo */
#undef INTERFACE
#define INTERFACE DAreaVisInfo

DECLARE_INTERFACE_(DAreaVisInfo, DVisInfo)
{
#ifndef NO_BASEINTERFACE_FUNCS

    /* IUnknown methods */
    STDMETHOD(QueryInterface)(THIS_ REFIID riid, LPVOID FAR* ppvObj) PURE;
    STDMETHOD_(ULONG, AddRef)(THIS) PURE;
    STDMETHOD_(ULONG, Release)(THIS) PURE;

    /* IDispatch methods */
    STDMETHOD(GetTypeInfoCount)(THIS_ UINT FAR* pctinfo) PURE;

    STDMETHOD(GetTypeInfo)(
      THIS_
      UINT itinfo,
      LCID lcid,
      ITypeInfo FAR* FAR* pptinfo) PURE;

    STDMETHOD(GetIDsOfNames)(
      THIS_
      REFIID riid,
      OLECHAR FAR* FAR* rgszNames,
      UINT cNames,
      LCID lcid,
      DISPID FAR* rgdispid) PURE;

    STDMETHOD(Invoke)(
      THIS_
      DISPID dispidMember,
      REFIID riid,
      LCID lcid,
      WORD wFlags,
      DISPPARAMS FAR* pdispparams,
      VARIANT FAR* pvarResult,
      EXCEPINFO FAR* pexcepinfo,
      UINT FAR* puArgErr) PURE;

    /* DVisInfo methods */
    STDMETHOD(get_isA)(THIS_ long FAR* plRTTI) PURE;
    STDMETHOD(get_Parent)(THIS_ IDispatch * FAR* ppIBase) PURE;
    STDMETHOD(put_Parent)(THIS_ IDispatch * pIBase) PURE;
    STDMETHOD(get_Application)(THIS_ IDispatch * FAR* ppIApp) PURE;
    STDMETHOD(put_Application)(THIS_ IDispatch * pIApp) PURE;
    STDMETHOD(get_Style)(THIS_ int FAR* piStyle) PURE;
    STDMETHOD(put_Style)(THIS_ int iStyle) PURE;
    STDMETHOD(get_Priority)(THIS_ int FAR* piPrio) PURE;
    STDMETHOD(put_Priority)(THIS_ int iPrio) PURE;
    STDMETHOD(get_Name)(THIS_ BSTR FAR* pbstrDesc) PURE;
    STDMETHOD(put_Name)(THIS_ BSTR bstrDesc) PURE;
    STDMETHOD(get_MainColor)(THIS_ TRIASCOLOR FAR* pocMain) PURE;
    STDMETHOD(put_MainColor)(THIS_ TRIASCOLOR ocMain) PURE;
#endif

    /* DAreaVisInfo methods */
    STDMETHOD(get_Width)(THIS_ int FAR* piWidth) PURE;
    STDMETHOD(put_Width)(THIS_ int iWidth) PURE;
    STDMETHOD(get_Opaque)(THIS_ int FAR* pfOpaque) PURE;
    STDMETHOD(put_Opaque)(THIS_ int fOpaque) PURE;
    STDMETHOD(get_BkContour)(THIS_ int FAR* pfBkContour) PURE;
    STDMETHOD(put_BkContour)(THIS_ int fBkContour) PURE;
    STDMETHOD(get_BkColor)(THIS_ TRIASCOLOR FAR* pocBack) PURE;
    STDMETHOD(put_BkColor)(THIS_ TRIASCOLOR ocBack) PURE;
};

DEFINE_GUID(IID_DTextVisInfo,0x0796386AL,0x3123,0x101C,0xBB,0x62,0x00,0xAA,0x00,0x18,0x49,0x7C);

/* Definition of interface: DTextVisInfo */
#undef INTERFACE
#define INTERFACE DTextVisInfo

DECLARE_INTERFACE_(DTextVisInfo, DVisInfo)
{
#ifndef NO_BASEINTERFACE_FUNCS

    /* IUnknown methods */
    STDMETHOD(QueryInterface)(THIS_ REFIID riid, LPVOID FAR* ppvObj) PURE;
    STDMETHOD_(ULONG, AddRef)(THIS) PURE;
    STDMETHOD_(ULONG, Release)(THIS) PURE;

    /* IDispatch methods */
    STDMETHOD(GetTypeInfoCount)(THIS_ UINT FAR* pctinfo) PURE;

    STDMETHOD(GetTypeInfo)(
      THIS_
      UINT itinfo,
      LCID lcid,
      ITypeInfo FAR* FAR* pptinfo) PURE;

    STDMETHOD(GetIDsOfNames)(
      THIS_
      REFIID riid,
      OLECHAR FAR* FAR* rgszNames,
      UINT cNames,
      LCID lcid,
      DISPID FAR* rgdispid) PURE;

    STDMETHOD(Invoke)(
      THIS_
      DISPID dispidMember,
      REFIID riid,
      LCID lcid,
      WORD wFlags,
      DISPPARAMS FAR* pdispparams,
      VARIANT FAR* pvarResult,
      EXCEPINFO FAR* pexcepinfo,
      UINT FAR* puArgErr) PURE;

    /* DVisInfo methods */
    STDMETHOD(get_isA)(THIS_ long FAR* plRTTI) PURE;
    STDMETHOD(get_Parent)(THIS_ IDispatch * FAR* ppIBase) PURE;
    STDMETHOD(put_Parent)(THIS_ IDispatch * pIBase) PURE;
    STDMETHOD(get_Application)(THIS_ IDispatch * FAR* ppIApp) PURE;
    STDMETHOD(put_Application)(THIS_ IDispatch * pIApp) PURE;
    STDMETHOD(get_Style)(THIS_ int FAR* piStyle) PURE;
    STDMETHOD(put_Style)(THIS_ int iStyle) PURE;
    STDMETHOD(get_Priority)(THIS_ int FAR* piPrio) PURE;
    STDMETHOD(put_Priority)(THIS_ int iPrio) PURE;
    STDMETHOD(get_Name)(THIS_ BSTR FAR* pbstrDesc) PURE;
    STDMETHOD(put_Name)(THIS_ BSTR bstrDesc) PURE;
    STDMETHOD(get_MainColor)(THIS_ TRIASCOLOR FAR* pocMain) PURE;
    STDMETHOD(put_MainColor)(THIS_ TRIASCOLOR ocMain) PURE;
#endif

    /* DTextVisInfo methods */
    STDMETHOD(get_SizeX)(THIS_ int FAR* piX) PURE;
    STDMETHOD(put_SizeX)(THIS_ int iX) PURE;
    STDMETHOD(get_SizeY)(THIS_ int FAR* piY) PURE;
    STDMETHOD(put_SizeY)(THIS_ int iY) PURE;
    STDMETHOD(get_Bold)(THIS_ int FAR* pfBold) PURE;
    STDMETHOD(put_Bold)(THIS_ int fBold) PURE;
    STDMETHOD(get_Italic)(THIS_ int FAR* pfItalic) PURE;
    STDMETHOD(put_Italic)(THIS_ int fItalic) PURE;
    STDMETHOD(get_Underline)(THIS_ int FAR* pfUnderline) PURE;
    STDMETHOD(put_Underline)(THIS_ int fUnderline) PURE;
    STDMETHOD(get_StrikeThrough)(THIS_ int FAR* pfStrikeThrough) PURE;
    STDMETHOD(put_StrikeThrough)(THIS_ int fStrikeThrough) PURE;
    STDMETHOD(get_FrameStyle)(THIS_ FRAMESTYLE FAR* prgFrameStyle) PURE;
    STDMETHOD(put_FrameStyle)(THIS_ FRAMESTYLE rgFrameStyle) PURE;
    STDMETHOD(get_AlignStyle)(THIS_ ALIGNSTYLE FAR* prgAlign) PURE;
    STDMETHOD(put_AlignStyle)(THIS_ ALIGNSTYLE rgAlign) PURE;
    STDMETHOD(get_Rotate)(THIS_ int FAR* piRot) PURE;
    STDMETHOD(put_Rotate)(THIS_ int iRot) PURE;
    STDMETHOD(get_Slant)(THIS_ int FAR* piSlant) PURE;
    STDMETHOD(put_Slant)(THIS_ int iSlant) PURE;
};

DEFINE_GUID(CLSID_PointVisInfo,0x0796385DL,0x3123,0x101C,0xBB,0x62,0x00,0xAA,0x00,0x18,0x49,0x7C);

#ifdef __cplusplus
class PointVisInfo;
#endif

DEFINE_GUID(CLSID_LineVisInfo,0x0796385FL,0x3123,0x101C,0xBB,0x62,0x00,0xAA,0x00,0x18,0x49,0x7C);

#ifdef __cplusplus
class LineVisInfo;
#endif

DEFINE_GUID(CLSID_AreaVisInfo,0x07963861L,0x3123,0x101C,0xBB,0x62,0x00,0xAA,0x00,0x18,0x49,0x7C);

#ifdef __cplusplus
class AreaVisInfo;
#endif

DEFINE_GUID(CLSID_TextVisInfo,0x07963863L,0x3123,0x101C,0xBB,0x62,0x00,0xAA,0x00,0x18,0x49,0x7C);

#ifdef __cplusplus
class TextVisInfo;
#endif

#endif
