# Makefile zur Erstellung von TRiAS3 - TRiASCFG

$(TRIASDIR_D)\TRiASCFGD.dll :
	SET T3PROJECT=TRiASCFG.dsp
	SET T3CONFIG="TRiASCFG - Win32 Debug"
	SET T3LOGFILE=TRiASCFG.log
!INCLUDE C:\MAKE\MkMSDEV.mak	

$(TRIASDIR_R)\TRiASCFG.dll :
	SET T3PROJECT=TRiASCFG.dsp
	SET T3CONFIG="TRiASCFG - Win32 Release MinSize"
	SET T3LOGFILE=TRiASCFG.log
!INCLUDE C:\MAKE\MkMSDEV.mak	

