// $Header: $
// Copyright© 1998-2000 TRiAS GmbH Potsdam, All rights reserved
// Created: 10.05.2000 19:36:40
//
// This file was generated by the TRiASDB Data Server Wizard V1.02.086 (#HK000510)
//
// @doc
// @module StdAfx.h | include file for standard system include files,
// or project specific include files that are used frequently,
// but are changed infrequently

#if !defined(_STDAFX_H__1D65238B_2902_494B_A744_5E022BA35243__INCLUDED_)
#define _STDAFX_H__1D65238B_2902_494B_A744_5E022BA35243__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000

#include "TRiASHPConfig.h"
#include <TRiASConfig.h>

#include <afxwin.h>
#include <afxdisp.h>

///////////////////////////////////////////////////////////////////////////////
// ospace-STL specific stuff
namespace ospace { namespace std { namespace rel_ops {} } }
using namespace ospace::std;
using namespace ospace::std::rel_ops;

#include <ospace/std/string>
typedef os_string string;

#include <ospace/std/list>
#include <ospace/std/map>
#include <ospace/std/vector>

///////////////////////////////////////////////////////////////////////////////
// ATL-related stuff 
#include <atlbase.h>
//You may derive a class from CComModule and use it if you want to override
//something, but do not change the name of _Module
extern CComModule _Module;
#include <atlcom.h>
#include <atlctl.h>

#include <Atl/Ciid.h>
#include <Atl/CieThis.h>
#include <Atl/AtlAggregate.h>
#include <Atl/DebugObjectCount.h>	// count objects in debug builds

///////////////////////////////////////////////////////////////////////////////
// Interfacewrapper und Fehlerbehandlung
#include <ospace/com/Iterenum.h>
#include <ospace/com/ComErrorMacros.h>
#include <Com/ErrorMacros2.h>

///////////////////////////////////////////////////////////////////////////////
// TRiAS Schnittstelle
#include <xtension.h>
#include <xtensnx.h>

///////////////////////////////////////////////////////////////////////////////
// Fehlercodes
#include <DBMsg.hmc>
#include "TRiASHP.hmc"

#include "DBUtil.h"

///////////////////////////////////////////////////////////////////////////////
// diverse Objekte/Interfaces, auf die Bezug genommen wird
#include <GMObjects/PBasic.tlh>		// GeoMedia-Geometrieobjekte

#pragma warning (disable: 4192)		// automatically excluding 'symbol' while importing type library
#import "tlb/TRiASDB.tlb" raw_interfaces_only raw_native_types no_namespace named_guids
#import "Tlb/TRiASCS.tlb" raw_interfaces_only raw_native_types no_namespace named_guids \
	exclude("IStaticCollection", "IEnumCoordSystemNames")
#import "tlb/TDBGeo.tlb" raw_interfaces_only raw_native_types no_namespace named_guids
#import "tlb/TRiASMDS.tlb" raw_interfaces_only raw_native_types no_namespace named_guids

#include <TRiASDBModuleStrings.h>
#include <TRiASDBGuids.h>

///////////////////////////////////////////////////////////////////////////////
// sonstiges
#include <Com/PropertyHelper.h>
#include <Com/SafeArray.h>

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(_STDAFX_H__1D65238B_2902_494B_A744_5E022BA35243__INCLUDED)
