// $Header: $
// Copyright© 1998-2000 TRiAS GmbH Potsdam, All rights reserved
// Created: 10.05.2000 19:36:40 
//
// This file was generated by the TRiASDB Data Server Wizard V1.02.086 (#HK000510)
//
// @doc
// @module Strings.cpp | Definition of global string constants

#include "stdafx.h"
#include "strings.h"

///////////////////////////////////////////////////////////////////////////////
// sonstiges
const TCHAR g_cbNil[] = _T("");

///////////////////////////////////////////////////////////////////////////////
// Properties
const OLECHAR g_cbTRiASCSService[] = L"TRiASCSService";
const OLECHAR g_cbTRiASCSTransform[] = L"TRiASCSTransform";
const OLECHAR g_cbObjectsCursor[] = L"ObjectsCursor";
const OLECHAR g_cbObjectCursor[] = L"ObjectCursor";
const OLECHAR g_cbFeatureCursor[] = L"FeatureCursor";
const OLECHAR g_cbCSSGuid[] = L"CSSGuid";
const OLECHAR g_cbObjectMap[] = L"ObjectMap";
const OLECHAR g_cbObjectsMap[] = L"ObjectsMap";
const OLECHAR g_cbFeatureMap[] = L"FeatureMap";
const OLECHAR g_cbMetaDataMap[] = L"MetaDataMap";
const OLECHAR g_cbGDODataSource[] = L"GDODataSource";

/////////////////////////////////////////////////////////////////////////////
// SuchPattern für Objektklassenschlüssel
const TCHAR g_cbOKS[] = 
TEXT("\\[\\([[:xdigit:]]+\\)\\]" "\\|"							// [OKS]
	 "\\(\\([[:xdigit:]]+\\)[[:punct:][:blank:]].*\\)" "\\|"	// OKS:irgend was
	 "\\[\\([[:xdigit:]]+\\)\\]\\(.*\\)"  "\\|"					// [OKS]irgend was
	 "!\\(.*\\):\\[\\([[:xdigit:]]+\\)\\]\\(.*\\)"				// irgendwas![OKS]irgendwas (Monikerformat)
	);

/////////////////////////////////////////////////////////////////////////////
// Standardnamen für diverse Objekteigenschaften
const OLECHAR g_cbGeometry[] = L"Geometry";
const OLECHAR g_cbPrimaryKey[] = L"PrimaryKey";
const OLECHAR g_cbObjektname[] = L"Objektname";
const OLECHAR g_cbShapeID[] = L"ShapeID";

const TCHAR g_cbCoordSystem[] = "CoordSystem";
const TCHAR g_cbLoadFromFile[] = "LoadFromFile";
const TCHAR g_cbRoot[] = "Root";
const TCHAR g_cbPattern[] = ";%1=%2";

///////////////////////////////////////////////////////////////////////////////
// Monikersupport
const TCHAR g_cbMkObjectsDef[] = TEXT("MkObjectsDef");
const TCHAR g_cbMkObjectDef[] = TEXT("MkObjectDef");
const TCHAR g_cbMkConnection[] = TEXT("MkConnection");
const TCHAR g_cbMkProject[] = TEXT("MkProject");
const TCHAR g_cbMkFeature[] = TEXT("MkFeature");
const OLECHAR g_cbMkDel[] =  L"!";
const OLECHAR g_cbMkWild[] = L"\\";
const OLECHAR g_cbColon[] = L":";

///////////////////////////////////////////////////////////////////////////////
// Dateierweiterungen
const TCHAR g_cbShp[] = TEXT("shp");
const TCHAR g_cbDbf[] = TEXT("dbf");
const TCHAR g_cbIni[] = TEXT("ini");
const TCHAR g_cbTcf[] = TEXT("tcf");

