// $Header: $
// Copyright© 1998-2000 TRiAS GmbH Potsdam, All rights reserved
// Created: 10.05.2000 19:36:40 
//
// This file was generated by the TRiASDB Data Server Wizard V1.02.086 (#HK000510)
//
// @doc
// @module TRiASHPFeatures.h | Declaration of the <c CTRiASHPFeatures> class

#if !defined(_TRIASHPFEATURES_H__D5D5A526_A0FC_45BE_BD82_261078283632__INCLUDED_)
#define _TRIASHPFEATURES_H__D5D5A526_A0FC_45BE_BD82_261078283632__INCLUDED_

#if _MSC_VER >= 1000
#pragma once
#endif // _MSC_VER >= 1000

#include "resource.h"       // main symbols

// Header include diagnostics
#if defined(_TRIAS_DBG_HEADER_DIAGNOSTICS)
#pragma message(__TIME__": include " __FILE__ )
#endif

/////////////////////////////////////////////////////////////////////////////
// SmartIF's
DefineSmartInterface(TRiASFeatures);

/////////////////////////////////////////////////////////////////////////////
// CTRiASHPFeatures
class ATL_NO_VTABLE CTRiASHPFeatures : 
	public CComObjectRootEx<CComObjectThreadModel>,
	public CComCoClass<CTRiASHPFeatures, &CLSID_TRiASHPFeatures>,
	public CErrSupport<CTRiASHPFeatures, &IID_ITRiASFeatures>,
	public ITRiASFeaturesCallback
{
public:
	CTRiASHPFeatures()
	{
	}

	_ATLX_DEBUG_OBJECTCOUNT_IMPL(CTRiASHPFeatures)

	DECLARE_ONE_SIZE_PRIVATE_HEAP2(CTRiASHPFeatures);
	DECLARE_REGISTRY_RESOURCEID(IDR_TRIASHPFEATURES_RGS)

	DECLARE_AGGREGATE_EX_SUPPORT();
	BEGIN_COM_MAP(CTRiASHPFeatures)
		COM_INTERFACE_ENTRY(ITRiASFeaturesCallback)
		COM_INTERFACE_ENTRY(ISupportErrorInfo)
		COM_INTERFACE_ENTRY_THIS()

	// durch aggregiertes Objekt implementierte Interfaces
		COM_INTERFACE_ENTRY_AGGREGATE_EX(IID_ITRiASFeatures, m_BaseUnk.p)
		COM_INTERFACE_ENTRY_AGGREGATE_EX(IID_ITRiASBase, m_BaseUnk.p)
		COM_INTERFACE_ENTRY_AGGREGATE_EX(IID_IDispatch, m_BaseUnk.p)
		COM_INTERFACE_ENTRY_AGGREGATE_BLIND(m_BaseUnk.p)		// alles andere nicht gesondert behandeln
	END_COM_MAP()

	DECLARE_GET_CONTROLLING_UNKNOWN()
	DECLARE_PROTECT_FINAL_CONSTRUCT()
	HRESULT FinalConstruct()
	{
		RETURN_FAILED_HRESULT(m_BaseUnk.CreateInstance (CLSID_TRiASFeatures, CLSCTX_ALL, GetControllingUnknown()));

	WTRiASFeatures BaseObjs;

		RETURN_FAILED_HRESULT(m_BaseUnk -> QueryInterface(BaseObjs.ppi()));
		return BaseObjs -> putref_FeaturesCallback(this);
	}
	void FinalRelease (void)
	{
		m_BaseUnk.Assign(NULL);
	}

// ISupportsErrorInfo
	STDMETHOD(InterfaceSupportsErrorInfo)(REFIID riid);

// ITRiASFeaturesCallback
public:
	STDMETHOD(get_DefaultType)(BSTR *pbstrType);
	STDMETHOD(SetupFeatures)(IDispatch *pIParent, SETUPFEATURESMODE rgSetupMode);
	STDMETHOD(OnCreate)(VARIANT NameOrHandle, BSTR Type, FEATURETYPE rgType, ITRiASFeature **ppIFeat);
	STDMETHOD(OnDelete)(VARIANT vWhich);
	STDMETHOD(OnChanging)(CHANGEDFEATURES rgWhat, VARIANT vNewValue, VARIANT_BOOL *pDisAllow);
	STDMETHOD(OnChanged)(CHANGEDFEATURES rgWhat, VARIANT vOldValue);
	STDMETHOD(OnFinalRelease)();

protected:
	HRESULT SetupFeature (IDispatch *pIParent, ITRiASFeatures *pIBaseFeat, CShapeFieldBase *pField);

private:
	WUnknown m_BaseUnk;				// aggregiertes Objekt (TRiASFeatures)
};

#endif // !defined(_TRIASHPFEATURES_H__D5D5A526_A0FC_45BE_BD82_261078283632__INCLUDED_)
