// $Header: $
// Copyright© 1998-2000 TRiAS GmbH Potsdam, All rights reserved
// Created: 10.05.2000 19:36:40 
//
// This file was generated by the TRiASDB Data Server Wizard V1.02.086 (#HK000510)
//
// @doc
// @module TRiASHPObjectsCollection.h | Declaration of the <c CTRiASHPObjectsCollection> class

#if !defined(_TRIASHPOBJECTSCOLLECTION_H__5A3A9608_E362_4A52_8459_70D84F395DE3__INCLUDED_)
#define _TRIASHPOBJECTSCOLLECTION_H__5A3A9608_E362_4A52_8459_70D84F395DE3__INCLUDED_

#if _MSC_VER >= 1000
#pragma once
#endif // _MSC_VER >= 1000

// Header include diagnostics
#if defined(_TRIAS_DBG_HEADER_DIAGNOSTICS)
#pragma message(__TIME__": include " __FILE__ )
#endif

#include "resource.h"       // main symbols

/////////////////////////////////////////////////////////////////////////////
// SmartIF's
DefineSmartInterface(TRiASObjectsCollection);

/////////////////////////////////////////////////////////////////////////////
// CTRiASHPObjectsCollection
class ATL_NO_VTABLE CTRiASHPObjectsCollection : 
	public CComObjectRootEx<CComObjectThreadModel>,
	public CComCoClass<CTRiASHPObjectsCollection, &CLSID_TRiASHPObjectsCollection>,
	public CErrSupport<CTRiASHPObjectsCollection, &IID_ITRiASObjectsCollection>,
	public ITRiASObjectsCollectionCallback
{
public:
	CTRiASHPObjectsCollection()
	{
	}

	_ATLX_DEBUG_OBJECTCOUNT_IMPL(CTRiASHPObjectsCollection)

	DECLARE_REGISTRY_RESOURCEID(IDR_TRIASHPOBJECTSCOLLECTION_RGS)
	DECLARE_AGGREGATE_EX_SUPPORT();

	BEGIN_COM_MAP(CTRiASHPObjectsCollection)
		COM_INTERFACE_ENTRY(ITRiASObjectsCollectionCallback)
		COM_INTERFACE_ENTRY(ISupportErrorInfo)
		COM_INTERFACE_ENTRY_THIS()
		
	// durch aggregiertes Objekt implementierte Interfaces
		COM_INTERFACE_ENTRY_AGGREGATE_EX(IID_ITRiASObjectsCollection, m_BaseUnk.p)
		COM_INTERFACE_ENTRY_AGGREGATE_EX(IID_ITRiASBase, m_BaseUnk.p)
		COM_INTERFACE_ENTRY_AGGREGATE_EX(IID_IDispatch, m_BaseUnk.p)
		COM_INTERFACE_ENTRY_AGGREGATE_BLIND(m_BaseUnk.p)		// alles andere nicht gesondert behandeln
	END_COM_MAP()

	DECLARE_GET_CONTROLLING_UNKNOWN()
	DECLARE_PROTECT_FINAL_CONSTRUCT()
	HRESULT FinalConstruct()
	{
		RETURN_FAILED_HRESULT(m_BaseUnk.CreateInstance (CLSID_TRiASObjectsCollection, CLSCTX_ALL, GetControllingUnknown()));

	WTRiASObjectsCollection BaseObj;

		RETURN_FAILED_HRESULT(m_BaseUnk -> QueryInterface(BaseObj.ppi()));
		return BaseObj -> putref_ObjectsCollectionCallback(this);
	}
	void FinalRelease()
	{
		m_BaseUnk.Assign(NULL);
	}

// ISupportsErrorInfo
	STDMETHOD(InterfaceSupportsErrorInfo)(REFIID riid);

// ITRiASObjectsCollectionCallback
public:
	STDMETHOD(get_DefaultType)(BSTR *pbstrType);
	STDMETHOD(OnCreate)(VARIANT NameOrHandle, BSTR Type, OBJECTSCOLLECTIONTYPE rgType, ITRiASObjects **ppIObjs);
	STDMETHOD(OnDelete)(VARIANT vWhich);
	STDMETHOD(OnFinalRelease)();

#if defined(_READ_WRITE)
protected:
	HRESULT CreateObject (VARIANT NameOrHandle, DWORD dwType, const CLSID *pClsId, ITRiASObjects **ppIObjs);
#endif // defined(_READ_WRITE)

private:
	WUnknown m_BaseUnk;					// aggregiertes Objekt
};

#endif // !defined(_TRIASHPOBJECTSCOLLECTION_H__5A3A9608_E362_4A52_8459_70D84F395DE3__INCLUDED_)
