import "oaidl.idl";
import "ocidl.idl";

#include "LPict42.ver"
#define STDINTERFACE(help)	pointer_default(unique), helpstring(help)

[ uuid(95F33831-BB7F-11d2-98EB-0060085FC1CE),
	, lcid(TYPELIB_LPict42_LCID)
	, helpstring(TYPELIB_LPict42_HELPSTRING)
	, version(TYPELIB_LPict42_VERSION)
] library LPict42 {
};
