!include $(TRIASINCLUDE)\TRiASVerLang.mak
APP_SHORT		= UiCtrl
APP_LONG		= User Interface
APP_YEAR		= 1998-2005
APP_COPYRIGHT	= HK050104
APP_VERSION		= 1
APP_RELEASE		= 00
APP_BUILD	= 123
APP_TLB_MINOR = 0
APP_TLB_MAJOR = 1
!include $(TRIASINCLUDE)\triasverEx.mak
