// $Header: $
// Copyright© 1998-2001 TRiAS GmbH Potsdam, All rights reserved
// Created: 27.04.2001 16:50:09 
//
// This file was generated by the TRiASDB Data Server Wizard V1.02.115 (#HK010427)
//
// @doc
// @module Strings.cpp | Definition of global string constants

#include "stdafx.h"
#include "strings.h"

///////////////////////////////////////////////////////////////////////////////
// sonstiges
const TCHAR g_cbNil[] = _T("");
const OLECHAR g_cbNoMemory[] = L"Out of memory error";

///////////////////////////////////////////////////////////////////////////////
// Properties
const OLECHAR g_cbTRiASCSService[] = L"TRiASCSService";
const OLECHAR g_cbTRiASCSTransform[] = L"TRiASCSTransform";
// BEGIN_SAMPLEDATA
const OLECHAR g_cbObjectsCursor[] = L"ObjectsCursor";
const OLECHAR g_cbObjectCursor[] = L"ObjectCursor";
const OLECHAR g_cbFeatureCursor[] = L"FeatureCursor";
const OLECHAR g_cbCSSGuid[] = L"CSSGuid";
const OLECHAR g_cbObjectMap[] = L"ObjectMap";
const OLECHAR g_cbObjectsMap[] = L"ObjectsMap";
const OLECHAR g_cbFeatureMap[] = L"FeatureMap";
// END_SAMPLE_DATA

/////////////////////////////////////////////////////////////////////////////
// SuchPattern für Objektklassenschlüssel
const TCHAR g_cbOKS[] = 
TEXT("\\[\\([[:xdigit:]]+\\)\\]" "\\|"							// [OKS]
	 "\\(\\([[:xdigit:]]+\\)[[:punct:][:blank:]].*\\)" "\\|"	// OKS:irgend was
	 "\\[\\([[:xdigit:]]+\\)\\]\\(.*\\)"  "\\|"					// [OKS]irgend was
	 "!\\(.*\\):\\[\\([[:xdigit:]]+\\)\\]\\(.*\\)"				// !irgendwas:[OKS]irgendwas (Monikerformat)
	);

/////////////////////////////////////////////////////////////////////////////
// Standardnamen für diverse Objekteigenschaften
const OLECHAR g_cbGeometry[] = L"Geometry";
const OLECHAR g_cbObjektname[] = L"Objektname";

///////////////////////////////////////////////////////////////////////////////
// Monikersupport
const TCHAR g_cbMkObjectsDef[] = TEXT("MkObjectsDef");
const TCHAR g_cbMkObjectDef[] = TEXT("MkObjectDef");
const TCHAR g_cbMkConnection[] = TEXT("MkConnection");
const TCHAR g_cbMkProject[] = TEXT("MkProject");
const TCHAR g_cbMkFeature[] = TEXT("MkFeature");
const OLECHAR g_cbMkDel[] =  L"!";
const OLECHAR g_cbMkWild[] = L"\\";

