// $Header: $
// Copyright© 1999-2001 TRiAS GmbH Potsdam, All rights reserved
// Created: 27.04.2001 16:50:09
//
// This file was generated by the TRiASDB Data Server Wizard V1.02.115 (#HK010427)
//
// THIS CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT WARRANTY OF ANY 
// KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
// IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A PARTICULAR 
// PURPOSE.
//
// @doc
// @module Version.h | Versionen dieses Modules

#if !defined(_VERSION_H__D54ADECD_1D8C_4ED9_AE31_D2AF277B365B__INCLUDED_)
#define _VERSION_H__D54ADECD_1D8C_4ED9_AE31_D2AF277B365B__INCLUDED_

#if _MSC_VER >= 1000
#pragma once
#endif // _MSC_VER >= 1000

// VersionsInfo des DataServers
#define TRIASOGC_VERSION	"1"
#define TRIASOGC_RELEASE	"00"
#define TRIASOGC_BUILD		"007"

// VersionsInfo der TRiASOGCDatabase
#define TRIASOGC_VERSION_MAJOR	1
#define TRIASOGC_VERSION_MINOR	00

#endif // !defined(_VERSION_H__D54ADECD_1D8C_4ED9_AE31_D2AF277B365B__INCLUDED_)
