#include "stdafx.h"
#include "TRiASCs.h"
CODENAME _CT_TRIASCSUNITOFANGLE[] = {
	{ tcsUOA_Radian, _T("radian") },
	{ tcsUOA_Degree, _T("degree") },
	{ tcsUOA_ArcMinute, _T("arc-minute") },
	{ tcsUOA_ArcSecond, _T("arc-second") },
	{ tcsUOA_Grad, _T("grad") },
	{ tcsUOA_Gon, _T("gon") },
	{ tcsUOA_DMS, _T("DMS") },
	{ tcsUOA_DMSH, _T("DMSH") },
	{ tcsUOA_Microradian, _T("microradian") },
	{ tcsUOA_DDDMMSSsss, _T("DDD.MMSSsss") },
	{ tcsUOA_Second, _T("Second") },
	{ tcsUOA_Undefined, NULL }
};
CODENAME _CT_TRIASCSDTRANSALGORITHM[] = {
	{ tcsDTA_LongitudeRotation, _T("Longitude rotation") },
	{ tcsDTA_GeodeticGeocentricConversions, _T("Geodetic/geocentric conversions") },
	{ tcsDTA_GeocentricTranslations, _T("Geocentric translations") },
	{ tcsDTA_Molodenski, _T("Molodenski") },
	{ tcsDTA_AbridgedMolodenski, _T("Abridged Molodenski") },
	{ tcsDTA_PositionVector7ParamTransformation, _T("Position Vector 7-param. transformation") },
	{ tcsDTA_CoordinateFrame7ParamTransformation, _T("Coordinate Frame 7-param. transformation") },
	{ tcsDTA_SimilarityTransform, _T("Similarity transform") },
	{ tcsDTA_2DimensionalAffineTransformation, _T("2-dimensional Affine transformation") },
	{ tcsDTA_2ndOrderPolynomialFunction, _T("2nd-order Polynomial function") },
	{ tcsDTA_3rdOrderPolynomialFunction, _T("3rd-order Polynomial function") },
	{ tcsDTA_4thOrderPolynomialFunction, _T("4th-order Polynomial function") },
	{ tcsDTA_NADCON, _T("NADCON") },
	{ tcsDTA_CanadaNTv1, _T("Canada NTv1") },
	{ tcsDTA_CanadaNTv2, _T("Canada NTv2") },
	{ tcsDTA_VerticalOffset, _T("Vertical Offset") },
	{ tcsDTA_Undefined, NULL }
};
CODENAME _CT_TRIASCSELLIPSOID[] = {
	{ tcsEL_Airy1830, _T("Airy 1830") },
	{ tcsEL_AiryModified1849, _T("Airy Modified 1849") },
	{ tcsEL_AustralianNationalSpheroid, _T("Australian National Spheroid") },
	{ tcsEL_Bessel1841, _T("Bessel 1841") },
	{ tcsEL_BesselModified, _T("Bessel Modified") },
	{ tcsEL_BesselNamibia, _T("Bessel Namibia") },
	{ tcsEL_Clarke1858, _T("Clarke 1858") },
	{ tcsEL_Clarke1866, _T("Clarke 1866") },
	{ tcsEL_Clarke1866Michigan, _T("Clarke 1866 Michigan") },
	{ tcsEL_Clarke1880Benoit, _T("Clarke 1880 (Benoit)") },
	{ tcsEL_Clarke1880IGN, _T("Clarke 1880 (IGN)") },
	{ tcsEL_Clarke1880RGS, _T("Clarke 1880 (RGS)") },
	{ tcsEL_Clarke1880Arc, _T("Clarke 1880 (Arc)") },
	{ tcsEL_Clarke1880SGA1922, _T("Clarke 1880 (SGA 1922)") },
	{ tcsEL_Everest18301937Adjustment, _T("Everest 1830 (1937 Adjustment)") },
	{ tcsEL_Everest18301967Definition, _T("Everest 1830 (1967 Definition)") },
	{ tcsEL_Everest18301975Definition, _T("Everest 1830 (1975 Definition)") },
	{ tcsEL_Everest1830Modified, _T("Everest 1830 Modified") },
	{ tcsEL_GRS1980, _T("GRS 1980") },
	{ tcsEL_Helmert1906, _T("Helmert 1906") },
	{ tcsEL_IndonesianNationalSpheroid, _T("Indonesian National Spheroid") },
	{ tcsEL_International1924, _T("International 1924") },
	{ tcsEL_Krassowsky1940, _T("Krassowsky 1940") },
	{ tcsEL_NWL9D, _T("NWL 9D") },
	{ tcsEL_NWL10D, _T("NWL 10D") },
	{ tcsEL_Plessis1817, _T("Plessis 1817") },
	{ tcsEL_Struve1860, _T("Struve 1860") },
	{ tcsEL_WarOffice, _T("War Office") },
	{ tcsEL_WGS84, _T("WGS 84") },
	{ tcsEL_GEM10C, _T("GEM 10C") },
	{ tcsEL_OSU86F, _T("OSU86F") },
	{ tcsEL_OSU91A, _T("OSU91A") },
	{ tcsEL_Clarke1880, _T("Clarke 1880") },
	{ tcsEL_Sphere, _T("Sphere") },
	{ tcsEL_GRS1967, _T("GRS 1967") },
	{ tcsEL_AverageTerrestrialSystem1977, _T("Average Terrestrial System 1977") },
	{ tcsEL_UserDefined, _T("User Defined") },
	{ tcsEL_Undefined, NULL }
};
CODENAME _CT_TRIASCSGEODETICDATUM[] = {
	{ tcsGD_NotSpecifiedBasedOnEllipsoid7001, _T("Not specified (based on ellipsoid 7001)") },
	{ tcsGD_NotSpecifiedBasedOnEllipsoid7002, _T("Not specified (based on ellipsoid 7002)") },
	{ tcsGD_NotSpecifiedBasedOnEllipsoid7003, _T("Not specified (based on ellipsoid 7003)") },
	{ tcsGD_NotSpecifiedBasedOnEllipsoid7004, _T("Not specified (based on ellipsoid 7004)") },
	{ tcsGD_NotSpecifiedBasedOnEllipsoid7005, _T("Not specified (based on ellipsoid 7005)") },
	{ tcsGD_NotSpecifiedBasedOnEllipsoid7006, _T("Not specified (based on ellipsoid 7006)") },
	{ tcsGD_NotSpecifiedBasedOnEllipsoid7007, _T("Not specified (based on ellipsoid 7007)") },
	{ tcsGD_NotSpecifiedBasedOnEllipsoid7008, _T("Not specified (based on ellipsoid 7008)") },
	{ tcsGD_NotSpecifiedBasedOnEllipsoid7009, _T("Not specified (based on ellipsoid 7009)") },
	{ tcsGD_NotSpecifiedBasedOnEllipsoid7010, _T("Not specified (based on ellipsoid 7010)") },
	{ tcsGD_NotSpecifiedBasedOnEllipsoid7011, _T("Not specified (based on ellipsoid 7011)") },
	{ tcsGD_NotSpecifiedBasedOnEllipsoid7012, _T("Not specified (based on ellipsoid 7012)") },
	{ tcsGD_NotSpecifiedBasedOnEllipsoid7013, _T("Not specified (based on ellipsoid 7013)") },
	{ tcsGD_NotSpecifiedBasedOnEllipsoid7014, _T("Not specified (based on ellipsoid 7014)") },
	{ tcsGD_NotSpecifiedBasedOnEllipsoid7015, _T("Not specified (based on ellipsoid 7015)") },
	{ tcsGD_NotSpecifiedBasedOnEllipsoid7016, _T("Not specified (based on ellipsoid 7016)") },
	{ tcsGD_NotSpecifiedBasedOnEllipsoid7017, _T("Not specified (based on ellipsoid 7017)") },
	{ tcsGD_NotSpecifiedBasedOnEllipsoid7018, _T("Not specified (based on ellipsoid 7018)") },
	{ tcsGD_NotSpecifiedBasedOnEllipsoid7019, _T("Not specified (based on ellipsoid 7019)") },
	{ tcsGD_NotSpecifiedBasedOnEllipsoid7020, _T("Not specified (based on ellipsoid 7020)") },
	{ tcsGD_NotSpecifiedBasedOnEllipsoid7021, _T("Not specified (based on ellipsoid 7021)") },
	{ tcsGD_NotSpecifiedBasedOnEllipsoid7022, _T("Not specified (based on ellipsoid 7022)") },
	{ tcsGD_NotSpecifiedBasedOnEllipsoid7024, _T("Not specified (based on ellipsoid 7024)") },
	{ tcsGD_NotSpecifiedBasedOnEllipsoid7025, _T("Not specified (based on ellipsoid 7025)") },
	{ tcsGD_NotSpecifiedBasedOnEllipsoid7026, _T("Not specified (based on ellipsoid 7026)") },
	{ tcsGD_NotSpecifiedBasedOnEllipsoid7027, _T("Not specified (based on ellipsoid 7027)") },
	{ tcsGD_NotSpecifiedBasedOnEllipsoid7028, _T("Not specified (based on ellipsoid 7028)") },
	{ tcsGD_NotSpecifiedBasedOnEllipsoid7029, _T("Not specified (based on ellipsoid 7029)") },
	{ tcsGD_NotSpecifiedBasedOnEllipsoid7030, _T("Not specified (based on ellipsoid 7030)") },
	{ tcsGD_NotSpecifiedBasedOnEllipsoid7031, _T("Not specified (based on ellipsoid 7031)") },
	{ tcsGD_NotSpecifiedBasedOnEllipsoid7032, _T("Not specified (based on ellipsoid 7032)") },
	{ tcsGD_NotSpecifiedBasedOnEllipsoid7033, _T("Not specified (based on ellipsoid 7033)") },
	{ tcsGD_NotSpecifiedBasedOnEllipsoid7034, _T("Not specified (based on ellipsoid 7034)") },
	{ tcsGD_NotSpecifiedBasedOnEllipsoid7035, _T("Not specified (based on ellipsoid 7035)") },
	{ tcsGD_NotSpecifiedBasedOnEllipsoid7036, _T("Not specified (based on ellipsoid 7036)") },
	{ tcsGD_Greek, _T("Greek") },
	{ tcsGD_GreekGeodeticReferenceSystem1987, _T("Greek Geodetic Reference System 1987") },
	{ tcsGD_AverageTerrestrialSystem1977, _T("Average Terrestrial System 1977") },
	{ tcsGD_Kartastokoordinaattijarjestelma, _T("Kartastokoordinaattijarjestelma") },
	{ tcsGD_RiketsKoordinatsystem1990, _T("Rikets koordinatsystem 1990") },
	{ tcsGD_Samboja, _T("Samboja") },
	{ tcsGD_Lithuania1994ETRS89, _T("Lithuania 1994 (ETRS89)") },
	{ tcsGD_Pulkovo1995, _T("Pulkovo 1995") },
	{ tcsGD_Adindan, _T("Adindan") },
	{ tcsGD_AustralianGeodeticDatum1966, _T("Australian Geodetic Datum 1966") },
	{ tcsGD_AustralianGeodeticDatum1984, _T("Australian Geodetic Datum 1984") },
	{ tcsGD_AinElAbd1970, _T("Ain el Abd 1970") },
	{ tcsGD_Afgooye, _T("Afgooye") },
	{ tcsGD_Agadez, _T("Agadez") },
	{ tcsGD_Lisbon, _T("Lisbon") },
	{ tcsGD_Aratu, _T("Aratu") },
	{ tcsGD_Arc1950, _T("Arc 1950") },
	{ tcsGD_Arc1960, _T("Arc 1960") },
	{ tcsGD_Batavia, _T("Batavia") },
	{ tcsGD_Barbados, _T("Barbados") },
	{ tcsGD_Beduaram, _T("Beduaram") },
	{ tcsGD_Beijing1954, _T("Beijing 1954") },
	{ tcsGD_ReseauNationalBelge1950, _T("Reseau National Belge 1950") },
	{ tcsGD_Bermuda1957, _T("Bermuda 1957") },
	{ tcsGD_Bern1898, _T("Bern 1898") },
	{ tcsGD_Bogota, _T("Bogota") },
	{ tcsGD_BukitRimpah, _T("Bukit Rimpah") },
	{ tcsGD_Camacupa, _T("Camacupa") },
	{ tcsGD_CampoInchauspe, _T("Campo Inchauspe") },
	{ tcsGD_Cape, _T("Cape") },
	{ tcsGD_Carthage, _T("Carthage") },
	{ tcsGD_Chua, _T("Chua") },
	{ tcsGD_CorregoAlegre, _T("Corrego Alegre") },
	{ tcsGD_CoteDIvoire, _T("Cote d'Ivoire") },
	{ tcsGD_DeirEzZor, _T("Deir ez Zor") },
	{ tcsGD_Douala, _T("Douala") },
	{ tcsGD_Egypt1907, _T("Egypt 1907") },
	{ tcsGD_EuropeanDatum1950, _T("European Datum 1950") },
	{ tcsGD_EuropeanDatum1987, _T("European Datum 1987") },
	{ tcsGD_Fahud, _T("Fahud") },
	{ tcsGD_Gandajika1970, _T("Gandajika 1970") },
	{ tcsGD_Garoua, _T("Garoua") },
	{ tcsGD_GuyaneFrancaise, _T("Guyane Francaise") },
	{ tcsGD_HuTzuShan, _T("Hu Tzu Shan") },
	{ tcsGD_HungarianDatum1972, _T("Hungarian Datum 1972") },
	{ tcsGD_IndonesianDatum1974, _T("Indonesian Datum 1974") },
	{ tcsGD_Indian1954, _T("Indian 1954") },
	{ tcsGD_Indian1975, _T("Indian 1975") },
	{ tcsGD_Jamaica1875, _T("Jamaica 1875") },
	{ tcsGD_Jamaica1969, _T("Jamaica 1969") },
	{ tcsGD_Kalianpur, _T("Kalianpur") },
	{ tcsGD_Kandawala, _T("Kandawala") },
	{ tcsGD_Kertau, _T("Kertau") },
	{ tcsGD_KuwaitOilCompany, _T("Kuwait Oil Company") },
	{ tcsGD_LaCanoa, _T("La Canoa") },
	{ tcsGD_ProvisionalSouthAmericanDatum1956, _T("Provisional South American Datum 1956") },
	{ tcsGD_Lake, _T("Lake") },
	{ tcsGD_Leigon, _T("Leigon") },
	{ tcsGD_Liberia1964, _T("Liberia 1964") },
	{ tcsGD_Lome, _T("Lome") },
	{ tcsGD_Luzon1911, _T("Luzon 1911") },
	{ tcsGD_HitoXVIII1963, _T("Hito XVIII 1963") },
	{ tcsGD_HeratNorth, _T("Herat North") },
	{ tcsGD_Mahe1971, _T("Mahe 1971") },
	{ tcsGD_Makassar, _T("Makassar") },
	{ tcsGD_EuropeanTerrestrialReferenceSystem89, _T("European Terrestrial Reference System 89") },
	{ tcsGD_Malongo1987, _T("Malongo 1987") },
	{ tcsGD_Manoca, _T("Manoca") },
	{ tcsGD_Merchich, _T("Merchich") },
	{ tcsGD_Massawa, _T("Massawa") },
	{ tcsGD_Minna, _T("Minna") },
	{ tcsGD_Mhast, _T("Mhast") },
	{ tcsGD_MonteMario, _T("Monte Mario") },
	{ tcsGD_MPoraloko, _T("M'poraloko") },
	{ tcsGD_NorthAmericanDatum1927, _T("North American Datum 1927") },
	{ tcsGD_NADMichigan, _T("NAD Michigan") },
	{ tcsGD_NorthAmericanDatum1983, _T("North American Datum 1983") },
	{ tcsGD_Nahrwan1967, _T("Nahrwan 1967") },
	{ tcsGD_Naparima1972, _T("Naparima 1972") },
	{ tcsGD_NewZealandGeodeticDatum1949, _T("New Zealand Geodetic Datum 1949") },
	{ tcsGD_NGO1948, _T("NGO 1948") },
	{ tcsGD_Datum73, _T("Datum 73") },
	{ tcsGD_NouvelleTriangulationFrancaise, _T("Nouvelle Triangulation Francaise") },
	{ tcsGD_NSWC9Z2, _T("NSWC 9Z-2") },
	{ tcsGD_OSGB1936, _T("OSGB 1936") },
	{ tcsGD_OSGB1970SN, _T("OSGB 1970 (SN)") },
	{ tcsGD_OSSN1980, _T("OS (SN) 1980") },
	{ tcsGD_Padang1884, _T("Padang 1884") },
	{ tcsGD_Palestine1923, _T("Palestine 1923") },
	{ tcsGD_PointeNoire, _T("Pointe Noire") },
	{ tcsGD_GeocentricDatumOfAustralia1994, _T("Geocentric Datum of Australia 1994") },
	{ tcsGD_Pulkovo1942, _T("Pulkovo 1942") },
	{ tcsGD_Qatar, _T("Qatar") },
	{ tcsGD_Qatar1948, _T("Qatar 1948") },
	{ tcsGD_Qornoq, _T("Qornoq") },
	{ tcsGD_LomaQuintana, _T("Loma Quintana") },
	{ tcsGD_Amersfoort, _T("Amersfoort") },
	{ tcsGD_SouthAmericanDatum1969, _T("South American Datum 1969") },
	{ tcsGD_SapperHill1943, _T("Sapper Hill 1943") },
	{ tcsGD_Schwarzeck, _T("Schwarzeck") },
	{ tcsGD_Segora, _T("Segora") },
	{ tcsGD_Serindung, _T("Serindung") },
	{ tcsGD_Sudan, _T("Sudan") },
	{ tcsGD_Tananarive1925, _T("Tananarive 1925") },
	{ tcsGD_Timbalai1948, _T("Timbalai 1948") },
	{ tcsGD_TM65, _T("TM65") },
	{ tcsGD_TM75, _T("TM75") },
	{ tcsGD_Tokyo, _T("Tokyo") },
	{ tcsGD_Trinidad1903, _T("Trinidad 1903") },
	{ tcsGD_TrucialCoast1948, _T("Trucial Coast 1948") },
	{ tcsGD_Voirol1875, _T("Voirol 1875") },
	{ tcsGD_VoirolUnifie1960, _T("Voirol Unifie 1960") },
	{ tcsGD_Bern1938, _T("Bern 1938") },
	{ tcsGD_NordSahara1959, _T("Nord Sahara 1959") },
	{ tcsGD_Stockholm1938, _T("Stockholm 1938") },
	{ tcsGD_Yacare, _T("Yacare") },
	{ tcsGD_Yoff, _T("Yoff") },
	{ tcsGD_Zanderij, _T("Zanderij") },
	{ tcsGD_MilitarGeographischeInstitut, _T("Militar-Geographische Institut") },
	{ tcsGD_ReseauNationalBelge1972, _T("Reseau National Belge 1972") },
	{ tcsGD_DeutscheHauptdreiecksnetz, _T("Deutsches Hauptdreiecksnetz") },
	{ tcsGD_Conakry1905, _T("Conakry 1905") },
	{ tcsGD_DealulPiscului1933, _T("Dealul Piscului 1933") },
	{ tcsGD_DealulPiscului1970, _T("Dealul Piscului 1970") },
	{ tcsGD_NationalGeodeticNetwork, _T("National Geodetic Network") },
	{ tcsGD_KuwaitUtility, _T("Kuwait Utility") },
	{ tcsGD_WorldGeodeticSystem1972, _T("World Geodetic System 1972") },
	{ tcsGD_WGS72TransitBroadcastEphemeris, _T("WGS 72 Transit Broadcast Ephemeris") },
	{ tcsGD_WorldGeodeticSystem1984, _T("World Geodetic System 1984") },
	{ tcsGD_AncienneTriangulationFrancaise, _T("Ancienne Triangulation Francaise") },
	{ tcsGD_NordDeGuerre, _T("Nord de Guerre") },
	{ tcsGD_DeutscheHauptdreiecksnetzAblN, _T("Deutsches Hauptdreiecksnetz, alte Bundesländer Nord (dreigeteilt)") },
	{ tcsGD_DeutscheHauptdreiecksnetzAblM, _T("Deutsches Hauptdreiecksnetz, alte Bundesländer Mitte (dreigeteilt)") },
	{ tcsGD_DeutscheHauptdreiecksnetzAblS, _T("Deutsches Hauptdreiecksnetz, alte Bundesländer Süd (dreigeteilt)") },
	{ tcsGD_DeutscheHauptdreiecksnetzRd83, _T("Deutsches Hauptdreiecksnetz, neue Bundesländer (außer Thüringen)") },
	{ tcsGD_DeutscheHauptdreiecksnetzPd83, _T("Deutsches Hauptdreiecksnetz, neue Bundesländer (Thüringen)") },
	{ tcsGD_DeutscheHauptdreiecksnetzRd83DHDN, _T("Deutsches Hauptdreiecksnetz RD83") },
	{ tcsGD_DeutscheHauptdreiecksnetzAblN2, _T("Deutsches Hauptdreiecksnetz, alte Bundesländer Nord (zweigeteilt)") },
	{ tcsGD_DeutscheHauptdreiecksnetzAblS2, _T("Deutsches Hauptdreiecksnetz, alte Bundesländer Süd (zweigeteilt)") },
	{ tcsGD_DeutscheHauptdreiecksnetzDHDN, _T("Deutsches Hauptdreiecksnetz, Alte Bundesländer (gesamt)") },
	{ tcsGD_DeutscheHauptdreiecksnetzBesD, _T("Deutsches Hauptdreiecksnetz, Überbreite Zone für Deutschland (GeoStar)") },
	{ tcsGD_UserDefined, _T("User Defined") },
	{ tcsGD_Undefined, NULL }
};
CODENAME _CT_TRIASCSUNITOFLENGTH[] = {
	{ tcsUOL_Metre, _T("meter") },
	{ tcsUOL_MilliMetre, _T("millimeter") },
	{ tcsUOL_KiloMetre, _T("kilometer") },
	{ tcsUOL_Foot, _T("foot") },
	{ tcsUOL_USSurveyFoot, _T("US survey foot") },
	{ tcsUOL_ModifiedAmericanFoot, _T("modified American foot") },
	{ tcsUOL_ClarkeSFoot, _T("Clarke's foot") },
	{ tcsUOL_IndianFootClarke, _T("Indian foot (Clarke)") },
	{ tcsUOL_Link, _T("link") },
	{ tcsUOL_LinkBenoit, _T("link (Benoit)") },
	{ tcsUOL_LinkSears, _T("link (Sears)") },
	{ tcsUOL_ChainBenoit, _T("chain (Benoit)") },
	{ tcsUOL_ChainSears, _T("chain (Sears)") },
	{ tcsUOL_YardSears, _T("yard (Sears)") },
	{ tcsUOL_IndianYard, _T("Indian yard") },
	{ tcsUOL_Fathom, _T("fathom") },
	{ tcsUOL_NauticalMile, _T("nautical mile") },
	{ tcsUOL_GermanLegalMetre, _T("German legal metre") },
	{ tcsUOL_FootSears, _T("foot (Sears)") },
	{ tcsUOL_USSurveyChain, _T("US survey chain") },
	{ tcsUOL_USSurveyLink, _T("US survey link") },
	{ tcsUOL_USSurveyMile, _T("US survey mile") },
	{ tcsUOL_Inch, _T("Inch") },
	{ tcsUOL_CentiMetre, _T("centimeter") },
	{ tcsUOL_Undefined, NULL }
};
CODENAME _CT_TRIASCSPRIMEMERIDIAN[] = {
	{ tcsPM_Greenwich, _T("Greenwich") },
	{ tcsPM_Lisbon, _T("Lisbon") },
	{ tcsPM_Paris, _T("Paris") },
	{ tcsPM_Bogota, _T("Bogota") },
	{ tcsPM_Madrid, _T("Madrid") },
	{ tcsPM_Rome, _T("Rome") },
	{ tcsPM_Bern, _T("Bern") },
	{ tcsPM_Jakarta, _T("Jakarta") },
	{ tcsPM_Ferro, _T("Ferro") },
	{ tcsPM_Brussels, _T("Brussels") },
	{ tcsPM_Stockholm, _T("Stockholm") },
	{ tcsPM_Athens, _T("Athens") },
	{ tcsPM_Undefined, NULL }
};
CODENAME _CT_TRIASCSPROJECTIONALGORITHM[] = {
	{ tcsPA_LambertConicConformal1SP, _T("Lambert Conic Conformal (1SP)") },
	{ tcsPA_LambertConicConformal2SP, _T("Lambert Conic Conformal (2SP)") },
	{ tcsPA_LambertConicConformal2SPBelgium, _T("Lambert Conic Conformal (2SP Belgium)") },
	{ tcsPA_Mercator1SP, _T("Mercator (1SP)") },
	{ tcsPA_Mercator2SP, _T("Mercator (2SP)") },
	{ tcsPA_CassiniSoldner, _T("Cassini-Soldner") },
	{ tcsPA_TransverseMercator, _T("Transverse Mercator") },
	{ tcsPA_TransverseMercatorSouthOrientated, _T("Transverse Mercator (South Orientated)") },
	{ tcsPA_ObliqueStereographic, _T("Oblique Stereographic") },
	{ tcsPA_PolarStereographic, _T("Polar Stereographic") },
	{ tcsPA_NewZealandMapGrid, _T("New Zealand Map Grid") },
	{ tcsPA_HotineObliqueMercator, _T("Hotine Oblique Mercator") },
	{ tcsPA_LabordeObliqueMercator, _T("Laborde Oblique Mercator") },
	{ tcsPA_SwissObliqueCylindrical, _T("Swiss Oblique Cylindrical") },
	{ tcsPA_ObliqueMercator, _T("Oblique Mercator") },
	{ tcsPA_AffineTransformation, _T("Affine Transformation") },
	{ tcsPA_GaussKrueger, _T("Gauss Krüger") },
	{ tcsPA_CylindricEquirectangular, _T("Cylindric Equirectangular") },
	{ tcsPA_Undefined, NULL }
};
CODEPARAM _PT_ELLIPSFROMGD[] = {
	{ tcsGD_Adindan, tcsEL_Clarke1880RGS },
	{ tcsGD_Afgooye, tcsEL_Krassowsky1940 },
	{ tcsGD_Agadez, tcsEL_Clarke1880IGN },
	{ tcsGD_AinElAbd1970, tcsEL_International1924 },
	{ tcsGD_Amersfoort, tcsEL_Bessel1841 },
	{ tcsGD_AncienneTriangulationFrancaise, tcsEL_Plessis1817 },
	{ tcsGD_Aratu, tcsEL_International1924 },
	{ tcsGD_Arc1950, tcsEL_Clarke1880Arc },
	{ tcsGD_Arc1960, tcsEL_Clarke1880RGS },
	{ tcsGD_AustralianGeodeticDatum1966, tcsEL_AustralianNationalSpheroid },
	{ tcsGD_AustralianGeodeticDatum1984, tcsEL_AustralianNationalSpheroid },
	{ tcsGD_AverageTerrestrialSystem1977, tcsEL_AverageTerrestrialSystem1977 },
	{ tcsGD_Barbados, tcsEL_Clarke1880RGS },
	{ tcsGD_Batavia, tcsEL_Bessel1841 },
	{ tcsGD_Beduaram, tcsEL_Clarke1880IGN },
	{ tcsGD_Beijing1954, tcsEL_Krassowsky1940 },
	{ tcsGD_Bermuda1957, tcsEL_Clarke1866 },
	{ tcsGD_Bern1898, tcsEL_Bessel1841 },
	{ tcsGD_Bern1938, tcsEL_Bessel1841 },
	{ tcsGD_Bogota, tcsEL_International1924 },
	{ tcsGD_BukitRimpah, tcsEL_Bessel1841 },
	{ tcsGD_Camacupa, tcsEL_Clarke1880RGS },
	{ tcsGD_CampoInchauspe, tcsEL_International1924 },
	{ tcsGD_Cape, tcsEL_Clarke1880Arc },
	{ tcsGD_Carthage, tcsEL_Clarke1880IGN },
	{ tcsGD_Chua, tcsEL_International1924 },
	{ tcsGD_Conakry1905, tcsEL_Clarke1880IGN },
	{ tcsGD_CorregoAlegre, tcsEL_International1924 },
	{ tcsGD_CoteDIvoire, tcsEL_Clarke1880IGN },
	{ tcsGD_Datum73, tcsEL_International1924 },
	{ tcsGD_DealulPiscului1933, tcsEL_International1924 },
	{ tcsGD_DealulPiscului1970, tcsEL_Krassowsky1940 },
	{ tcsGD_DeirEzZor, tcsEL_Clarke1880IGN },
	{ tcsGD_DeutscheHauptdreiecksnetz, tcsEL_Bessel1841 },
	{ tcsGD_DeutscheHauptdreiecksnetzAblN, tcsEL_Bessel1841 },
	{ tcsGD_DeutscheHauptdreiecksnetzAblM, tcsEL_Bessel1841 },
	{ tcsGD_DeutscheHauptdreiecksnetzAblS, tcsEL_Bessel1841 },
	{ tcsGD_DeutscheHauptdreiecksnetzRd83, tcsEL_Bessel1841 },
	{ tcsGD_DeutscheHauptdreiecksnetzPd83, tcsEL_Bessel1841 },
	{ tcsGD_DeutscheHauptdreiecksnetzRd83DHDN, tcsEL_Bessel1841 },
	{ tcsGD_DeutscheHauptdreiecksnetzDHDN, tcsEL_Bessel1841 },
	{ tcsGD_DeutscheHauptdreiecksnetzAblN2, tcsEL_Bessel1841 },
	{ tcsGD_DeutscheHauptdreiecksnetzAblS2, tcsEL_Bessel1841 },
	{ tcsGD_DeutscheHauptdreiecksnetzBesD, tcsEL_Bessel1841 },
	{ tcsGD_Douala, tcsEL_Clarke1880IGN },
	{ tcsGD_Egypt1907, tcsEL_Helmert1906 },
	{ tcsGD_EuropeanDatum1950, tcsEL_International1924 },
	{ tcsGD_EuropeanDatum1987, tcsEL_International1924 },
	{ tcsGD_EuropeanTerrestrialReferenceSystem89, tcsEL_GRS1980 },
	{ tcsGD_Fahud, tcsEL_Clarke1880RGS },
	{ tcsGD_Gandajika1970, tcsEL_International1924 },
	{ tcsGD_Garoua, tcsEL_Clarke1880IGN },
	{ tcsGD_GeocentricDatumOfAustralia1994, tcsEL_GRS1980 },
	{ tcsGD_Greek, tcsEL_Bessel1841 },
	{ tcsGD_GreekGeodeticReferenceSystem1987, tcsEL_GRS1980 },
	{ tcsGD_GuyaneFrancaise, tcsEL_International1924 },
	{ tcsGD_HeratNorth, tcsEL_International1924 },
	{ tcsGD_HitoXVIII1963, tcsEL_International1924 },
	{ tcsGD_HuTzuShan, tcsEL_International1924 },
	{ tcsGD_HungarianDatum1972, tcsEL_GRS1967 },
	{ tcsGD_Indian1954, tcsEL_Everest18301937Adjustment },
	{ tcsGD_Indian1975, tcsEL_Everest18301937Adjustment },
	{ tcsGD_IndonesianDatum1974, tcsEL_IndonesianNationalSpheroid },
	{ tcsGD_Jamaica1875, tcsEL_Clarke1880 },
	{ tcsGD_Jamaica1969, tcsEL_Clarke1866 },
	{ tcsGD_Kalianpur, tcsEL_Everest18301975Definition },
	{ tcsGD_Kandawala, tcsEL_Everest18301937Adjustment },
	{ tcsGD_Kartastokoordinaattijarjestelma, tcsEL_International1924 },
	{ tcsGD_Kertau, tcsEL_Everest1830Modified },
	{ tcsGD_KuwaitOilCompany, tcsEL_Clarke1880RGS },
	{ tcsGD_KuwaitUtility, tcsEL_GRS1980 },
	{ tcsGD_LaCanoa, tcsEL_International1924 },
	{ tcsGD_Lake, tcsEL_International1924 },
	{ tcsGD_Leigon, tcsEL_Clarke1880RGS },
	{ tcsGD_Liberia1964, tcsEL_Clarke1880RGS },
	{ tcsGD_Lisbon, tcsEL_International1924 },
	{ tcsGD_Lithuania1994ETRS89, tcsEL_GRS1980 },
	{ tcsGD_LomaQuintana, tcsEL_International1924 },
	{ tcsGD_Lome, tcsEL_Clarke1880IGN },
	{ tcsGD_Luzon1911, tcsEL_Clarke1866 },
	{ tcsGD_MPoraloko, tcsEL_Clarke1880IGN },
	{ tcsGD_Mahe1971, tcsEL_Clarke1880RGS },
	{ tcsGD_Makassar, tcsEL_Bessel1841 },
	{ tcsGD_Malongo1987, tcsEL_International1924 },
	{ tcsGD_Manoca, tcsEL_Clarke1880RGS },
	{ tcsGD_Massawa, tcsEL_Bessel1841 },
	{ tcsGD_Merchich, tcsEL_Clarke1880IGN },
	{ tcsGD_Mhast, tcsEL_International1924 },
	{ tcsGD_MilitarGeographischeInstitut, tcsEL_Bessel1841 },
	{ tcsGD_Minna, tcsEL_Clarke1880RGS },
	{ tcsGD_MonteMario, tcsEL_International1924 },
	{ tcsGD_NADMichigan, tcsEL_Clarke1866Michigan },
	{ tcsGD_Nahrwan1967, tcsEL_Clarke1880RGS },
	{ tcsGD_Naparima1972, tcsEL_International1924 },
	{ tcsGD_NationalGeodeticNetwork, tcsEL_WGS84 },
	{ tcsGD_NewZealandGeodeticDatum1949, tcsEL_International1924 },
	{ tcsGD_NGO1948, tcsEL_BesselModified },
	{ tcsGD_NordDeGuerre, tcsEL_Plessis1817 },
	{ tcsGD_NordSahara1959, tcsEL_Clarke1880IGN },
	{ tcsGD_NorthAmericanDatum1927, tcsEL_Clarke1866 },
	{ tcsGD_NorthAmericanDatum1983, tcsEL_GRS1980 },
	{ tcsGD_NotSpecifiedBasedOnEllipsoid7001, tcsEL_Airy1830 },
	{ tcsGD_NotSpecifiedBasedOnEllipsoid7002, tcsEL_AiryModified1849 },
	{ tcsGD_NotSpecifiedBasedOnEllipsoid7003, tcsEL_AustralianNationalSpheroid },
	{ tcsGD_NotSpecifiedBasedOnEllipsoid7004, tcsEL_Bessel1841 },
	{ tcsGD_NotSpecifiedBasedOnEllipsoid7005, tcsEL_BesselModified },
	{ tcsGD_NotSpecifiedBasedOnEllipsoid7006, tcsEL_BesselNamibia },
	{ tcsGD_NotSpecifiedBasedOnEllipsoid7007, tcsEL_Clarke1858 },
	{ tcsGD_NotSpecifiedBasedOnEllipsoid7008, tcsEL_Clarke1866 },
	{ tcsGD_NotSpecifiedBasedOnEllipsoid7009, tcsEL_Clarke1866Michigan },
	{ tcsGD_NotSpecifiedBasedOnEllipsoid7010, tcsEL_Clarke1880Benoit },
	{ tcsGD_NotSpecifiedBasedOnEllipsoid7011, tcsEL_Clarke1880IGN },
	{ tcsGD_NotSpecifiedBasedOnEllipsoid7012, tcsEL_Clarke1880RGS },
	{ tcsGD_NotSpecifiedBasedOnEllipsoid7013, tcsEL_Clarke1880Arc },
	{ tcsGD_NotSpecifiedBasedOnEllipsoid7014, tcsEL_Clarke1880SGA1922 },
	{ tcsGD_NotSpecifiedBasedOnEllipsoid7015, tcsEL_Everest18301937Adjustment },
	{ tcsGD_NotSpecifiedBasedOnEllipsoid7016, tcsEL_Everest18301967Definition },
	{ tcsGD_NotSpecifiedBasedOnEllipsoid7017, tcsEL_Everest18301975Definition },
	{ tcsGD_NotSpecifiedBasedOnEllipsoid7018, tcsEL_Everest1830Modified },
	{ tcsGD_NotSpecifiedBasedOnEllipsoid7019, tcsEL_GRS1980 },
	{ tcsGD_NotSpecifiedBasedOnEllipsoid7020, tcsEL_Helmert1906 },
	{ tcsGD_NotSpecifiedBasedOnEllipsoid7021, tcsEL_IndonesianNationalSpheroid },
	{ tcsGD_NotSpecifiedBasedOnEllipsoid7022, tcsEL_International1924 },
	{ tcsGD_NotSpecifiedBasedOnEllipsoid7024, tcsEL_Krassowsky1940 },
	{ tcsGD_NotSpecifiedBasedOnEllipsoid7025, tcsEL_NWL9D },
	{ tcsGD_NotSpecifiedBasedOnEllipsoid7026, tcsEL_NWL10D },
	{ tcsGD_NotSpecifiedBasedOnEllipsoid7027, tcsEL_Plessis1817 },
	{ tcsGD_NotSpecifiedBasedOnEllipsoid7028, tcsEL_Struve1860 },
	{ tcsGD_NotSpecifiedBasedOnEllipsoid7029, tcsEL_WarOffice },
	{ tcsGD_NotSpecifiedBasedOnEllipsoid7030, tcsEL_WGS84 },
	{ tcsGD_NotSpecifiedBasedOnEllipsoid7031, tcsEL_GEM10C },
	{ tcsGD_NotSpecifiedBasedOnEllipsoid7032, tcsEL_OSU86F },
	{ tcsGD_NotSpecifiedBasedOnEllipsoid7033, tcsEL_OSU91A },
	{ tcsGD_NotSpecifiedBasedOnEllipsoid7034, tcsEL_Clarke1880 },
	{ tcsGD_NotSpecifiedBasedOnEllipsoid7035, tcsEL_Sphere },
	{ tcsGD_NotSpecifiedBasedOnEllipsoid7036, tcsEL_GRS1967 },
	{ tcsGD_NouvelleTriangulationFrancaise, tcsEL_Clarke1880IGN },
	{ tcsGD_NSWC9Z2, tcsEL_NWL9D },
	{ tcsGD_OSSN1980, tcsEL_Airy1830 },
	{ tcsGD_OSGB1936, tcsEL_Airy1830 },
	{ tcsGD_OSGB1970SN, tcsEL_Airy1830 },
	{ tcsGD_Padang1884, tcsEL_Bessel1841 },
	{ tcsGD_Palestine1923, tcsEL_Clarke1880Benoit },
	{ tcsGD_PointeNoire, tcsEL_Clarke1880IGN },
	{ tcsGD_ProvisionalSouthAmericanDatum1956, tcsEL_International1924 },
	{ tcsGD_Pulkovo1942, tcsEL_Krassowsky1940 },
	{ tcsGD_Pulkovo1995, tcsEL_Krassowsky1940 },
	{ tcsGD_Qatar, tcsEL_International1924 },
	{ tcsGD_Qatar1948, tcsEL_Helmert1906 },
	{ tcsGD_Qornoq, tcsEL_International1924 },
	{ tcsGD_ReseauNationalBelge1950, tcsEL_International1924 },
	{ tcsGD_ReseauNationalBelge1972, tcsEL_International1924 },
	{ tcsGD_RiketsKoordinatsystem1990, tcsEL_Bessel1841 },
	{ tcsGD_Samboja, tcsEL_Bessel1841 },
	{ tcsGD_SapperHill1943, tcsEL_International1924 },
	{ tcsGD_Schwarzeck, tcsEL_BesselNamibia },
	{ tcsGD_Segora, tcsEL_Bessel1841 },
	{ tcsGD_Serindung, tcsEL_Bessel1841 },
	{ tcsGD_SouthAmericanDatum1969, tcsEL_GRS1967 },
	{ tcsGD_Stockholm1938, tcsEL_Bessel1841 },
	{ tcsGD_Sudan, tcsEL_Clarke1880IGN },
	{ tcsGD_Tananarive1925, tcsEL_International1924 },
	{ tcsGD_Timbalai1948, tcsEL_Everest18301967Definition },
	{ tcsGD_TM65, tcsEL_AiryModified1849 },
	{ tcsGD_TM75, tcsEL_AiryModified1849 },
	{ tcsGD_Tokyo, tcsEL_Bessel1841 },
	{ tcsGD_Trinidad1903, tcsEL_Clarke1858 },
	{ tcsGD_TrucialCoast1948, tcsEL_Helmert1906 },
	{ tcsGD_Voirol1875, tcsEL_Clarke1880IGN },
	{ tcsGD_VoirolUnifie1960, tcsEL_Clarke1880IGN },
	{ tcsGD_WGS72TransitBroadcastEphemeris, tcsEL_NWL10D },
	{ tcsGD_WorldGeodeticSystem1972, tcsEL_NWL10D },
	{ tcsGD_WorldGeodeticSystem1984, tcsEL_WGS84 },
	{ tcsGD_Yacare, tcsEL_International1924 },
	{ tcsGD_Yoff, tcsEL_Clarke1880IGN },
	{ tcsGD_Zanderij, tcsEL_International1924 },
	{ tcsGD_Undefined, tcsEL_Undefined }
};
CODEPARAMSET _PT_ELLIPSPARAM[] = {
	tcsEL_Airy1830, { 6377563.396, 6356256.90923729, 0.00334085064149708 },
	tcsEL_AiryModified1849, { 6377340.189, 6356034.44793853, 0.00334085064149708 },
	tcsEL_AustralianNationalSpheroid, { 6378160.0, 6356774.71919531, 0.00335289186923722 },
	tcsEL_Bessel1841, { 6377397.155, 6356078.96281819, 0.00334277318217481 },
	tcsEL_BesselModified, { 6377492.018, 6356173.5087127, 0.00334277318217481 },
	tcsEL_BesselNamibia, { 6377483.865, 6356165.38296633, 0.00334277318217481 },
	tcsEL_Clarke1858, { 20926348.0, 20855233.0, 0.00339834738483753 },
	tcsEL_Clarke1866, { 6378206.4, 6356583.8, 0.00339007530392879 },
	tcsEL_Clarke1866Michigan, { 20926631.53, 20855688.67, 0.00339007545950705 },
	tcsEL_Clarke1880, { 20926202.0, 20854895.0, 0.00340754619495693 },
	tcsEL_Clarke1880Arc, { 6378249.145, 6356514.96639875, 0.00340754619444173 },
	tcsEL_Clarke1880Benoit, { 6378300.79, 6356566.43, 0.00340754704357559 },
	tcsEL_Clarke1880IGN, { 6378249.2, 6356515.00000047, 0.00340754951994165 },
	tcsEL_Clarke1880RGS, { 6378249.145, 6356514.86954978, 0.00340756137869933 },
	tcsEL_Clarke1880SGA1922, { 6378249.2, 6356514.99694178, 0.00340754999949228 },
	tcsEL_Everest18301937Adjustment, { 6377276.345, 6356075.41314024, 0.00332444929666288 },
	tcsEL_Everest18301967Definition, { 6377298.556, 6356097.5503009, 0.00332444929666288 },
	tcsEL_Everest18301975Definition, { 6377301.243, 6356100.231, 0.00332444888396502 },
	tcsEL_Everest1830Modified, { 6377304.063, 6356103.03899315, 0.00332444929666288 },
	tcsEL_GEM10C, { 6378137.0, 6356752.31424783, 0.00335281066433155 },
	tcsEL_GRS1967, { 6378160.0, 6356774.51608878, 0.00335292371329995 },
	tcsEL_GRS1980, { 6378137.0, 6356752.31407576, 0.00335281069131077 },
	tcsEL_Helmert1906, { 6378200.0, 6356818.16962789, 0.00335232986925914 },
	tcsEL_IndonesianNationalSpheroid, { 6378160.0, 6356774.50408554, 0.00335292559522812 },
	tcsEL_International1924, { 6378388.0, 6356911.94612795, 0.00336700336700337 },
	tcsEL_Krassowsky1940, { 6378245.0, 6356863.01877305, 0.00335232986925914 },
	tcsEL_NWL10D, { 6378135.0, 6356750.52001609, 0.00335277945416751 },
	tcsEL_NWL9D, { 6378145.0, 6356759.76948868, 0.00335289186923722 },
	tcsEL_OSU86F, { 6378136.2, 6356751.51693008, 0.00335281066433155 },
	tcsEL_OSU91A, { 6378136.3, 6356751.6165948, 0.00335281066433155 },
	tcsEL_Plessis1817, { 6376523.0, 6355862.93325557, 0.00324002073613271 },
	tcsEL_Sphere, { 6371000.0, 6371000.0, 0 },
	tcsEL_Struve1860, { 6378297.0, 6356655.84708038, 0.00339293590744071 },
	tcsEL_WarOffice, { 6378300.583, 6356752.27021959, 0.00337837837837838 },
	tcsEL_WGS84, { 6378137.0, 6356752.31424783, 0.00335281066433155 },
	tcsEL_AverageTerrestrialSystem1977, { 6378135.0, 6356750.30492159, 0.00335281317789691 },
	tcsEL_Undefined, {0}
};
PA_ATTRIBUTESET _PA_ATTRIBUTES[] = {
{tcsPA_CassiniSoldner, tcsPP_CassiniSoldner_LatitudeOfNaturalOrigin, _T("Latitude of natural origin")},
{tcsPA_CassiniSoldner, tcsPP_CassiniSoldner_LongitudeOfNaturalOrigin, _T("Longitude of natural origin")},
{tcsPA_CassiniSoldner, tcsPP_CassiniSoldner_FalseEasting, _T("False easting")},
{tcsPA_CassiniSoldner, tcsPP_CassiniSoldner_FalseNorthing, _T("False northing")},
{tcsPA_HotineObliqueMercator, tcsPP_HotineObliqueMercator_LatitudeOfProjectionCentre, _T("Latitude of projection centre")},
{tcsPA_HotineObliqueMercator, tcsPP_HotineObliqueMercator_LongitudeOfProjectionCentre, _T("Longitude of projection centre")},
{tcsPA_HotineObliqueMercator, tcsPP_HotineObliqueMercator_AzimuthOfInitialLine, _T("Azimuth of initial line")},
{tcsPA_HotineObliqueMercator, tcsPP_HotineObliqueMercator_AngleFromRectifiedToSkewGrid, _T("Angle from Rectified to Skew Grid")},
{tcsPA_HotineObliqueMercator, tcsPP_HotineObliqueMercator_ScaleFactorOnInitialLine, _T("Scale factor on initial line")},
{tcsPA_HotineObliqueMercator, tcsPP_HotineObliqueMercator_FalseEasting, _T("False easting")},
{tcsPA_HotineObliqueMercator, tcsPP_HotineObliqueMercator_FalseNorthing, _T("False northing")},
{tcsPA_LabordeObliqueMercator, tcsPP_LabordeObliqueMercator_LatitudeOfProjectionCentre, _T("Latitude of projection centre")},
{tcsPA_LabordeObliqueMercator, tcsPP_LabordeObliqueMercator_LongitudeOfProjectionCentre, _T("Longitude of projection centre")},
{tcsPA_LabordeObliqueMercator, tcsPP_LabordeObliqueMercator_AzimuthOfInitialLine, _T("Azimuth of initial line")},
{tcsPA_LabordeObliqueMercator, tcsPP_LabordeObliqueMercator_ScaleFactorOnInitialLine, _T("Scale factor on initial line")},
{tcsPA_LabordeObliqueMercator, tcsPP_LabordeObliqueMercator_FalseEasting, _T("False easting")},
{tcsPA_LabordeObliqueMercator, tcsPP_LabordeObliqueMercator_FalseNorthing, _T("False northing")},
{tcsPA_LambertConicConformal1SP, tcsPP_LambertConicConformal1SP_LatitudeOfNaturalOrigin, _T("Latitude of natural origin")},
{tcsPA_LambertConicConformal1SP, tcsPP_LambertConicConformal1SP_LongitudeOfNaturalOrigin, _T("Longitude of natural origin")},
{tcsPA_LambertConicConformal1SP, tcsPP_LambertConicConformal1SP_ScaleFactorAtNaturalOrigin, _T("Scale factor at natural origin")},
{tcsPA_LambertConicConformal1SP, tcsPP_LambertConicConformal1SP_FalseEasting, _T("False easting")},
{tcsPA_LambertConicConformal1SP, tcsPP_LambertConicConformal1SP_FalseNorthing, _T("False northing")},
{tcsPA_LambertConicConformal2SP, tcsPP_LambertConicConformal2SP_LatitudeOfFirstStandardParallel, _T("Latitude of first standard parallel")},
{tcsPA_LambertConicConformal2SP, tcsPP_LambertConicConformal2SP_LatitudeOfSecondStandardParallel, _T("Latitude of second standard parallel")},
{tcsPA_LambertConicConformal2SP, tcsPP_LambertConicConformal2SP_LatitudeOfFalseOrigin, _T("Latitude of false origin")},
{tcsPA_LambertConicConformal2SP, tcsPP_LambertConicConformal2SP_LongitudeOfFalseOrigin, _T("Longitude of false origin")},
{tcsPA_LambertConicConformal2SP, tcsPP_LambertConicConformal2SP_EastingAtFalseOrigin, _T("Easting at false origin")},
{tcsPA_LambertConicConformal2SP, tcsPP_LambertConicConformal2SP_NorthingAtFalseOrigin, _T("Northing at false origin")},
{tcsPA_LambertConicConformal2SPBelgium, tcsPP_LambertConicConformal2SPBelgium_LatitudeOfFirstStandardParallel, _T("Latitude of first standard parallel")},
{tcsPA_LambertConicConformal2SPBelgium, tcsPP_LambertConicConformal2SPBelgium_LatitudeOfSecondStandardParallel, _T("Latitude of second standard parallel")},
{tcsPA_LambertConicConformal2SPBelgium, tcsPP_LambertConicConformal2SPBelgium_LatitudeOfFalseOrigin, _T("Latitude of false origin")},
{tcsPA_LambertConicConformal2SPBelgium, tcsPP_LambertConicConformal2SPBelgium_LongitudeOfFalseOrigin, _T("Longitude of false origin")},
{tcsPA_LambertConicConformal2SPBelgium, tcsPP_LambertConicConformal2SPBelgium_EastingAtFalseOrigin, _T("Easting at false origin")},
{tcsPA_LambertConicConformal2SPBelgium, tcsPP_LambertConicConformal2SPBelgium_NorthingAtFalseOrigin, _T("Northing at false origin")},
{tcsPA_Mercator1SP, tcsPP_Mercator1SP_LatitudeOfNaturalOrigin, _T("Latitude of natural origin")},
{tcsPA_Mercator1SP, tcsPP_Mercator1SP_LongitudeOfNaturalOrigin, _T("Longitude of natural origin")},
{tcsPA_Mercator1SP, tcsPP_Mercator1SP_ScaleFactorAtNaturalOrigin, _T("Scale factor at natural origin")},
{tcsPA_Mercator1SP, tcsPP_Mercator1SP_FalseEasting, _T("False easting")},
{tcsPA_Mercator1SP, tcsPP_Mercator1SP_FalseNorthing, _T("False northing")},
{tcsPA_Mercator2SP, tcsPP_Mercator2SP_LatitudeOfFirstStandardParallel, _T("Latitude of first standard parallel")},
{tcsPA_Mercator2SP, tcsPP_Mercator2SP_LongitudeOfNaturalOrigin, _T("Longitude of natural origin")},
{tcsPA_Mercator2SP, tcsPP_Mercator2SP_FalseEasting, _T("False easting")},
{tcsPA_Mercator2SP, tcsPP_Mercator2SP_FalseNorthing, _T("False northing")},
{tcsPA_NewZealandMapGrid, tcsPP_NewZealandMapGrid_LatitudeOfNaturalOrigin, _T("Latitude of natural origin")},
{tcsPA_NewZealandMapGrid, tcsPP_NewZealandMapGrid_LongitudeOfNaturalOrigin, _T("Longitude of natural origin")},
{tcsPA_NewZealandMapGrid, tcsPP_NewZealandMapGrid_FalseEasting, _T("False easting")},
{tcsPA_NewZealandMapGrid, tcsPP_NewZealandMapGrid_FalseNorthing, _T("False northing")},
{tcsPA_ObliqueStereographic, tcsPP_ObliqueStereographic_LatitudeOfNaturalOrigin, _T("Latitude of natural origin")},
{tcsPA_ObliqueStereographic, tcsPP_ObliqueStereographic_LongitudeOfNaturalOrigin, _T("Longitude of natural origin")},
{tcsPA_ObliqueStereographic, tcsPP_ObliqueStereographic_ScaleFactorAtNaturalOrigin, _T("Scale factor at natural origin")},
{tcsPA_ObliqueStereographic, tcsPP_ObliqueStereographic_FalseEasting, _T("False easting")},
{tcsPA_ObliqueStereographic, tcsPP_ObliqueStereographic_FalseNorthing, _T("False northing")},
{tcsPA_PolarStereographic, tcsPP_PolarStereographic_LatitudeOfNaturalOrigin, _T("Latitude of natural origin")},
{tcsPA_PolarStereographic, tcsPP_PolarStereographic_LongitudeOfNaturalOrigin, _T("Longitude of natural origin")},
{tcsPA_PolarStereographic, tcsPP_PolarStereographic_ScaleFactorAtNaturalOrigin, _T("Scale factor at natural origin")},
{tcsPA_PolarStereographic, tcsPP_PolarStereographic_FalseEasting, _T("False easting")},
{tcsPA_PolarStereographic, tcsPP_PolarStereographic_FalseNorthing, _T("False northing")},
{tcsPA_SwissObliqueCylindrical, tcsPP_SwissObliqueCylindrical_LatitudeOfProjectionCentre, _T("Latitude of projection centre")},
{tcsPA_SwissObliqueCylindrical, tcsPP_SwissObliqueCylindrical_LongitudeOfProjectionCentre, _T("Longitude of projection centre")},
{tcsPA_SwissObliqueCylindrical, tcsPP_SwissObliqueCylindrical_EastingAtProjectionCentre, _T("Easting at projection centre")},
{tcsPA_SwissObliqueCylindrical, tcsPP_SwissObliqueCylindrical_NorthingAtProjectionCentre, _T("Northing at projection centre")},
{tcsPA_TransverseMercator, tcsPP_TransverseMercator_LatitudeOfNaturalOrigin, _T("Latitude of natural origin")},
{tcsPA_TransverseMercator, tcsPP_TransverseMercator_LongitudeOfNaturalOrigin, _T("Longitude of natural origin")},
{tcsPA_TransverseMercator, tcsPP_TransverseMercator_ScaleFactorAtNaturalOrigin, _T("Scale factor at natural origin")},
{tcsPA_TransverseMercator, tcsPP_TransverseMercator_FalseEasting, _T("False easting")},
{tcsPA_TransverseMercator, tcsPP_TransverseMercator_FalseNorthing, _T("False northing")},
{tcsPA_TransverseMercatorSouthOrientated, tcsPP_TransverseMercatorSouthOrientated_LatitudeOfNaturalOrigin, _T("Latitude of natural origin")},
{tcsPA_TransverseMercatorSouthOrientated, tcsPP_TransverseMercatorSouthOrientated_LongitudeOfNaturalOrigin, _T("Longitude of natural origin")},
{tcsPA_TransverseMercatorSouthOrientated, tcsPP_TransverseMercatorSouthOrientated_ScaleFactorAtNaturalOrigin, _T("Scale factor at natural origin")},
{tcsPA_TransverseMercatorSouthOrientated, tcsPP_TransverseMercatorSouthOrientated_FalseEasting, _T("False easting")},
{tcsPA_TransverseMercatorSouthOrientated, tcsPP_TransverseMercatorSouthOrientated_FalseNorthing, _T("False northing")},
{tcsPA_ObliqueMercator, tcsPP_ObliqueMercator_LatitudeOfProjectionCentre, _T("Latitude of projection centre")},
{tcsPA_ObliqueMercator, tcsPP_ObliqueMercator_LongitudeOfProjectionCentre, _T("Longitude of projection centre")},
{tcsPA_ObliqueMercator, tcsPP_ObliqueMercator_AzimuthOfInitialLine, _T("Azimuth of initial line")},
{tcsPA_ObliqueMercator, tcsPP_ObliqueMercator_AngleFromRectifiedToSkewGrid, _T("Angle from Rectified to Skew Grid")},
{tcsPA_ObliqueMercator, tcsPP_ObliqueMercator_ScaleFactorOnInitialLine, _T("Scale factor on initial line")},
{tcsPA_ObliqueMercator, tcsPP_ObliqueMercator_EastingAtProjectionCentre, _T("Easting at projection centre")},
{tcsPA_ObliqueMercator, tcsPP_ObliqueMercator_NorthingAtProjectionCentre, _T("Northing at projection centre")},
{tcsPA_AffineTransformation, tcsPP_AffineTransformation_OffsetX, _T("Offset X")},
{tcsPA_AffineTransformation, tcsPP_AffineTransformation_OffsetY, _T("Offset Y")},
{tcsPA_AffineTransformation, tcsPP_AffineTransformation_RotatePhi, _T("Rotation Phi")},
{tcsPA_AffineTransformation, tcsPP_AffineTransformation_ScaleX, _T("Skalierung X")},
{tcsPA_AffineTransformation, tcsPP_AffineTransformation_ScaleY, _T("Skalierung Y")},
{tcsPA_GaussKrueger, tcsPP_GaussKrueger_FalseEasting, _T("False easting")},
{tcsPA_GaussKrueger, tcsPP_GaussKrueger_FalseNorthing, _T("False northing")},
{tcsPA_GaussKrueger, tcsPP_GaussKrueger_LatitudeOfNaturalOrigin, _T("Latitude of natural origin")},
{tcsPA_GaussKrueger, tcsPP_GaussKrueger_LongitudeOfNaturalOrigin, _T("Longitude of natural origin")},
{tcsPA_GaussKrueger, tcsPP_GaussKrueger_ScaleFactorAtNaturalOrigin, _T("Scale factor at natural origin")},
{tcsPA_CylindricEquirectangular, tcsPP_CylindricEquirectangular_FalseEasting, _T("False easting")},
{tcsPA_CylindricEquirectangular, tcsPP_CylindricEquirectangular_FalseNorthing, _T("False northing")},
{tcsPA_CylindricEquirectangular, tcsPP_CylindricEquirectangular_LatitudeOfNaturalOrigin, _T("Latitude of natural origin")},
{tcsPA_CylindricEquirectangular, tcsPP_CylindricEquirectangular_LongitudeOfNaturalOrigin, _T("Longitude of natural origin")},
{tcsPA_Undefined, tcsPP_Undefined, NULL}
};
DT_ATTRIBUTESET _DT_ATTRIBUTES[] = {
{tcsDTA_LongitudeRotation, tcsDTP_LongitudeRotation_LongitudeRotation, _T("Longitude rotation")},
{tcsDTA_GeocentricTranslations, tcsDTP_GeocentricTranslations_XAxisTranslation, _T("X-axis translation")},
{tcsDTA_GeocentricTranslations, tcsDTP_GeocentricTranslations_YAxisTranslation, _T("Y-axis translation")},
{tcsDTA_GeocentricTranslations, tcsDTP_GeocentricTranslations_ZAxisTranslation, _T("Z-axis translation")},
{tcsDTA_Molodenski, tcsDTP_Molodenski_XAxisTranslation, _T("X-axis translation")},
{tcsDTA_Molodenski, tcsDTP_Molodenski_YAxisTranslation, _T("Y-axis translation")},
{tcsDTA_Molodenski, tcsDTP_Molodenski_ZAxisTranslation, _T("Z-axis translation")},
{tcsDTA_Molodenski, tcsDTP_Molodenski_SemiMajorAxisLengthDifference, _T("Semi-major axis length difference")},
{tcsDTA_Molodenski, tcsDTP_Molodenski_FlatteningDifference, _T("Flattening difference")},
{tcsDTA_AbridgedMolodenski, tcsDTP_AbridgedMolodenski_XAxisTranslation, _T("X-axis translation")},
{tcsDTA_AbridgedMolodenski, tcsDTP_AbridgedMolodenski_YAxisTranslation, _T("Y-axis translation")},
{tcsDTA_AbridgedMolodenski, tcsDTP_AbridgedMolodenski_ZAxisTranslation, _T("Z-axis translation")},
{tcsDTA_AbridgedMolodenski, tcsDTP_AbridgedMolodenski_SemiMajorAxisLengthDifference, _T("Semi-major axis length difference")},
{tcsDTA_AbridgedMolodenski, tcsDTP_AbridgedMolodenski_FlatteningDifference, _T("Flattening difference")},
{tcsDTA_PositionVector7ParamTransformation, tcsDTP_PositionVector7ParamTransformation_XAxisTranslation, _T("X-axis translation")},
{tcsDTA_PositionVector7ParamTransformation, tcsDTP_PositionVector7ParamTransformation_YAxisTranslation, _T("Y-axis translation")},
{tcsDTA_PositionVector7ParamTransformation, tcsDTP_PositionVector7ParamTransformation_ZAxisTranslation, _T("Z-axis translation")},
{tcsDTA_PositionVector7ParamTransformation, tcsDTP_PositionVector7ParamTransformation_XAxisRotation, _T("X-axis rotation")},
{tcsDTA_PositionVector7ParamTransformation, tcsDTP_PositionVector7ParamTransformation_YAxisRotation, _T("Y-axis rotation")},
{tcsDTA_PositionVector7ParamTransformation, tcsDTP_PositionVector7ParamTransformation_ZAxisRotation, _T("Z-axis rotation")},
{tcsDTA_PositionVector7ParamTransformation, tcsDTP_PositionVector7ParamTransformation_ScaleDifference, _T("Scale difference")},
{tcsDTA_CoordinateFrame7ParamTransformation, tcsDTP_CoordinateFrame7ParamTransformation_XAxisTranslation, _T("X-axis translation")},
{tcsDTA_CoordinateFrame7ParamTransformation, tcsDTP_CoordinateFrame7ParamTransformation_YAxisTranslation, _T("Y-axis translation")},
{tcsDTA_CoordinateFrame7ParamTransformation, tcsDTP_CoordinateFrame7ParamTransformation_ZAxisTranslation, _T("Z-axis translation")},
{tcsDTA_CoordinateFrame7ParamTransformation, tcsDTP_CoordinateFrame7ParamTransformation_XAxisRotation, _T("X-axis rotation")},
{tcsDTA_CoordinateFrame7ParamTransformation, tcsDTP_CoordinateFrame7ParamTransformation_YAxisRotation, _T("Y-axis rotation")},
{tcsDTA_CoordinateFrame7ParamTransformation, tcsDTP_CoordinateFrame7ParamTransformation_ZAxisRotation, _T("Z-axis rotation")},
{tcsDTA_CoordinateFrame7ParamTransformation, tcsDTP_CoordinateFrame7ParamTransformation_ScaleDifference, _T("Scale difference")},
{tcsDTA_SimilarityTransform, tcsDTP_SimilarityTransform_A1, _T("A1")},
{tcsDTA_SimilarityTransform, tcsDTP_SimilarityTransform_A2M, _T("A2 * m")},
{tcsDTA_SimilarityTransform, tcsDTP_SimilarityTransform_A3N, _T("A3 * n")},
{tcsDTA_SimilarityTransform, tcsDTP_SimilarityTransform_B1, _T("B1")},
{tcsDTA_SimilarityTransform, tcsDTP_SimilarityTransform_B2M, _T("B2 * m")},
{tcsDTA_SimilarityTransform, tcsDTP_SimilarityTransform_B3N, _T("B3 * n")},
{tcsDTA_2DimensionalAffineTransformation, tcsDTP_2DimensionalAffineTransformation_A1, _T("A1")},
{tcsDTA_2DimensionalAffineTransformation, tcsDTP_2DimensionalAffineTransformation_A2M, _T("A2 * m")},
{tcsDTA_2DimensionalAffineTransformation, tcsDTP_2DimensionalAffineTransformation_A3N, _T("A3 * n")},
{tcsDTA_2DimensionalAffineTransformation, tcsDTP_2DimensionalAffineTransformation_B1, _T("B1")},
{tcsDTA_2DimensionalAffineTransformation, tcsDTP_2DimensionalAffineTransformation_B2M, _T("B2 * m")},
{tcsDTA_2DimensionalAffineTransformation, tcsDTP_2DimensionalAffineTransformation_B3N, _T("B3 * n")},
{tcsDTA_2ndOrderPolynomialFunction, tcsDTP_2ndOrderPolynomialFunction_Ordinate1OfSourceEvaluationPoint, _T("Ordinate 1 of source evaluation point")},
{tcsDTA_2ndOrderPolynomialFunction, tcsDTP_2ndOrderPolynomialFunction_Ordinate2OfSourceEvaluationPoint, _T("Ordinate 2 of source evaluation point")},
{tcsDTA_2ndOrderPolynomialFunction, tcsDTP_2ndOrderPolynomialFunction_Ordinate1OfTargetEvaluationPoint, _T("Ordinate 1 of target evaluation point")},
{tcsDTA_2ndOrderPolynomialFunction, tcsDTP_2ndOrderPolynomialFunction_Ordinate2OfTargetEvaluationPoint, _T("Ordinate 2 of target evaluation point")},
{tcsDTA_2ndOrderPolynomialFunction, tcsDTP_2ndOrderPolynomialFunction_A1, _T("A1")},
{tcsDTA_2ndOrderPolynomialFunction, tcsDTP_2ndOrderPolynomialFunction_A2M, _T("A2 * m")},
{tcsDTA_2ndOrderPolynomialFunction, tcsDTP_2ndOrderPolynomialFunction_A3N, _T("A3 * n")},
{tcsDTA_2ndOrderPolynomialFunction, tcsDTP_2ndOrderPolynomialFunction_A4Mm, _T("A4 * mm")},
{tcsDTA_2ndOrderPolynomialFunction, tcsDTP_2ndOrderPolynomialFunction_A5Mn, _T("A5 * mn")},
{tcsDTA_2ndOrderPolynomialFunction, tcsDTP_2ndOrderPolynomialFunction_A6Nn, _T("A6 * nn")},
{tcsDTA_2ndOrderPolynomialFunction, tcsDTP_2ndOrderPolynomialFunction_B1, _T("B1")},
{tcsDTA_2ndOrderPolynomialFunction, tcsDTP_2ndOrderPolynomialFunction_B2M, _T("B2 * m")},
{tcsDTA_2ndOrderPolynomialFunction, tcsDTP_2ndOrderPolynomialFunction_B3N, _T("B3 * n")},
{tcsDTA_2ndOrderPolynomialFunction, tcsDTP_2ndOrderPolynomialFunction_B4Mm, _T("B4 * mm")},
{tcsDTA_2ndOrderPolynomialFunction, tcsDTP_2ndOrderPolynomialFunction_B5Mn, _T("B5 * mn")},
{tcsDTA_2ndOrderPolynomialFunction, tcsDTP_2ndOrderPolynomialFunction_B6Nn, _T("B6 * nn")},
{tcsDTA_3rdOrderPolynomialFunction, tcsDTP_3rdOrderPolynomialFunction_Ordinate1OfSourceEvaluationPoint, _T("Ordinate 1 of source evaluation point")},
{tcsDTA_3rdOrderPolynomialFunction, tcsDTP_3rdOrderPolynomialFunction_Ordinate2OfSourceEvaluationPoint, _T("Ordinate 2 of source evaluation point")},
{tcsDTA_3rdOrderPolynomialFunction, tcsDTP_3rdOrderPolynomialFunction_Ordinate1OfTargetEvaluationPoint, _T("Ordinate 1 of target evaluation point")},
{tcsDTA_3rdOrderPolynomialFunction, tcsDTP_3rdOrderPolynomialFunction_Ordinate2OfTargetEvaluationPoint, _T("Ordinate 2 of target evaluation point")},
{tcsDTA_3rdOrderPolynomialFunction, tcsDTP_3rdOrderPolynomialFunction_A1, _T("A1")},
{tcsDTA_3rdOrderPolynomialFunction, tcsDTP_3rdOrderPolynomialFunction_A2M, _T("A2 * m")},
{tcsDTA_3rdOrderPolynomialFunction, tcsDTP_3rdOrderPolynomialFunction_A3N, _T("A3 * n")},
{tcsDTA_3rdOrderPolynomialFunction, tcsDTP_3rdOrderPolynomialFunction_A4Mm, _T("A4 * mm")},
{tcsDTA_3rdOrderPolynomialFunction, tcsDTP_3rdOrderPolynomialFunction_A5Mn, _T("A5 * mn")},
{tcsDTA_3rdOrderPolynomialFunction, tcsDTP_3rdOrderPolynomialFunction_A6Nn, _T("A6 * nn")},
{tcsDTA_3rdOrderPolynomialFunction, tcsDTP_3rdOrderPolynomialFunction_A7Mmm, _T("A7 * mmm")},
{tcsDTA_3rdOrderPolynomialFunction, tcsDTP_3rdOrderPolynomialFunction_A8Mmn, _T("A8 * mmn")},
{tcsDTA_3rdOrderPolynomialFunction, tcsDTP_3rdOrderPolynomialFunction_A9Mnn, _T("A9 * mnn")},
{tcsDTA_3rdOrderPolynomialFunction, tcsDTP_3rdOrderPolynomialFunction_A10Nnn, _T("A10 * nnn")},
{tcsDTA_3rdOrderPolynomialFunction, tcsDTP_3rdOrderPolynomialFunction_B1, _T("B1")},
{tcsDTA_3rdOrderPolynomialFunction, tcsDTP_3rdOrderPolynomialFunction_B2M, _T("B2 * m")},
{tcsDTA_3rdOrderPolynomialFunction, tcsDTP_3rdOrderPolynomialFunction_B3N, _T("B3 * n")},
{tcsDTA_3rdOrderPolynomialFunction, tcsDTP_3rdOrderPolynomialFunction_B4Mm, _T("B4 * mm")},
{tcsDTA_3rdOrderPolynomialFunction, tcsDTP_3rdOrderPolynomialFunction_B5Mn, _T("B5 * mn")},
{tcsDTA_3rdOrderPolynomialFunction, tcsDTP_3rdOrderPolynomialFunction_B6Nn, _T("B6 * nn")},
{tcsDTA_3rdOrderPolynomialFunction, tcsDTP_3rdOrderPolynomialFunction_B7Mmm, _T("B7 * mmm")},
{tcsDTA_3rdOrderPolynomialFunction, tcsDTP_3rdOrderPolynomialFunction_B8Mmn, _T("B8 * mmn")},
{tcsDTA_3rdOrderPolynomialFunction, tcsDTP_3rdOrderPolynomialFunction_B9Mnn, _T("B9 * mnn")},
{tcsDTA_3rdOrderPolynomialFunction, tcsDTP_3rdOrderPolynomialFunction_B10Nnn, _T("B10 * nnn")},
{tcsDTA_4thOrderPolynomialFunction, tcsDTP_4thOrderPolynomialFunction_Ordinate1OfSourceEvaluationPoint, _T("Ordinate 1 of source evaluation point")},
{tcsDTA_4thOrderPolynomialFunction, tcsDTP_4thOrderPolynomialFunction_Ordinate2OfSourceEvaluationPoint, _T("Ordinate 2 of source evaluation point")},
{tcsDTA_4thOrderPolynomialFunction, tcsDTP_4thOrderPolynomialFunction_Ordinate1OfTargetEvaluationPoint, _T("Ordinate 1 of target evaluation point")},
{tcsDTA_4thOrderPolynomialFunction, tcsDTP_4thOrderPolynomialFunction_Ordinate2OfTargetEvaluationPoint, _T("Ordinate 2 of target evaluation point")},
{tcsDTA_4thOrderPolynomialFunction, tcsDTP_4thOrderPolynomialFunction_A1, _T("A1")},
{tcsDTA_4thOrderPolynomialFunction, tcsDTP_4thOrderPolynomialFunction_A2M, _T("A2 * m")},
{tcsDTA_4thOrderPolynomialFunction, tcsDTP_4thOrderPolynomialFunction_A3N, _T("A3 * n")},
{tcsDTA_4thOrderPolynomialFunction, tcsDTP_4thOrderPolynomialFunction_A4Mm, _T("A4 * mm")},
{tcsDTA_4thOrderPolynomialFunction, tcsDTP_4thOrderPolynomialFunction_A5Mn, _T("A5 * mn")},
{tcsDTA_4thOrderPolynomialFunction, tcsDTP_4thOrderPolynomialFunction_A6Nn, _T("A6 * nn")},
{tcsDTA_4thOrderPolynomialFunction, tcsDTP_4thOrderPolynomialFunction_A7Mmm, _T("A7 * mmm")},
{tcsDTA_4thOrderPolynomialFunction, tcsDTP_4thOrderPolynomialFunction_A8Mmn, _T("A8 * mmn")},
{tcsDTA_4thOrderPolynomialFunction, tcsDTP_4thOrderPolynomialFunction_A9Mnn, _T("A9 * mnn")},
{tcsDTA_4thOrderPolynomialFunction, tcsDTP_4thOrderPolynomialFunction_A10Nnn, _T("A10 * nnn")},
{tcsDTA_4thOrderPolynomialFunction, tcsDTP_4thOrderPolynomialFunction_A11Mmmm, _T("A11 * mmmm")},
{tcsDTA_4thOrderPolynomialFunction, tcsDTP_4thOrderPolynomialFunction_A12Mmmn, _T("A12 * mmmn")},
{tcsDTA_4thOrderPolynomialFunction, tcsDTP_4thOrderPolynomialFunction_A13Mmnn, _T("A13 * mmnn")},
{tcsDTA_4thOrderPolynomialFunction, tcsDTP_4thOrderPolynomialFunction_A14Mnnn, _T("A14 * mnnn")},
{tcsDTA_4thOrderPolynomialFunction, tcsDTP_4thOrderPolynomialFunction_A15Nnnn, _T("A15 * nnnn")},
{tcsDTA_4thOrderPolynomialFunction, tcsDTP_4thOrderPolynomialFunction_B1, _T("B1")},
{tcsDTA_4thOrderPolynomialFunction, tcsDTP_4thOrderPolynomialFunction_B2M, _T("B2 * m")},
{tcsDTA_4thOrderPolynomialFunction, tcsDTP_4thOrderPolynomialFunction_B3N, _T("B3 * n")},
{tcsDTA_4thOrderPolynomialFunction, tcsDTP_4thOrderPolynomialFunction_B4Mm, _T("B4 * mm")},
{tcsDTA_4thOrderPolynomialFunction, tcsDTP_4thOrderPolynomialFunction_B5Mn, _T("B5 * mn")},
{tcsDTA_4thOrderPolynomialFunction, tcsDTP_4thOrderPolynomialFunction_B6Nn, _T("B6 * nn")},
{tcsDTA_4thOrderPolynomialFunction, tcsDTP_4thOrderPolynomialFunction_B7Mmm, _T("B7 * mmm")},
{tcsDTA_4thOrderPolynomialFunction, tcsDTP_4thOrderPolynomialFunction_B8Mmn, _T("B8 * mmn")},
{tcsDTA_4thOrderPolynomialFunction, tcsDTP_4thOrderPolynomialFunction_B9Mnn, _T("B9 * mnn")},
{tcsDTA_4thOrderPolynomialFunction, tcsDTP_4thOrderPolynomialFunction_B10Nnn, _T("B10 * nnn")},
{tcsDTA_4thOrderPolynomialFunction, tcsDTP_4thOrderPolynomialFunction_B11Mmmm, _T("B11 * mmmm")},
{tcsDTA_4thOrderPolynomialFunction, tcsDTP_4thOrderPolynomialFunction_B12Mmmn, _T("B12 * mmmn")},
{tcsDTA_4thOrderPolynomialFunction, tcsDTP_4thOrderPolynomialFunction_B13Mmnn, _T("B13 * mmnn")},
{tcsDTA_4thOrderPolynomialFunction, tcsDTP_4thOrderPolynomialFunction_B14Mnnn, _T("B14 * mnnn")},
{tcsDTA_4thOrderPolynomialFunction, tcsDTP_4thOrderPolynomialFunction_B15Nnnn, _T("B15 * nnnn")},
{tcsDTA_VerticalOffset, tcsDTP_VerticalOffset_VerticalOffset, _T("Vertical offset")},
{tcsDTA_Undefined, tcsDTP_Undefined, NULL}
};
