# Makefile für Export-Filter für AutoCAD-DXF-Format

.SUFFIXES:
.SUFFIXES: .cxx .obj .rc .res .c

COPY = 1
NAME = ACADDXF

# Generierungsdatum (yymmdd) und Version
DATE = 980701
VERSION = 1
RELEASE = 04
BUILD = 032
COPYRIGHT = JB$(DATE)

PNAME = "Version für den internen Gebrauch"
PADDRESS = "uve GmbH Fernerkundungszentrum Potsdam"

LIBD = e:\triasdev.mvc\lib32
WINDIR = c:\trias.mvc\trias

MAP = $(NAME).map
LINK = f:\c8\bin\link
ASM = masm
STUB = rights
OUTDLL = $(NAME).flt
DEF = $(NAME).def
RIGHTS = $(STUB).exe

#!include "acaddxf.mak"

copy:
!IF $(COPY)
    copy $(NAME).dll $(WINDIR)\$(OUTDLL)
!ENDIF

# Versionskontrolle -----------------------------------------------------------
$(STUB).exe:    $(STUB).asm
	masm rights;
        $(LINK) /KNOWEAS rights;

# alle versionsabhängien Datein löschen
new:
	@del $(DEF) > nul
	@del $(STUB).asm > nul
	@del $(NAME).rcv > nul
       
# nur Versionsabhängigkeiten auflösen
formake: $(NAME).tpl $(NAME).rcv $(DEF)

# ModulDefinitionsDatei mit allen Exporten generieren
$(DEF): $(NAME).tpl
	ersetz $(VERSION) $(RELEASE) $(BUILD) $(COPYRIGHT) $(NAME).tpl $(DEF)

$(STUB).asm:    $(STUB).tpl 
	ersetz $(VERSION) $(RELEASE) $(BUILD) $(COPYRIGHT) $(STUB).tpl $(STUB).asm

# Personalisierungsinformation
$(NAME).rcv:    $(NAME)v.tpl
	ersetz $(VERSION) $(RELEASE) $(BUILD) $(COPYRIGHT) @A @B $(NAME)v.tpl tmp.rcv
	ersetz $(PNAME) $(PADDRESS) tmp.rcv $(NAME).rcv
	@del tmp.rcv > nul
	
# archivieren ---------------------------------------------------------------
store:  
	@echo off
	del *.bak
	del *.dmp
	del *.tmp
	del *.zip
	del *.sym
	del *.sts
	del *.lst
	del *.aps
	del *.pch
	del *.bnd
	del *.pdb
	del *.sbr
	del *.bsc 
        zip -m -x*.ncb $(NAME)
	

