//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by MapMgr.rc
//
#define IDR_MAINFRAME                   2
#define IDD_ABOUTBOX                    100
#define ID_STS_TIME                     102
#define ID_STS_PICTCOORD                103
#define ID_STS_PICTSIZE                 104
#define IDS_DEFAULT_FONT                105
#define IDD_FORM_MAPLIST                128
#define IDW_TB_MODES                    131
#define IDR_MENU1                       133
#define IDB_BMPSTART                    142
#define IDI_WIZARD                      149
#define IDI_OPEN                        150
#define IDI_LAST                        151
#define IDR_COLORCMDS                   152
#define IDD_PG_FILEOPT                  154
#define IDD_DLG_MAPSPECIAL              157
#define IDD_PG_MAPPROP_COMMON           159
#define IDD_PG_MAPPROP_PICT             164
#define IDB_COLORRGB                    167
#define IDD_PG_INVALIDDOC               168
#define IDD_DLG_DOCNEWDIALOG            210
#define IDD_PG_DOCSTART                 211
#define IDD_PG_MAPTYPE                  212
#define IDD_PG_DOSEARCH                 213
#define IDD_PG_FINISHDOCNEW             214
#define IDD_DLG_DOCPROPERTIES           220
#define IDD_PG_HDRGEODATA               221
#define IDD_DLG_MAPPROPERTIES           221
#define IDD_PG_HDRVISDATA               222
#define IDD_DLG_MAPSELECT               300
#define IDD_DLG_MAPNAME                 301
#define IDD_PG_OPT_VIEW                 302
#define ID_MODE_ADD                     990
#define ID_MODE_DEL                     992
#define ID_MODE_EDT                     993
#define ID_GCP                          1000
#define ID_GCP_BL                       1001
#define ID_GCP_BR                       1002
#define ID_GCP_TR                       1003
#define ID_GCP_TL                       1004
#define ID_OBJ_POINT                    1005
#define ID_OBJ_LINE                     1006
#define IDC_LIST_MAPDIRS                1012
#define IDC_LIST_MAPS                   1012
#define IDC_TREE_OF_MAPS                1013
#define IDC_MAPDESCR                    1029
#define IDC_BTN_APPLY                   1030
#define IDC_EDIT_MAPNAME                1036
#define IDC_MAP_AS                      1041
#define IDC_MAP_AV                      1043
#define IDC_MAP_N                       1044
#define ID_BL                           1050
#define ID_BR                           1051
#define ID_TR                           1052
#define ID_TL                           1053
#define IDC_MAPLIST                     1053
#define ID_MAP_SELECT                   1054
#define IDW_TB_MAPS                     1055
#define IDC_BTN_TREE                    1056
#define IDW_TB_OBJECTS                  1056
#define IDB_COLORPAL                    1057
#define IDC_MAPVCODE                    1065
#define IDC_MAPMCODE                    1066
#define IDC_IDENT                       1067
#define IDC_S11                         1068
#define IDC_MAPICODE                    1068
#define IDC_S12                         1069
#define IDC_S21                         1070
#define IDC_S22                         1071
#define IDC_OFFSET_X                    1072
#define IDC_OFFSET_Y                    1073
#define IDC_MAPTYPE                     1074
#define IDC_MCODE_DEC                   1077
#define IDC_MCODE_HEX                   1078
#define IDC_IDENT_DEC                   1079
#define IDC_IDENT_HEX                   1080
#define IDC_DROP_MAPTYPESTYPES          1082
#define IDC_EDIT_MAPPARAM               1085
#define IDC_BTN_PRJNEW                  1086
#define IDC_BTN_MAPLAST                 1087
#define IDC_BTN_MAPOTHER                1088
#define IDC_SEARCHMAPS                  1089
#define IDC_ANIMATE                     1091
#define IDC_EDIT1                       1092
#define IDC_EDIT2                       1093
#define IDC_EDIT_SEARCHMASK             1094
#define IDC_BMP1                        1095
#define IDC_BMP2                        1096
#define IDC_EDIT_X                      1097
#define IDC_EDIT_Y                      1098
#define IDC_LIST_GCP                    1099
#define IDC_EDIT_X_BTM                  1101
#define IDC_EDIT_Y_BTM                  1102
#define IDC_EDIT_X_TOP                  1103
#define IDC_EDIT_Y_TOP                  1104
#define IDC_TEXT_COORDTRANS             1112
#define IDC_LST_ERRORS                  1113
#define IDC_SPIN_LINE_X                 1114
#define IDC_SPIN_LINE_Y                 1115
#define IDC_EDIT_LINE_X                 1116
#define IDC_EDIT_LINE_Y                 1117
#define IDC_EDIT_PAGE_X                 1118
#define IDC_VERSION_5                   1118
#define IDC_SPIN_PAGE_X                 1119
#define IDC_VERSION_4                   1119
#define IDC_EDIT_PAGE_Y                 1120
#define IDC_SPIN_PAGE_Y                 1121
#define ID_OPT_SELECTDIALOG             32782
#define ID_OPT_AS                       32783
#define ID_EXPORT_TEXT                  32785
#define ID_ADD_MAP                      32786
#define ID_DEL_MAP                      32787
#define ID_REDRAW                       32795
#define ID_MAP_MODIFY_IDENT             32796
#define ID_MAP_MODIFY_FILENAME          32797
#define ID_COLORCMD_SHOWPALETTE         32799
#define ID_FILE_PROPERTIES              32801
#define ID_MAP_PROPERTIES               32802
#define ID_MAP_SPECIAL                  32803
#define ID_MAP_PROPCOLORS               32804
#define ID_COLORCMD_SHOWR               32806
#define ID_COLORCMD_SHOWG               32807
#define ID_COLORCMD_SHOWB               32808
#define ID_APPSTART                     32809
#define ID_COLORCMD_SHOWRGB             32812
#define ID_COLORCMD_SHOWHUE             32813
#define ID_COLORCMD_SHOWSAT             32814
#define ID_COLORCMD_SHOWBRI             32815
#define ID_STS_PERCENT                  63000
#define IDS_PICTTYPE_ALL                63050
#define IDS_PICTTYPE_BMP                63051
#define IDS_PICTTYPE_TIFF               63053
#define IDS_FILETYPE_ASC                63060
#define IDS_FILETYPE_TXT                63061
#define IDS_ERR_WRONGVERSION            63100
#define IDS_MAPTYPES                    63102
#define IDS_NEWDOC                      63103
#define IDS_NOSRCHDIR                   63104
#define IDS_SRCHDIR                     63105
#define IDS_INI_SECTION                 63150
#define IDS_INI_WNDPOS                  63151
#define IDS_ERRORS                      63190
#define IDS_WARNINGS                    63191
#define IDS_INVALID_DOCUMENT            63200
#define IDS_INVALID_BTMLEFT             63201
#define IDS_INVALID_TOPRIGHT            63202
#define IDS_INVALID_OFFSETX1            63203
#define IDS_INVALID_OFFSETY1            63204
#define IDS_INVALID_OFFSETX2            63205
#define IDS_INVALID_OFFSETY2            63206
#define IDS_INVALID_PICTPATH            63209
#define IDS_INVALID_OFFSETX0            63210
#define IDS_INVALID_OFFSETY0            63211

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        174
#define _APS_NEXT_COMMAND_VALUE         32818
#define _APS_NEXT_CONTROL_VALUE         1122
#define _APS_NEXT_SYMED_VALUE           103
#endif
#endif
