# Genrieren der Versionsinfo's für COLORS.EBN

!include "$(TRIASINCLUDE)/triasver.mak"

# Generierungsdatum (yymmdd) und Version
DATE=001206
VERSION = 1
RELEASE = 00
BUILD = 018

COPYRIGHT = HK$(DATE)

PNAME = $(TRIAS_PNAME)
PADDRESS = $(TRIAS_PADDRESS)

STUB = rights
RIGHTS = $(STUB).exe
REPLACE = ersetz
NAME = colors
DEF = $(NAME).def

ASM = masm
ASMF = /D?PLM=0 /D?WIN=1
LINK = link16.exe

# Alles neubilden
all:	formake 

$(STUB).exe:	$(STUB).asm
	$(ASM) $(ASMF) $(STUB) 
	$(LINK) /NOLOGO /KNOWEAS $(STUB);

# -----------------------------------------------------------------------------
# CopyrightEintraege Generieren 
new:
#	@del $(STUB).asm
	@del res\$(NAME).rcv
	@del $(DEF)
	@del res\Colors.rc2

formake:	$(DEF) res\$(NAME).rcv res\Colors.rc2	# $(STUB).exe 

$(STUB).asm:	$(STUB).tpl 
	$(REPLACE) $(VERSION) $(RELEASE) $(BUILD) $(COPYRIGHT) $(STUB).tpl $(STUB).asm

# Personalisierungsinformation
res\$(NAME).rcv:	res\$(NAME)v.tpl makefile
	$(REPLACE) $(VERSION) $(RELEASE) $(BUILD) $(COPYRIGHT) @A @B @C @D @E res\$(NAME)v.tpl tmp.rcv
	$(REPLACE) $(PNAME) $(PADDRESS) $(TRIAS_VERSION) $(TRIAS_RELEASE) @A tmp.rcv tmp1 
	$(REPLACE) $(COMPANYNAME) tmp1 res\$(NAME).rcv
	@del tmp.rcv > nul
	@del tmp1 > nul

$(DEF):		$(NAME).tpl makefile
	$(REPLACE) $(VERSION) $(RELEASE) $(BUILD) $(COPYRIGHT) $(NAME).tpl $(DEF)

res\Colors.rc2:	res\Colorsp.tpl
	$(REPLACE) $(VERSION) $(RELEASE) res\Colorsp.tpl res\Colors.rc2
