/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
** Help Context Identifiers for az.HH
** Generated by RoboHELP
** 
** RoboHELP observes a polite protocol for dealing with this file.
** It will add new identifiers for new Topic IDs that are
** added to the RTF file with the same name.
** 
** RoboHELP will also preserve comments which are placed in this
** file, so documentation staff can insert notes to those crazy
** developers and vice versa. 
** 
** However, the numeric values of the identifiers are stored only
** in this file.  Therefore, if you change the numeric value here,
** it is changed for good.  RoboHELP will not try to change it back.
**
** Normally, RoboHELP will remove the symbols for Topic IDs
** which have been removed from the .RTF file.  However, you can
** set a checkbox in your project setup to prevent RoboHELP from
** doing this.  You may want to do this and make use of the Alias
** capability of the help compiler.
**
*/

#define Contacting_Summit_Software 1
#define Language_Element_Not_Found 2

/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
** Help Context Identifiers for azmisc.HH
** Generated by RoboHELP
** 
*/

#define Application_States 20501
#define File_Types 20502
#define Basic_Object 20503
#define FreeMemory_Property 20504
#define Clipboard_Statement_and_Function 20505
#define Clipboard_Object 20506
#define Clear_Method 20507
#define Clipboard_Methods 20508
#define Close_keyword 20509
#define Equal_keyword 20510
#define General_Constants 20511
#define Date_keyword 20512
#define Date_Dollar_keyword 20513
#define As_keyword 20514
#define Desktop_Object 20515
#define Dialog_keyword 20516
#define File_Attributes 20517
#define DlgCaption_Statement_and_Function 20518
#define DlgEnable_Statement_and_Function 20519
#define DlgFocus_Statement_and_Function 20520
#define DlgListBoxArray_Statement_and_Function 20521
#define DlgText_Statement_and_Function 20522
#define DlgValue_Statement_and_Function 20523
#define DlgVisible_Statement_and_Function 20524
#define Do_and_While_Loops 20525
#define DoEvents_Statement_and_Function 20526
#define End_keyword 20527
#define Err_Object 20528
#define Error_keyword 20529
#define Exit_keyword 20530
#define For_keyword 20531
#define Next_keyword 20532
#define To_keyword 20533
#define Goto_keyword 20534
#define Else_keyword 20535
#define Input_keyword 20536
#define Len_Statement_and_Function 20537
#define Lock_keyword 20538
#define Mid_MidB_Statements_and_Functions 20539
#define Msg_Object 20540
#define MsgBox_Statement_and_Function 20541
#define Net_Object 20542
#define Open_keyword 20543
#define Option_keyword 20544
#define Print_keyword 20545
#define Printer_Orientation_Constants 20546
#define Mouse_Button_Constants 20547
#define Random_keyword 20548
#define Screen_Object 20549
#define Seek_Statement_and_Function 20550
#define String_keyword 20551
#define Optional_keyword 20552
#define System_Object 20553
#define Text_keyword 20554
#define Text_Font_Constants 20555
#define Time_Statement_and_Function 20556
#define Viewport_Object 20557
#define Date_Constants 20558
#define Write_keyword 20559
#define Pound_keyword 20560
#define Ampersand_keyword 20561
#define Static_keyword 20562

/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
** Help Context Identifiers for lrspchar.HH
** Generated by RoboHELP
** 
*/

#define Apostrophe_keyword 16001
#define Minus_operator 16002
#define Const_directive_directive 16003
#define IfThenElse_Directive_directive 16004
#define Ampersand_operator 16005
#define Parentheses_keyword 16006
#define Multiply_operator 16007
#define Dot_keyword 16008
#define Slash_operator 16009
#define Backslash_operator 16010
#define Exponent_operator 16011
#define Underscore_keyword 16012
#define Plus_operator 16013
#define LessThan_operator 16014
#define LessThanOrEqual_operator 16015
#define NotEqual_operator 16016
#define Equal_statement 16017
#define Equal_Operator_operator 16018
#define GreaterThan_operator 16019
#define GreaterThanOrEqual_operator 16020

/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
** Help Context Identifiers for LRA-B.HH
** Generated by RoboHELP
** 
*/

#define Abs_function 8501
#define ActivateControl_statement 8502
#define And_operator 8503
#define AnswerBox_function 8504
#define Any_data_type 8505
#define AppActivate_statement 8506
#define AppClose_statement 8507
#define AppFilename_function 8508
#define AppFind_AppFind_functions 8509
#define AppGetActive_function 8510
#define AppGetPosition_statement 8511
#define AppGetState_function 8512
#define AppHide_statement 8513
#define AppList_statement 8514
#define AppMaximize_statement 8515
#define AppMinimize_statement 8516
#define AppMove_statement 8517
#define AppRestore_statement 8518
#define AppSetState_statement 8519
#define AppShow_statement 8520
#define AppSize_statement 8521
#define AppType_function 8522
#define ArrayDims_function 8523
#define Arrays_topic 8524
#define ArraySort_statement 8525
#define Asc_AscB_AscW_functions 8526
#define AskBox_AskBox_functions 8527
#define AskPassword_AskPassword_functions 8528
#define Atn_function 8529
#define Basic_Architecture_property 8530
#define Basic_Capability_method 8531
#define Basic_CodePage_property 8532
#define Basic_Eoln_property 8533
#define Basic_FreeMemory_property 8534
#define Basic_HomeDir_property 8535
#define Basic_Locale_property 8536
#define Basic_OperatingSystem_property 8537
#define Basic_OperatingSystemVendor_property 8538
#define Basic_OperatingSystemVersion_property 8539
#define Basic_OS_property 8540
#define Basic_PathSeparator_property 8541
#define Basic_Processor_property 8542
#define Basic_ProcessorCount_property 8543
#define Basic_Version_property 8544
#define Beep_statement 8545
#define Begin_Dialog_statement 8546
#define Boolean_data_type 8547
#define ButtonEnabled_function 8548
#define ButtonExists_function 8549
#define ByRef_keyword 8550
#define ByVal_keyword 8551

/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
** Help Context Identifiers for LRC.HH
** Generated by RoboHELP
**
*/

#define Call_statement 9001
#define CancelButton_statement 9002
#define CBool_function 9003
#define CCur_function 9004
#define CDate_CVDate_functions 9005
#define CDbl_function 9006
#define ChDir_statement 9007
#define ChDrive_statement 9008
#define CheckBox_statement 9009
#define CheckBoxEnabled_function 9010
#define CheckBoxExists_function 9011
#define Choose_function 9012
#define Chr_Chr_ChrB_ChrB_ChrW_ChrW_functions 9013
#define CInt_function 9014
#define Clipboard_function 9015
#define Clipboard_statement 9016
#define Clipboard_Clear_method 9017
#define Clipboard_GetFormat_method 9018
#define Clipboard_GetText_method 9019
#define Clipboard_SetText_method 9020
#define CLng_function 9021
#define Close_statement 9022
#define ComboBox_statement 9023
#define ComboBoxEnabled_function 9024
#define ComboBoxExists_function 9025
#define Command_Command_functions 9026
#define Comments_topic 9027
#define Comparison_Operators_topic 9028
#define Const_statement 9029
#define Constants_topic 9030
#define Cos_function 9031
#define CreateObject_function 9032
#define Cross_Platform_Scripting_topic 9033
#define CSng_function 9034
#define CStr_function 9035
#define CurDir_CurDir_functions 9036
#define Currency_data_type 9037
#define CVar_function 9038
#define CVErr_function 9039

/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
** Help Context Identifiers for LRD.HH
** Generated by RoboHELP
** 
*/

#define Date_data_type 9501
#define Date_Date_functions 9502
#define Date_Date_statements 9503
#define DateAdd_function 9504
#define DateDiff_function 9505
#define DatePart_function 9506
#define DateSerial_function 9507
#define DateValue_function 9508
#define Day_function 9509
#define DDB_function 9510
#define DDEExecute_statement 9511
#define DDEInitiate_function 9512
#define DDEPoke_statement 9513
#define DDERequest_DDERequest_functions 9514
#define DDESend_statement 9515
#define DDETerminate_statement 9516
#define DDETerminateAll_statement 9517
#define DDETimeout_statement 9518
#define Declare_statement 9519
#define DefType_statement 9520
#define DeleteSetting_statement 9521
#define Desktop_ArrangeIcons_method 9522
#define Desktop_Cascade_method 9523
#define Desktop_SetColors_method 9524
#define Desktop_SetWallpaper_method 9525
#define Desktop_Snapshot_method 9526
#define Desktop_Tile_method 9527
#define Dialog_function 9528
#define Dialog_statement 9529
#define Dialogs_topic 9530
#define Dim_statement 9531
#define Dir_Dir_functions 9532
#define DiskDrives_statement 9533
#define DiskFree_function 9534
#define DlgCaption_function 9535
#define DlgCaption_statement 9536
#define DlgControlId_function 9537
#define DlgEnable_function 9538
#define DlgEnable_statement 9539
#define DlgFocus_function 9540
#define DlgFocus_statement 9541
#define DlgListBoxArray_function 9542
#define DlgListBoxArray_statement 9543
#define DlgProc_function 9544
#define DlgSetPicture_statement 9545
#define DlgText_statement 9546
#define DlgText_function 9547
#define DlgValue_function 9548
#define DlgValue_statement 9549
#define DlgVisible_function 9550
#define DlgVisible_statement 9551
#define Do_Loop_statement 9552
#define DoEvents_function 9553
#define DoEvents_statement 9554
#define DoKeys_statement 9555
#define Double_data_type 9556
#define DropListBox_statement 9557

/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
** Help Context Identifiers for LRE.HH
** Generated by RoboHELP
** 
*/

#define EditEnabled_function 10001
#define EditExists_function 10002
#define End_statement 10003
#define Environ_Environ_functions 10004
#define EOF_function 10005
#define Eqv_operator 10006
#define Erase_statement 10007
#define Erl_function 10008
#define Err_Clear_method 10009
#define Err_Description_property 10010
#define Err_HelpContext_property 10011
#define Err_HelpFile_property 10012
#define Err_LastDLLError_property 10013
#define Err_Number_property 10014
#define Err_Raise_method 10016
#define Err_Source_property 10017
#define Error_statement 10018
#define Error_Handling_topic 10019
#define Error_Error_functions 10020
#define Exit_Do_statement 10021
#define Exit_For_statement 10022
#define Exit_Function_statement 10023
#define Exit_Sub_statement 10024
#define Exp_function 10025
#define Expression_Evaluation_topic 10026

/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
** Help Context Identifiers for LRF-I.HH
** Generated by RoboHELP
** 
*/

#define FileAttr_function 19501
#define FileCopy_statement 19502
#define FileDateTime_function 19503
#define FileDirs_statement 19504
#define FileExists_function 19505
#define FileLen_function 19506
#define FileList_statement 19507
#define FileParse_function 19508
#define FileType_function 19509
#define Fix_function 19510
#define For_Each_statement 19511
#define For_Next_statement 19512
#define Format_Format_functions 19513
#define FreeFile_function 19514
#define Function_End_Function_statement 19515
#define Fv_function 19516
#define Get_statement 19517
#define GetAllSettings_function 19518
#define GetAttr_function 19519
#define GetCheckBox_function 19520
#define GetComboBoxItem_function 19521
#define GetComboBoxItemCount_function 19522
#define GetEditText_function 19523
#define GetListBoxItem_function 19524
#define GetListBoxItemCount_function 19525
#define GetObject_function 19526
#define GetOption_function 19527
#define GetSetting_function 19528
#define Global_statement 19529
#define GoSub_statement 19530
#define Goto_statement 19531
#define GroupBox_statement 19532
#define HelpButton_statement 19533
#define Hex_Hex_functions 19534
#define HLine_statement 19535
#define Hour_function 19536
#define HPage_statement 19537
#define HScroll_statement 19538
#define HWND_object 19539
#define HWND_Value_property 19540
#define If_Then_Else_statement 19541
#define IIf_function 19542
#define IMEStatus_function 19543
#define Imp_operator 19544
#define Inline_statement 19545
#define Input_Pound_statement 19546
#define Input_Input_InputB_InputB_functions 19547
#define InputBox_InputBox_functions 19548
#define InStr_InstrB_functions 19549
#define Int_function 19550
#define Integer_data_type 19551
#define IPmt_function 19552
#define IRR_function 19553
#define Is_operator 19554
#define IsDate_function 19555
#define IsEmpty_function 19556
#define IsError_function 19557
#define IsMissing_function 19558
#define IsNull_function 19559
#define IsNumeric_function 19560
#define IsObject_function 19561
#define Item_function 19562
#define ItemCount_function 19563

/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
** Help Context Identifiers for lrk-l.HH
** Generated by RoboHELP
**
*/

#define Keywords_topic 11001
#define Kill_statement 11002
#define LBound_function 11003
#define LCase_LCase_functions 11004
#define Left_Left_LeftB_LeftB_functions 11005
#define Len_LenB_functions 11006
#define Let_statement 11007
#define Like_operator 11008
#define Line_Numbers_topic 11009
#define Line_function 11010
#define LineCount_function 11011
#define Line_Input_Pound_statement 11012
#define ListBox_statement 11013
#define ListBoxEnabled_function 11014
#define ListBoxExists_function 11015
#define Literals_topic 11016
#define Loc_function 11017
#define Lock_Unlock_statements 11018
#define Lof_function 11019
#define Log_function 11020
#define Long_data_type 11021
#define LSet_statement 11022
#define LTrim_LTrim_functions 11023


/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
** Help Context Identifiers for LRM.HH
** Generated by RoboHELP
** 
*/

#define MacID_function 11501
#define MacScript_statement 11502
#define Main_statement 11503
#define Mci_function 11504
#define Menu_statement 11505
#define MenuItemChecked_function 11506
#define MenuItemEnabled_function 11507
#define MenuItemExists_function 11508
#define Mid_Mid_MidB_MidB_functions 11509
#define Mid_Mid_MidB_MidB_statements 11510
#define Minute_function 11511
#define MIRR_function 11512
#define MkDir_statement 11513
#define Mod_operator 11514
#define Month_function 11515
#define Msg_Close_method 11516
#define Msg_Open_method 11517
#define Msg_Text_property 11518
#define Msg_Thermometer_property 11519
#define MsgBox_function 11520
#define MsgBox_statement 11521

/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
** Help Context Identifiers for LRN-O.HH
** Generated by RoboHELP
** 
*/

#define Name_statement 12001
#define Named_Parameters_topic 12002
#define Net_AddCon_method 12003
#define Net_Browse_method 12004
#define Net_CancelCon_method 12005
#define Net_Dialog_method 12006
#define Net_GetCaps_method 12007
#define Net_GetCon_method 12008
#define Net_User_property 12009
#define New_keyword 12010
#define Not_operator 12011
#define Now_function 12012
#define NPer_function 12013
#define Npv_function 12014
#define Object_data_type 12015
#define Objects_topic 12016
#define Oct_Oct_functions 12017
#define OKButton_statement 12018
#define On_Error_statement 12019
#define Open_statement 12020
#define OpenFilename_function 12021
#define Operator_Precedence_topic 12022
#define Operator_Precision_topic 12023
#define Option_Base_statement 12024
#define Option_Compare_statement 12025
#define Option_CStrings_statement 12026
#define Option_Default_statement 12027
#define Option_Explicit_statement 12028
#define OptionButton_statement 12029
#define OptionEnabled_function 12030
#define OptionExists_function 12031
#define OptionGroup_statement 12032
#define Or_operator 12033

/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
** Help Context Identifiers for LRP-R.HH
** Generated by RoboHELP
*/

#define Picture_statement 12501
#define PictureButton_statement 12502
#define Pmt_function 12503
#define PopupMenu_function 12504
#define PPmt_function 12505
#define Print_Pound_statement 12506
#define Print_statement 12507
#define PrinterGetOrientation_function 12508
#define PrinterSetOrientation_statement 12509
#define PrintFile_function 12510
#define Private_statement 12511
#define Public_statement 12512
#define PushButton_statement 12513
#define Put_statement 12514
#define Pv_function 12515
#define QueEmpty_statement 12516
#define QueFlush_statement 12517
#define QueKeyDn_statement 12518
#define QueKeys_statement 12519
#define QueKeyUp_statement 12520
#define QueMouseClick_statement 12521
#define QueMouseDblClk_statement 12522
#define QueMouseDblDn_statement 12523
#define QueMouseDn_statement 12524
#define QueMouseMove_statement 12525
#define QueMouseMoveBatch_statement 12526
#define QueMouseUp_statement 12527
#define QueSetRelativeWindow_statement 12528
#define Random_function 12529
#define Randomize_statement 12530
#define Rate_function 12531
#define ReadIni_function 12532
#define ReadIniSection_statement 12533
#define Redim_statement 12534
#define Rem_statement 12535
#define Reset_statement 12536
#define Resume_statement 12537
#define Return_statement 12538
#define Right_Right_RightB_RightB_functions 12539
#define RmDir_statement 12540
#define Rnd_function 12541
#define RSet_statement 12542
#define RTrim_RTrim_functions 12543


/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
** Help Context Identifiers for LRS.HH
** Generated by RoboHELP
**
*/

#define SaveFilename_function 13001
#define SaveSetting_statement 13002
#define Screen_DlgBaseUnitsX_property 13003
#define Screen_DlgBaseUnitsY_property 13004
#define Screen_Height_property 13005
#define Screen_TwipsPerPixelX_property 13006
#define Screen_TwipsPerPixelY_property 13007
#define Screen_Width_property 13008
#define Second_function 13009
#define Seek_function 13010
#define Seek_statement 13011
#define Select_Case_statement 13012
#define SelectBox_function 13013
#define SelectButton_statement 13014
#define SelectComboBoxItem_statement 13015
#define SelectListBoxItem_statement 13016
#define SendKeys_statement 13017
#define Set_statement 13018
#define SetAttr_statement 13019
#define SetCheckBox_statement 13020
#define SetEditText_statement 13021
#define SetOption_statement 13022
#define Sgn_function 13023
#define Shell_function 13024
#define Sin_function 13025
#define Single_data_type 13026
#define Sleep_statement 13027
#define Sln_function 13028
#define Space_Space_functions 13029
#define Spc_function 13030
#define SQLBind_function 13031
#define SQLClose_function 13032
#define SQLError_function 13033
#define SQLExecQuery_function 13034
#define SQLGetSchema_function 13035
#define SQLOpen_function 13036
#define SQLRequest_function 13037
#define SQLRetrieve_function 13038
#define SQLRetrieveToFile_function 13039
#define Sqr_function 13040
#define Stop_statement 13041
#define Str_Str_functions 13042
#define StrComp_function 13043
#define StrConv_function 13044
#define String_data_type 13045
#define String_String_functions 13046
#define Sub_End_Sub_statement 13047
#define Switch_function 13048
#define SYD_function 13049
#define System_Exit_method 13050
#define System_FreeMemory_property 13051
#define System_FreeResources_property 13052
#define System_MouseTrails_method 13053
#define System_Restart_method 13054
#define System_TotalMemory_property 13055
#define System_WindowsDirectory_property 13056
#define System_WindowsVersion_property 13057

/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
** Help Context Identifiers for LRT-Z.HH
** Generated by RoboHELP
** 
*/

#define Tab_function 13501
#define Tan_function 13502
#define Text_statement 13503
#define TextBox_statement 13504
#define Time_Time_functions 13505
#define Time_Time_statements 13506
#define Timer_function 13507
#define TimeSerial_function 13508
#define TimeValue_function 13509
#define Trim_Trim_LTrim_LTrim_RTrim_RTrim_functions 13510
#define Type_statement 13511
#define TypeName_function 13512
#define TypeOf_function 13513
#define UBound_function 13514
#define UCase_UCase_functions 13515
#define Unlock_statement 13516
#define User_Defined_Types_topic 13517
#define Val_function 13518
#define Variant_data_type 13519
#define VarType_function 13520
#define Viewport_Clear_method 13521
#define Viewport_Close_method 13522
#define Viewport_Open_method 13523
#define VLine_statement 13524
#define VPage_statement 13525
#define VScroll_statement 13526
#define Weekday_function 13527
#define While_Wend_statement 13528
#define Width_Pound_statement 13529
#define WinActivate_statement 13530
#define WinClose_statement 13531
#define WinFind_function 13532
#define WinList_statement 13533
#define WinMaximize_statement 13534
#define WinMinimize_statement 13535
#define WinMove_statement 13536
#define WinRestore_statement 13537
#define WinSize_statement 13538
#define Word_function 13539
#define WordCount_function 13540
#define Write_Pound_statement 13541
#define WriteIni_statement 13542
#define Xor_operator 13543
#define Year_function 13544

