//{{NO_DEPENDENCIES}}
// App Studio generated include file.
// Used by TRIAS03.RC
//
#define VER_DEBUG                       0
#define IDS_FILETEMPLATE                1
#define IMPEXPORTSTATUS                 500
#define IDD_STATUSDLG                   500
#define IDPB_STATUS                     501
#define IDT_FILENAME                    1000
#define IDT_TIMETEXT                    1001
#define IDT_TIME                        1002
#define IDT_OBJECTNUMBER                1003
#define IDT_FILE                        -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS

#define _APS_NEXT_RESOURCE_VALUE        101
#define _APS_NEXT_COMMAND_VALUE         101
#define _APS_NEXT_CONTROL_VALUE         1004
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
