#!/bin/sh

prefix=/usr/local
exec_prefix=${prefix}
exec_prefix_set=no

usage()
{
	cat <<EOF
Usage: goose-config [OPTIONS] [LIBRARIES]
Options:
	[--prefix[=DIR]]
	[--exec-prefix[=DIR]]
	[--version]
	[--libs]
	[--cflags]
Libraries:
        goose
        scm
EOF
	exit $1
}

if test $# -eq 0; then
	usage 1 1>&2
fi

lib_goose=yes

while test $# -gt 0; do
  case "$1" in
  -*=*) optarg=`echo "$1" | sed 's/[-_a-zA-Z0-9]*=//'` ;;
  *) optarg= ;;
  esac

  case $1 in
    --prefix=*)
      prefix=$optarg
      if test $exec_prefix_set = no ; then
        exec_prefix=$optarg
      fi
      ;;
    --prefix)
      echo_prefix=yes
      ;;
    --exec-prefix=*)
      exec_prefix=$optarg
      exec_prefix_set=yes
      ;;
    --exec-prefix)
      echo_exec_prefix=yes
      ;;
    --version)
      echo 0.0.10
      exit 0
      ;;
    --cflags)
      if test "${prefix}/include" != /usr/include ; then
        includes="-I${prefix}/include"
      fi
      echo_cflags=yes
      ;;
    --libs)
      echo_libs=yes
      ;;
    goose)
      lib_goose=yes
      ;;
    scm)
      lib_scm=yes;
      ;;
    *)
      usage 1 1>&2
      ;;
  esac
  shift
done

if test "$echo_prefix" = "yes"; then
	echo $prefix
fi
if test "$echo_exec_prefix" = "yes"; then
	echo $exec_prefix
fi
if test "$echo_cflags" = "yes"; then
	cflags=""
	glib_cflags=`glib-config --cflags`
	echo $includes -I$prefix/include/goose $cflags $glib_cflags 
fi
if test "$echo_libs" = "yes"; then
	libsp=""
	libsa=""
	libglib=`glib-config --libs`
	if test "$lib_goose" = "yes"; then
		libsp="$libglib -lpthread -lgoose-specfns -lgoose-util -lgoose-linear -lgoose-containers -lgoose-stats"
	fi
        if test "$lib_scm" = "yes"; then
                libsp="$libsp  -lgoose-guile"
        fi
	echo -L${exec_prefix}/lib $libsp $libsa
fi










