// Used by Percent.rc2
//
//#define IDB_PERCENT_0                   2048
#define IDB_PERCENT_5                   2048
#define IDB_PERCENT_10                  2049
#define IDB_PERCENT_20                  2050
#define IDB_PERCENT_25                  2051
#define IDB_PERCENT_30                  2052
#define IDB_PERCENT_40                  2053
#define IDB_PERCENT_50                  2054
#define IDB_PERCENT_60                  2055
#define IDB_PERCENT_70                  2056
#define IDB_PERCENT_75                  2057
#define IDB_PERCENT_80                  2058
#define IDB_PERCENT_90                  2059
//#define IDB_PERCENT_100                 2061

