# gui/Makefile
# Copyright (c) 1998, Regents of the University of California
# $Id: Makefile,v 1.1 1999/06/21 00:34:22 marcel Exp $

include ../Makefile.inc

SRCS = 	TreeView.java Node.java NodeDump.java SuperNode.java \
	TreeDisplay.java TreeDisplayUI.java NodePanel.java NodeView.java \
	GlobalView.java PaintScale.java PredInfoPack.java

CLASSES = $(SRCS:.java=.class)

all: $(CLASSES)

clean:
	$(RM) *.class

cleanmake:

depend:

# DO NOT DELETE THIS LINE -- make depend depends on it.
