//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by MapMgr.rc
//
#define IDR_MENUMAPIMPORT               1
#define ID_MAPIMPORT                    2
#define IDR_PICTHOLDER                  101
#define IDR_MAPIMPORT                   128
#define IDS_PROJNAME                    129
#define IDB_LUFTBILD                    150
#define IDC_EDITSRCMAP                  1007
#define IDC_PROGRESSIMPORT              1010
#define IDC_BUTTONSTART                 1011
#define IDC_PROGRESSMESSAGE             1013
#define IDC_PROGRESSCHUNK               1014
#define IDC_COMBOPOINTSCHEMA            1020
#define IDC_BUTTONDEFCS                 1021
#define IDC_P0X                         1026
#define IDC_P0Y                         1027
#define IDC_P1X                         1028
#define IDC_P1Y                         1029
#define IDC_TRIASCSUI1                  1030
#define IDC_TRANSFORMMATRIX             1033
#define IDC_ORIGX                       1034
#define IDC_ORIGY                       1035
#define IDC_ORIGZ                       1036
#define IDC_COMBO_SCALE                 1037
#define IDC_TREEOFENGINES               1039
#define IDC_EDITNAME                    1040
#define IDC_BUTTONNAME                  1041
#define IDC_DESCRIPTION                 1042
#define IDC_BUTTONNAME2                 1042
#define IDC_BUTTONAUSGABE               1043
#define IDC_LISTGCPS                    1044
#define IDC_EDITDIR                     1045
#define IDC_BUTTONSELDIR                1046
#define IDC_EDITAUSGABE                 1049
#define IDC_FILEDESCRIPTION             1050
#define IDC_CHECKASCIIFILE              1051
#define IDC_SELSOURCE                   1055
#define IDC_SELDESTINATION              1056
#define IDC_SELREFFILES                 1057
#define IDC_STATIC_DESTINATION          1058
#define IDC_STATIC_ALTFILES             1059
#define IDC_STATIC_FILESORDIR           1060
#define IDC_SELECTDATASOURCE            1063
#define IDS_UNIQUEIDENT                 18000
#define IDD_PPGSELMAPTYPE               18001
#define IDS_OBJNAME                     18001
#define IDD_PPGMAPINFO                  18002
#define IDS_TKINFO                      18002
#define IDD_PPGIMPORTFILE               18003
#define IDS_OBJKLASSE                   18003
#define IDD_PPGREFPOINTS                18004
#define IDS_UIDCODE                     18004
#define IDD_PPGSELADDFILE               18005
#define IDS_OBJNAMECODE                 18005
#define IDD_PPGNOMENCLATUR              18006
#define IDS_TKINFOCODE                  18006
#define IDD_PPGSELDOCFILE               18007
#define IDS_OKLKEY                      18007
#define IDS_MYINISECTION                18008
#define IDS_MAPDIRENTRY                 18009
#define IDS_INDICATORCAPTION            18010
#define IDS_INDICATORSTATUS             18011
#define IDS_INDICATORTAGS               18012
#define IDS_INDICATORDOC                18013
#define IDS_SETCOORDINATE               18014
#define IDS_MAPREDUCE                   18015
#define IDS_STOREMAP                    18016
#define IDS_STOPPMAPS                   18017
#define IDS_VIEWNAME                    18017
#define IDS_NOMAP                       18018
#define IDS_HARDERROR                   18019
#define IDS_NOMAPDOC                    18020
#define IDS_NOMAPTYPE                   18021
#define IDS_NOMAPINIT                   18022
#define IDS_OPENFILETITLE               18023
#define IDS_SELECTDIRTITLE              18024
#define IDS_MAPIMPORTCAPTION            18025
#define IDS_ERRORREDUCEMAP              18026
#define IDS_ERRORACCESSDENIED           18027
#define IDS_ERRORDISKFULL               18028
#define IDS_ERRORCOPYFILE               18029
#define IDS_IMPORTNAME                  18030
#define IDS_DISPLAYPROTOCOL             18031
#define IDS_IMPORTMENU                  18032
#define IDS_NOMAPNAME                   18033
#define IDS_MAPREDUCETITLE              18034
#define IDB_MAPTYPES                    18035
#define IDS_SELECTDIRTITLE_SRC          18035
#define IDB_BITMAP_TRIAS                18036
#define IDS_SELECTDIRTITLE_ALT          18036
#define IDD_PPGINTERGRAPH               18037
#define IDS_DDX_GF_EDIT_TEXT            18037
#define IDR_MAINFRAME                   18038
#define IDD_PPGSELDIRECTORIES           18038
#define IDS_DDX_GFLDR_TT_MODIFY         18038
#define IDD_PPGSELFILES                 18039
#define IDS_DDX_GF_TT_MODIFY            18039
#define IDS_DDX_GF_OK                   18040
#define IDD_PPGSELDATASOURCE            18040
#define IDS_DDX_GF_OVERWRITE_PROMPT     18041
#define IDS_ALTFILEPROMPT               18042
#define IDS_SRCDIRECTORY                18043
#define IDS_SRCFILES                    18044
#define IDS_NOMAP_MULTI                 18045
#define IDS_NOMAP_DIR                   18046
#define IDB_PROJECTTYPES                18047
#define IDB_PROJECTTYPES_MASK           18048
#define IDC_COORDSYSTEMS                18049
#define IDC_COORDDESCRIPTION            18050
#define IDC_DESCTEXT                    18051
#define IDD_SELECT_COORDSYS             18052
#define IDB_COORDSYSTEM                 18053
#define IDS_DISPLAYNAME_ARC             25000
#define IDS_DISPLAYNAME_FK              25001
#define IDS_DISPLAYNAME_BRB             25002
#define IDS_DISPLAYNAME_REF             25003
#define IDS_DISPLAYNAME_SAL             25004
#define IDS_DISPLAYFILTER_ARC           25100
#define IDS_DISPLAYFILTER_BRB           25102
#define IDS_DISPLAYFILTER_SAL           25104

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        18054
#define _APS_NEXT_COMMAND_VALUE         32772
#define _APS_NEXT_CONTROL_VALUE         1064
#define _APS_NEXT_SYMED_VALUE           102
#endif
#endif
