// GUID für die Linienverfolgung
// File: LINVGUID.H
// Erarbeitet: J. Benkenstein                             Stand vom 12.9.1996

#ifndef _LINVGUID_H
#define _LINVGUID_H

// 079638D9-3123-101C-BB62-00AA0018497C	
DEFINE_GUID(LIBID_LinienVerfolgung, 0x079638D9L, 0x3123, 0x101C, 0xBB, 0x62, 0x00, 0xAA, 0x00, 0x18, 0x49, 0x7C);

// ED9655E6-3122-101C-BB62-00AA0018497C	
DEFINE_GUID(CLSID_LinienVerfolgung, 0xED9655E6L, 0x3122, 0x101C, 0xBB, 0x62, 0x00, 0xAA, 0x00, 0x18, 0x49, 0x7C);

#endif          // _LINVGUID_H




