//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by bnaimp.rc
//
#define IDD_STATUSDLG                   101
#define IDD_RESULTDLG                   102
#define IDI_BNAIMP                      103
#define IDT_TEXTS                       104
#define IDD_CONFIGDLG                   104
#define IDT_POINTS                      105
#define IDD_CLASSDLG                    105
#define IDB_PLFT_LARGE                  105
#define IDT_LINES                       106
#define IDR_BNAIMPORTCONFIG_REG         106
#define IDT_AREAS                       107
#define IDD_ASSOCIATE_LAYERS            107
#define IDT_IMPORTED                    108
#define IDD_PROGRESSBAR                 108
#define IDT_TIME                        109
#define IDT_KOMPLEX                     110
#define IDT_NOTIMPORTED                 111
#define IDT_WITHERRORS                  112
#define IDR_POLYGISFEATURE_REG          113
#define IDR_DATIMPORTCONFIG_REG         114
#define IDPB_STATUS                     1000
#define IDT_PERCENT                     1001
#define IDT_FILENAME                    1002
#define IDC_DEFINENEW                   1003
#define IDC_OBJECTNUMBER                1004
#define IDC_ASSOCIATE                   1004
#define IDT_TIMETEXT                    1005
#define IDC_NAME1                       1006
#define IDC_COPYCLASS                   1006
#define IDC_NAME2                       1007
#define IDC_ID                          1008
#define IDC_OFFSETX                     1009
#define IDC_OFFSETY                     1011
#define IDC_SKALIERUNG                  1012
#define IDC_BNALIST                     1013
#define IDC_CONTROLLIST                 1014
#define IDC_LAYERS_AND_CLASSES          1018
#define IDT_FILESPROMPT                 1021
#define IDPB_FILES_STATUS               1022
#define IDC_ANIMATE_SEARCH              2000
#define IDR_ANI_SEARCH                  2000
#define IDS_LONGCLASSNAME               26001
#define IDS_FORMATDESCRIPTION           26002
#define IDS_DEFAULTEXTENSION            26003
#define IDS_PARSERERRORCAP              26004
#define IDS_PARSERERROR                 26005
#define IDS_FILETEMPLATE                26006
#define IDS_PERCENTTEMPLATE             26007
#define IDS_OBJECTNUMBERTEMPLATE        26008
#define IDS_IMPORTHEADER                26009
#define IDS_POLYNAME1                   26010
#define IDS_POLYNAME2                   26011
#define IDS_POLYID                      26012
#define IDS_BNAKEYNAME1                 26013
#define IDS_BNAKEYNAME2                 26014
#define IDS_BNAKEYID                    26015
#define IDS_BNASTRASSENSCHLUESSEL       26016
#define IDS_BNASTRASSENNAME             26017
#define IDS_BNAORTSTEIL                 26018
#define IDS_BNAKEYSUFFIX                26019
#define IDS_POLYSUFFIX                  26020
#define IDS_BNAKEYORDNUNG               26021
#define IDS_STRASSENORDNUNG             26022
#define IDS_BNAKEYMEMO                  26023
#define IDS_MEMOKLASSE                  26024
#define IDS_BNAMEMO                     26025
#define IDS_KEYMEMOKLASSE               26026
#define IDS_PROJEKTLAYER                26027
#define IDS_STANDARDDEFINITION          26028
#define IDS_STANDARDKLASSEN             26029
#define IDS_MEMOKLASSEN                 26030
#define IDS_STANDARD                    26031
#define IDS_IMPORT                      26032
#define IDS_EXPORT                      26033
#define IDS_BNALAYER                    26034
#define IDS_BNALAYERNAME1               26035
#define IDS_BNALAYERNAME2               26036
#define IDS_BNALAYERID                  26037
#define IDS_BNALAYERLAYER               26038
#define IDS_ASSOCIATE_LAYERS_CAP        26039
#define IDS_FILES_PROMPT                26040
#define IDS_HEADERTYP                   26041
#define IDS_HEADERLAYER                 26042
#define IDS_HEADERCLASS                 26043
#define IDS_HEADERIMPORT                26044
#define IDS_NEWITEM                     26045
#define IDS_KEYMEMOKLASSEREPLACE        26046
#define IDS_BNAITEM                     26047
#define IDS_NEXTEXTENSION               26048
#define IDS_NEXTFORMAT                  26049
#define IDS_NEXTCLASSNAME               26050
#define IDS_DATIMPORTGCO                26051
#define IDS_GPSEXTENSION                26052
#define IDS_GPSFORMAT                   26053
#define IDS_GPSCLASSNAME                26054
#define IDS_IMPORTSTANDARDDAT           26055
#define IDS_IMPORTPUNKTDAT              26056
#define IDS_DATKEY01                    26057
#define IDS_DATKEY02                    26058
#define IDS_DATKEY03                    26059
#define IDS_GCAEXTENSION                26060
#define IDS_GCAFORMAT                   26061
#define IDS_GCACLASSNAME                26062
#define IDS_GCACODE                     26063
#define IDS_GCASTRASSE                  26064
#define IDS_GCAHAUSNUMMER               26065
#define IDS_GCAHAUSNRZUSATZ             26066
#define IDS_GCABISHAUSNR                26067
#define IDS_GCABISHAUSNRZUSATZ          26068
#define IDS_GCAPLZ                      26069
#define IDS_GCAORT                      26070
#define IDS_GCAORTSTEIL                 26071

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        108
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1025
#define _APS_NEXT_SYMED_VALUE           102
#endif
#endif
