//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Objoper.rc
//
#define IDM_OPERATMENU                  30
#define IDM_OPERATIONEN                 31
#define IDM_OPLOESCHEN                  32
#define IDM_OPORIGLOESCHEN              33
#define IDR_REGOPERATPROPACT            111
#define IDR_LINESPLITPROPACT            112
#define IDR_SETSOPERATPROPACT           113
#define IDR_AREABUILDROPACT             114
#define IDR_OPTIONSPROPACT              115
#define IDR_OBJEKTEVEREINIGEN           116
#define IDR_SCRIPT_UNIONOBJECTS         117
#define IDR_SCRIPT_BLINKEL              118
#define IDB_INTER                       119
#define IDB_EXTER                       120
#define IDB_BOUND                       121
#define IDB_OR                          122
#define IDB_AND                         123
#define IDB_XOR                         124
#define IDD_REGOPERATPROPACT            1000
#define IDC_CLASSKEY                    1001
#define IDT_LOCATION                    1002
#define IDC_INTER                       1003
#define IDC_EXTER                       1004
#define IDC_BOUND                       1005
#define IDP_INTER                       1006
#define IDP_EXTER                       1007
#define IDP_BOUND                       1008
#define IDT_REGDESCRIPT                 1009
#define IDD_SETSOPERATPROPACT           1100
#define IDC_OROPERAT                    1101
#define IDC_ANDOPERAT                   1102
#define IDC_XOROPERAT                   1103
#define IDP_OR                          1104
#define IDP_AND                         1105
#define IDP_XOR                         1106
#define IDT_FUZZY1                      1107
#define IDE_FUZZY1                      1108
#define IDT_SETSDESCRIPT                1109
#define IDD_LINESPLITPROPACT            1200
#define IDT_FUZZY2                      1201
#define IDE_FUZZY2                      1202
#define IDT_DANGLE                      1203
#define IDE_DANGLE                      1204
#define IDT_LINEDESCRIPT                1205
#define IDD_AREABUILDPROPACT            1300
#define IDC_LINESUNION                  1301
#define IDT_FUZZY3                      1302
#define IDE_FUZZY3                      1303
#define IDT_AREADESCRIPT                1304
#define IDD_OPTIONSPROPACT              1400
#define IDC_FEATFROMORIGIN              1401
#define IDC_ORIGINDEL                   1402
#define IDC_ORIGINMARK                  1403
#define IDC_SHOWNEW                     1404
#define IDC_SHOWORIG                    1405
#define IDT_OPTDESCRIPT                 1406
#define IDS_LONGCLASSNAME               2000
#define IDS_GEOREIN                     2001
#define IDS_NEUEOBJ                     2002
#define IDS_ALTEOBJ                     2003
#define IDS_BOXTEXT1                    2004
#define IDS_BOXTEXT2                    2005
#define IDS_BOXTEXT3                    2006
#define IDS_BOXTEXT4                    2007
#define IDS_BOXTEXT5                    2008
#define IDS_BOXTEXT6                    2009
#define IDS_BOXTEXT7                    2010
#define IDS_KOMM1                       2011
#define IDS_KOMM2                       2012
#define IDS_KOMM3                       2013
#define IDS_KOMM4                       2014
#define IDS_KOMM5                       2015
#define IDS_KOMM6                       2016
#define IDS_KOMM7                       2017
#define IDS_KOMM8                       2018
#define IDS_KOMM9                       2019
#define IDS_KOMM10                      2020
#define IDS_KOMM11                      2021
#define IDS_KOMM12                      2022
#define IDS_KOMM13                      2023
#define IDS_KOMM14                      2024
#define IDS_KOMM15                      2025
#define IDS_KOMM16                      2026
#define IDS_KOMM17                      2027
#define IDS_KOMM18                      2028
#define IDS_KOMM19                      2029
#define IDS_KOMM20                      2030
#define IDS_KOMM21                      2031
#define IDS_KOMM22                      2032
#define IDS_KOMM23                      2033
#define IDS_KOMM24                      2034
#define IDS_KOMM25                      2035
#define IDS_KOMM26                      2036
#define IDS_KOMM27                      2037
#define IDS_KOMM28                      2038
#define IDS_GEOFEHL1                    2039
#define IDS_GEOFEHL2                    2040
#define IDS_SCHNITT_CAPTION             2041
#define IDS_DURCHSCHNITT_CAPTION        2042
#define IDS_VEREINIGUNG_CAPTION         2043
#define IDS_EXKLUSIVODER_CAPTION        2044
#define IDS_GEMKONTUR_CAPTION           2045
#define IDS_VERSCHNITT_CAPTION          2046
#define IDS_BEARB_OBJEKT                2047
#define IDS_STATUS_STAND                2048
#define IDS_DELOBJECTS                  2049
#define IDS_DELETE_STATUS               2050
#define IDS_NOMASCHBLD                  2051
#define IDS_TOLERANZ                    2052
#define IDS_SHIFTEDLINE                 2053
#define IDS_REGADCAPT                   2054
#define IDS_HELPINFO_REGOPERAT          2055
#define IDS_SETSCAPT                    2056
#define IDS_HELPINFO_SETSOPERAT         2057
#define IDS_SPLITCAPT                   2058
#define IDS_HELPINFO_LINESPLIT          2059
#define IDS_AREACAPT                    2060
#define IDS_HELPINFO_AREABUILD          2061
#define IDS_OPTIONSCAPT                 2062
#define IDS_HELPINFO_OPTIONS            2063
#define IDS_MARK_OBJECT                 2064
#define IDS_NOGEOREIN                   2065
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        148
#define _APS_NEXT_COMMAND_VALUE         40002
#define _APS_NEXT_CONTROL_VALUE         1029
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
