/*
@doc

@contents1 Inhaltsverzeichnis | Um eine Liste der Kapitel nach
ihrer Kategorie anzuzeigen, müssen Sie auf einen der folgenden Kapiteleinträge
klicken. Um eine alphabetische Liste der Kapitel anzuzeigen, wählen Sie die Index - 
Schaltfläche.

@head3 COM Elemente |

@subindex Objekte
@subindex Objektinterfaces
@subindex Notifikationsinterfaces

@head3 C/C++ Elemente |

@subindex Klassen and Klassenmember
@subindex Funktionen
@subindex Messages
@subindex Strukturen und Enums

@head3 Sonstiges |

@subindex Übersichten
@subindex Module
@subindex Konstanten

@normal Diese Hilfedatei wurde erzeugt am: <date>

@subindex Über diese Hilfedatei

@head3 Was sonst noch zu bemerken wäre ... | Creating unrealistic customer 
expectations about schedule, cost, or 
functionality for any reason - to get a controversial project approved,
to get adequate funding for a project, to be the low bidder, whatever - 
creates a virtually insurmountable risk to any project. Software projects
have a hard enough time performing to middle-of-the-road expectations.
Creating inflated expectations sets up a situation in which the project 
will look like it's in trouble even when it's going smoothly. With inflated
expectations, developers look like losers even when we do a good job. 
People who inflate expectations damage their credibility, and they undermine 
their working relationships with their customers. People who overpromise
might have an easier time initially, but they will have a rougher time in 
the long run. Therefore, part of the developer's job is to set realistic 
expectations.
<nl>Steve McConnell, Rapid Development: taming wild software schedules,
Microsoft Press 1996, ISBN 1-55615-900-5, page 245.<nl><nl>

***********************************************************************
@contents2 Objekte |
@normal Objekte der TRiASDB-Schnittstelle
@index object | (OBJECT & TRIASDB) 
@normal Zusätzliche Rechercheobjekte
@index object | (OBJECT & TRIASQUERYDEF)
@normal Hilfsobjekte
@index interface | (OBJECT & HELPER)

***********************************************************************
@contents2 Objektinterfaces |
@normal Objektinterfaces der TRiASDB-Schnittstelle
@index interface | (INTERFACE & TRIASDB)
@normal Objektinterfaces, spezifisch für eine <tr>-Datenbank
@index interface | (INTERFACE & TRIASGEODB)
@normal Objektinterfaces, spezifisch für diverse Recherchen
@index interface | (INTERFACE & TRIASQUERYDEF)
@normal Objektinterfaces von Hilfsobjekten
@index interface | (INTERFACE & HELPER)

***********************************************************************
@contents2 Notifikationsinterfaces |
@index interface | EVENTINTERFACE

***********************************************************************
@contents2 Klassen and Klassenmember |
@index class,mfunc,mdata |

***********************************************************************
@contents2 Funktionen |
@index func,cb |

***********************************************************************
@contents2 Messages |
@index msg |

***********************************************************************
@contents2 Strukturen und Enums |
@index struct,enum |

***********************************************************************
@contents2 Übersichten |
@index topic |

***********************************************************************
@contents2 Module |
@index module |

***********************************************************************
@contents2 Konstanten |
@index const, constv |

***********************************************************************
@contents2 Über diese Hilfedatei | 

Copyright<csign> 1991-2000 <company>, #<copyright> V<version>
<nl>For more information about TRiASDB, contact Hartmut Kaiser (H.Kaiser@intertrias.com)

<nl><nl>The sources for this Help file were generated
by Autoduck, the source code documentation tool that generates Print or
Help files from tagged comments in C, C++, Assembly, and Basic source
files.

<nl>For more information about Autoduck, contact Eric Artzt (erica@microsoft.com).
*/

