// Fehlernummern
// File: BCLERROR.H

#if !defined(_BCLERROR_H)
#define _BCLERROR_H

#define BCL_FATAL_NOINPUTFILE		1001
#define BCL_FATAL_COULDNTPRINTLOGO	1002
#define BCL_FATAL_COULDNTINITBASIC	1003

#define BCL_ERROR_FILENOTFOUND		2006
#define BCL_ERROR_STATFAILED		2007
#define BCL_ERROR_READERROR			2008
#define BCL_ERROR_COMPILERERROR		2009
#define BCL_ERROR_CANTCREATEOUTPUT	2010

#define BCL_MESSAGE_NOINISECTION	4001

#define BCL_CMDLINEERROR_BADDEFINE	5001
#define BCL_CMDLINEERROR_NOINPUTFILE	5002
#define BCL_CMDLINEERROR_BADUNDEFINE	5003
#define BCL_CMDLINEERROR_NOCONFIGFILE	5004

#endif // _BCLERROR_H
