#define UNDEFINEDIDENT              104
#define IDB_DEFIDERRHELP            1040
#define IDB_DEFIDERRIGNORE          1041
#define IDT_DEFIDERRTEXT            1042
#define IDB_DEFIDERRALLIGNORE       1043
#define UNDEFINEDMERKMAL            108
#define IDB_DEFMKERRIGNORE          1046
#define IDB_DEFMKERRALLIGNORE       1044
#define IDB_DEFMKERRHELP            1045
#define IDT_DEFMKERRTEXT            1047
#define UNDEFINEDRELATION           112
#define IDB_DEFRELERRHELP           1050
#define IDB_DEFRELERRIGNORE         1051
#define IDB_DEFRELERRALLIGNORE      1052
#define IDT_DEFRELERRTEXT           1054
#define IDF_IERRORLOGO              1055
#define IDF_MERRORLOGO              1056
#define IDF_RERRORLOGO              1057
