#define DEFINEIDENT                 100
#define IDT_DEFIDDBNAME             1000
#define IDE_DEFIDSHORT              1002
#define IDE_DEFIDLONG               1003
#define IDB_DEFIDHELP               1004
#define DEFINEMERKMAL               101
#define IDT_DEFMKDBNAME             1011
#define IDR_DEFMKTEXT               1012
#define IDR_DEFMKINT                1013
#define IDR_DEFMKFLOAT              1014
#define IDE_DEFMKMAXLEN             1015
#define IDE_DEFMKSHORT              1016
#define IDE_DEFMKLONG               1017
#define IDB_DEFMKHELP               1018
#define DEFINERELATION              102
#define IDR_DEFRELHORIZ             1021
#define IDR_DEFRELKOMPLEX           1022
#define IDE_DEFRELSHORT             1023
#define IDE_DEFRELLONG              1024
#define IDB_DEFRELHELP              1025
#define IDT_DEFRELRCODE             1020
#define IDT_DEFMKMCODE              1010
#define IDT_DEFIDIDENT              1001
#define IDR_OBJMERKMAL              1026
#define IDR_IDENTMERKMAL            1027
#define IDR_SICHTMERKMAL            1028
#define IDT_DEFRELDBNAME            1029
#define IDCB_SYSTEMFLAG             1030
