#define DEFINERELATIONDLG           113
#define DELRELATIONDLG              114
#define IDB_NEWRELHELP              1130
#define IDL_NEWRELLIST              1131
#define IDB_DELRELUNUSED            1132
#define IDE_DELRELRCODE             1133
#define IDL_DELRELLIST              1134
#define IDB_DELRELHELP              1135
#define IDB_DELRELDELETE            1136
#define IDE_NEWRELRCODE             1138
#define IDB_DELRELRESTORE           1140
