[MSVC Status File]
Version=1.00
ProjectType=12
External=1
DebugBuildCmd=NMAKE /f MAKEFILE
ReleaseBuildCmd=NMAKE /f MAKEFILE
RebuildOption=/a
BuildMode=1
TargetName=C:\TRIASDEV.MVC\TRIAS02\all
BrkptCount=0
WatchCount=0
