Attribute VB_Name = "OcxAnn"

' Annotation   object types

Global Const ANNOBJECT_CONTAINER = 0
Global Const ANNOBJECT_POINTER = 1
Global Const ANNOBJECT_AUDIO = 2
Global Const ANNOBJECT_BUTTON = 3
Global Const ANNOBJECT_ELLIPSE = 4
Global Const ANNOBJECT_FREEHAND = 5
Global Const ANNOBJECT_HILITE = 6
Global Const ANNOBJECT_HOTSPOT = 7
Global Const ANNOBJECT_LINE = 8
Global Const ANNOBJECT_NOTE = 9
Global Const ANNOBJECT_POLYGON = 10
Global Const ANNOBJECT_POLYLINE = 11
Global Const ANNOBJECT_RECT = 12
Global Const ANNOBJECT_REDACT = 13
Global Const ANNOBJECT_STAMP = 14
Global Const ANNOBJECT_TEXT = 15
Global Const ANNOBJECT_AUTOMATION = 16
Global Const ANNOBJECT_RULER = 17
Global Const ANNOBJECT_CROSSPRODUCT = 18
Global Const ANNOBJECT_POINT = 19
Global Const ANNOBJECT_PROTRACTOR = 20
Global Const ANNOBJECT_VIDEO = 21
Global Const ANNOBJECT_PUSHPIN = 22
Global Const ANNOBJECT_FREEHANDHOTSPOT = 23

' Annotation save/clipboard formats

Global Const ANNFMT_NATIVE = 0
Global Const ANNFMT_WMF = 1
Global Const ANNFMT_TIFFTAG = 2     ' Save all Lead info
Global Const ANNFMT_WANGTAG = 3     ' Wang annotation compatibility mode
Global Const ANNFMT_ENCODED = 4     ' Encoded native format (better security, smaller file size)

' Annotation toolbar buttons

Global Const ANNTOOL_SELECT = 0
Global Const ANNTOOL_LINE = 1
Global Const ANNTOOL_RECT = 2
Global Const ANNTOOL_ELLIPSE = 3
Global Const ANNTOOL_POLYLINE = 4
Global Const ANNTOOL_POLYGON = 5
Global Const ANNTOOL_POINTER = 6
Global Const ANNTOOL_FREEHAND = 7
Global Const ANNTOOL_HILITE = 8
Global Const ANNTOOL_REDACT = 9
Global Const ANNTOOL_TEXT = 10
Global Const ANNTOOL_NOTE = 11
Global Const ANNTOOL_STAMP = 12
Global Const ANNTOOL_BUTTON = 13
Global Const ANNTOOL_HOTSPOT = 14
Global Const ANNTOOL_AUDIO = 15
Global Const ANNTOOL_RULER = 16
Global Const ANNTOOL_CROSSPRODUCT = 17
Global Const ANNTOOL_POINT = 18
Global Const ANNTOOL_PROTRACTOR = 19
Global Const ANNTOOL_VIDEO = 20
Global Const ANNTOOL_PUSHPIN = 21
Global Const ANNTOOL_FREEHANDHOTSPOT = 22

Global Const ANNTOOL_STAMP_FIRST = 23        ' define that marks the first rubber stamp
Global Const ANNTOOL_STAMP_APPROVED = 23
Global Const ANNTOOL_STAMP_ASSIGNED = 24
Global Const ANNTOOL_STAMP_CHECKED = 25
Global Const ANNTOOL_STAMP_CLATPRV = 26
Global Const ANNTOOL_STAMP_COPY = 27
Global Const ANNTOOL_STAMP_DRAFT = 28
Global Const ANNTOOL_STAMP_EXTENDED = 29
Global Const ANNTOOL_STAMP_FAX = 30
Global Const ANNTOOL_STAMP_FAXED = 31
Global Const ANNTOOL_STAMP_IMPORTANT = 32
Global Const ANNTOOL_STAMP_INVOICE = 33
Global Const ANNTOOL_STAMP_NOTICE = 34
Global Const ANNTOOL_STAMP_OFFICIAL = 35
Global Const ANNTOOL_STAMP_ONFILE = 36
Global Const ANNTOOL_STAMP_PAID = 37
Global Const ANNTOOL_STAMP_PASSED = 38
Global Const ANNTOOL_STAMP_PENDING = 39
Global Const ANNTOOL_STAMP_PROCESSED = 40
Global Const ANNTOOL_STAMP_RECEIVED = 41
Global Const ANNTOOL_STAMP_REJECTED = 42
Global Const ANNTOOL_STAMP_RELEASE = 43
Global Const ANNTOOL_STAMP_SENT = 44
Global Const ANNTOOL_STAMP_SHIPPED = 45
Global Const ANNTOOL_STAMP_TOPSECRET = 46
Global Const ANNTOOL_STAMP_URGENT = 47
Global Const ANNTOOL_STAMP_VOID = 48
Global Const ANNTOOL_STAMP_LAST = 48       ' define that marks the last rubber stamp

Global Const ANNTOOL_LAST = 48

Global Const ANNTOOL_USER = &H100             ' first user defined tool
Global Const ANNTOOL_USERLAST = &H200         ' last allowed user tools

Global Const ANNBUTTON_MULTIPLE = &H1         ' if this flag is set, then the pButtonArray defines the button

' Annotation generated messages

Global Const WM_USER = &H400
Global Const WM_LTANNEVENT = (WM_USER + 512)
Global Const WM_LTANNHYPERLINK = (WM_USER + 513)   ' message used internally by LEADTOOLS ActiveX

'   width and height of the toolbar bitmaps
Global Const TOOLBARIMAGECX = 16
Global Const TOOLBARIMAGECY = 15

'   width and height of the toolbar buttons
Global Const TOOLBARBUTTONCX = 24
Global Const TOOLBARBUTTONCY = 22


' Messages generated by annotation toolbar
'   wParam = event id
'   lParam = specific event data

Global Const LTANNEVENT_TOOLCHECKED = 0
Global Const LTANNEVENT_TOOLCREATE = 1
Global Const LTANNEVENT_TOOLDESTROY = 2
Global Const LTANNEVENT_ACTIVATE = 3
Global Const LTANNEVENT_DEACTIVATE = 4
Global Const LTANNEVENT_INSERT = 5
Global Const LTANNEVENT_REMOVE = 6
Global Const LTANNEVENT_AUTOBEGINSET = 7
Global Const LTANNEVENT_AUTOENDSET = 8
Global Const LTANNEVENT_AUTOCLICKED = 9
Global Const LTANNEVENT_AUTOCHANGED = 10
Global Const LTANNEVENT_AUTOITEMCHANGED = 11
Global Const LTANNEVENT_AUTOSELECT = 12
Global Const LTANNEVENT_LOCKED = 13
Global Const LTANNEVENT_UNLOCKED = 14
Global Const LTANNEVENT_HYPERLINK = 15
Global Const LTANNEVENT_HYPERLINKMENU = 16
Global Const LTANNEVENT_LBUTTONDOWN = 17
Global Const LTANNEVENT_MOUSEMOVE = 18
Global Const LTANNEVENT_LBUTTONUP = 19
Global Const LTANNEVENT_MENU = 20
Global Const LTANNEVENT_AUTOITEMCHANGING = 21

'   allowed range for user defined menus
Global Const LTANNEVENT_MENUFIRST = &H100
Global Const LTANNEVENT_MENULAST = &H1FF

' Annotation line styles

Global Const ANNLINE_SOLID = 0
Global Const ANNLINE_DASH = 1
Global Const ANNLINE_DOT = 2
Global Const ANNLINE_DASHDOT = 3
Global Const ANNLINE_DASHDOTDOT = 4
Global Const ANNLINE_NULL = 5

' Annotation fill patterns

Global Const ANNPATTERN_SOLID = 0
Global Const ANNPATTERN_BDIAGONAL = 1
Global Const ANNPATTERN_CROSS = 2
Global Const ANNPATTERN_DIAGCROSS = 3
Global Const ANNPATTERN_FDIAGONAL = 4
Global Const ANNPATTERN_HORIZONTAL = 5
Global Const ANNPATTERN_VERTICAL = 6

' Annotation fill mode

Global Const ANNMODE_TRANSPARENT = 0
Global Const ANNMODE_TRANSLUCENT = 1
Global Const ANNMODE_OPAQUE = 2

' Annotation poly fill mode

Global Const ANNPOLYFILL_WINDING = 0
Global Const ANNPOLYFILL_ALTERNATE = 1

' Annotation define states

Global Const ANNDEFINE_BEGINSET = 0
Global Const ANNDEFINE_BEGINMOVE = 1
Global Const ANNDEFINE_BEGINROTATE = 2
Global Const ANNDEFINE_BEGINRESIZE = 3
Global Const ANNDEFINE_BEGINSELECT = 4
Global Const ANNDEFINE_APPEND = 5
Global Const ANNDEFINE_UPDATE = 6
Global Const ANNDEFINE_END = 7
Global Const ANNDEFINE_BEGINMOVESELECTED = 8
Global Const ANNDEFINE_BEGINROTATESELECTED = 9
Global Const ANNDEFINE_BEGINRESIZESELECTED = 10
Global Const ANNDEFINE_BEGINMOVEPOINT = 11
Global Const ANNDEFINE_BEGINMOVENAME = 12

' Annotation active states

Global Const ANNACTIVE_DISABLED = 0
Global Const ANNACTIVE_ENABLED = 1

' Annotation hittest results

Global Const ANNHIT_NONE = 0
Global Const ANNHIT_BODY = 1
Global Const ANNHIT_HANDLE = 2
Global Const ANNHIT_NAME = 3

' Annotation user modes

Global Const ANNUSER_NONE = 0
Global Const ANNUSER_DESIGN = 1
Global Const ANNUSER_RUN = 2

' Annotation flags for set functions

Global Const ANNFLAG_SELECTED = &H1
Global Const ANNFLAG_NOTCONTAINER = &H2
Global Const ANNFLAG_NOTTHIS = &H4
Global Const ANNFLAG_RECURSE = &H8
Global Const ANNFLAG_NOINVALIDATE = &H10
Global Const ANNFLAG_CHECKMENU = &H20
Global Const ANNFLAG_USER = &H40

'   Angle units
Global Const ANNANGLE_DEGREES = 0
Global Const ANNANGLE_RADIANS = 1

'   Metafile types
Global Const ANNMETAFILE_USER = &H7FFF        ' user-defined metafiles
Global Const ANNMETAFILE_APPROVED = 0         ' predefined metafiles
Global Const ANNMETAFILE_ASSIGNED = 1
Global Const ANNMETAFILE_CHECKED = 2
Global Const ANNMETAFILE_CLATPRV = 3
Global Const ANNMETAFILE_COPY = 4
Global Const ANNMETAFILE_DRAFT = 5
Global Const ANNMETAFILE_EXTENDED = 6
Global Const ANNMETAFILE_FAX = 7
Global Const ANNMETAFILE_FAXED = 8
Global Const ANNMETAFILE_IMPORTANT = 9
Global Const ANNMETAFILE_INVOICE = 10
Global Const ANNMETAFILE_NOTICE = 11
Global Const ANNMETAFILE_OFFICIAL = 12
Global Const ANNMETAFILE_ONFILE = 13
Global Const ANNMETAFILE_PAID = 14
Global Const ANNMETAFILE_PASSED = 15
Global Const ANNMETAFILE_PENDING = 16
Global Const ANNMETAFILE_PROCESSED = 17
Global Const ANNMETAFILE_RECEIVED = 18
Global Const ANNMETAFILE_REJECTED = 19
Global Const ANNMETAFILE_RELEASE = 20
Global Const ANNMETAFILE_SENT = 21
Global Const ANNMETAFILE_SHIPPED = 22
Global Const ANNMETAFILE_TOPSECRET = 23
Global Const ANNMETAFILE_URGENT = 24
Global Const ANNMETAFILE_VOID = 25
Global Const ANNMETAFILE_HOTSPOT = 26
Global Const ANNMETAFILE_LAST = 26           ' last predefined metafile

'   Show flags
Global Const ANNSHOW_LENGTH = &H1
Global Const ANNSHOW_GAUGE = &H2


'   automation option flags
Global Const ANNAUTO_TABBEDDIALOG = &H1      ' display tabbed dialog boxes

'   defines and structures that describe parameter for LTANNEVENT_AUTOCHANGING notification event
Global Const SUCCESS_CHANGE = 1     ' change the object
Global Const SUCCESS_NOCHANGE = 2   ' do not change the object

Global Const ANNCHANGE_DELETE = 0   ' the object is being deleted
Global Const ANNCHANGE_ROTATE = 1   ' the object is being rotated

' Annotation toolbar create alignment
Global Const ANNTOOLALIGN_LEFT = &H0
Global Const ANNTOOLALIGN_RIGHT = &H1
Global Const ANNTOOLALIGN_TOP = &H0
Global Const ANNTOOLALIGN_BOTTOM = &H2

'     Constants used to change the text of the annotation menus
'    automation menu text

Global Const ANNAUTOTEXT_MENU_UNDO = 0
Global Const ANNAUTOTEXT_MENU_CUT = 1
Global Const ANNAUTOTEXT_MENU_COPY = 2
Global Const ANNAUTOTEXT_MENU_PASTE = 3
Global Const ANNAUTOTEXT_MENU_DELETE = 4
Global Const ANNAUTOTEXT_MENU_SELECTALL = 5
Global Const ANNAUTOTEXT_MENU_BRINGTOFRONT = 6
Global Const ANNAUTOTEXT_MENU_SENDTOBACK = 7
Global Const ANNAUTOTEXT_MENU_DEFAULTPROPERTIES = 8
Global Const ANNAUTOTEXT_MENU_SELECTEDPROPERTIES = 9
Global Const ANNAUTOTEXT_MENU_CONTAINERPROPERTIES = 10
Global Const ANNAUTOTEXT_MENU_POINTERPROPERTIES = 11
Global Const ANNAUTOTEXT_MENU_AUDIOPROPERTIES = 12
Global Const ANNAUTOTEXT_MENU_BUTTONPROPERTIES = 13
Global Const ANNAUTOTEXT_MENU_ELLIPSEPROPERTIES = 14
Global Const ANNAUTOTEXT_MENU_FREEHANDPROPERTIES = 15
Global Const ANNAUTOTEXT_MENU_HILITEPROPERTIES = 16
Global Const ANNAUTOTEXT_MENU_HOTSPOTPROPERTIES = 17
Global Const ANNAUTOTEXT_MENU_LINEPROPERTIES = 18
Global Const ANNAUTOTEXT_MENU_NOTEPROPERTIES = 19
Global Const ANNAUTOTEXT_MENU_POLYGONPROPERTIES = 20
Global Const ANNAUTOTEXT_MENU_POLYLINEPROPERTIES = 21
Global Const ANNAUTOTEXT_MENU_RECTANGLEPROPERTIES = 22
Global Const ANNAUTOTEXT_MENU_REDACTPROPERTIES = 23
Global Const ANNAUTOTEXT_MENU_STAMPPROPERTIES = 24
Global Const ANNAUTOTEXT_MENU_TEXTPROPERTIES = 25
Global Const ANNAUTOTEXT_MENU_AUTOMATIONPROPERTIES = 26
Global Const ANNAUTOTEXT_MENU_RULERPROPERTIES = 27
Global Const ANNAUTOTEXT_MENU_CROSSPRODUCTPROPERTIES = 28
Global Const ANNAUTOTEXT_MENU_POINTPROPERTIES = 29
Global Const ANNAUTOTEXT_MENU_PROTRACTORPROPERTIES = 30
Global Const ANNAUTOTEXT_MENU_VIDEOPROPERTIES = 31
Global Const ANNAUTOTEXT_MENU_PUSHPINPROPERTIES = 32
Global Const ANNAUTOTEXT_MENU_FREEHANDHOSPOTPROPERTIES = 33

Global Const ANNAUTOTEXT_MENU_LINE = 34
Global Const ANNAUTOTEXT_MENU_FILL = 35
Global Const ANNAUTOTEXT_MENU_FOREGROUNDCOLOR = 36
Global Const ANNAUTOTEXT_MENU_BACKGROUNDCOLOR = 37
Global Const ANNAUTOTEXT_MENU_FONT = 38
Global Const ANNAUTOTEXT_MENU_BITMAP = 39
Global Const ANNAUTOTEXT_MENU_TEXT = 40
Global Const ANNAUTOTEXT_MENU_FILE = 41

Global Const ANNAUTOTEXT_MENU_ROP2 = 42
Global Const ANNAUTOTEXT_MENU_TRANSPARENT = 43
Global Const ANNAUTOTEXT_MENU_LOCK = 44
Global Const ANNAUTOTEXT_MENU_UNLOCK = 45
Global Const ANNAUTOTEXT_MENU_LOCKALL = 46
Global Const ANNAUTOTEXT_MENU_UNLOCKALL = 47
Global Const ANNAUTOTEXT_MENU_HYPERLINK = 48
Global Const ANNAUTOTEXT_MENU_NOTEBACKGROUNDCOLOR = 49
Global Const ANNAUTOTEXT_MENU_REDACTBACKGROUNDCOLOR = 50
Global Const ANNAUTOTEXT_MENU_HILITEBACKGROUNDCOLOR = 51
Global Const ANNAUTOTEXT_MENU_HOTSPOTMETAFILE = 52
Global Const ANNAUTOTEXT_MENU_RULER = 53
Global Const ANNAUTOTEXT_MENU_BUTTONFONT = 54
Global Const ANNAUTOTEXT_MENU_GROUP = 55
Global Const ANNAUTOTEXT_MENU_UNGROUP = 56
Global Const ANNAUTOTEXT_MENU_NODES = 57
Global Const ANNAUTOTEXT_MENU_PROTRACTOR = 58
Global Const ANNAUTOTEXT_MENU_NAME = 59
Global Const ANNAUTOTEXT_MENU_METAFILE = 60
Global Const ANNAUTOTEXT_MENU_SECONDARYFILE = 61
Global Const ANNAUTOTEXT_MENU_TRANSPARENTCOLOR = 62
Global Const ANNAUTOTEXT_MENU_DELETENODE = 63
Global Const ANNAUTOTEXT_MENU_ADDNODE = 64
Global Const ANNAUTOTEXT_MENU_CAPTURE = 65

'   toolbar rubber stamps menu text
Global Const ANNAUTOTEXT_MENU_STAMP_APPROVED = 66
Global Const ANNAUTOTEXT_MENU_STAMP_ASSIGNED = 67
Global Const ANNAUTOTEXT_MENU_STAMP_CHECKED = 68
Global Const ANNAUTOTEXT_MENU_STAMP_CLATPRV = 69
Global Const ANNAUTOTEXT_MENU_STAMP_COPY = 70
Global Const ANNAUTOTEXT_MENU_STAMP_DRAFT = 71
Global Const ANNAUTOTEXT_MENU_STAMP_EXTENDED = 72
Global Const ANNAUTOTEXT_MENU_STAMP_FAX = 73
Global Const ANNAUTOTEXT_MENU_STAMP_FAXED = 74
Global Const ANNAUTOTEXT_MENU_STAMP_IMPORTANT = 75
Global Const ANNAUTOTEXT_MENU_STAMP_INVOICE = 76
Global Const ANNAUTOTEXT_MENU_STAMP_NOTICE = 77
Global Const ANNAUTOTEXT_MENU_STAMP_OFFICIAL = 78
Global Const ANNAUTOTEXT_MENU_STAMP_ONFILE = 79
Global Const ANNAUTOTEXT_MENU_STAMP_PAID = 80
Global Const ANNAUTOTEXT_MENU_STAMP_PASSED = 81
Global Const ANNAUTOTEXT_MENU_STAMP_PENDING = 82
Global Const ANNAUTOTEXT_MENU_STAMP_PROCESSED = 83
Global Const ANNAUTOTEXT_MENU_STAMP_RECEIVED = 84
Global Const ANNAUTOTEXT_MENU_STAMP_REJECTED = 85
Global Const ANNAUTOTEXT_MENU_STAMP_RELEASE = 86
Global Const ANNAUTOTEXT_MENU_STAMP_SENT = 87
Global Const ANNAUTOTEXT_MENU_STAMP_SHIPPED = 88
Global Const ANNAUTOTEXT_MENU_STAMP_TOPSECRET = 89
Global Const ANNAUTOTEXT_MENU_STAMP_URGENT = 90
Global Const ANNAUTOTEXT_MENU_STAMP_VOID = 91
                                                     
'   automation line dialog text
                                                     
Global Const ANNAUTOTEXT_LINE_CAPTION = 92
Global Const ANNAUTOTEXT_LINE_WIDTH = 93
Global Const ANNAUTOTEXT_LINE_STYLE = 94
Global Const ANNAUTOTEXT_LINE_OK = 95
Global Const ANNAUTOTEXT_LINE_CANCEL = 96
Global Const ANNAUTOTEXT_LINE_APPLY = 97

Global Const ANNAUTOTEXT_LINE_SOLID = 98
Global Const ANNAUTOTEXT_LINE_DASH = 99
Global Const ANNAUTOTEXT_LINE_DOT = 100
Global Const ANNAUTOTEXT_LINE_DASHDOT = 101
Global Const ANNAUTOTEXT_LINE_DASHDOTDOT = 102
Global Const ANNAUTOTEXT_LINE_NULL = 103

'   automation fill dialog text

Global Const ANNAUTOTEXT_FILL_CAPTION = 104
Global Const ANNAUTOTEXT_FILL_MODE = 105
Global Const ANNAUTOTEXT_FILL_PATTERNS = 106
Global Const ANNAUTOTEXT_FILL_POLYGON = 107
Global Const ANNAUTOTEXT_FILL_OK = 108
Global Const ANNAUTOTEXT_FILL_CANCEL = 109
Global Const ANNAUTOTEXT_FILL_APPLY = 110
Global Const ANNAUTOTEXT_FILL_TRANSPARENT = 111
Global Const ANNAUTOTEXT_FILL_TRANSLUCENT = 112
Global Const ANNAUTOTEXT_FILL_OPAQUE = 113
Global Const ANNAUTOTEXT_FILL_SOLID = 114
Global Const ANNAUTOTEXT_FILL_BACKWARDDIAGONAL = 115
Global Const ANNAUTOTEXT_FILL_CROSS = 116
Global Const ANNAUTOTEXT_FILL_DIAGONALCROSS = 117
Global Const ANNAUTOTEXT_FILL_FORWARDDIAGONAL = 118
Global Const ANNAUTOTEXT_FILL_HORIZONTAL = 119
Global Const ANNAUTOTEXT_FILL_VERTICAL = 120
Global Const ANNAUTOTEXT_FILL_WINDING = 121
Global Const ANNAUTOTEXT_FILL_ALTERNATE = 122
                                                      
' automation text dialog text
                                                      
Global Const ANNAUTOTEXT_TEXT_CAPTION = 123
Global Const ANNAUTOTEXT_TEXT_OK = 124
Global Const ANNAUTOTEXT_TEXT_CANCEL = 125
Global Const ANNAUTOTEXT_TEXT_APPLY = 126

' automation audio file dialog text

Global Const ANNAUTOTEXT_AUDIOFILE_CAPTION = 127
Global Const ANNAUTOTEXT_AUDIOFILE_FILTER = 128

'   automation stamp file dialog text
Global Const ANNAUTOTEXT_STAMPFILE_CAPTION = 129
Global Const ANNAUTOTEXT_STAMPFILE_FILTER = 130

'   automation point file dialog text
Global Const ANNAUTOTEXT_POINTFILE_CAPTION = 131
Global Const ANNAUTOTEXT_POINTFILE_FILTER = 132

'   automation audio file dialog text
Global Const ANNAUTOTEXT_VIDEOFILE_CAPTION = 133
Global Const ANNAUTOTEXT_VIDEOFILE_FILTER = 134

'   automation pushpin file dialog text
Global Const ANNAUTOTEXT_PUSHPINFILE_CAPTION = 135
Global Const ANNAUTOTEXT_PUSHPINFILE_FILTER = 136
Global Const ANNAUTOTEXT_PUSHPINSECONDARYFILE_CAPTION = 137
Global Const ANNAUTOTEXT_PUSHPINSECONDARYFILE_FILTER = 138

'   automation default item text
Global Const ANNAUTOTEXT_ITEM_DEFAULTTEXT = 139

'   automation ROP2 dialog text
Global Const ANNAUTOTEXT_ROP2_CAPTION = 140
Global Const ANNAUTOTEXT_ROP2_TEXT = 141
Global Const ANNAUTOTEXT_ROP2_OK = 142
Global Const ANNAUTOTEXT_ROP2_CANCEL = 143
Global Const ANNAUTOTEXT_ROP2_APPLY = 144
Global Const ANNAUTOTEXT_ROP2_COPY = 145
Global Const ANNAUTOTEXT_ROP2_AND = 146
Global Const ANNAUTOTEXT_ROP2_XOR = 147

Global Const ANNAUTOTEXT_LOCK_CAPTION = 148
Global Const ANNAUTOTEXT_LOCK_TEXT = 149
Global Const ANNAUTOTEXT_LOCK_OK = 150
Global Const ANNAUTOTEXT_LOCK_CANCEL = 151
Global Const ANNAUTOTEXT_UNLOCK_CAPTION = 152
Global Const ANNAUTOTEXT_UNLOCK_TEXT = 153
Global Const ANNAUTOTEXT_UNLOCK_OK = 154
Global Const ANNAUTOTEXT_UNLOCK_CANCEL = 155

Global Const ANNAUTOTEXT_RULER_CAPTION = 156
Global Const ANNAUTOTEXT_RULER_UNITS = 157
Global Const ANNAUTOTEXT_RULER_ABBREV = 158
Global Const ANNAUTOTEXT_RULER_PRECISION = 159
Global Const ANNAUTOTEXT_RULER_LENGTH = 160
Global Const ANNAUTOTEXT_RULER_OK = 161
Global Const ANNAUTOTEXT_RULER_CANCEL = 162
Global Const ANNAUTOTEXT_RULER_APPLY = 163

Global Const ANNAUTOTEXT_RULER_INCHES = 164
Global Const ANNAUTOTEXT_RULER_FEET = 165
Global Const ANNAUTOTEXT_RULER_YARDS = 166
Global Const ANNAUTOTEXT_RULER_MICROMETERS = 167
Global Const ANNAUTOTEXT_RULER_MILIMETERS = 168
Global Const ANNAUTOTEXT_RULER_CENTIMETERS = 169
Global Const ANNAUTOTEXT_RULER_METERS = 170
Global Const ANNAUTOTEXT_RULER_TWIPS = 171
Global Const ANNAUTOTEXT_RULER_POINTS = 172
Global Const ANNAUTOTEXT_RULER_PIXELS = 173

Global Const ANNAUTOTEXT_RULER_SHOWLENGTH = 174
Global Const ANNAUTOTEXT_RULER_SHOWGAUGE = 175

'   automation Nodes dialog text
Global Const ANNAUTOTEXT_NODES_CAPTION = 176
Global Const ANNAUTOTEXT_NODES_DISPLAYNODES = 177
Global Const ANNAUTOTEXT_NODES_GAP = 178
Global Const ANNAUTOTEXT_NODES_OK = 179
Global Const ANNAUTOTEXT_NODES_CANCEL = 180
Global Const ANNAUTOTEXT_NODES_APPLY = 181

'   automation Protractor dialog text
Global Const ANNAUTOTEXT_PROTRACTOR_CAPTION = 182
Global Const ANNAUTOTEXT_PROTRACTOR_ACUTE = 183
Global Const ANNAUTOTEXT_PROTRACTOR_UNITS = 184
Global Const ANNAUTOTEXT_PROTRACTOR_ABBREV = 185
Global Const ANNAUTOTEXT_PROTRACTOR_PRECISION = 186
Global Const ANNAUTOTEXT_PROTRACTOR_ARCRADIUS = 187
Global Const ANNAUTOTEXT_PROTRACTOR_OK = 188
Global Const ANNAUTOTEXT_PROTRACTOR_CANCEL = 189
Global Const ANNAUTOTEXT_PROTRACTOR_APPLY = 190

Global Const ANNAUTOTEXT_PROTRACTOR_DEGREES = 191
Global Const ANNAUTOTEXT_PROTRACTOR_RADIANS = 192

'   automation Name dialog text
Global Const ANNAUTOTEXT_NAME_CAPTION = 193
Global Const ANNAUTOTEXT_NAME_SHOW = 194
Global Const ANNAUTOTEXT_NAME_OFFSET = 195
Global Const ANNAUTOTEXT_NAME_OFFSET_X = 196
Global Const ANNAUTOTEXT_NAME_OFFSET_Y = 197
Global Const ANNAUTOTEXT_NAME_RESTRICT = 198
Global Const ANNAUTOTEXT_NAME_OK = 199
Global Const ANNAUTOTEXT_NAME_CANCEL = 200
Global Const ANNAUTOTEXT_NAME_APPLY = 201

'   automation default item text
Global Const ANNAUTOTEXT_ITEM_DEFAULTNAME = 202

'   automation Play Video dialog text
Global Const ANNAUTOTEXT_PLAYVIDEO_CAPTION = 203
Global Const ANNAUTOTEXT_PLAYVIDEO_BALANCE = 204
Global Const ANNAUTOTEXT_PLAYVIDEO_VOLUME = 205
Global Const ANNAUTOTEXT_PLAYVIDEO_SPEED = 206

Global Const ANNAUTOTEXT_PLAYVIDEO_TIP_PLAY = 207
Global Const ANNAUTOTEXT_PLAYVIDEO_TIP_PAUSE = 208
Global Const ANNAUTOTEXT_PLAYVIDEO_TIP_STOP = 209
Global Const ANNAUTOTEXT_PLAYVIDEO_TIP_REWIND = 210
Global Const ANNAUTOTEXT_PLAYVIDEO_TIP_FORWARD = 211
Global Const ANNAUTOTEXT_PLAYVIDEO_TIP_PREVMARK = 212
Global Const ANNAUTOTEXT_PLAYVIDEO_TIP_NEXTMARK = 213
Global Const ANNAUTOTEXT_PLAYVIDEO_TIP_NEXTFRAME = 214
Global Const ANNAUTOTEXT_PLAYVIDEO_TIP_PREVFRAME = 215
Global Const ANNAUTOTEXT_PLAYVIDEO_TIP_STARTSEL = 216
Global Const ANNAUTOTEXT_PLAYVIDEO_TIP_ENDSEL = 217

'   automation stamp metafile dialog text
Global Const ANNAUTOTEXT_STAMPMETAFILE_CAPTION = 218
Global Const ANNAUTOTEXT_STAMPMETAFILE_FILTER = 219

'   automation hotspot metafile dialog text
Global Const ANNAUTOTEXT_HOTSPOTMETAFILE_CAPTION = 220
Global Const ANNAUTOTEXT_HOTSPOTMETAFILE_FILTER = 221

'   toolbar buttons tooltip text
Global Const ANNAUTOTEXT_TOOLTIP_SELECT = 222
Global Const ANNAUTOTEXT_TOOLTIP_LINE = 223
Global Const ANNAUTOTEXT_TOOLTIP_RECT = 224
Global Const ANNAUTOTEXT_TOOLTIP_ELLIPSE = 225
Global Const ANNAUTOTEXT_TOOLTIP_POLYLINE = 226
Global Const ANNAUTOTEXT_TOOLTIP_POLYGON = 227
Global Const ANNAUTOTEXT_TOOLTIP_POINTER = 228
Global Const ANNAUTOTEXT_TOOLTIP_FREEHAND = 229
Global Const ANNAUTOTEXT_TOOLTIP_HILITE = 230
Global Const ANNAUTOTEXT_TOOLTIP_REDACT = 231
Global Const ANNAUTOTEXT_TOOLTIP_TEXT = 232
Global Const ANNAUTOTEXT_TOOLTIP_NOTE = 233
Global Const ANNAUTOTEXT_TOOLTIP_STAMP = 234
Global Const ANNAUTOTEXT_TOOLTIP_RUBBERSTAMP = 235
Global Const ANNAUTOTEXT_TOOLTIP_HOTSPOT = 236
Global Const ANNAUTOTEXT_TOOLTIP_FREEHANDHOTSPOT = 237
Global Const ANNAUTOTEXT_TOOLTIP_AUDIO = 238
Global Const ANNAUTOTEXT_TOOLTIP_BUTTON = 239
Global Const ANNAUTOTEXT_TOOLTIP_RULER = 240
Global Const ANNAUTOTEXT_TOOLTIP_CROSSPRODUCT = 241
Global Const ANNAUTOTEXT_TOOLTIP_POINT = 242
Global Const ANNAUTOTEXT_TOOLTIP_PROTRACTOR = 243
Global Const ANNAUTOTEXT_TOOLTIP_VIDEO = 244
Global Const ANNAUTOTEXT_TOOLTIP_PUSHPIN = 245

'   automation transparent color dialog text
Global Const ANNAUTOTEXT_TRANSPARENTCOLOR_CAPTION = 246
Global Const ANNAUTOTEXT_TRANSPARENTCOLOR_COLORARRAYFRAME = 247
Global Const ANNAUTOTEXT_TRANSPARENTCOLOR_CURRENTCOLORFRAME = 248
Global Const ANNAUTOTEXT_TRANSPARENTCOLOR_COLOR = 249
Global Const ANNAUTOTEXT_TRANSPARENTCOLOR_RED = 250
Global Const ANNAUTOTEXT_TRANSPARENTCOLOR_GREEN = 251
Global Const ANNAUTOTEXT_TRANSPARENTCOLOR_BLUE = 252
Global Const ANNAUTOTEXT_TRANSPARENTCOLOR_OK = 253
Global Const ANNAUTOTEXT_TRANSPARENTCOLOR_CANCEL = 254

'   automation capture file dialog text
Global Const ANNAUTOTEXT_CAPTUREFILE_CAPTION = 255
Global Const ANNAUTOTEXT_CAPTUREFILE_FILTER = 256

'   automation capture dialog text
Global Const ANNAUTOTEXT_CAPTUREWINDOW_CAPTION = 257
Global Const ANNAUTOTEXT_CAPTURE_CAPTION = 258
Global Const ANNAUTOTEXT_CAPTURE_CAPTUREDRIVERS = 259
Global Const ANNAUTOTEXT_CAPTURE_VIDEODIALOGS = 260
Global Const ANNAUTOTEXT_CAPTURE_VIDEOFORMAT = 261
Global Const ANNAUTOTEXT_CAPTURE_VIDEODISPLAY = 262
Global Const ANNAUTOTEXT_CAPTURE_VIDEOSOURCE = 263
Global Const ANNAUTOTEXT_CAPTURE_VIDEOCOMPRESSION = 264
Global Const ANNAUTOTEXT_CAPTURE_DISPLAYMODE = 265
Global Const ANNAUTOTEXT_CAPTURE_NONE = 266
Global Const ANNAUTOTEXT_CAPTURE_NONEOVERLAY = 267
Global Const ANNAUTOTEXT_CAPTURE_PREVIEW = 268
Global Const ANNAUTOTEXT_CAPTURE_PREVIEWFRAMESPERSEC = 269
Global Const ANNAUTOTEXT_CAPTURE_OPTIONS = 270
Global Const ANNAUTOTEXT_CAPTURE_TIMELIMIT = 271
Global Const ANNAUTOTEXT_CAPTURE_CAPTUREFRAMESPERSEC = 272
Global Const ANNAUTOTEXT_CAPTURE_STARTCAPTURE = 273
Global Const ANNAUTOTEXT_CAPTURE_ENDCAPTURE = 274
Global Const ANNAUTOTEXT_CAPTURE_FRAMESCAPTURED = 275
Global Const ANNAUTOTEXT_CAPTURE_AUDIOOPTIONS = 276
Global Const ANNAUTOTEXT_CAPTURE_CAPTUREAUDIO = 277
Global Const ANNAUTOTEXT_CAPTURE_SYNCAUDIO = 278
Global Const ANNAUTOTEXT_CAPTURE_CAPTUREFILE = 279
Global Const ANNAUTOTEXT_CAPTURE_BROWSE = 280
Global Const ANNAUTOTEXT_CAPTURE_FILESIZE = 281
Global Const ANNAUTOTEXT_CAPTURE_OK = 282
Global Const ANNAUTOTEXT_CAPTURE_CANCEL = 283

Global Const ANNAUTOTEXT_CAPTURE_WAV_1M08 = 284
Global Const ANNAUTOTEXT_CAPTURE_WAV_1S08 = 285
Global Const ANNAUTOTEXT_CAPTURE_WAV_1M16 = 286
Global Const ANNAUTOTEXT_CAPTURE_WAV_1S16 = 287
Global Const ANNAUTOTEXT_CAPTURE_WAV_2M08 = 288
Global Const ANNAUTOTEXT_CAPTURE_WAV_2S08 = 289
Global Const ANNAUTOTEXT_CAPTURE_WAV_2M16 = 290
Global Const ANNAUTOTEXT_CAPTURE_WAV_2S16 = 291
Global Const ANNAUTOTEXT_CAPTURE_WAV_4M08 = 292
Global Const ANNAUTOTEXT_CAPTURE_WAV_4S08 = 293
Global Const ANNAUTOTEXT_CAPTURE_WAV_4M16 = 294
Global Const ANNAUTOTEXT_CAPTURE_WAV_4S16 = 295

Global Const ANNAUTOTEXT_CAPTURE_DEFAULTNAME = 296
Global Const ANNAUTOTEXT_CAPTURE_NODRIVERS = 297

Global Const ANNAUTOTEXT_DIALOG_FONT = 298
Global Const ANNAUTOTEXT_MAX = 298

Global Const ANNMENU_DISABLED = 0
Global Const ANNMENU_ENABLED = 1
Global Const ANNMENU_DEFAULT = 2

'   ROP2 values
Global Const ANNROP2_COPY = 0
Global Const ANNROP2_AND = 1
Global Const ANNROP2_XOR = 2

'   Hyperlink types
Global Const ANNLINK_NONE = 0
Global Const ANNLINK_LTANNEVENT = 1
Global Const ANNLINK_USERMSG = 2
Global Const ANNLINK_RUN = 3
Global Const ANNLINK_WEBPAGE = 4

'distance units
Global Const ANNUNIT_INCH = 0
Global Const ANNUNIT_FEET = 1
Global Const ANNUNIT_YARDS = 2
Global Const ANNUNIT_MICROMETERS = 3
Global Const ANNUNIT_MILIMETERS = 4
Global Const ANNUNIT_CENTIMETERS = 5
Global Const ANNUNIT_METERS = 6
Global Const ANNUNIT_TWIPS = 7
Global Const ANNUNIT_POINTS = 8
Global Const ANNUNIT_PIXELS = 9

' Annotation structures
Type ANNPOINT
   x As Double
   y As Double
End Type

Type ANNRECT
   left As Double
   top As Double
   right As Double
   bottom As Double
End Type

Type ANNTOOL
   uTool As Long
   nMenuTextID As Long          ' used if uMenuTextID >= 0
   pMenuText As Long               ' used if uMenuTextID == -1
End Type

Type ANNBUTTON
   uFlags As Long
   uTool As Long
   uToolCount As Long
   pTools As Long

   pBitmapUp As Long
   pBitmapDown As Long
   nToolTipTextID As Long       ' used if uToolTipTextID >= 0
   pToolTipText As Long            ' used if uToolTipTextID == -1
End Type

Type ANNTOOLBARINFO
   uButtons As Long
   uRows As Long
   uColumns As Long
End Type

'   structure passed to the mouse notifications
Type ANNMOUSEPOS
   fDoubleClick As Boolean  ' valid only for LTANNEVENT_LBUTTONDOWN
   pt As POINT
   uKeyFlags As Long
   fUpdatePos As Boolean    ' if TRUE, the mouse cursor is updated
End Type

'   defines and structures that describe parameter for LTANNEVENT_AUTOCHANGING notification event
Type ANNCHANGEPARAM
   nSize As Long
   hObject As Long          ' object being changed.
   uChange As Long          ' the type of change being performed
   nChange As Long          ' set to TRUE to allow the modification, set to FALSE to disable it
   dAngle As Double         ' valid if the object is being rotated
End Type

Type ANNFILEINFO
   nSize As Long
   nOffset As Long
   nVersion As Long
   uFormat As Long          ' ANNFMT_NATIVE, ANNFMT_WMF, ANNFMT_ENCODED
   nTotalPages As Long
   nReserved As Long
End Type

' Functions in LTANN DLL

Declare Function L_AnnBringToFront Lib "LTANN13N" (ByVal hObject&) As Long
Declare Function L_AnnClipboardReady Lib "LTANN13N" (ByRef pfReady&) As Long
Declare Function L_AnnCopy Lib "LTANN13N" (ByVal hSource&, ByRef phDest&) As Long
Declare Function L_AnnCopyFromClipboard Lib "LTANN13N" (ByVal hWnd&, ByRef phContainer&) As Long
Declare Function L_AnnCopyToClipboard Lib "LTANN13N" (ByVal hObject&, ByVal uFormat&, ByVal fSelected&, ByVal fEmpty&, ByVal fCheckMenu&) As Long
Declare Function L_AnnCutToClipboard Lib "LTANN13N" (ByVal hObject&, ByVal uFormat&, ByVal fSelected&, ByVal fEmpty&) As Long
Declare Function L_AnnCreate Lib "LTANN13N" (ByVal uObjectType&, ByRef phObject&) As Long
Declare Function L_AnnCreateContainer Lib "LTANN13N" (ByVal hWnd&, ByRef pRect As ANNRECT, ByVal fVisible&, ByRef phObject&) As Long
Declare Function L_AnnCreateItem Lib "LTANN13N" (ByVal hContainer&, ByVal uObjectType&, ByVal fVisible&, ByRef phObject&) As Long
Declare Function L_AnnCreateToolBar Lib "LTANN13N" (ByVal hWndParent&, ByRef pPoint As POINT, ByVal uAlign&, ByVal fVisible&, ByRef phWnd&, ByVal uButtons&, pButtons As ANNBUTTON) As Long
Declare Function L_AnnDefine Lib "LTANN13N" (ByVal hObject&, ByRef pPoint As POINT, ByVal uState&) As Long
Declare Function L_AnnDestroy Lib "LTANN13N" (ByVal hObject&, ByVal uFlags&) As Long
Declare Function L_AnnDraw Lib "LTANN13N" (ByVal hDC&, ByRef prcInvalid As RECT, ByVal hObject&) As Long
Declare Function L_AnnEnumerate Lib "LTANN13N" (ByVal hObject&, ByVal pfnCallBack&, ByVal pUserData&, ByVal uFlags&, ByVal pUserList$) As Long
Declare Function L_AnnFlip Lib "LTANN13N" (ByVal hObject&, ByRef pCenter As ANNPOINT, ByVal uFlags&) As Long
Declare Function L_AnnGetActiveState Lib "LTANN13N" (ByVal hObject&, ByRef puState&) As Long
Declare Function L_AnnGetAutoContainer Lib "LTANN13N" (ByVal hObject&, ByRef phContainer&) As Long
Declare Function L_AnnGetBackColor Lib "LTANN13N" (ByVal hObject&, ByRef pcrBack&) As Long
Declare Function L_AnnGetBitmap Lib "LTANN13N" (ByVal hObject&, ByRef pBitmap As LEADBitmapHandle) As Long
Declare Function L_AnnGetBoundingRect Lib "LTANN13N" (ByVal hObject&, ByRef pRect As RECT, pRectName As RECT) As Long
Declare Function L_AnnGetContainer Lib "LTANN13N" (ByVal hObject&, ByRef phContainer&) As Long
Declare Function L_AnnGetDpiX Lib "LTANN13N" (ByVal hObject&, ByRef pdDpiX As Double) As Long
Declare Function L_AnnGetDpiY Lib "LTANN13N" (ByVal hObject&, ByRef pdDpiY As Double) As Long
Declare Function L_AnnGetFillMode Lib "LTANN13N" (ByVal hObject&, ByRef puFillMode&) As Long
Declare Function L_AnnGetFillPattern Lib "LTANN13N" (ByVal hObject&, ByRef puFillPattern&) As Long
Declare Function L_AnnGetFontBold Lib "LTANN13N" (ByVal hObject&, ByRef pfFontBold&) As Long
Declare Function L_AnnGetFontItalic Lib "LTANN13N" (ByVal hObject&, ByRef pfFontItalic&) As Long
Declare Function L_AnnGetFontName Lib "LTANN13N" (ByVal hObject&, ByVal pFontName$) As Long
Declare Function L_AnnGetFontNameLen Lib "LTANN13N" (ByVal hObject&, ByRef puLen&) As Long
Declare Function L_AnnGetFontSize Lib "LTANN13N" (ByVal hObject&, ByRef pdFontSize As Double) As Long
Declare Function L_AnnGetFontStrikeThrough Lib "LTANN13N" (ByVal hObject&, ByRef pfFontStrikeThrough&) As Long
Declare Function L_AnnGetFontUnderline Lib "LTANN13N" (ByVal hObject&, ByRef pfFontUnderline&) As Long
Declare Function L_AnnGetForeColor Lib "LTANN13N" (ByVal hObject&, ByRef pcrFore&) As Long
Declare Function L_AnnGetHyperlink Lib "LTANN13N" (ByVal hObject&, puType&, puMsg&, pwParam&, ByVal pLink$) As Long
Declare Function L_AnnGetHyperlinkLen Lib "LTANN13N" (ByVal hObject&, puLen&) As Long
Declare Function L_AnnGetHyperlinkMenuEnable Lib "LTANN13N" (ByVal hObject&, pfEnable&) As Long
Declare Function L_AnnGetLineStyle Lib "LTANN13N" (ByVal hObject&, ByRef puLineStyle&) As Long
Declare Function L_AnnGetLineWidth Lib "LTANN13N" (ByVal hObject&, ByRef pdLineWidth As Double) As Long
Declare Function L_AnnGetLocked Lib "LTANN13N" (ByVal hObject&, pfLocked&) As Long
Declare Function L_AnnGetOffsetX Lib "LTANN13N" (ByVal hObject&, ByRef pdOffsetX As Double) As Long
Declare Function L_AnnGetOffsetY Lib "LTANN13N" (ByVal hObject&, ByRef pdOffsetY As Double) As Long
Declare Function L_AnnGetPointCount Lib "LTANN13N" (ByVal hObject&, ByRef puCount&) As Long
Declare Function L_AnnGetPoints Lib "LTANN13N" (ByVal hObject&, ByRef pPoints As ANNPOINT) As Long
Declare Function L_AnnGetPolyFillMode Lib "LTANN13N" (ByVal hObject&, ByRef puPolyFillMode&) As Long
Declare Function L_AnnGetRect Lib "LTANN13N" (ByVal hObject&, ByRef pRect As ANNRECT, pRectName As ANNRECT) As Long
Declare Function L_AnnGetROP2 Lib "LTANN13N" (ByVal hObject&, puRop2&) As Long
Declare Function L_AnnGetScalarX Lib "LTANN13N" (ByVal hObject&, ByRef pdScalarX As Double) As Long
Declare Function L_AnnGetScalarY Lib "LTANN13N" (ByVal hObject&, ByRef pdScalarY As Double) As Long
Declare Function L_AnnGetSelectCount Lib "LTANN13N" (ByVal hObject&, ByRef puCount&) As Long
Declare Function L_AnnGetSelected Lib "LTANN13N" (ByVal hObject&, ByRef pfSelected&) As Long
Declare Function L_AnnGetSelectItems Lib "LTANN13N" (ByVal hObject&, pItems&) As Long
Declare Function L_AnnGetSelectRect Lib "LTANN13N" (ByVal hObject&, ByRef pRect As RECT) As Long
Declare Function L_AnnGetTag Lib "LTANN13N" (ByVal hObject&, ByRef puTag&) As Long
Declare Function L_AnnGetText Lib "LTANN13N" (ByVal hObject&, ByVal pText$) As Long
Declare Function L_AnnGetTextLen Lib "LTANN13N" (ByVal hObject&, ByRef puLen&) As Long
Declare Function L_AnnGetTool Lib "LTANN13N" (ByVal hObject&, ByRef puTool&) As Long
Declare Function L_AnnGetToolBarChecked Lib "LTANN13N" (ByVal hwndToolBar&, ByRef puChecked&) As Long
Declare Function L_AnnGetTransparent Lib "LTANN13N" (ByVal hwndToolBar&, pbTransparent&) As Long
Declare Function L_AnnGetType Lib "LTANN13N" (ByVal hObject&, ByRef puObjectType&) As Long
Declare Function L_AnnGetTopContainer Lib "LTANN13N" (ByVal hObject&, ByRef phContainer&) As Long
Declare Function L_AnnGetUserMode Lib "LTANN13N" (ByVal hObject&, ByRef puMode&) As Long
Declare Function L_AnnGetVisible Lib "LTANN13N" (ByVal hObject&, ByRef pfVisible&) As Long
Declare Function L_AnnGetWnd Lib "LTANN13N" (ByVal hObject&, ByRef phWnd&) As Long
Declare Function L_AnnHitTest Lib "LTANN13N" (ByVal hObject&, ByRef pPoint As POINT, ByRef puResult&, ByRef phObjectHit&) As Long
Declare Function L_AnnInsert Lib "LTANN13N" (ByVal hContainer&, ByVal hObject&, ByVal fStripContainer&) As Long
Declare Function L_AnnGetItem Lib "LTANN13N" (ByVal hContainer&, ByRef phItem&) As Long
Declare Function L_AnnLoad Lib "LTANN13N" (ByVal pFile$, ByRef phObject&, pLoadOptions As LOADFILEOPTION) As Long
Declare Function L_AnnLoadOffset Lib "LTANN13N" (ByVal fd&, ByVal nOffset&, ByVal nLen&, ByRef phObject&, pLoadOptions As LOADFILEOPTION) As Long
Declare Function L_AnnLoadMemory Lib "LTANN13N" (ByRef pMem$, ByVal uMemSize&, ByRef phObject&, pLoadOptions As LOADFILEOPTION) As Long
Declare Function L_AnnLock Lib "LTANN13N" (ByVal hObject&, ByVal pLockKey$, ByVal uFlags&) As Long
Declare Function L_AnnMove Lib "LTANN13N" (ByVal hObject&, ByVal dDx As Double, ByVal dDy As Double, ByVal uFlags&) As Long
Declare Function L_AnnPrint Lib "LTANN13N" (ByVal hDC&, ByRef prcBounds As RECT, ByVal hObject&) As Long
Declare Function L_AnnRealize Lib "LTANN13N" (ByRef pBitmap As LEADBitmapHandle, ByRef prcBounds As RECT, ByVal hObject&, ByVal fRedactOnly&) As Long
Declare Function L_AnnResize& Lib "LTANN13N" (ByVal hObject&, ByVal dFactorX As Double, ByVal dFactorY#, ByRef pCenter As ANNPOINT, ByVal uFlags&)
Declare Function L_AnnReverse& Lib "LTANN13N" (ByVal hObject&, ByRef pCenter As ANNPOINT, ByVal uFlags&)
Declare Function L_AnnRemove& Lib "LTANN13N" (ByVal hObject&)
Declare Function L_AnnRotate Lib "LTANN13N" (ByVal hObject&, ByVal dAngle As Double, ByRef pCenter As ANNPOINT, ByVal uFlags&) As Long
Declare Function L_AnnSave Lib "LTANN13N" (ByVal pFile$, ByVal hObject&, ByVal uFormat&, ByVal fSelected&, ByRef SaveOptions As SAVEFILEOPTION) As Long
Declare Function L_AnnSaveOffset Lib "LTANN13N" (ByVal fd&, ByVal nOffset&, ByRef puSizeWritten&, ByVal hObject&, ByVal uFormat&, ByVal fSelected&, ByRef SaveOptions As SAVEFILEOPTION) As Long
Declare Function L_AnnSaveMemory Lib "LTANN13N" (ByVal hObject&, ByVal uFormat&, ByVal fSelected&, ByRef phMem&, ByRef puMemSize&, ByRef SaveOptions As SAVEFILEOPTION) As Long
Declare Function L_AnnSaveTag Lib "LTANN13N" (ByVal hObject&, ByVal uFormat&, ByVal fSelected&) As Long
Declare Function L_AnnSelectPoint Lib "LTANN13N" (ByVal hObject&, ByRef pPoint As POINT) As Long
Declare Function L_AnnSelectRect Lib "LTANN13N" (ByVal hObject&, ByRef pRect&) As Long
Declare Function L_AnnSendToBack Lib "LTANN13N" (ByVal hObject&) As Long
Declare Function L_AnnSetActiveState Lib "LTANN13N" (ByVal hObject&, ByVal uState&) As Long
Declare Function L_AnnSetAutoContainer Lib "LTANN13N" (ByVal hObject&, ByVal hContainer&) As Long
Declare Function L_AnnSetBackColor Lib "LTANN13N" (ByVal hObject&, ByVal crBack&, ByVal uFlags&) As Long
Declare Function L_AnnSetBitmap Lib "LTANN13N" (ByVal hObject&, ByRef pBitmap As LEADBitmapHandle, ByVal uFlags&) As Long
Declare Function L_AnnSetDpiX Lib "LTANN13N" (ByVal hObject&, ByVal dDpiX#, ByVal uFlags&) As Long
Declare Function L_AnnSetDpiY Lib "LTANN13N" (ByVal hObject&, ByVal dDpiY#, ByVal uFlags&) As Long
Declare Function L_AnnSetFillMode Lib "LTANN13N" (ByVal hObject&, ByVal uFillMode&, ByVal uFlags&) As Long
Declare Function L_AnnSetFillPattern Lib "LTANN13N" (ByVal hObject&, ByVal uFillPattern&, ByVal uFlags&) As Long
Declare Function L_AnnSetFontBold Lib "LTANN13N" (ByVal hObject&, ByVal fFontBold&, ByVal uFlags&) As Long
Declare Function L_AnnSetFontItalic Lib "LTANN13N" (ByVal hObject&, ByVal fFontItalic&, ByVal uFlags&) As Long
Declare Function L_AnnSetFontName Lib "LTANN13N" (ByVal hObject&, ByVal pFontName$, ByVal uFlags&) As Long
Declare Function L_AnnSetFontSize Lib "LTANN13N" (ByVal hObject&, ByVal dFontSize As Double, ByVal uFlags&) As Long
Declare Function L_AnnSetFontStrikeThrough Lib "LTANN13N" (ByVal hObject&, ByVal fFontStrikeThrough&, ByVal uFlags&) As Long
Declare Function L_AnnSetFontUnderline Lib "LTANN13N" (ByVal hObject&, ByVal fFontUnderline&, ByVal uFlags&) As Long
Declare Function L_AnnSetForeColor Lib "LTANN13N" (ByVal hObject&, ByVal crFore&, ByVal uFlags&) As Long
Declare Function L_AnnSetHyperlink Lib "LTANN13N" (ByVal hObject&, ByVal uType&, ByVal uMsg&, ByVal wParam&, ByVal pLink$, ByVal uFlags&) As Long
Declare Function L_AnnSetHyperlinkMenuEnable Lib "LTANN13N" (ByVal hObject&, ByVal fEnable&, ByVal uFlags&) As Long
Declare Function L_AnnSetLineStyle Lib "LTANN13N" (ByVal hObject&, ByVal uLineStyle&, ByVal uFlags&) As Long
Declare Function L_AnnSetLineWidth Lib "LTANN13N" (ByVal hObject&, ByVal dLineWidth As Double, ByVal uFlags&) As Long
Declare Function L_AnnSetOffsetX Lib "LTANN13N" (ByVal hObject&, ByVal dOffsetX As Double, ByVal uFlags&) As Long
Declare Function L_AnnSetOffsetY Lib "LTANN13N" (ByVal hObject&, ByVal dOffsetY As Double, ByVal uFlags&) As Long
Declare Function L_AnnSetPoints Lib "LTANN13N" (ByVal hObject&, ByRef pPoints As ANNPOINT, ByVal uCount&) As Long
Declare Function L_AnnSetPolyFillMode Lib "LTANN13N" (ByVal hObject&, ByVal uPolyFillMode&, ByVal uFlags&) As Long
Declare Function L_AnnSetROP2 Lib "LTANN13N" (ByVal hObject&, ByVal uROP2&, ByVal uFlags&) As Long
Declare Function L_AnnSetRect Lib "LTANN13N" (ByVal hObject&, ByRef pRect As ANNRECT) As Long
Declare Function L_AnnSetSelected Lib "LTANN13N" (ByVal hObject&, ByVal fSelected&, ByVal uFlags&) As Long
Declare Function L_AnnSetScalarX Lib "LTANN13N" (ByVal hObject&, ByVal dScalarX As Double, ByVal uFlags&) As Long
Declare Function L_AnnSetScalarY Lib "LTANN13N" (ByVal hObject&, ByVal dScalarY As Double, ByVal uFlags&) As Long
Declare Function L_AnnSetTag Lib "LTANN13N" (ByVal hObject&, ByVal uTag&, ByVal uFlags&) As Long
Declare Function L_AnnSetText Lib "LTANN13N" (ByVal hObject&, ByVal pText$, ByVal uFlags&) As Long
Declare Function L_AnnSetTool Lib "LTANN13N" (ByVal hObject&, ByVal uTool&) As Long
Declare Function L_AnnSetToolBarChecked Lib "LTANN13N" (ByVal hwndToolBar&, ByVal uChecked&) As Long
Declare Function L_AnnSetTransparent Lib "LTANN13N" (ByVal hObject&, ByVal bTransparent&, ByVal uFlags&) As Long
Declare Function L_AnnSetUndoDepth Lib "LTANN13N" (ByVal hObject&, ByVal uLevels&) As Long
Declare Function L_AnnSetUserMode Lib "LTANN13N" (ByVal hObject&, ByVal uMode&) As Long
Declare Function L_AnnSetVisible Lib "LTANN13N" (ByVal hObject&, ByVal fVisible&, ByVal uFlags&, ByVal pUserList$) As Long
Declare Function L_AnnSetWnd Lib "LTANN13N" (ByVal hObject&, ByVal hWnd&) As Long
Declare Function L_AnnShowLockedIcon Lib "LTANN13N" (ByVal hObject&, ByVal bShow&, ByVal uFlags&) As Long
Declare Function L_AnnUndo Lib "LTANN13N" (ByVal hObject&) As Long
Declare Function L_AnnUnlock Lib "LTANN13N" (ByVal hObject&, ByVal pUnlockKey$, ByVal uFlags&) As Long
Declare Function L_AnnUnrealize Lib "LTANN13N" (hBitmap As LEADBitmapHandle, prcBounds As RECT, ByVal hObject&, ByVal fSelected&) As Long

Declare Function L_AnnGetAutoText Lib "LTANN13N" (ByVal hObject&, ByVal uItem&, ByVal pText$) As Long
Declare Function L_AnnGetAutoTextLen Lib "LTANN13N" (ByVal hObject&, ByVal uItem&, ByRef puLen&) As Long
Declare Function L_AnnGetToolBarButtonVisible Lib "LTANN13N" (ByVal hwndToolBar&, ByVal uButton&, ByRef pfVisible&) As Long
Declare Function L_AnnSetAutoText Lib "LTANN13N" (ByVal hObject&, ByVal uItem&, ByVal pText$) As Long
Declare Function L_AnnSetToolBarButtonVisible Lib "LTANN13N" (ByVal hwndToolBar&, ByVal uButton&, ByVal fVisible&) As Long
Declare Function L_AnnGetAutoDrawEnable Lib "LTANN13N" (ByVal hObject&, ByRef pfEnable&) As Long
Declare Function L_AnnSetAutoDrawEnable Lib "LTANN13N" (ByVal hObject&, ByVal pfEnable&) As Long

Declare Function L_AnnSetBitmapDpiX Lib "LTANN13N" (ByVal hObject&, ByVal dDpiX As Double, ByVal uFlags&) As Long
Declare Function L_AnnSetBitmapDpiY Lib "LTANN13N" (ByVal hObject&, ByVal dDpiY As Double, ByVal uFlags&) As Long
Declare Function L_AnnGetBitmapDpiX Lib "LTANN13N" (ByVal hObject&, ByRef pdDpiX As Double) As Long
Declare Function L_AnnGetBitmapDpiY Lib "LTANN13N" (ByVal hObject&, ByRef pdDpiY As Double) As Long
Declare Function L_AnnSetUnit Lib "LTANN13N" (ByVal hObject&, ByVal uUnit&, ByVal pUnitAbbrev$, ByVal uPrecision&, ByVal uFlags&) As Long
Declare Function L_AnnGetUnit Lib "LTANN13N" (ByVal hObject&, ByRef puUnit&, ByVal pUnitAbbrev$, ByRef puPrecision&) As Long
Declare Function L_AnnGetUnitLen Lib "LTANN13N" (ByVal hObject&, ByRef puLen&) As Long
Declare Function L_AnnGetDistance Lib "LTANN13N" (ByVal hObject&, ByRef pdDistance As Double, ByRef pdDistance2 As Double) As Long
Declare Function L_AnnSetGaugeLength Lib "LTANN13N" (ByVal hObject&, ByVal dLength As Double, ByVal uFlags&) As Long
Declare Function L_AnnGetGaugeLength Lib "LTANN13N" (ByVal hObject&, ByRef pdLength As Double) As Long

Declare Function L_AnnSetNodes Lib "LTANN13N" (ByVal hObject&, ByVal bShowNodes As Boolean, ByVal uGapNodes&, ByVal uFlags&) As Long
Declare Function L_AnnGetNodes Lib "LTANN13N" (ByVal hObject&, pbShowNodes As Boolean, puGapNodes&) As Long
Declare Function L_AnnSetProtractorOptions Lib "LTANN13N" (ByVal hObject&, ByVal bAcute As Boolean, ByVal uUnit&, ByVal pszAbbrev$, ByVal uPrecision&, ByVal dArcRadius As Double, ByVal uFlags&) As Long
Declare Function L_AnnGetProtractorOptions Lib "LTANN13N" (ByVal hObject&, pbAcute As Boolean, puUnit&, puAbbrevLen&, pszAbbrev$, puPrecision&, pdArcRadius As Double) As Long
Declare Function L_AnnSetName Lib "LTANN13N" (ByVal hObject&, ByVal bShowName As Boolean, ByVal pText$, NameOffset As ANNPOINT, bNameRestrict As Long, ByVal uFlags&) As Long
Declare Function L_AnnGetName Lib "LTANN13N" (ByVal hObject&, pbShowName As Boolean, puNameLen&, ByVal pName$, NameOffset As ANNPOINT, ByVal pbNameRestrict&) As Long
Declare Function L_AnnSetShowFlags Lib "LTANN13N" (ByVal hObject&, ByVal uShowFlags&, ByVal uFlags&) As Long
Declare Function L_AnnGetShowFlags Lib "LTANN13N" (ByVal hObject&, puShowFlags&) As Long
Declare Function L_AnnGetAngle Lib "LTANN13N" (ByVal hObject&, pdAngle As Double) As Long
Declare Function L_AnnSetMetafile Lib "LTANN13N" (ByVal hObject&, ByVal hMetafile&, ByVal uType&, ByVal uFlags&) As Long
Declare Function L_AnnGetMetafile Lib "LTANN13N" (ByVal hObject&, phMetafile&) As Long
Declare Function L_AnnSetPredefinedMetafile Lib "LTANN13N" (ByVal uType&, ByVal hMetafile&) As Long
Declare Function L_AnnGetPredefinedMetafile Lib "LTANN13N" (ByVal uType&, phMetafile&, pbEnhanced As Boolean) As Long
Declare Function L_AnnSetSecondaryBitmap Lib "LTANN13N" (ByVal hObject&, hBitmap As LEADBITMAPHANDLE, ByVal uFlags&) As Long
Declare Function L_AnnGetSecondaryBitmap Lib "LTANN13N" (ByVal hObject&, hBitmap As LEADBITMAPHANDLE) As Long
Declare Function L_AnnGetAutoMenuEnable Lib "LTANN13N" (ByVal hObject&, ByRef pfSelected&) As Long
Declare Function L_AnnSetAutoMenuEnable Lib "LTANN13N" (ByVal hObject&, ByVal pfSelected&) As Long
Declare Function L_AnnSetAutoMenuItemEnable Lib "LTANN13N" (ByVal hObject&, ByVal nObjectType&, ByVal uItem&, ByVal uEnable&, ByVal uFlags&, ByVal pUserList$) As Long
Declare Function L_AnnGetAutoMenuItemEnable Lib "LTANN13N" (ByVal hObject&, ByVal nObjectType&, ByVal uItem&, puEnable&) As Long
Declare Function L_AnnSetAutoMenuState Lib "LTANN13N" (ByVal hObject&, ByVal nObjectType&, pEnable&, pEnableFlags&, ByVal uBits&, ByVal uFlags&) As Long
Declare Function L_AnnGetAutoMenuState Lib "LTANN13N" (ByVal hObject&, ByVal nObjectType&, pEnable&, pEnableFlags&, ByVal uBits&) As Long
Declare Function L_AnnSetUser Lib "LTANN13N" (ByVal hObject&, ByVal pOldUser$, ByVal pNewUser$, ByVal uFlags&) As Long
Declare Function L_AnnSetToolBarButtons Lib "LTANN13N" (ByVal hwndToolBar&, pButtons As ANNBUTTON, ByVal uButtons&) As Long
Declare Function L_AnnGetToolBarButtons Lib "LTANN13N" (ByVal hwndToolBar&, pButtons As ANNBUTTON, puButtons&) As Long
Declare Function L_AnnFreeToolBarButtons Lib "LTANN13N" (pButtons As ANNBUTTON, ByVal uButtons&) As Long
Declare Function L_AnnGetToolBarInfo Lib "LTANN13N" (ByVal hwndToolBar&, pInfo As ANNTOOLBARINFO) As Long
Declare Function L_AnnSetToolBarColumns Lib "LTANN13N" (ByVal hwndToolBar&, ByVal uColumns&) As Long
Declare Function L_AnnSetToolBarRows Lib "LTANN13N" (ByVal hwndToolBar&, ByVal uColumns&) As Long
Declare Function L_AnnSetAutoDefaults Lib "LTANN13N" (ByVal hAutomation&, ByVal hObject&, ByVal uFlags&) As Long
Declare Function L_AnnSetTransparentColor Lib "LTANN13N" (ByVal hObject&, ByVal crTransparent&, ByVal uFlags%) As Long
Declare Function L_AnnGetTransparentColor Lib "LTANN13N" (ByVal hObject&, pcrTransparent&) As Long
Declare Function L_AnnGetUndoDepth Lib "LTANN13N" (ByVal hObject&, puUsedLevels&, puMaxLevels&) As Long
Declare Function L_AnnGroup Lib "LTANN13N" (ByVal hObject&, ByVal uFlags&, ByVal pUserList$) As Long
Declare Function L_AnnUngroup Lib "LTANN13N" (ByVal hObject&, ByVal uFlags&, ByVal pUserList$) As Long
Declare Function L_AnnSetAutoOptions Lib "LTANN13N" (ByVal hObject&, ByVal uFlags&) As Long
Declare Function L_AnnGetAutoOptions Lib "LTANN13N" (ByVal hObject&, puFlags&) As Long
Declare Function L_AnnGetObjectFromTag Lib "LTANN13N" (ByVal hContainer&, ByVal uFlags&, ByVal uTag&, phTagObject&) As Long
Declare Function L_AnnGetRgnHandle Lib "LTANN13N" (ByVal hObject&, ByVal pXForm&, ByVal phRgn&) As Long
Declare Function L_AnnGetArea Lib "LTANN13N" (ByVal hObject&, puCount&) As Long
Declare Function L_AnnDeletePageOffset Lib "LTANN13N" (ByVal fd&, ByVal nOffset&, ByVal nPage&) As Long
Declare Function L_AnnDeletePage Lib "LTANN13N" ( ByVal pFile$, ByVal nPage&) As Long
Declare Function L_AnnDeletePageMemory Lib "LTANN13N" (ByVal hMem&, ByVal puMemSize&, ByVal nPage&) As Long
Declare Function L_AnnFileInfo Lib "LTANN13N" (ByVal pszFile$, AnnFileInfo As ANNFILEINFO) As Long
Declare Function L_AnnFileInfoOffset Lib "LTANN13N" (ByVal fd&, AnnFileInfo As ANNFILEINFO) As Long
Declare Function L_AnnFileInfoMemory Lib "LTANN13N" (ByVal pMem&, ByVal uMemSize&, AnnFileInfo As ANNFILEINFO) As Long
