/*
   LTFPX.H - file module header file
   Copyright (c) 1991-2000 LEAD Technologies, Inc.
   All Rights Reserved.
*/

#ifndef _LTFPX_H_
#define _LTFPX_H_

typedef struct _FPXCOMMENT_HEADER_ELEMENT
{
   L_UINT32 size;
   L_UINT32 type;
} FPXCOMMENT_HEADER_ELEMENT;

typedef struct _FPXCOMMENT_HEADER_ARRAY
{
   L_UINT32 size;
   L_UINT32 type;
   L_UINT32 elements;
} FPXCOMMENT_HEADER_ARRAY;

typedef enum
{
   FPXENUM_BOOL = 0,            
   FPXENUM_SHORT,          
   FPXENUM_SHORT_ARRAY,      
   FPXENUM_LONG,            
   FPXENUM_LONG_ARRAY,       
   FPXENUM_FLOAT,           
   FPXENUM_FLOAT_ARRAY,       
   FPXENUM_STRING,              
   FPXENUM_STRING_ARRAY,        
   FPXENUM_WIDE_STRING,         
   FPXENUM_WIDE_STRING_ARRAY,   
   FPXENUM_THUMBNAIL,        
   FPXENUM_SPACIAL_FREQUENCY_RESPONSE_BLOCK,   
   FPXENUM_OECF_BLOCK,      
   FPXENUM_CFA_PATTERN_BLOCK,       
   FPXENUM_SCANNED_IMAGE_SIZE_BLOCK,
   FPXENUM_DATE,            
   FPXENUM_SYSTEM_TIME,         
} FPXTYPE_DATA;

typedef enum 
{
   FPXENUM_UNIDENTIFIED_SOURCE = 0,
   FPXENUM_FILM_SCANNER,
   FPXENUM_REFLECTION_PRINT_SCANNER,
   FPXENUM_DIGITAL_CAMERA,
   FPXENUM_STILL_FROM_VIDEO,
   FPXENUM_COMPUTER_GRAPHICS
} FPXTYPE_SOURCE;

typedef enum 
{
   FPXENUM_UNIDENTIFIED_SCENE = 0,
   FPXENUM_ORIGINAL_SCENE,
   FPXENUM_SECOND_GENERATION_SCENE,
   FPXENUM_DIGITAL_SCENE_GENERATION
} FPXTYPE_SCENE;

typedef enum 
{
   FPXENUM_UNIDENTIFIED_EXPOSURE_PROGRAM = 0,
   FPXENUM_MANUAL,
   FPXENUM_PROGRAM_NORMAL,
   FPXENUM_APERTURE_PRIORITY,
   FPXENUM_SHUTTER_PRIORITY,
   FPXENUM_PROGRAM_CREATIVE,
   FPXENUM_PROGRAM_ACTION,
   FPXENUM_PROTRAIT_MODE,
   FPXENUM_LANDSCAPE_MODE
} FPXTYPE_EXPOSURE_PROGRAM;

typedef enum 
{
   FPXENUM_UNIDENTIFED_METERING_MODE = 0,
   FPXENUM_AVERAGE,
   FPXENUM_CENTER_WEIGHTED_AVERAGE,
   FPXENUM_SPOT,
   FPXENUM_MULTI_SPOT
} FPXTYPE_METERING_MODE;

typedef enum 
{
   FPXENUM_UNIDENTIFIED_SCENE_ILLUMINANT = 0,
   FPXENUM_DAYLIGHT,
   FPXENUM_FLUORESCENT_LIGHT,
   FPXENUM_TUNGSTEN_LAMP,
   FPXENUM_FLASH,
   FPXENUM_STANDARD_ILLUMINANT_A,
   FPXENUM_STANDARD_ILLUMINANT_B,
   FPXENUM_STANDARD_ILLUMINANT_C,
   FPXENUM_D55_ILLUMINANT,
   FPXENUM_D65_ILLUMINANT,
   FPXENUM_D75_ILLUMINANT
} FPXTYPE_SCENE_ILLUMINANT;

typedef enum 
{
   FPXENUM_FLASH_USE_UNKNOWN = 0,
   FPXENUM_NO_FLASH_USED,
   FPXENUM_FLASH_USED
} FPXTYPE_FLASH;

typedef enum 
{
   FPXENUM_NOT_A_CAMERA_FEATURE_FLASH_RETURN = 0,
   FPXENUM_SUBJECT_OUTSIDE_FLASH_RANGE,
   FPXENUM_SUBJECT_INSIDE_FLASH_RANGE
} FPXTYPE_FLASH_RETURN;

typedef enum 
{
   FPXENUM_NOT_A_CAMERA_FEATURE_BACKLIGHT = 0,
   FPXENUM_FRONT_LIT,
   FPXENUM_BACK_LIT1,
   FPXENUM_BACK_LIT2
} FPXTYPE_BACK_LIGHT;

typedef enum 
{
   FPXENUM_UNDEFINED = 0,
   FPXENUM_MONOCHROME_AREA_SENSOR,
   FPXENUM_ONE_CHIP_COLOR_AREA_SENSOR,
   FPXENUM_TWO_CHIP_COLOR_AREA_SENSOR,
   FPXENUM_THREE_CHIP_COLOR_AREA_SENSOR,
   FPXENUM_COLOR_SEQUENCIAL_AREA_SENSOR,
   FPXENUM_MONOCHROME_LINEAR_SENSOR,
   FPXENUM_TRILINEAR_SENSOR,
   FPXENUM_COLOR_SEQUENCIAL_LINEAR_SENSOR
} FPXTYPE_SENSING_METHOD;

typedef enum 
{
   FPXENUM_RED = 0,
   FPXENUM_GREEN,
   FPXENUM_BLUE,
   FPXENUM_CYAN,
   FPXENUM_MAGENTA,
   FPXENUM_YELLOW,
   FPXENUM_WHITE
} FPXTYPE_COLOR_FILTER_PATTERN_VALUES;

typedef enum 
{
   FPXENUM_UNIDENTIFIED = 0,
   FPXENUM_NEGATIVE_BW,
   FPXENUM_NEGATIVE_COLOR,
   FPXENUM_REVERSAL_BW,
   FPXENUM_REVERSAL_COLOR,
   FPXENUM_CHROMAGENIC,
   FPXENUM_INTERNEGATIVE_BW,
   FPXENUM_INTERNEGATIVE_COLOR
} FPXTYPE_FILM_CATEGORY;

typedef enum 
{
   FPXENUM_UNIDENTIFIED_ORIGINAL_MEDIUM = 0,
   FPXENUM_CONTINUOUS_TONE_IMAGE,
   FPXENUM_HALFTONE_IMAGE,
   FPXENUM_LINE_ART
} FPXTYPE_ORIGINAL_MEDIUM;

typedef enum 
{
   FPXENUM_UNIDENTIFIED_TYPE_OF_REFLECTION_ORIGINAL = 0,
   FPXENUM_BW_PRINT,
   FPXENUM_COLOR_PRINT,
   FPXENUM_BW_DOCUMENT,
   FPXENUM_COLOR_DOCUMENT
} FPXTYPE_TYPE_OF_REFLECTION_ORIGINAL;

typedef enum 
{
   FPXENUM_INCHES = 0,
   FPXENUM_METERS,
   FPXENUM_CENTIMETERS,
   FPXENUM_MILLIMETERS
} FPXTYPE_RESOLUTION_UNIT;

#endif                          /* _LTFPX_H_ */
