#ifdef _UNICODE
#define MYTEXT TEXT
#else
#define MYTEXT(x) x
#endif

#define L_KEY_DOCUMENT           MYTEXT("xxIjk7ex")
#define L_KEY_GIFLZW             MYTEXT("JnjmyyTss")
#define L_KEY_TIFLZW             MYTEXT("JGgUy78FRRx")
#define L_KEY_FPXEXTENSIONS      MYTEXT("JUhyF76")
#define L_KEY_OCR                MYTEXT("juhDEs")
#define L_KEY_MULTIMEDIA         MYTEXT("XXx7yHHYs")
#define L_KEY_MEDICAL            MYTEXT("HNuhjYre4")
#define L_KEY_MEDICAL_NET        MYTEXT("aHmen27dQQ")
#define L_KEY_VECTOR             MYTEXT("8Xyzraex8")
#define L_KEY_BARCODES_1D        MYTEXT("873TtuHjjj")
#define L_KEY_BARCODES_2D_READ   MYTEXT("JKIDksi299")
#define L_KEY_BARCODES_2D_WRITE  MYTEXT("ASdfqwert9")
#define L_KEY_BARCODES_PDF_READ  MYTEXT("gGsS883zZ")
#define L_KEY_BARCODES_PDF_WRITE MYTEXT("JUHYYYdad5")
#define L_KEY_INTERNET           MYTEXT("diSH732")
#define L_KEY_VECTOR_DWG         MYTEXT("SSaZ887")
#define L_KEY_VECTOR_DXF         MYTEXT("NVvCdi3")
#define L_KEY_VECTOR_MISC        MYTEXT("hHKkNY79")
#define L_KEY_VECTOR_ALL         MYTEXT("JUijhkPL")
#define L_KEY_VECTOR_DWF         MYTEXT("FR5KIJLK")
#define L_KEY_MRC                MYTEXT("i3k5e9x")
#define L_KEY_PDF                MYTEXT("haet23")
#define L_KEY_VECTOR_VIEW        MYTEXT("cvbzm94")
#define L_KEY_DIGITALPAINT       MYTEXT("qwertiup")
#define L_KEY_J2K                MYTEXT("87fwrd")
#define L_KEY_CMW                MYTEXT("apkdjfj")
#define L_KEY_DICOM              MYTEXT("aw98um")
#define L_KEY_EXTGRAY            MYTEXT("T38v8sp")
#define L_KEY_BITONAL            MYTEXT("as7wn8mrk")
#define L_KEY_MEDICAL_SECURITY   MYTEXT("u3vx74h")
#define L_KEY_PDF_SAVE           MYTEXT("")
#define L_KEY_OCR_PDF_OUTPUT     MYTEXT("")
#define L_KEY_BARCODES_DATAMATRIX_READ   MYTEXT("")
#define L_KEY_BARCODES_DATAMATRIX_WRITE  MYTEXT("")
