unit LTSCROCX;
interface

const

  {ScreenCaptureResourceTypes}
  SCR_CAP_ALL    = 0;
  SCR_CAP_BITMAP = 1;
  SCR_CAP_ICON   = 2;
  SCR_CAP_CURSOR = 4;

  {ScreenCaptureExeDlgTypes}
  SCR_CAP_EXEDLG_TABVIEW  = 0;
  SCR_CAP_EXEDLG_TREEVIEW = 1;

  {ScreenCaptureAreaTypes}
  SCR_CAP_AREA_TRIANGLE  = 1;
  SCR_CAP_AREA_RECT      = 2;
  SCR_CAP_AREA_ROUNDRECT = 3;
  SCR_CAP_AREA_ELLIPSE   = 4;
  SCR_CAP_AREA_POLYGON   = 5;
  SCR_CAP_AREA_FREEHAND  = 6;

  {ScreenCaptureWindowTypes}
  SCR_CAP_CLIENT_AREA = 1;
  SCR_CAP_WINDOW      = 2;

  CAPTURE_AREA_PATTERN_HORIZONTAL = 0; { ----- }
  CAPTURE_AREA_PATTERN_VERTICAL   = 1; { ||||| }
  CAPTURE_AREA_PATTERN_FDIAGONAL  = 2; { \\\\\ }
  CAPTURE_AREA_PATTERN_BDIAGONAL  = 3; { ///// }
  CAPTURE_AREA_PATTERN_CROSS      = 4; { +++++ }
  CAPTURE_AREA_PATTERN_DIAGCROSS  = 5; { xxxxx }
  CAPTURE_AREA_PATTERN_SOLID      = 6; {Solid Fill}

  CAPTURE_AREA_LINE_SOLID         = 0; { Solid   }
  CAPTURE_AREA_LINE_DASH          = 1; { ------- }
  CAPTURE_AREA_LINE_DOT           = 2; { ....... }
  CAPTURE_AREA_LINE_DASHDOT       = 3; { _._._._ }
  CAPTURE_AREA_LINE_DASHDOTDOT    = 4; { _.._.._ }

  CAPTURE_AREA_INFOWND_SIZE_TINY   = -1;
  CAPTURE_AREA_INFOWND_SIZE_SMALL  = -2;
  CAPTURE_AREA_INFOWND_SIZE_MEDIUM = -3;
  CAPTURE_AREA_INFOWND_SIZE_LARGE  = -4;
  CAPTURE_AREA_INFOWND_SIZE_XLARGE = -5;

  CAPTURE_AREA_INFOWND_POS_LEFT    = -1;
  CAPTURE_AREA_INFOWND_POS_RIGHT   = -2;
  CAPTURE_AREA_INFOWND_POS_TOP     = -3;
  CAPTURE_AREA_INFOWND_POS_BOTTOM  = -4;

  CAPTURE_AREA_SHOW_DRAWCURSOR       = $0001;
  CAPTURE_AREA_INCLUDE_CURSOR	       = $0002;
  CAPTURE_AREA_ENABLE_KEYBOARD       = $0004;
  CAPTURE_AREA_SHOW_OPAQUE_TEXT      = $0008;
  CAPTURE_AREA_SHOW_CURSORPOS	       = $0010;
  CAPTURE_AREA_SHOW_CAPTURESIZE      = $0020;
  CAPTURE_AREA_SHOW_INFOWINDOW       = $0040;
  CAPTURE_AREA_SENSITIVE_INFOWINDOW  = $0080;
  CAPTURE_AREA_BITMAP_WITH_REGION    = $0100;
  CAPTURE_AREA_USE_DEFAULT_VALUES    = $0200;

  {zooming factors (exclusive)}
  CAPTURE_AREA_ZOOM_NORM          = 1;
  CAPTURE_AREA_ZOOM_BY2X          = 2;
  CAPTURE_AREA_ZOOM_BY3X          = 3;
  CAPTURE_AREA_ZOOM_BY4X          = 4;
  CAPTURE_AREA_ZOOM_BY5X          = 5;
  CAPTURE_AREA_ZOOM_BY6X          = 6;
  CAPTURE_AREA_ZOOM_BY7X          = 7;
  CAPTURE_AREA_ZOOM_BY8X          = 8;
  CAPTURE_AREA_ZOOM_BY9X          = 9;
  CAPTURE_AREA_ZOOM_BY10X         = 10;
  CAPTURE_AREA_ZOOM_BY11X         = 11;
  CAPTURE_AREA_ZOOM_BY12X         = 12;
  CAPTURE_AREA_ZOOM_BY13X         = 13;
  CAPTURE_AREA_ZOOM_BY14X         = 14;
  CAPTURE_AREA_ZOOM_BY15X         = 15;

  CAPTURE_OBJECT_INVERT	          = $0001;
  CAPTURE_OBJECT_ENABLE_KEYBOARD  = $0002;

  {HotKeyModifierConstants}
  SCR_MOD_ALT     =    $0001;
  SCR_MOD_CONTROL =    $0002;
  SCR_MOD_SHIFT   =    $0004;

implementation
end.
