// Funktionsdeklarationen fÅr unabhÑngige Funktionen
// File: GEO_DEF.HXX

// IRISWIN: %W%	%E%

#ifndef _GEO_DEF_HXX
#define _GEO_DEF_HXX

// Hilfsfunktionen
INLINE short shortMin (short x, short y);
INLINE short shortMax (short x, short y);
INLINE long longMin (long x, long y);
INLINE long longMax (long x, long y); 

INLINE KoOrd KoOrdAbs (KoOrd x);
INLINE KoOrd KoOrdMin (KoOrd x, KoOrd y);
INLINE KoOrd KoOrdMax (KoOrd x, KoOrd y);

#endif
