
//////////////////////////////////////////////////////////////////////////////
//
//  Copyright (c) 1990-94, Compiler Resources, Inc.
//
//  FILENAME:             yy_help.h
//  
//  FILE DESCRIPTION:     insert file with help support declarations.
//  
//  MODIFICATION HISTORY:
//  
//    08/07/92   bz       removed macros and #ifdefs in C++ only version.
//    03/30/90   bz/cc    coding and final review completed.
//  
//////////////////////////////////////////////////////////////////////////////

#ifndef yy_help_h_
#define yy_help_h_

//////////////////////////////////////////////////////////////////////////////
//
//  FUNCTION DECLARATIONS
//
//  yy_help               prints help messages for invocation and command 
//                        line options.
//
//////////////////////////////////////////////////////////////////////////////

void yy_help(void);

#endif
