# gui/Makefile
# Copyright (c) 1998, Regents of the University of California
# $Id: Makefile,v 1.1 1999/06/21 00:33:50 marcel Exp $

include ../Makefile.inc

SRCS = MainWindow.java \
	ConsoleWindow.java \
	OpThread.java \
	Breakpoint.java \
	BreakHandler.java \
	Breakpoints.java \
	BpTableModel.java \
	BreakInfo.java \
	Properties.java \
	DbgOutput.java


CLASSES = $(SRCS:.java=.class)

all: $(CLASSES)

clean:
	$(RM) *.class core

cleanmake:

depend:

# DO NOT DELETE THIS LINE -- make depend depends on it.
