//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Trias322.RC
//
#define VER_DEBUG                       0
#define IDR_MSGTABLE                    1
#define IDD_SCHRIFTARTOBJ               100
#define IDI_DEINSTALL                   102
#define IDS_POINTS                      1003
#define IDS_LINES                       1004
#define IDCB_ROUNDFRAME                 1005
#define IDS_AREAS                       1005
#define IDCB_LEFTTEXT                   1006
#define IDS_TEXTS                       1006
#define IDCB_CENTREDTEXT                1007
#define IDCB_RIGHTTEXT                  1008
#define IDCB_JUSTIFIED                  1009
#define IDS_POSTEXTATBASELINE           1035
#define IDS_COMPATIBILITY_16BIT         1133
#define IDS_PBDCOMENTRY                 1252
#define IDS_COMPBDNAME                  1253
#define IDS_CTFDISTANCEEX               1435
#define IDS_HDRUNIQUESYSMCODE           1500
#define IDS_HDRUNIQUESYSICODE           1501
#define IDS_NODEPOBJPROP                1502
#define IDS_NODEPOBJECT                 1503
#define IDS_KONSCAPTION                 5000
#define IDS_KONSBADGEOMETRIE            5001
#define IDS_KONSINVADDR                 5002
#define IDS_KONSDELRECORD               5003
#define IDS_KONSPOINT                   5004
#define IDS_KONSLINE                    5005
#define IDS_KONSAREA                    5006
#define IDS_KONSTEXT                    5007
#define IDS_KONSKOMPLEX                 5008
#define IDS_KONSSACH                    5009
#define IDS_KONSOBJECT                  5010
#define IDS_KONSBADCOORD                5011
#define IDS_KONSBADZVGO                 5012
#define IDS_KONSVIEW                    5013
#define IDS_KONSIDENT                   5014
#define IDS_KONSBADZVIO                 5015
#define IDS_KONSBADZVOM                 5016
#define IDS_KONSBADZVMO                 5017
#define IDS_KONSBADZDBT                 5018
#define IDS_KONSBADZMI                  5019
#define IDS_FILEKAL                     5020
#define IDS_FILESPL                     5021
#define IDS_FILEKPL                     5022
#define IDS_FILEMAL                     5023
#define IDS_FILEKFL                     5024
#define IDS_FILEVGO                     5025
#define IDS_FILEOBL                     5026
#define IDS_FILEVOG                     5027
#define IDS_FILEVOM                     5028
#define IDS_FILEMKL                     5029
#define IDS_FILEVMO                     5030
#define IDS_FILEVOR                     5031
#define IDS_FILEREL                     5032
#define IDS_FILEIDL                     5033
#define IDS_FILEVIO                     5034
#define IDS_FILEVRE                     5035
#define IDS_FILERAL                     5036
#define IDS_FILEDBT                     5037
#define IDS_FILEHKE                     5038
#define IDS_FILEHTK                     5039
#define IDS_FILEQKE                     5040
#define IDS_FILEQTK                     5041
#define IDS_FILEMKK                     5042
#define IDS_FILEIDK                     5043
#define IDS_FILERLK                     5044
#define IDS_FILEHDR                     5045
#define IDS_FILEHDK                     5046
#define IDS_FILEVIS                     5047
#define IDS_FILEATT                     5048
#define IDS_FILEVSK                     5049
#define IDS_FILEVAT                     5050
#define IDS_FILEBMI                     5051
#define IDS_KONSDUPZVIO                 5052
#define IDS_KONSDUPZVOM                 5053
#define IDS_KONSDUPZVMO                 5054
#define IDS_KONSDUPZDBT                 5055
#define IDS_KONSDUPZMI                  5056
#define IDS_KONSDUPZVGO                 5057
#define IDS_RECORDKAL                   5060
#define IDS_RECORDKPL                   5061
#define IDS_RECORDSPL                   5062
#define IDS_RECORDMAL                   5063
#define IDS_RECORDKFK                   5064
#define IDS_RECORDKFM                   5065
#define IDS_RECORDOBL                   5066
#define IDS_RECORDREL                   5067
#define IDS_RECORDIDL                   5068
#define IDS_RECORDMKL                   5069
#define IDS_RECORDMI                    5070
#define IDS_RECORDDBT                   5071
#define IDS_RECORDVGO                   5072
#define IDS_RECORDVZO                   5073
#define IDS_RECORDVOL                   5074
#define IDS_RECORDVOA                   5075
#define IDS_RECORDVOM                   5076
#define IDS_RECORDVMO                   5077
#define IDS_RECORDVOR                   5078
#define IDS_RECORDVIO                   5079
#define IDS_RECORDVRE                   5080
#define IDS_RECORDRAL                   5081
#define IDS_RECORDPOL                   5082
#define IDS_RECORDHEAD                  5083
#define IDS_RECORDFHEAD                 5084
#define IDS_RECORDSICHT                 5085
#define IDS_RECORDPATTRIBS              5086
#define IDS_RECORDLATTRIBS              5087
#define IDS_RECORDFATTRIBS              5088
#define IDS_RECORDRELTYP                5089
#define IDS_RECORDTATTRIBS              5090
#define IDS_RECORDBINMI                 5091
#define IDS_RECORDKDBT                  5091
#define IDS_RECORDOBLNEW                5092
#define IDS_RECORDMCODEB                5093
#define IDS_RECORDIDENTB                5094
#define IDS_RECORDLONGSPL               5095
#define IDS_KONSUNKNOWN                 5100
#define IDS_NOTEXT                      5101
#define IDS_KONSQUERYTEXT               5102
#define IDS_CSSERRORCAPTION             5103
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        104
#define _APS_NEXT_COMMAND_VALUE         101
#define _APS_NEXT_CONTROL_VALUE         1009
#define _APS_NEXT_SYMED_VALUE           102
#endif
#endif
