	///////////////////////////////////////////////////////////////////////////////
	// @doc STRUCT TRIASCS
	// @struct CSGUID | Unsere 'eigene' GUID - Deklaration
	// @devnote CSGUID ist genau dasselbe wie ein GUID; nur mit einem anderen Namen
	// ohne diesen zweiten Namen würde das '#import' - Statement
	// nur Fehler produzieren...
	// @index | CSGUID
	typedef struct CSGUID {
		DWORD Data1;		// @field ...
		WORD   Data2;		// @field ...
		WORD   Data3;		// @field ...
		BYTE  Data4[8];		// @field ...
	} CSGUID;
