// $Header: $
// Copyright© 1998-2002 GEOPunkt GmbH & Co. KG, NL Potsdam, All rights reserved
// Created: 25.02.2002 16:45:45 
//
// This file was generated by the TRiASDB Data Server Wizard V1.02.117 (#HK010502)
//
// THIS CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT WARRANTY OF ANY 
// KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
// IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A PARTICULAR 
// PURPOSE.
//
// @doc
// @module Strings.cpp | Definition of global string constants

#include "stdafx.h"
#include "strings.h"

///////////////////////////////////////////////////////////////////////////////
// sonstiges
const TCHAR g_cbNil[] = _T("");

///////////////////////////////////////////////////////////////////////////////
// Properties
const OLECHAR g_cbTRiASCSService[] = L"TRiASCSService";
const OLECHAR g_cbTRiASCSTransform[] = L"TRiASCSTransform";
// BEGIN_SAMPLEDATA
const OLECHAR g_cbObjectsCursor[] = L"ObjectsCursor";
const OLECHAR g_cbObjectCursor[] = L"ObjectCursor";
const OLECHAR g_cbFeatureCursor[] = L"FeatureCursor";
const OLECHAR g_cbCSSGuid[] = L"CSSGuid";
const OLECHAR g_cbObjectMap[] = L"ObjectMap";
const OLECHAR g_cbObjectsMap[] = L"ObjectsMap";
const OLECHAR g_cbFeatureMap[] = L"FeatureMap";
// END_SAMPLE_DATA

/////////////////////////////////////////////////////////////////////////////
// SuchPattern für Objektklassenschlüssel
const TCHAR g_cbOKS[] = 
TEXT("\\[\\([[:xdigit:]]+\\)\\]" "\\|"							// [OKS]
	 "\\(\\([[:xdigit:]]+\\)[[:punct:][:blank:]].*\\)" "\\|"	// OKS:irgend was
	 "\\[\\([[:xdigit:]]+\\)\\]\\(.*\\)"  "\\|"					// [OKS]irgend was
	 "!\\(.*\\):\\[\\([[:xdigit:]]+\\)\\]\\(.*\\)"				// !irgendwas:[OKS]irgendwas (Monikerformat)
	);

/////////////////////////////////////////////////////////////////////////////
// Standardnamen für diverse Objekteigenschaften
const OLECHAR g_cbGeometry[] = L"Geometry";
const OLECHAR g_cbObjektname[] = L"Objektname";

///////////////////////////////////////////////////////////////////////////////
// Monikersupport
const TCHAR g_cbMkObjectsDef[] = TEXT("MkObjectsDef");
const TCHAR g_cbMkObjectDef[] = TEXT("MkObjectDef");
const TCHAR g_cbMkConnection[] = TEXT("MkConnection");
const TCHAR g_cbMkProject[] = TEXT("MkProject");
const TCHAR g_cbMkFeature[] = TEXT("MkFeature");
const OLECHAR g_cbMkDel[] =  L"!";
const OLECHAR g_cbMkWild[] = L"\\";

const TCHAR g_cbCollatePattern[] = TEXT(";%1=%2");

/////////////////////////////////////////////////////////////////////////////
// ProgID des zugehörigen Database-Objektes
const OLECHAR g_cbDatabase[] = L"TRiASDB.PolyGIS.Database.1";


