// $Header: $
// Copyright© 1998-2002 GEOPunkt GmbH & Co. KG, NL Potsdam, All rights reserved
// Created: 25.02.2002 16:45:45 
//
// This file was generated by the TRiASDB Data Server Wizard V1.02.117 (#HK010502)
//
// THIS CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT WARRANTY OF ANY 
// KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
// IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A PARTICULAR 
// PURPOSE.
//
// @doc
// @module strings.h | Declaration of global string constants

#if !defined(_STRINGS_H__A259FF25_F6F4_4ED0_ACEC_4AA7C6537799__INCLUDED_)
#define _STRINGS_H__A259FF25_F6F4_4ED0_ACEC_4AA7C6537799__INCLUDED_

#if _MSC_VER >= 1000
#pragma once
#endif // _MSC_VER >= 1000

// Header include diagnostics
#if defined(_TRIAS_DBG_HEADER_DIAGNOSTICS)
#pragma message(__TIME__": include " __FILE__ )
#endif

///////////////////////////////////////////////////////////////////////////////
// sonstiges
extern const TCHAR g_cbNil[];						// _T("");

///////////////////////////////////////////////////////////////////////////////
// Properties
extern const OLECHAR g_cbTRiASCSService[];			// L"TRiASCSService";
extern const OLECHAR g_cbTRiASCSTransform[];		// L"TRiASCSTransform";
// BEGIN_SAMPLE_DATA
extern const OLECHAR g_cbObjectsCursor[];			// L"ObjectsCursor";
extern const OLECHAR g_cbObjectCursor[];			// L"ObjectCursor";
extern const OLECHAR g_cbFeatureCursor[];			// L"FeatureCursor";
extern const OLECHAR g_cbCSSGuid[];					// L"CSSGuid";
extern const OLECHAR g_cbObjectMap[];				// L"ObjectMap";
extern const OLECHAR g_cbObjectsMap[];				// L"ObjectsMap";
extern const OLECHAR g_cbFeatureMap[];				// L"FeatureMap";
// END_SAMPLE_DATA

/////////////////////////////////////////////////////////////////////////////
// SuchPattern für Objektklassenschlüssel
extern const TCHAR g_cbOKS[];
//TEXT("\\[\\([[:xdigit:]]+\\)\\]" "\\|"						// [OKS]
//	 "\\(\\([[:xdigit:]]+\\)[[:punct:][:blank:]].*\\)" "\\|"	// OKS:irgend was
//	 "\\[\\([[:xdigit:]]+\\)\\]\\(.*\\)"  "\\|"					// [OKS]irgend was
//	 "!\\(.*\\):\\[\\([[:xdigit:]]+\\)\\]\\(.*\\)"				// !irgendwas:[OKS]irgendwas (Monikerformat)
//	);

/////////////////////////////////////////////////////////////////////////////
// Standardnamen für diverse Objekteigenschaften
extern const OLECHAR g_cbGeometry[];				// L"Geometry";
extern const OLECHAR g_cbObjektname[];				// L"Objektname";

///////////////////////////////////////////////////////////////////////////////
// Monikersupport
extern const TCHAR g_cbMkObjectsDef[];				// TEXT("MkObjectsDef");
extern const TCHAR g_cbMkObjectDef[];				// TEXT("MkObjectDef");
extern const TCHAR g_cbMkConnection[];				// TEXT("MkConnection");
extern const TCHAR g_cbMkProject[];					// TEXT("MkProject");
extern const TCHAR g_cbMkFeature[];					// TEXT("MkFeature");
extern const OLECHAR g_cbMkDel[];					// L"!";
extern const OLECHAR g_cbMkWild[];					// L"\\";

extern const TCHAR g_cbCollatePattern[];			// TEXT(";%1=%2");

/////////////////////////////////////////////////////////////////////////////
// ProgID des zugehörigen Database-Objektes
extern const OLECHAR g_cbDatabase[];				// L"TRiASDB.PolyGIS.Database.1";

#endif // !defined(_STRINGS_H__A259FF25_F6F4_4ED0_ACEC_4AA7C6537799__INCLUDED_)
