// $Header: $
// Copyright© 1998-2002 GEOPunkt GmbH & Co. KG, NL Potsdam, All rights reserved
// Created: 25.02.2002 16:45:45 
//
// This file was generated by the TRiASDB Data Server Wizard V1.02.117 (#HK010502)
//
// THIS CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT WARRANTY OF ANY 
// KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
// IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A PARTICULAR 
// PURPOSE.
//
// @doc
// @module TDBPGISObjectsCollection.h | Declaration of the <c CTDBPGISObjectsCollection> class

#if !defined(_TDBPGISOBJECTSCOLLECTION_H__5335E2BE_A791_4FD6_AC0B_BDEEA5378CA9__INCLUDED_)
#define _TDBPGISOBJECTSCOLLECTION_H__5335E2BE_A791_4FD6_AC0B_BDEEA5378CA9__INCLUDED_

#if _MSC_VER >= 1000
#pragma once
#endif // _MSC_VER >= 1000

// Header include diagnostics
#if defined(_TRIAS_DBG_HEADER_DIAGNOSTICS)
#pragma message(__TIME__": include " __FILE__ )
#endif

#include "resource.h"       // main symbols

/////////////////////////////////////////////////////////////////////////////
// CTDBPGISObjectsCollection
class ATL_NO_VTABLE CTDBPGISObjectsCollection : 
	public CComObjectRootEx<CComObjectThreadModel>,
	public CComCoClass<CTDBPGISObjectsCollection, &CLSID_TDBPGISObjectsCollection>,
	public CErrSupport<CTDBPGISObjectsCollection, &IID_ITRiASObjectsCollection>,
	public ITRiASObjectsCollectionCallback
{
public:
	CTDBPGISObjectsCollection()
	{
	}

	_ATLX_DEBUG_OBJECTCOUNT_IMPL(CTDBPGISObjectsCollection)

	DECLARE_REGISTRY_RESOURCEID(IDR_TDBPGISOBJECTSCOLLECTION_RGS)
	DECLARE_AGGREGATE_EX_SUPPORT();

	BEGIN_COM_MAP(CTDBPGISObjectsCollection)
		COM_INTERFACE_ENTRY(ITRiASObjectsCollectionCallback)
		COM_INTERFACE_ENTRY(ISupportErrorInfo)

	// durch aggregiertes Objekt implementierte Interfaces
		COM_INTERFACE_ENTRY_AGGREGATE_EX(IID_ITRiASObjectsCollection, m_BaseUnk.p)
		COM_INTERFACE_ENTRY_AGGREGATE_EX(IID_ITRiASBase, m_BaseUnk.p)
		COM_INTERFACE_ENTRY_AGGREGATE_EX(IID_IDispatch, m_BaseUnk.p)
		COM_INTERFACE_ENTRY_AGGREGATE_BLIND(m_BaseUnk.p)		// alles andere nicht gesondert behandeln
	END_COM_MAP()

	DECLARE_GET_CONTROLLING_UNKNOWN()
	DECLARE_PROTECT_FINAL_CONSTRUCT()
	HRESULT FinalConstruct()
	{
		RETURN_FAILED_HRESULT(m_BaseUnk.CreateInstance (CLSID_TRiASObjectsCollection, CLSCTX_ALL, GetControllingUnknown()));

	WTRiASObjectsCollection BaseObj;

		RETURN_FAILED_HRESULT(m_BaseUnk -> QueryInterface(BaseObj.ppi()));
		return BaseObj -> putref_ObjectsCollectionCallback(this);
	}
	void FinalRelease()
	{
		m_BaseUnk.Assign(NULL);
	}

// ISupportsErrorInfo
	STDMETHOD(InterfaceSupportsErrorInfo)(REFIID riid);

// ITRiASObjectsCollectionCallback
public:
	STDMETHOD(get_DefaultType)(BSTR *pbstrType);
	STDMETHOD(OnCreate)(VARIANT NameOrHandle, BSTR Type, OBJECTSCOLLECTIONTYPE rgType, ITRiASObjects **ppIObjs);
	STDMETHOD(OnDelete)(VARIANT vWhich);
	STDMETHOD(OnFinalRelease)();

#if defined(_READ_WRITE)
protected:
	HRESULT CreateObject (VARIANT NameOrHandle, DWORD dwType, const CLSID *pClsId, ITRiASObjects **ppIObjs);
#endif // defined(_READ_WRITE)

private:
	WUnknown m_BaseUnk;					// aggregiertes Objekt
};

#endif // !defined(_TDBPGISOBJECTSCOLLECTION_H__5335E2BE_A791_4FD6_AC0B_BDEEA5378CA9__INCLUDED_)
