// $Header: $
// Copyright© 1998-2002 GEOPunkt GmbH & Co. KG, NL Potsdam, All rights reserved
// Created: 25.02.2002 16:45:45
//
// This file was generated by the TRiASDB Data Server Wizard V1.02.117 (#HK010502)
//
// THIS CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT WARRANTY OF ANY 
// KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
// IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A PARTICULAR 
// PURPOSE.
//
// @doc 
// @module TDBPGISEngine.h | Databaseengine für TRiASDB Data Server TDBPGIS

#if !defined(_TDBPGISDBENGINE_H__0179A455_47DE_4023_9043_AFE8512CD7C0__INCLUDED_)
#define _TDBPGISDBENGINE_H__0179A455_47DE_4023_9043_AFE8512CD7C0__INCLUDED_

#if _MSC_VER >= 1000
#pragma once
#endif // _MSC_VER >= 1000

// Header include diagnostics
#if defined(_TRIAS_DBG_HEADER_DIAGNOSTICS)
#pragma message(__TIME__": include " __FILE__ )
#endif

#include "resource.h"       // main symbols
#include "CPTDBPGISDBEngineEvents.h"

/////////////////////////////////////////////////////////////////////////////
// CTDBPGISDBEngine
class ATL_NO_VTABLE CTDBPGISDBEngine : 
	public CComObjectRootEx<CComObjectThreadModel>,
	public CErrSupport<CTDBPGISDBEngine, &IID_ITRiASDBEngine>,
	public CComCoClass<CTDBPGISDBEngine, &CLSID_TDBPGISDBEngine>,
	public IConnectionPointContainerImpl<CTDBPGISDBEngine>,
	public CProxyITRiASDBEngineEvents<CTDBPGISDBEngine>,
	public IDispatchImpl<ITRiASDBEngine, &IID_ITRiASDBEngine, &LIBID_TRiASDB,
		TYPELIB_TRiASDB_VERSION_MAJOR, TYPELIB_TRiASDB_VERSION_MINOR>
{
public:
	CTDBPGISDBEngine()
		: m_fIsStarted(false),
		  m_bstrUserName(g_cbNil), m_bstrPassword(g_cbNil)
	{
	}

	_ATLX_DEBUG_OBJECTCOUNT_IMPL(CTDBPGISDBEngine)

	DECLARE_REGISTRY_RESOURCEID(IDR_TDBPGISDBENGINE_RGS)
	DECLARE_PROTECT_FINAL_CONSTRUCT()
	DECLARE_CLASSFACTORY_SINGLETON(CTDBPGISDBEngine)	// DBEngines existieren nur einmal

	BEGIN_COM_MAP(CTDBPGISDBEngine)
		COM_INTERFACE_ENTRY(ITRiASDBEngine)
		COM_INTERFACE_ENTRY(ISupportErrorInfo)
		COM_INTERFACE_ENTRY(IDispatch)
	END_COM_MAP()

	BEGIN_CONNECTION_POINT_MAP(CTDBPGISDBEngine)
		CONNECTION_POINT_ENTRY(IID_ITRiASDBEngineEvents)
	END_CONNECTION_POINT_MAP()

	HRESULT FinalConstruct();
	void FinalRelease();

// ISupportsErrorInfo
	STDMETHOD(InterfaceSupportsErrorInfo)(REFIID riid);

// ITRiASDBEngine
public:
	STDMETHOD(get_Version)(BSTR *pVal);
	STDMETHOD(put_Password)(BSTR bstrPwd);
	STDMETHOD(put_UserName)(BSTR bstrUser);
	STDMETHOD(get_Description)(BSTR *pVal);

	STDMETHOD(Start)(STARTMODE Mode);
	STDMETHOD(EnumDataBaseTypes)(IUnknown **ppIEnum);
	STDMETHOD(Stop)();

public:
// Konvertieren Blob <--> _DGMGeometry
	HRESULT StorageToGeometry (const VARIANT &Blob, GEOMETRYTYPE *prgType, IDispatch **ppIGeometry) throw(_com_error &)
	{
		_ASSERTE(m_Service.IsValid());
		return m_Service -> StorageToGeometry (Blob, prgType, ppIGeometry);
	}
	HRESULT GeometryToStorage (GEOMETRYTYPE rgType, IDispatch *pIGeometry, VARIANT *pBlob) throw(_com_error &)
	{
		_ASSERTE(m_Service.IsValid());
		return m_Service -> GeometryToStorage (rgType, pIGeometry, pBlob);
	}

private:
	bool m_fIsStarted;			// Engine wurde gestartet
	CComBSTR m_bstrUserName;	// Nutzername (optional)
	CComBSTR m_bstrPassword;	// Paßword (optional)

	WTRiASCSStorageService m_Service;	// Service für Geometrieoperationen
};

/////////////////////////////////////////////////////////////////////////////
// globale Instanz der DBEngine
extern CTDBPGISDBEngine *g_pDBEngine;
extern STARTMODE g_rgStartMode;

#endif // !defined(_TDBPGISDBENGINE_H__0179A455_47DE_4023_9043_AFE8512CD7C0__INCLUDED_)
