// linesig.odl : type library source for OLE Control project.

// This file will be processed by the Make Type Library (mktyplib) tool to
// produce the type library (karten.tlb) that will become a resource in
// linesig.vmd.

// #include <olectl.h>

[ uuid(1380ead5-04af-11d0-AC37-00A024145748), version(1.0), helpstring("Vismodule for linesignatures"), control ]
library LinesigLib
{
	importlib("stdole.tlb");
	// importlib("STDTYPE.TLB");

	//  Primary dispatch interface for CKartenCtrl
	[ uuid(51C39830-04B2-11d0-AC38-00A024145748), helpstring("Dispatch interface for Linesig.vmd"), hidden ]
	dispinterface _DKarten
	{
		properties:
			// NOTE - ClassWizard will maintain property information here.
			//    Use extreme caution when editing this section.
			//{{AFX_ODL_PROP(CKartenCtrl)
			//}}AFX_ODL_PROP

		methods:
			// NOTE - ClassWizard will maintain method information here.
			//    Use extreme caution when editing this section.
			//{{AFX_ODL_METHOD(CKartenCtrl)
			//}}AFX_ODL_METHOD
	};

	//  Event dispatch interface for CKartenCtrl

	[ uuid(51C39831-04B2-11d0-AC38-00A024145748), helpstring("Event interface for Linesig.vmd") ]
	dispinterface _DKartenEvents
	{
		properties:
			//  Event interface has no properties

		methods:
			// NOTE - ClassWizard will maintain event information here.
			//    Use extreme caution when editing this section.
			//{{AFX_ODL_EVENT(CKartenCtrl)
			//}}AFX_ODL_EVENT
	};

	//  Class information for CKartenCtrl

#ifdef _WIN32
	[ uuid(07963892-3123-101C-BB62-00AA0018497C), helpstring("Linesig.vmd"), control ]
#else
	[ uuid(321C58E0-0C60-101B-AAE1-E7E7E7E7E7E7), helpstring("Linesig.vmd"), control ]
#endif
	coclass Linesig
	{
		[default] dispinterface _DKarten;
		[default, source] dispinterface _DKartenEvents;
	};

	//{{AFX_APPEND_ODL}}
};
