//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by gak.rc
//
#define IDD_ABOUTBOX                    100
#define IDD_GAK_FORM                    101
#define IDM_SEND_NUMBER                 101
#define IDS_CREATE_TABLE                101
#define IDM_SEND_DELETEOBJ              102
#define IDD_PARAMS                      102
#define DATEI                           102
#define IDP_FAILED_OPEN_DATABASE        103
#define IDM_SEND_TEXT                   103
#define IDD_DOABGLEICH                  103
#define IDD_RESULT                      104
#define IDD_ABFART_PARAMS               105
#define IDD_OUTPUT_TABLE                106
#define IDM_DOABGLEICH                  106
#define IDM_STATISTIK                   107
#define IDD_BRANCHE_PARAM               107
#define IDM_HELP_DATABSE_ERRORS         108
#define IDS_LIZENS                      110
#define IDM_POPUP                       110
#define IDS_FUER                        112
#define IDC_USER_NAME                   113
#define IDM_EXPORT                      114
#define IDD_SELECT_TABLE                114
#define IDT_PROGRESS                    115
#define IDT_ACTIONTEXT                  116
#define IDD_ERZ_INFO                    116
#define IDD_RECHERCHESTATUS             117
#define IDD_EXPORT_TABLES               118
#define IDD_EXPORT_RESULT               119
#define IDC_ERZ_CNT                     120
#define IDC_ABF_CNT                     121
#define IDC_SUM_CNT                     122
#define IDB_AFIS                        123
#define IDC_AFIS                        124
#define IDC_KREISE                      125
#define IDD_AFI                         126
#define IDR_MAINFRAME                   128
#define IDR_GAKTYPE                     129
#define IDD_ANFALLSTELLE                131
#define IDD_FIRMA                       132
#define IDD_ENTSORGUNG                  133
#define IDD_BRANCHE                     134
#define IDD_ANSPRECH                    135
#define IDD_SEL_NUMMER                  137
#define IDD_USER_NAME                   138
#define IDD_LOOK_NR                     140
#define IDD_SEARCH_RESULT               141
#define IDD_CHANGE_ERZ_NR               145
#define IDD_COMPACT_DATABASE            146
#define IDD_ABFAELLE                    148
#define IDD_TRANSPORTEUR                162
#define IDD_FELDINFO                    163
#define IDD_ENTSORGER                   164
#define IDD_QUERY_SELECT                165
#define IDD_QUERY_DEF                   166
#define IDD_QUERY_PARAM                 168
#define IDD_QUERY_RESULT                169
#define IDD_INPUT_TABLE_NAME            170
#define IDD_IMPORT_INPUT                171
#define IDD_RECORDS_SELECT              174
#define IDD_IMPORT_SUM                  175
#define IDD_DO_IMPORT                   176
#define IDD_IMPORT_RESULT               177
#define IDD_IMPORT_QUERY                178
#define IDD_STATISTIK                   179
#define IDB_IMAGE_LIST                  180
#define IDD_BETREIBER                   186
#define IDD_ERZEUGER_PARAM              196
#define IDD_GEBIET_PARAM                197
#define IDD_ABFALL_PARAM                199
#define IDD_RESULT_PARAM                201
#define IDI_ICON1                       203
#define IDB_ERZBILANZ                   205
#define IDD_ENTSORGER1                  206
#define IDD_DOKONTROLLE                 207
#define IDD_REPORT_TABLE                208
#define IDE_ANFALLSTELLE                1004
#define IDE_FIRMA                       1005
#define IDE_OUTPUT_DB                   1007
#define IDE_STRASSE                     1008
#define IDB_OUTPUT_DB                   1008
#define IDE_HNR                         1009
#define IDE_MENGE2                      1009
#define IDE_ORT                         1010
#define IDE_MENGE_REC                   1010
#define IDE_PLZ                         1011
#define IDC_ERZEUGER_TABLE              1012
#define IDE_ART                         1014
#define IDC_ABFALL_TABLE                1014
#define IDE_BETRIEB                     1015
#define IDC_BGS_TABLE                   1015
#define IDB_SONDERABFALL                1016
#define IDC_VJABFALL_TABLE              1017
#define IDB_ESCAPE                      1018
#define IDT_AKTION                      1019
#define IDE_GKZ                         1023
#define IDT_PROGRESS2                   1024
#define IDT_ABGL_CNT                    1026
#define IDE_COMMENT                     1027
#define IDT_UEBERN_CNT                  1027
#define IDT_INLISTE_DEL_CNT             1028
#define IDB_CHANGE                      1029
#define IDB_CHANGE_VERF                 1030
#define IDE_NAME                        1031
#define IDE_BB_NAME                     1032
#define IDE_TELEFON                     1034
#define IDE_TELEFAX                     1035
#define IDE_TRANSPORTEUR                1035
#define IDE_NUMMER                      1036
#define IDE_BETREIBER_NR                1036
#define IDE_BB_TELEFON                  1036
#define IDE_ENTSORGER                   1036
#define IDE_BILANZ_NR                   1037
#define IDE_BB_TELEFAX                  1037
#define IDC_SELECT                      1038
#define IDB_CREATE_ERZLISTE             1038
#define IDT_ERZLISTE                    1039
#define IDB_GET_ADDRESS                 1040
#define IDB_INLISTE                     1040
#define IDE_USER_NAME                   1041
#define IDE_NUMBER                      1042
#define IDT_ESC_CNT                     1042
#define IDL_NUMMERN                     1043
#define IDB_ABFAELLE                    1044
#define IDB_OUTPUT_ERZLISTE             1044
#define IDC_FOUND                       1047
#define IDE_ERZ_NUMMER                  1047
#define IDB_GR_EQ                       1048
#define IDB_GR                          1049
#define IDB_EQ                          1050
#define IDE_TABLE                       1050
#define IDB_LESS                        1051
#define IDL_LIST_TABLES                 1051
#define IDB_LESS_EQ                     1052
#define IDB_ABGLEICH                    1052
#define IDB_LIKE                        1053
#define IDB_STAMM                       1054
#define IDB_KONTROLLE                   1054
#define IDB_RD1                         1055
#define IDB_RD2                         1056
#define IDB_RD3                         1057
#define IDS_INFOTEXT                    1060
#define IDB_FILE_NAME                   1062
#define IDB_ERZ_INFO                    1062
#define IDB_VERSION10                   1063
#define IDE_ENSN_NR                     1063
#define IDB_VERSION11                   1064
#define IDE_RD_VERFAHREN                1064
#define IDB_VERSION20                   1065
#define IDE_PRIO                        1065
#define IDB_VERSION30                   1066
#define IDE_ABFALLART                   1066
#define IDB_AS_NEW                      1068
#define IDE_FILENAME                    1069
#define IDB_STORE_DATA                  1070
#define IDT_DELETED_REC                 1071
#define IDL_ABFALLART                   1072
#define IDB_ERZ_NR                      1072
#define IDT_BRANCHE                     1073
#define IDB_ARTNEU                      1074
#define IDT_PARTNER                     1074
#define IDB_ARTDEL                      1075
#define IDT_ANF_STELLE                  1075
#define IDT_ANF_ORT                     1076
#define IDT_TEL                         1077
#define IDC_LIST                        1077
#define IDL_ABFALL_VJN                  1078
#define IDT_FAX                         1078
#define IDT_FIRMA                       1079
#define IDL_ABFALLN                     1080
#define IDL_BGSN                        1081
#define IDT_STRASSE                     1081
#define IDE_MENGEM                      1082
#define IDE_ASN                         1082
#define IDE_MENGET                      1083
#define IDE_FERZNR                      1088
#define IDE_ABFART                      1089
#define IDB_ARTCHA                      1090
#define IDE_DICHTE                      1091
#define IDC_FELDINFO                    1094
#define IDE_SEARCH                      1099
#define IDC_CNT                         1101
#define IDE_BEMERKUNGEN                 1109
#define IDB_EIGENTRANSPORT              1111
#define IDE_SEARCH_NUMBER               1112
#define IDC_QUERIES                     1113
#define IDB_AENDERN                     1114
#define IDB_NEU                         1115
#define IDB_DELETE                      1116
#define IDE_SQL                         1120
#define IDE_PARAM                       1121
#define IDS_TYPE                        1122
#define IDC_QUERY_LIST                  1123
#define IDB_ALLE                        1124
#define IDB_ONLY_SELECTED               1125
#define IDB_FELDNAMEN                   1126
#define IDB_COPY                        1127
#define IDS_FOUND                       1129
#define IDB_DATENBLATT                  1130
#define IDB_QUERY_LISTE                 1131
#define IDS_SELECT_INFO                 1132
#define IDL_TABLES                      1133
#define IDL_FIELDS                      1134
#define IDL_FUNCTIONS                   1135
#define IDL_OPERATORS                   1136
#define IDE_DESCRPITION                 1137
#define IDB_ED_BACK                     1138
#define IDB_CHECK                       1139
#define IDC_TABLES                      1140
#define IDC_FUNCTIONS                   1141
#define IDC_FIELDS                      1142
#define IDC_OPERATORS                   1143
#define IDB_TABLE                       1145
#define IDB_MDB_TABLE                   1147
#define IDB_FOX_TABLE                   1148
#define IDB_ERZEUGER                    1151
#define IDB_ABFALL                      1152
#define IDB_BRANCH                      1153
#define IDB_TRANSPORTEURE               1154
#define IDB_ENTSORGER                   1155
#define IDB_GEMEINDEN                   1156
#define IDB_ABFALL_ARTEN                1157
#define IDE_PATH                        1158
#define IDE_TABLE_NAME                  1162
#define IDB_CREATE                      1163
#define IDS_INFO                        1164
#define IDB_ALL_RECORDS                 1172
#define IDB_ONLY_REFERENZ               1173
#define IDB_ONLY_NOT_REFERENZ           1174
#define IDB_ALWAYS_MOD                  1175
#define IDB_NEVER_MOD                   1177
#define IDS_INPUT_DATABASE              1178
#define IDS_INPUT_TABLE                 1179
#define IDS_OUTPUT_DATABASE             1180
#define IDS_OUTPUT_TABLE                1181
#define IDS_ACTUAL                      1184
#define IDS_SELECTED                    1185
#define IDC_PROGRESS                    1186
#define IDS_AKTION                      1187
#define IDS_ACT_CNT                     1188
#define IDS_NEW_CNT                     1189
#define IDS_ACT_ERR_CNT                 1190
#define IDS_NEW_ERR_CNT                 1191
#define IDS_SUM_CNT                     1192
#define IDS_SUM_ERR_CNT                 1193
#define IDB_SHOW_PROTOKOLL              1194
#define IDB_ALWAYS_INDEX                1195
#define IDS_AS_NEW_TABLE                1197
#define IDB_IMPORT                      1198
#define IDL_QUERIES                     1199
#define IDB_SELECT                      1200
#define IDS_ALLE                        1204
#define IDT_TABLES                      1205
#define IDS_ONLY_VALIDS                 1205
#define IDB_ERROR_HELP                  1206
#define IDS_SONDER_ABFALL               1209
#define IDS_ARTEN_INFO                  1210
#define IDB_STANDARD                    1211
#define IDM_CALL_ADMIN                  1211
#define IDB_QUERY_ART                   1212
#define IDM_CONFIG_DSN                  1212
#define IDB_OLD_VERSION                 1214
#define IDB_OLD_VERSION_FOX             1215
#define IDE_PARTNER                     1216
#define IDE_KREIS_KUERZEL               1217
#define IDE_FUNKTION                    1221
#define IDE_BIMSCH_NUMMER               1222
#define IDC_SPALTE                      1223
#define IDE_BIMSCH_NUMMERG              1224
#define IDB_LIEGT_VOR                   1225
#define IDE_ANUMMER                     1226
#define IDB_VORBEHANDLUNG               1227
#define IDE_INTERNE_BEZ                 1228
#define IDB_EIGEN                       1230
#define IDB_FREI                        1232
#define IDE_FREI_NR                     1233
#define IDE_VERBRINGUNG                 1238
#define IDB_KREISE                      1239
#define IDB_VERBRINGUNG                 1240
#define IDL_NUMMERN_ERZ                 1241
#define IDE_VERFAHREN                   1242
#define IDB_VERFAHREN                   1243
#define IDE_NACHWEIS_NR                 1244
#define IDE_EAK_NR                      1245
#define IDB_UNTERSCHRIFT                1246
#define IDE_ERZ_NR                      1249
#define IDB_GEMEINDE_SEL                1253
#define IDB_KREIS_SEL                   1254
#define IDT_GEMEINDE                    1255
#define IDB_ONLY_SONDER_ABF             1260
#define IDE_ABF_BEZ                     1266
#define IDE_MENGE                       1267
#define IDE_RESULT                      1272
#define IDT_QUERY_NAME                  1273
#define IDB_ALLE_GEMEINDEN              1274
#define IDB_ALL_ABF                     1279
#define IDE_DATABASE                    1281
#define IDB_SELECT_DB                   1284
#define IDB_SONDER_ABF                  1285
#define IDC_COPYCLIPBOARD               1287
#define IDC_ERZLISTDRUCK                1288
#define IDC_ERZLISTDRUCKVOR             1289
#define IDC_PLACEHOLDER                 1290
#define IDC_ONLYNOTEXPORTED             1291
#define IDC_ANFALLSTELLE                1292
#define IDC_BRANCHENNUMMER              1293
#define IDC_ABFALLBEZ                   1294
#define IDC_BEFOERDNAME                 1295
#define IDC_BEFOERDORT                  1296
#define IDC_BEFOERDSTR                  1297
#define IDC_ENTSORGNAME                 1298
#define IDC_ENTSORGORT                  1299
#define IDC_ENTSORGSTR                  1300
#define IDC_SELECTBEFOERD               1301
#define IDC_SELECTENTSORG               1302
#define IDC_ENTSORGANLAGE               1303
#define IDC_BEFOERDKOMMENTAR            1304
#define IDC_ENTSORGKOMMENTAR            1305
#define IDM_STAMMDATEN                  32771
#define IDM_LOOK_NR                     32772
#define IDS_EINGABE_STD                 32773
#define IDM_ABFALL                      32774
#define IDS_NAME                        32775
#define IDM_NEW_REKORD                  32776
#define IDM_COPY                        32777
#define IDM_DELETE_REKORD               32778
#define IDM_INSERT                      32779
#define IDM_CHANGE_KEY                  32780
#define IDM_CUT                         32781
#define IDM_SET_BOOKMARK                32782
#define IDM_DELETE                      32783
#define IDM_GOTO_BOOKMARK               32784
#define IDM_BACK                        32785
#define IDS_NUMMER_EXIST                32786
#define IDM_SELECT                      32787
#define IDS_GEMEINDE_CAPTION            32788
#define IDM_DRUCK_ERZLISTE              32789
#define IDS_BR_TABLE_NAME               32790
#define IDM_AKTBILANZ                   32791
#define IDM_LAST_ABGLEICH               32792
#define IDS_GEM_TABLE_NAME              32793
#define IDM_ABGLEICH_AKT                32794
#define IDS_OUTPUT_TABLE_INFO           32795
#define IDM_ODBC_ACESS                  32796
#define IDS_QUERY_OK                    32797
#define IDM_AKTBILANZ_2                 32798
#define IDS_SELECT_AUSWAHL              32799
#define IDM_ABGLEICH_AKTNEW             32800
#define IDS_FIND_NUMMER                 32801
#define IDS_CHANGE_NR                   32802
#define IDM_COMPACT_DATABASE            32803
#define IDS_REC_USED                    32804
#define IDS_ERZ_PRIM_INDEX              32805
#define IDS_NO_REC_FOUND                32806
#define IDS_ENTER_NR                    32807
#define IDS_FOUND_RESULT                32808
#define IDS_SELECT_NUMBER               32809
#define IDS_GREATER_EQUAL               32810
#define IDS_GREATER                     32811
#define IDS_EQUAL                       32812
#define IDS_LESS_EQUAL                  32813
#define IDS_LESS                        32814
#define IDS_WHERE_KLAUSEL               32815
#define IDS_LIKE                        32816
#define IDS_NO_DRECORD_FOUND            32817
#define IDS_NUMMER                      32818
#define IDS_BRANCHE_CAPTION             32819
#define IDS_CONFIG_SECTION              32820
#define IDS_DATEN_ENTRY                 32821
#define IDS_ST_NUMMER_INDEX             32822
#define IDS_COMPACT_DATABASE            32823
#define IDS_DATABASE_EXTENSION          32824
#define IDS_DIFF_DATABASE               32825
#define IDS_MDB_FILTER                  32826
#define IDM_REPAIR_DATABASE             32827
#define IDM_RECHERCHE                   32828
#define IDS_PAGE_HEADER                 32829
#define IDS_NO_PRINT_ENGINE             32830
#define IDS_ERZEUGER_FORMULAR           32831
#define IDS_ABF_TABLE_ENTRY             32832
#define IDS_ABF_TABLE_NAME              32833
#define IDS_ABFALL_INDEX                32834
#define IDS_ERZ_TABLE_NAME              32835
#define IDS_ERZ_TABLE_ENTRY             32836
#define IDS_ABFALL_DATEN_CAPT           32837
#define IDS_ABFALL_FORMULAR             32838
#define IDS_KEINE                       32839
#define IDS_SELECT_NUMMER_WW            32840
#define IDS_DELETE_ERZ                  32841
#define IDS_REPAIR_DATABASE             32842
#define IDS_COMPACT_DATASE              32843
#define IDS_SELECT_FELDINFO             32844
#define IDS_FELDNAME                    32845
#define IDS_ABFART_CAPTION              32846
#define IDS_ABFART_TABLE_NAME           32847
#define IDS_FELDINHALT                  32848
#define IDS_SEL_ABF_ARTEN               32849
#define IDS_JA                          32850
#define IDS_NEIN                        32851
#define IDS_TR_TABLE_NAME               32852
#define IDS_TRANSP_CAPTION              32853
#define IDS_SELBST                      32854
#define IDS_TRANSP_SELECT               32855
#define IDS_ENTS_SELECT                 32856
#define IDS_ENTS_TABLE_NAME             32857
#define IDS_ENTS_CAPTION                32858
#define IDS_ABF_CAPT_FORMAT             32859
#define IDS_DELETE_ABFALL               32860
#define IDS_SELECT_NR                   32861
#define IDS_NUMMER_NOT_EXIST            32862
#define IDS_DELETE_ABFGR                32863
#define IDS_INFO_SECTION                32864
#define IDS_INFO_FUER                   32865
#define IDS_INFO_LIZENS                 32866
#define IDS_CONFIG_ONLY_VALID_TRANS     32867
#define IDS_TRANS_WHERE                 32868
#define IDS_ENTS_WHERE                  32869
#define IDS_CONFIG_ONLY_VALID_ENTS      32870
#define IDS_DATE_FORMAT                 32871
#define IDS_QUERY_SELECTION             32872
#define IDS_QUERY_ACTION                32873
#define IDS_QUERY_CROSSTAB              32874
#define IDS_QUERY_DELETE                32875
#define IDS_QUERY_UPDATE                32876
#define IDS_QUERY_APPEND                32877
#define IDS_QUERY_MAKE_TABLE            32878
#define IDS_QUERY_DDL                   32879
#define IDS_QUERY_PASS_THR              32880
#define IDS_QUERY_UNION                 32881
#define IDS_QUERY_UNKNOWN               32882
#define IDS_QUERY_NAME                  32883
#define IDS_QUERY_TYPE                  32884
#define IDS_QUERY_AEND                  32885
#define IDS_QUERY_RETREC                32886
#define IDS_QUERY_SQLST                 32887
#define IDS_DATETIME_FORMAT             32888
#define IDS_DELETE_QUERY                32889
#define IDS_NEW_QUERY                   32890
#define IDS_MODIFY_QUERY                32891
#define IDS_UNKN_QUERY                  32892
#define IDS_DORECHERCHE                 32893
#define IDS_QUERY_PARAM_INFO            32894
#define IDS_TYPE_PARAM                  32895
#define IDS_TEXT                        32896
#define IDS_BOOLEAN                     32897
#define IDS_BYTE                        32898
#define IDS_ERROR_HELP_FILE_NAME        32899
#define IDS_WAEHRUNG                    32900
#define IDS_LOOK_ERZEUGER               32901
#define IDS_DATUM                       32902
#define IDS_QUERY_TEMP                  32903
#define IDS_QUERY_RES_CAPTION           32904
#define IDS_QUERY_RESULT_FOUND          32905
#define IDS_SATZ                        32906
#define IDS_NO_REC_FOUND_QUERY          32907
#define IDS_CLIPB_ERROR                 32908
#define IDS_CHECK_SELECT                32909
#define IDS_NUMMER_QUERY                32910
#define IDS_UNKNOWN_DATA_TYPE           32911
#define IDS_MEMO                        32912
#define IDS_DABASE_ERROR_FORMAT         32913
#define IDS_FIELD_INFO                  32914
#define IDS_TABLE_INFO                  32915
#define IDS_BRACKETS                    32916
#define IDS_TABLE_COUNT                 32917
#define IDS_FIELD_COUNT                 32918
#define IDS_FUNCTION_COUNT              32919
#define IDS_OPERA_COUNT                 32920
#define IDS_COPY_IN_TABLE               32921
#define IDS_COPY_TOCL                   32922
#define IDS_INIT_QUERY_RESULT           32923
#define IDS_BEREIT                      32924
#define IDM_IMPORT                      32925
#define IDS_FOXPRO_EXTENSION            32926
#define IDS_FOXPRO_FILTER               32927
#define IDS_FOXPRO_CONNECT              32928
#define IDS_SELECT_ALL                  32929
#define IDS_AND_KLAUSEL                 32930
#define IDS_NO_VALID_STRUCTUR           32931
#define IDS_DATABASE_NAME               32932
#define IDS_GEM_TABLE_ENTRY             32933
#define IDS_BR_TABLE_ENTRY              32934
#define IDS_ABFART_TABLE_ENTRY          32935
#define IDS_TRANSP_TABLE_ENTRY          32936
#define IDS_ENTS_TABLE_ENTRY            32937
#define IDS_ABFA_INDEX_NAME             32938
#define IDS_BRANCHEN_DDL                32939
#define IDS_GEMEINDEN_DDL               32940
#define IDS_ABFALL_DDL                  32941
#define IDS_ERZEUGER_DDL                32942
#define IDS_ABFALLARTEN_DDL             32943
#define IDS_ENTSORGER_DDL               32944
#define IDS_TRANSPORTEURE_DDL           32945
#define IDS_CREATE_INDEX_DDL            32946
#define IDS_DISALLOW_NULL               32947
#define IDS_IMPORT_ALL_RECORDS          32948
#define IDS_IMPORT_ONLY_REF             32949
#define IDS_IMPORT_WITHOUT_REF          32950
#define IDS_ACTUAL_AUTOMATIC            32951
#define IDS_DATABASE_CONNECT            32952
#define IDS_ACTUAL_NEVER                32953
#define IDS_DIFF_IN_OUT_TABLE           32954
#define IDS_BEENDEN                     32955
#define IDS_GET_RECORD_COUNT            32956
#define IDS_SELECT_COUNT                32957
#define IDS_DO_IMPORT                   32958
#define IDS_SEARCH_FIELD                32959
#define IDS_ERR_EXT                     32960
#define IDS_IMPORT_HEAD                 32961
#define IDS_REPORT_ERR_FORMAT           32962
#define IDS_EMPTY_INPUT_TABLE           32963
#define IDS_EDIT_COMMAND                32964
#define IDS_UPDATE_IMPORT_CNT           32965
#define IDS_NEW_IMPORT_CNT              32966
#define IDS_UPDATE_IMPORT_ERRCNT        32967
#define IDS_APPEND_IMPORT_ERRCNT        32968
#define IDS_SUMME_IMPORT_CNT            32969
#define IDS_SUMME_IMPORT_ERRCNT         32970
#define IDS_ABFRAGEN                    32971
#define IDS_AUTOMATIC_INDEX             32972
#define IDS_TABLE_NOT_FOUND             32973
#define IDS_ABF_TABLE_NAME_DESCR        32974
#define IDS_TABLE_ENTRY                 32975
#define IDS_ENTRY_FORMAT                32976
#define IDS_FIND_DICHTE                 32977
#define IDS_SELECT_DICHTEART            32978
#define IDS_TEXT_ALL_SELECT             32979
#define IDS_TEXT_NO_SELECT              32980
#define IDS_IMP_QUERY_CAPTION           32981
#define IDS_NO_QUERIES                  32982
#define IDS_DIFF_IN_OUT_DB              32983
#define IDS_QUERY_INFO                  32984
#define IDS_STAT_CAPT_FORMAT            32985
#define IDS_INTEGER                     32986
#define IDS_LONG_INTEGER                32987
#define IDS_TABELLEN                    32988
#define IDS_FELDER                      32989
#define IDS_INDICES                     32990
#define IDS_RELATIONS                   32991
#define IDS_SINGLE                      32992
#define IDS_DOUBLE                      32993
#define IDS_LONG_BINARY                 32994
#define IDS_GUID                        32995
#define IDS_POSITION                    32996
#define IDS_COLLECTION_FORMAT           32997
#define IDS_STANDARD_QUEYRIES           32998
#define IDS_BILANZ_QUERIES              32999
#define IDS_STANDARD_QUEYRY             33000
#define IDS_BILANZ_QUERY                33001
#define IDS_UNKNOWN_QUERY_PARAM         33002
#define IDS_INI_ENTRIES                 33003
#define IDS_ENTSORGER                   33004
#define IDS_TRANSP                      33005
#define IDS_KREISE_DDL                  33006
#define IDS_KUERZEL                     33007
#define IDS_REPORT_FFORMAT              33008
#define IDS_DSN_GAK                     33009
#define IDS_CONFIG_DSN                  33010
#define IDS_VERBR_TABLE_ENTRY           33011
#define IDS_VERBR_TABLE_NAME            33012
#define IDS_VERBRC_CAPTION              33013
#define IDS_KREISE_TABLE_ENTRY          33014
#define IDS_KREISE_TABLE_NAME           33015
#define IDS_VERBRINGUNG_DDL             33016
#define IDS_VERFAHREN_TABLE_ENTRY       33017
#define IDS_VERFAHREN_TABLE_NAME        33018
#define IDS_VERFAHREN_DDL               33019
#define IDS_VERFAHREN_CAPTION           33020
#define IDS_COMPACT_CAPTION             33021
#define IDS_SELECT_DB_CAPTION           33022
#define IDS_BOOL_VALUES                 33023
#define IDS_DSNGLEICH                   57347
#define IDS_ODBCINI                     57348
#define IDS_DSNSECTION                  57349
#define IDS_DEFAULT_DIR                 57350
#define IDB_WEITER                      57671
#define IDM_NEW_ABGLEICH                61207
#define IDS_FOXPRO_DSN                  61208
#define IDS_MDB_DSN                     61209
#define IDS_NOMEMORY                    61210
#define IDS_FILE_ERROR                  61214
#define IDS_SELECT_ABFART               61216
#define IDS_BILANZEN_SELECT             61217
#define IDS_TABLE_EXIST                 61220
#define IDS_UEBERNEHMEN                 61221
#define IDS_CREATE_OUTPUT_TABLE         61222
#define IDS_READ_ABFART_TABLE           61223
#define IDS_READ_ABFALL_TABLE           61224
#define IDS_READ_ABFALLBGS_TABLE        61225
#define IDS_READ_ERZ_TABLE              61226
#define IDS_CREATE_TABLE_TEXT           61228
#define IDS_INDEX_REGNR                 61229
#define IDS_INDEX_ABFART                61230
#define IDS_JA2                         61231
#define IDS_NEIN2                       61232
#define IDS_OUTPUT_RECORDS              61233
#define IDS_ABBRUCH                     61234
#define IDS_BEREIT2                     61235
#define IDS_ABFART_TABLE                61236
#define IDS_ERZEUGER_CAPTION            61238
#define IDS_SEARCH_NEXT_ERZ             61242
#define IDS_SEARCH_CAPTION              61243
#define IDS_ABFART_CAPTION2             61244
#define IDS_DELETE_TABLE2               61245
#define IDS_CREATE_ERZLISTE             61246
#define IDS_CREATE_ERZLISTE_TABLE       61247
#define IDS_SELECT_ERZSET               61250
#define IDS_LISTE_OHNE                  61252
#define IDS_ERZ_LISTE                   61253
#define IDS_LISTE_LISTE                 61254
#define IDS_ERZLISTE_SELECT             61257
#define IDS_ERZLISTE_TXT                61258
#define IDS_FILE_NOT_FOUND              61259
#define IDS_TOO_MANY_OPEN_FILES         61260
#define IDS_ASSESS_DENIED               61261
#define IDS_REMOVE_CURRENT_DIR          61262
#define IDS_DIRECTORY_FULL              61263
#define IDS_HARD_IO                     61264
#define IDS_LOCK_VIOLATION              61265
#define IDS_INTERNAL_ERROR              61268
#define IDS_ERZ_TABLE_ERROR             61270
#define IDS_BILANZ_TABLE_ERROR          61272
#define IDS_BGS_TABLE_ERROR             61274
#define IDS_ERZLISTE_TABLE_ERROR        61275
#define IDS_ABFARTEN_TABLE_ERROR        61276
#define IDS_NO_LIST_RECORDS             61277
#define IDS_SAVE_STATUS                 61278
#define IDS_CONFIG                      61279
#define IDS_ERZEUGER_KEY                61280
#define IDS_BILANZ_KEY                  61281
#define IDS_BGS_KEY                     61282
#define IDS_OUTPUT_KEY                  61283
#define IDS_ERZLIST_KEY                 61284
#define IDS_ERZNAME_KEY                 61285
#define IDS_ONLY_SONDER_ABFALL_KEY      61288
#define IDS_MENGEN_SCHWELLE_KEY         61291
#define IDS_DSNGLEICH2                  61294
#define IDS_ODBCINI2                    61295
#define IDS_DSNSECTION2                 61296
#define IDS_DEFAULT_DIR2                61297
#define IDS_CREATE_ACCESSDSN            61298
#define IDS_CREATE_FOXDSN               61302
#define IDS_ERZLISTE_SEL                61303
#define IDS_SELECT_OUTPUT_TABLE         61304
#define IDS_PRIO_FIELDNAME              61305
#define IDS_BEARBEITET_FIELDNAME        61306
#define IDS_ALTER_TABLE                 61308
#define IDS_BILANZ_KEY_VJ               61312
#define IDS_PRIO_KEY                    61313
#define IDS_MODUS_KEY                   61314
#define IDS_MENGEN_SCHWELLE_KEY_REC     61315
#define IDS_START_TEXT1                 61316
#define IDS_START_TEXT2                 61317
#define IDS_DELETE_RECS                 61318
#define IDS_NUMMER_FILTER               61319
#define IDS_NOT_BEARBEITET              61320
#define IDS_FILTER_PRIO123              61321
#define IDS_FILTER_PRIO23               61322
#define IDS_NUMMER_FILTER_EQ            61323
#define IDS_MENGEN_FILTER               61324
#define IDS_SORT_ERZNR_ASN              61325
#define IDS_NO_RECORDS_FOUND            61326
#define IDS_READ_ABFALLVJ_TABLE         61327
#define IDS_NUMMER2                     61328
#define IDS_ERZ_NUMMER_FILTER           61329
#define IDS_ASN_NR                      61330
#define IDS_ABF_NR                      61331
#define IDS_ERZSTATUS_KEY               61332
#define IDS_ERZNR_FILTER                61333
#define IDS_SELECT_SET_ABGL             61334
#define IDS_NOT_BEARBEITET_PARAM        61335
#define IDS_ONLY_SONDER_ABFALL          61336
#define IDS_SELECT_SET_ABGL1            61337
#define IDS_ERZ_ASN_FILTER              61338
#define IDS_BGS_ERZ_ASN_FILTER          61339
#define IDS_ERZ_NOT_FOUND2              61340
#define IDS_MENGE_BGS_FILTER            61342
#define IDS_OUTPUT_SET                  61343
#define IDS_DATEN_ABGLEICH              61344
#define IDS_DATEN_KONTROLLE             61345
#define IDS_ERZEUGER_SELECT             61346
#define IDS_ASN_KEY                     61347
#define IDS_ONLY_THIS_ERZ_KEY           61348
#define IDS_ERZEUGER_NOT_FOUND          61349
#define IDS_READ_ABFALL_TABLEVJ         61350
#define IDS_MENGE_FROM_LISTE            61351
#define IDS_MENGE_FROM_BILANZ           61352
#define IDS_FILTER_ERZNZ_BILANZ         61353
#define IDS_FILTER_ASN_BILANZ           61356
#define IDS_NO_ABGL_RECORDS             61357
#define IDS_NO_KONTRL_RECORDS           61358
#define IDS_ABBRUCH_KONTROLLE           61359
#define IDS_CONTROL_CAPTION             61360
#define IDS_DELETE_RECORDS              61361
#define IDS_SAVE_STATUS_C               61362
#define IDS_ERZ_NR_FILTER               61363
#define IDS_ERZB_NR_FILTER              61364
#define IDS_BGS_ERZABF_TABLE            61365
#define IDS_CREATE_TEMP_TABLE           61366
#define IDS_CREATE_BGS_TABEL            61367
#define IDS_SEARCH_ERZ                  61368
#define IDS_NOT_FOUND                   61369
#define IDS_MENU_COPY                   61370
#define IDS_CLIPB_ERROR2                61371
#define IDS_ERZNR_ASN_FILTER            61372
#define IDS_DELETE_FROM                 61373
#define IDS_UPDATE_KLAUSEL              61374
#define IDS_ERZNR_ASNB_FILTER           61375
#define IDS_ERZNR_BRBRG_FORMAT          61446
#define IDS_ERZNR_BRBRG                 61447
#define IDS_SIZEORG                     61448
#define IDS_SIZEORG_FORMAT              61449
#define IDS_BILANZ_ERZ_KENNUNG          61450
#define IDS_ERZ_NOT_FOUND               61451
#define IDS_ABF_NOT_FOUND               61452
#define IDS_PREPARE_DISK                61453
#define IDS_RUECK_OUT_CAPTION           61454
#define IDS_DIFF_NAMES                  61455
#define IDS_PREPARE_EXPORT              61456
#define IDS_NO_RECORDS                  61457
#define IDS_EXPORT_TABLES               61458
#define IDS_EXPORT_TABLE_FORMAT         61459
#define IDS_DELETE_TABLE                61460
#define IDS_ERZEUGER_PARAM              61461
#define IDS_QUERY_PARAM_TITLE           61462
#define IDS_DATE_VALUES                 61463
#define IDS_BRANCHE_PARAM               61464
#define IDS_GEMEINDE_PARAM              61465
#define IDS_ALLE_GEMEINDEN_PARAM        61466
#define IDS_KREIS_PARAM                 61467
#define IDS_ALLE_KREISE_PARAM           61468
#define IDS_KREIS_CAPTION               61469
#define IDS_ABF_ART_PARAM               61470
#define IDS_ALLE_ABF_ART_PARAM          61471
#define IDS_ONLY_SONDER_ABF_PARAM       61472
#define IDS_MENGE_PARAM                 61473
#define IDS_OR                          61474
#define IDS_ALLE_BRANCHEN_PARAM         61475
#define IDS_SELECT_AFIS                 61476
#define IDS_SELECT_AFI                  61477
#define IDS_SELECT_NAME                 61478
#define IDS_WHERE_GKZ                   61479
#define IDS_LDB_EXT                     61480
#define IDS_FIELD_NOT_FOUND             61480
#define IDS_FIELD_NO_TYPE               61481
#define IDS_FIELD_NO_LEN                61482
#define IDS_TABLE_OUT_CAPTION           61483

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        212
#define _APS_NEXT_COMMAND_VALUE         33024
#define _APS_NEXT_CONTROL_VALUE         1306
#define _APS_NEXT_SYMED_VALUE           127
#endif
#endif
