//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Trias323.RC
//
#define IDS_GLOBALUNDOLIST              1
#define IDR_TYPELIB                     1
#define IDR_REGISTRYHELPER              1
#define IDS_GLOBALREDOLIST              2
#define IDS_UNDOCREATEFEATURE           3
#define IDB_REPLACEALL                  3
#define IDS_UNDOEDITFEATURE             4
#define IDB_REPLACE                     4
#define IDS_UNDODELETEFEATURE           5
#define IDS_UNDODELETETEXT              6
#define IDS_UNDOCREATETEXT              7
#define IDS_UNDODELETERELATION          8
#define IDS_UNDOCREATERELATION          9
#define IDS_DELETEOBJHWND               10
#define IDS_UNDODELETEOBJECT            11
#define IDS_UNDOMODIFYOBJECT            12
#define IDS_FILETEMPLATE                13
#define IDS_UNDOCREATEPBDDATA           14
#define IDS_UNDOCREATEPBDDATA2          15
#define IDS_UNDOCREATEPBDDATA3          16
#define IDS_UNDOCREATEPBDDATA4          17
#define IDS_UNDODELETEPBDDATA           18
#define IDS_UNDODELETEPBDDATA2          19
#define IDS_UNDODELETEPBDDATA3          20
#define IDS_UNDODELETEPBDDATA4          21
#define IDS_UNDOEDITPBDDATA             22
#define IDS_UNDOEDITPBDDATA2            23
#define IDS_UNDOEDITPBDDATA3            24
#define IDS_UNDOEDITPBDDATA4            25
#define IDS_HEADERIDENT                 26
#define IDS_HEADERDESC                  27
#define IDS_UNDOVISINFO                 28
#define IDS_UNDOMODIDENT                29
#define IDS_GENERRORCAP                 30
#define IDS_ADDERROR                    31
#define IDS_QUERYCONTINUE               32
#define IDS_PROPINFO_IDENTOTYP          33
#define IDS_HELPDESC_IDENTOTYP          34
#define IDS_PROPGROUPNAME               35
#define IDS_PROPINFO_CLASSIFYOBJ        35
#define IDS_PROPINFO_MODIDENT           36
#define IDS_HELPDESC_MODIDENT           37
#define IDS_UNDOMODIDENTS               38
#define IDS_PROPINFO_OBJWND             39
#define IDS_HELPDESC_OBJWND             40
#define IDS_HELPDESC_PROPSEQUENCE       41
#define IDS_PROPINFO_PROPSEQUENCE       42
#define IDS_ENUMOBJECTSBYNMUMBER        43
#define IDS_PROPINFO_ORWNDDEST          44
#define IDS_HELPDESC_ORWNDDEST          45
#define IDS_NEWOBJCAPTION               46
#define IDS_TEXTSEARCHENGINE_DESC       47
#define IDS_REGISTRAR_DESC              48
#define IDS_NOT_IN_MAP                  49
#define IDS_UNEXPECTED_EOS              50
#define IDS_VALUE_SET_FAILED            51
#define IDS_RECURSE_DELETE_FAILED       52
#define IDS_EXPECTING_EQUAL             53
#define IDS_CREATE_KEY_FAILED           54
#define IDS_DELETE_KEY_FAILED           55
#define IDS_OPEN_KEY_FAILED             56
#define IDS_CLOSE_KEY_FAILED            57
#define IDS_UNABLE_TO_COERCE            58
#define IDS_BAD_HKEY                    59
#define IDS_MISSING_OPENKEY_TOKEN       60
#define IDS_CONVERT_FAILED              61
#define IDS_TYPE_NOT_SUPPORTED          62
#define IDS_COULD_NOT_CONCAT            63
#define IDS_COMPOUND_KEY                64
#define IDS_INVALID_MAPKEY              65
#define IDS_UNSUPPORTED_VT              66
#define IDS_VALUE_GET_FAILED            67
#define IDS_VALUE_TOO_LARGE             68
#define IDS_MISSING_VALUE_DELIMETER     69
#define IDS_DATA_NOT_BYTE_ALIGNED       70
#define IDS_UNDOCREATEOBJECT            71
#define IDS_NOOBJECTSFOUND              72
#define IDS_PROPINFO_DELOBJECT          73
#define IDS_HELPDESC_DELOBJECT          74
#define IDS_DELOBJECTRESULT             75
#define IDS_DELOBJECTSTATUS             76
#define IDS_PROPINFO_CREATETEXT         77
#define IDS_HELPDESC_CREATETEXT         78
#define IDS_REPLACEOBJHWND              79
#define IDS_ADDTOOBJHWND                80
#define IDS_HELPDESC_CLASSIFYOBJ        81
#define IDS_NOVALUE                     82
#define IDS_PROPINFO_IMPORTDATA         83
#define IDS_HELPDESC_IMPORTDATA         84
#define IDS_IMPORTFMTDLGCAP             85
#define IDS_NOIMPORTFILTERS             86
#define IDS_IMPORTNOMULTISEL            87
#define IDS_GENTEXTPROPACT_DESC         88
#define IDS_HELPDESC_GENTEXTPROPACT     89
#define IDS_NODEPOBJPROP                90
#define IDS_SCRIPTPROPACT_DESC          90
#define IDS_SCRIPTPROPACT_HELPDESC      91
#define IDS_STANDARDSTATUSTEXT          92
#define IDS_HEADERCONN                  93
#define IDS_NOWRITEABLECONNECTIONS      94
#define IDS_HEADERTYP                   95
#define IDS_DESCRIPTION_SELECTEXPORTOBJECTS 96
#define IDS_NOOPENCONNECTIONS           97
#define IDS_EXPORTFMTDLGCAP             98
#define IDS_SELFREGISTERSUCCEEDED       99
#define IDS_SELFREGISTERFAILED          100
#define IDD_STATUSDLG                   101
#define IDB_SELALLCLASSES               101
#define IDS_LOADLIBRARYFAILED           101
#define IDR_TEXTREPLACEENGINE           101
#define IDT_FILE                        102
#define IDS_NOSELFREGISTER              102
#define IDS_ENTRYPOINTNOTFOUND          103
#define IDD_GENERATEOBJECTPROPERTIES_SELECTPROPS 103
#define IDB_PLFT_SMALL                  104
#define IDS_MAKEOBJCLASS_DESC           104
#define IDD_SAVEOBJECTCOLLECTION_OPTIONS 104
#define IDB_PLFT_LARGE                  105
#define IDD_SELECTIDS_WIZ               105
#define IDS_ADDASOBJECTCLASS_UNDO       105
#define IDD_OBJECTROP_WIZ               106
#define IDB_PLFT_SMALL1                 106
#define IDS_DESCRIPTION_TEXTREPLACEENGINE 106
#define IDD_SELECTREL_WIZ               107
#define IDS_DESCRIPTION_DELETEOBJECTPROPERTY 107
#define IDD_SELECTOBJWND_WIZ            108
#define IDS_UNDO_REPLACE                108
#define IDT_TIME                        109
#define IDD_DESTOBJWND_WIZ              109
#define IDR_TEXTSEARCHENGINE            109
#define IDS_UNDO_DELETEPROPERTY         109
#define IDD_MODIFYIDS_WIZ               110
#define IDR_PROPINFO_IDENTOTYP          110
#define IDS_DESCRIPTION_PROPERTYOPERATION 110
#define IDD_TEXTSEARCHENGINE_CFG        111
#define IDR_PROPINFO_MODIDENT           111
#define IDS_DESCRIPTION_PROPERTYACTIONJOIN 111
#define IDR_PROPINFO_OBJWND             112
#define IDD_TEXTSEARCHENGINE_CFG_WIN32S 112
#define IDS_DESCRIPTION_PROPERTYACTIONSPLIT 112
#define IDR_PROPINFO_PROPSEQUENCE       113
#define IDD_SELECT_OBJPROPS             113
#define IDS_DESCRIPTION_GENERATEOBJECTPROPERTIES 113
#define IDR_PROPINFO_ORWNDDEST          114
#define IDD_STATUSDLG_AVI               114
#define IDS_OBJPROPERTY_COLUMN          114
#define IDR_ENUMOBJECTSBYNMUMBER        115
#define IDD_CREATETEXTS_WIZ             115
#define IDS_GROUP_COLUMN                115
#define IDI_DEINSTALL                   116
#define IDD_IMPORT_WIZ                  116
#define IDS_SUBGROUP_COLUMN             116
#define IDB_ARROW_RIGHT                 117
#define IDD_SELECTIDS_WIZPP             117
#define IDS_DELIMITER_SPACE             117
#define IDB_ARROW_RIGHT_SEL             118
#define IDR_REGEXPR                     118
#define IDD_SELECTFROMDS_WIZ            118
#define IDS_DELIMITER_COMMA             118
#define IDB_ARROW_RIGHT_DISABLED        119
#define IDB_OBJPROPTYPES                119
#define IDD_SELECTFROMDS_WIZPP          119
#define IDS_DELIMITER_SEMICOLON         119
#define IDB_ARROW_RIGHT_FOCUS           120
#define IDS_DELIMITER_TABULATOR         120
#define IDS_COLUMNHEADER                121
#define IDB_ARROW_DOWN_DISABLED         122
#define IDD_OBJPROPDESTWINDOW           122
#define IDS_COLUMN_NUMBER               122
#define IDB_ARROW_DOWN_FOCUS            123
#define IDS_ORIGINDEL_COMMENT           123
#define IDB_ARROW_DOWN_SEL              124
#define IDS_ORIGINMARK_COMMENT          124
#define IDB_ARROW_DOWN                  125
#define IDS_WARNIFTOMANYORWNDS          125
#define IDS_CLASSIFYCAPTION             126
#define IDS_COPYNOTUSED                 127
#define IDS_COPYNOTUSED_COMMENT         127
#define IDR_PROGRESSINDICATOR_RGS       128
#define IDS_DELIMITER_NODELIMITER       128
#define IDS_NUMMER                      129
#define IDR_MULTIPI_RGS                 130
#define IDS_INDEX                       130
#define IDR_PROPINFO_DELOBJECT          131
#define IDS_COUNT                       131
#define IDR_PROPINFO_CREATETEXT_RGS     132
#define IDS_DATASOURCE                  132
#define IDB_CHECKMARKS_NT               133
#define IDS_UNDOCLONEOBJECT             133
#define IDB_CHECKMARKS_40               134
#define IDM_DUMMY                       134
#define IDS_COPYOBJECTS_UNDO            134
#define IDR_REGISTEREXT_RGS             135
#define IDS_NOOPENWRITABLECONNECTIONS   135
#define IDR_REGISTRY                    136
#define IDS_COPYOBJECTSFMTDLGCAP        136
#define IDR_PROPINFO_CLASSIFYBYOBJPROP  137
#define IDS_DATASOURCE_NOTRO            137
#define IDS_DESCRIPTION_LIMITSEARCHES   138
#define IDS_WARNOBJECTDELETE            139
#define IDR_PROPINFO_IMPORTDATA         140
#define IDS_LIMIT_PACKETS               140
#define IDS_NOLIMIT_PACKETS             141
#define IDR_GENTEXTPROPACT              142
#define IDS_DESCRIPTION_LIMITPACKETS    142
#define IDR_SCRIPTPROPACT               143
#define IDS_LESSER                      143
#define IDS_LESSEREQUAL                 144
#define IDR_SCRIPT_COPYOBJECTS          145
#define IDS_EQUAL                       145
#define IDS_MOREEQUAL                   146
#define IDR_OBJEKTEDOPPELN              147
#define IDS_MORE                        147
#define IDR_SCRIPT_UNIONOBJECTS         148
#define IDB_UP                          148
#define IDS_DESCRIPTION_VBPROPERTYSEQUENCE 148
#define IDB_UP_SEL                      149
#define IDS_WARNIFTOMANYORWNDS_ADDON    149
#define IDR_OBJEKTEVEREINIGEN           150
#define IDB_UP_FOCUS                    150
#define IDS_WARNIFREALLYTOMANYORWNDS    150
#define IDR_FAKETRIASLOCKFEATURE        151
#define IDB_UP_DISABLED                 151
#define IDS_DESCRIPTION_LOADOBJECTCOLLECTION 151
#define IDR_SELECTEXPORTOBJECTS         152
#define IDB_DOWN                        152
#define IDS_DESCRIPTION_SAVEOBJECTCOLLECTION 152
#define IDR_ADDASOBJECTCLASS            153
#define IDB_DOWN_SEL                    153
#define IDS_MANAGEOBJECTPROPERTIES_CAP  153
#define IDR_SCRIPT_UNIONOBJECTS_OPT     154
#define IDB_DOWN_FOCUS                  154
#define IDS_UNDOAREATOLINE              154
#define IDB_DOWN_DISABLED               155
#define IDS_UNDOLINETOAREA              155
#define IDS_AREASTOLINES_UNDO           156
#define IDD_TEXTREPLACE_WIZ             157
#define IDS_LINESTOAREAS_UNDO           157
#define IDR_DELETEOBJECTPROPERTY        158
#define IDD_GENERATEOBJECTPROPERTIES_SEQUENCE 159
#define IDR_OBJPROP_OBJNR               160
#define IDD_DELETEOBJECTPROPERTY_OPTIONS 160
#define IDR_OBJPROP_DATASOURCEDESC      161
#define IDD_GENERATEOBJECTPROPERTIES_OPTIONS 161
#define QUERYFIELDDLG                   162
#define IDR_OBJPROP_GUID                162
#define IDR_OBJPROP_QUERYFIELD          163
#define IDR_OBJPROP_OBJTYPLONG          164
#define IDR_OBJPROP_OBJTYPSHORT         165
#define IDR_OBJPROP_DATASOURCE          166
#define IDR_OBJPROP_OKS                 167
#define IDR_OBJPROP_IDENT               168
#define IDR_OBJPROP_FEATURE             169
#define IDR_PROPERTYOPERATION           170
#define IDR_PROPERTYACTIONJOIN          171
#define IDR_PROPERTYACTIONSPLIT         172
#define IDR_GENERATEOBJECTPROPERTIES    173
#define IDR_PROPERTYSEQUENCESERVICE     175
#define IDR_CATSIMPLECACHE              176
#define IDR_LIMITSEARCHES               177
#define IDR_LIMITPACKETS                179
#define IDR_TRIASDATAOBJECT             181
#define IDR_VBGEOCOMPONENT              182
#define IDR_MKVBGEOCOMPONENT            183
#define IDR_SAVEOBJECTCOLLECTION        184
#define IDR_LOADOBJECTCOLLECTION        185
#define IDD_LOADOBJECTCOLLECTION_OPTIONS 186
#define IDB_HEADER                      187
#define IDR_MANAGEOBJECTPROPERTIES      189
#define IDR_AREASTOLINES                191
#define IDR_LINESTOAREAS                192
#define IDB_PROJECTTYPES                219
#define IDS_COPYOBJECTS_ISCOPY          512
#define IDS_COPYOBJECTS_UIDENT          513
#define IDS_COPYOBJECTS_ERROR           514
#define IDS_COPYOBJECTS_ERRORNUM        515
#define IDS_COPYOBJECTS_OBJ             516
#define IDS_COPYOBJECTS_ERRORTEXT1      517
#define IDS_COPYOBJECTS_ERRORTEXT2      518
#define IDS_COPYOBJECTS_COPYOBJS        519
#define IDS_COPYOBJECTS_COUNT           520
#define IDS_COPYOBJECTS_OBJECTS         521
#define IDS_COPYOBJECTS_STATUS          522
#define IDS_UNION_OBJCLASSNAME          544
#define IDS_UNION_STATUSCAP             545
#define IDS_UNION_STATUSTEXT            546
#define IDS_UNION_MARKFEATURE           547
#define IDS_UNION_MARK                  548
#define IDS_UNION_MARKFEATURE_DESC      549
#define IDS_UNION_ERRORCAPTION          550
#define IDS_OBJEKTEVEREINIGEN           552
#define IDS_DESCRIPTION_AREASTOLINES    553
#define IDS_DESCRIPTION_LINESTOAREAS    554
#define IDT_PERCENT                     1001
#define IDC_LISTDESTIDENTS              1001
#define IDT_FILENAME                    1002
#define IDC_ADDTOVIEW                   1002
#define IDC_LISTIDENTS                  1003
#define IDC_DEFINENEW                   1003
#define IDT_OBJECTNUMBER                1004
#define IDC_ACTIVATED                   1004
#define IDT_TIMETEXT                    1005
#define IDC_OBJPROPS                    1005
#define IDC_OBJPROPERTY                 1005
#define IDC_FINDWHAT                    1007
#define IDC_EQUAL                       1008
#define IDC_INSERT_REGEXPR              1008
#define IDC_EXISTS                      1009
#define IDC_SELECT_OBJPROP              1009
#define IDC_CAPITAL                     1010
#define IDC_LISTRELATIONS               1011
#define IDC_FULLMATCH                   1011
#define IDC_LISTOBJWND                  1012
#define IDC_USEREGEXPR                  1012
#define IDC_SELECTALL                   1013
#define IDC_FUZZYMATCH                  1013
#define IDC_ALLOBJECTS                  1014
#define IDC_SELECTEDOBJECTS             1015
#define IDC_CREATENEWOBJWND             1016
#define IDC_SELECTOBJWND                1017
#define IDC_ANIMATE                     1017
#define IDC_RETAINSELECTION             1018
#define IDC_SELECTNEW                   1019
#define IDC_PARTIALMATCH                1019
#define IDC_BEGINOFTEXT                 1020
#define IDC_EXISTSONLY                  1021
#define IDT_SEARCH                      1022
#define IDT_REPLACE                     1023
#define IDC_OBJECTPROPS                 1024
#define IDC_CREATEDEPENDEND             1025
#define IDC_DONOTMOVE                   1028
#define IDC_IMPORTGEOMETRY              1028
#define IDC_DELETE                      1029
#define IDC_IMPORTFEATURES              1029
#define IDC_REPLACE                     1030
#define IDC_IMPORTRELATIONS             1030
#define IDC_OPTIONSELECT                1031
#define IDC_IMPORTVISUALISATION         1031
#define IDC_NEGATE                      1032
#define IDB_CONFIG                      1032
#define IDC_CLASSIFYALL                 1033
#define IDC_DYNAMICLABEL                1034
#define IDC_IMPORTFORMATS               1035
#define IDC_IMPORTFILES                 1036
#define IDC_SELECTIMPORTFILES           1037
#define IDC_FROMOBJPROP                 1038
#define IDC_IMPORTANSIOEM               1039
#define IDC_DIRECTINPUT                 1039
#define IDC_ROTATEFORLINES              1040
#define IDC_DIRECTTEXTLIST              1041
#define IDC_NOTEXISTANT                 1042
#define IDC_DELETETARGETOBJECT          1043
#define IDC_CHECK_SELECTIDENT           1044
#define IDC_STATIC_SELECTIDENT          1045
#define IDC_DATASOURCES                 1046
#define IDC_SELECT_DATASOURCES          1048
#define IDB_SELALLDATASOURCES           1049
#define IDC_OBJPROPDESTWINDOW           1050
#define IDC_OBJECTPROPERTIES            1053
#define IDC_PROPERTY_SEQUENCE           1054
#define IDC_OBJPROP_DESCRIPTION         1055
#define IDC_OBJPROPFILE                 1056
#define IDC_CONFIG_PROP                 1058
#define IDC_SEPARATOR                   1059
#define IDC_COORDSYS                    1060
#define IDC_COPYTOCLIPBOARD             1060
#define IDC_COUNT_CHARS                 1060
#define IDC_COUNT_CHARS_SPIN            1061
#define IDC_CAPITAL_CLASSIFY            1062
#define IDC_BEGINOFTEXT_CLASSIFY        1063
#define IDC_MATCH_CHARS_STATIC          1064
#define IDC_CLOSEWHENREADY              1066
#define IDC_OLDVALUE                    1068
#define IDC_NEWVALUE                    1069
#define IDB_SHOW_OBJECT                 1070
#define IDC_OBJECT_PROPS                1071
#define IDC_UP                          1074
#define IDC_DOWN                        1075
#define IDC_SELECT_DATASOURCE           1076
#define IDC_COMPARE                     1078
#define IDC_OBJCOUNT                    1079
#define IDC_SPIN_COUNT                  1080
#define IDC_LIMITPACKETS_DESC           1081
#define IDC_OBJECTCOUNT                 1082
#define IDC_NOLIMIT                     1083
#define IDC_ADDITIONAL_LIMIT            1084
#define IDC_VBDIALOG                    1085
#define IDC_COUNT_ORWNDS                1085
#define IDC_VBDIALOGWRAPPER             1086
#define IDC_LIMIT_ORWNDS                1086
#define IDC_SPIN_COUNT_ORWNDS           1087
#define IDC_SAVEASFILENAME              1087
#define IDC_SELECTSAVEAS                1088
#define IDC_SAVEINPROJECT               1089
#define IDC_NAMEINPROJECT               1091
#define IDC_SAVEASEXTERNALFILE          1092
#define IDC_OBJPROP_PROPS               1094
#define IDC_DELOBJPROP                  1095
#define IDC_EDIT1                       1095
#define IDC_NEWOBJPROP                  1096
#define IDC_BUTTON1                     1096
#define IDC_DESCRIPTION                 1097
#define IDS_BADREGISTRATION_CAP         1133
#define IDS_OBJPROPFTEXT                1326
#define IDD_OBJEKTEVEREINIGEN           1400
#define IDD_OBJECTROP_WIZPP             1401
#define IDC_ORIGINDEL                   1402
#define IDD_TEXTSEARCHENGINE_CFGPP      1402
#define IDC_ORIGINMARK                  1403
#define IDD_REPLACE_CONFIRM             1403
#define IDC_COPYNOTUSED                 1404
#define IDD_COPYOBJECTS_OPTIONS         1404
#define IDD_COPYOBJECTS_OPTIONSPP       1405
#define IDT_OPTDESCRIPT                 1406
#define IDD_MODIFYIDS_WIZPP             1406
#define IDD_CLASSIFYRESULT_WIZ          1407
#define IDD_VBPROPERTYSEQUENCE_OPTIONS  1408
#define IDD_SELECTOBJWND_WIZPP          1409
#define IDD_MANAGEOBJECTPROPERTIES      1410
#define IDD_NEWOBJPROP                  1411
#define IDD_SELECTCOORDSYSACTION_OPTIONS 1412
#define IDS_OBJPROPPUNKTOBJSH           1413
#define IDS_OBJPROPKANTENOBJSH          1414
#define IDS_OBJPROPFLAECHENOBJSH        1415
#define IDS_OBJPROPTEXTOBJSH            1416
#define IDS_OBJPROPKOMPLEXOBJSH         1417
#define IDS_OBJPROPUNKNOWNOBJSH         1418
#define IDS_OBJPROPOBJTYPSHORT          1419
#define IDS_OBJPROPTYPHELPSHORT         1420
#define IDM_MCODEFORMAT                 1422
#define IDS_BADREGISTRATION             1484
#define IDS_OBJPROPDATASOURCEDESC       1514
#define IDS_OBJPROPDATASOURCEDESC_HELP  1515
#define IDR_OBJPROPCLIPBOARD            1822
#define IDR_OBJPROPFILE                 1823
#define IDE_OBJPROPFILE                 1824
#define IDCB_OBJPROPHEADLINE            1826
#define IDCB_OBJPROPCUMULATE            1827
#define IDCB_OBJPROPCOUNT               1828
#define IDCB_OBJPROPPROPS               1829
#define IDR_OBJPROPWINDOW               1830
#define IDR_OBJPROPMCODE                1833
#define IDCB_USEFORALL                  1840
#define IDE_FIELDTEXT                   1841
#define ID_ANYCHAR                      2000
#define IDPB_STATUS                     2000
#define IDR_COPY_AVI                    2000
#define ID_CHARINRANGE                  2001
#define IDR_MOVE_AVI                    2001
#define ID_CHARNOTINRANGE               2002
#define IDR_DELETE_AVI                  2002
#define ID_WORDBOUNDARY                 2003
#define ID_WORDBEGIN                    2004
#define ID_WORDEND                      2005
#define ID_WITHINWORD                   2006
#define ID_BEGINOFLINE                  2007
#define ID_ENDOFLINE                    2008
#define ID_BEGINOFTEXT                  2009
#define ID_LINEEND                      2010
#define ID_OR                           2011
#define ID_GROUPTOKENS                  2012
#define ID_ZEROORMORE                   2013
#define ID_ONEORMORE                    2014
#define ID_ZEROORONE                    2015
#define ID_ORIGVALUE                    2020
#define ID_GRUPPIERUNG_1                2021
#define ID_GRUPPIERUNG_2                2022
#define ID_GRUPPIERUNG_3                2023
#define ID_GRUPPIERUNG_4                2024
#define ID_GRUPPIERUNG_5                2025
#define ID_GRUPPIERUNG_6                2026
#define ID_GRUPPIERUNG_7                2027
#define ID_GRUPPIERUNG_8                2028
#define ID_GRUPPIERUNG_9                2029
#define ID_FROMCLIPBOARD                2030
#define ID_FIRST_OBJPROP                2050
#define IDC_OBJPROPERTY_SRC             3000
#define IDC_SELECT_OBJPROP_SRC          3001
#define IDC_INSERT_REGEXPR_SEARCH       3003
#define IDC_REPLACEWITH                 3004
#define IDC_INSERT_REGEXPR_REPLACE      3005
#define IDC_OBJPROPERTY_DEST            3006
#define IDC_SELECT_OBJPROP_DEST         3007
#define IDC_FINDWHAT_REPLACE            3010
#define IDC_CAPITAL_REPLACE             3011
#define IDC_USEREGEXPR_REPLACE          3012
#define IDC_PARTIALMATCH_REPLACE        3013
#define IDC_BEGINOFTEXT_REPLACE         3014
#define IDC_COORDSYSTEMS                18049
#define IDC_COORDDESCRIPTION            18050
#define IDC_DESCTEXT                    18051
#define IDB_COORDSYSTEM                 18053
#define IDB_PROJECTTYPES_MASK           24746

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        193
#define _APS_NEXT_COMMAND_VALUE         135
#define _APS_NEXT_CONTROL_VALUE         1098
#define _APS_NEXT_SYMED_VALUE           120
#endif
#endif
