EXPORTS
	??0ActPrinterPars@@QAE@XZ                                   	@5
	??0CBmpButton@@QAE@PAVDialogWindow@@VResID@@@Z              	@6
	??0CBmpButton@@QAE@PAVWindow@@VCvID@@VPoint@@VDimension@@PBD@Z	@7
	??0CCheckTreeView@@QAE@PAVDialogWindow@@VResID@@@Z          	@8
	??0CCoordEdit@CCoordPairEdit@@QAE@ABV01@@Z                  	@9
	??0CCoordEdit@CCoordPairEdit@@QAE@PAVDialogWindow@@VResID@@PAV1@@Z	@10
	??0CCoordPairEdit@@QAE@ABV0@@Z                              	@11
	??0CCoordPairEdit@@QAE@PAVDialogWindow@@AAVCoordTrans@@VResID@@2@Z	@12
	??0CExtReg@@QAE@AAVCVersionBind@@AAVstring@@@Z              	@13
	??0CHelpText@@QAE@PAVDialogWindow@@VResID@@@Z               	@14
	??0CInPlaceCombo@@QAE@ABV0@@Z                               	@25
	??0CInPlaceCombo@@QAE@PAVWindow@@VCvID@@VPoint@@VDimension@@K@Z	@260
	??0CManageUndoRedo@@IAE@XZ                                  	@15
	??0CPropertyName@@QAE@PAUIObjectProperty@@@Z                	@16
	??0CPropertyName@@QAE@PBD@Z                                 	@17
	??0CPropertyName@@QAE@W4tagPROPTYPE@@PBD11@Z                	@18
	??0CPropertyName@@QAE@XZ                                    	@19
	??0CPropertySheetExt@@QAE@ABV0@@Z                           	@20
	??0CPropertySheetExt@@QAE@PBDPAVWindow@@KI@Z                	@21
	??0CSelIdentItem@@QAE@KH@Z                                  	@22
	??0CSelIdentList@@QAE@PAVDialogWindow@@VResID@@@Z           	@23
	??0CSelIdentListView@@QAE@ABV0@@Z                           	@24
	??0CSelIdentListView@@QAE@PAVDialogWindow@@VResID@@PAVCSelIdentListViewWindow@@@Z	@344
	??0CSelIdentListViewWindow@@QAE@ABV0@@Z                     	@345
	??0CSelIdentListViewWindow@@QAE@PAVDialogWindow@@IK@Z       	@346
	??0CVersionBind@@QAE@XZ                                     	@26
	??0DoubleNumEdit@@QAE@ABV0@@Z                               	@27
	??0DoubleNumEdit@@QAE@PAVDialogWindow@@VResID@@@Z           	@28
	??0DoubleNumEdit@@QAE@PAVWindow@@IVPoint@@VDimension@@@Z    	@29
	??0HorizMicroScroll@@QAE@PAVDialogWindow@@VResID@@@Z        	@30
	??0NumEdit@@QAE@ABV0@@Z                                     	@31
	??0NumEdit@@QAE@PAVDialogWindow@@VResID@@F@Z                	@32
	??0NumEdit@@QAE@PAVWindow@@IVPoint@@VDimension@@F@Z         	@33
	??0OwnerDrawComboBox@@QAE@ABV0@@Z                           	@34
	??0OwnerDrawComboBox@@QAE@PAVDialogWindow@@VResID@@@Z       	@35
	??0OwnerDrawListBox@@QAE@ABV0@@Z                            	@36
	??0OwnerDrawListBox@@QAE@PAVControl@@@Z                     	@37
	??0OwnerDrawListBox@@QAE@PAVDialogWindow@@VResID@@@Z        	@38
	??0OwnerDrawListBoxEx@@QAE@ABV0@@Z                          	@39
	??0OwnerDrawListBoxEx@@QAE@PAVDialogWindow@@VResID@@@Z      	@40
	??0SpinControl@@QAE@ABV0@@Z                                 	@41
	??0SpinControl@@QAE@PAVDialogWindow@@IIVRange@@@Z           	@42
	??0SpinEdit@@QAE@ABV0@@Z                                    	@43
	??0SpinEdit@@QAE@PAVDialogWindow@@VResID@@VRange@@@Z        	@44
	??0VertMicroScroll@@QAE@PAVDialogWindow@@VResID@@@Z         	@45
	??1CBmpButton@@QAE@XZ                                       	@46
	??1CCheckTreeView@@UAE@XZ                                   	@47
	??1CCoordEdit@CCoordPairEdit@@UAE@XZ                        	@48
	??1CCoordPairEdit@@QAE@XZ                                   	@49
	??1CExtReg@@QAE@XZ                                          	@50
	??1CHelpText@@QAE@XZ                                        	@51
	??1CInPlaceCombo@@UAE@XZ                                    	@347
	??1CManageUndoRedo@@QAE@XZ                                  	@52
	??1CPropertySheetExt@@UAE@XZ                                	@53
	??1CSelIdentList@@QAE@XZ                                    	@54
	??1CSelIdentListView@@QAE@XZ                                	@55
	??1CSelIdentListViewWindow@@UAE@XZ                          	@348
	??1DoubleNumEdit@@UAE@XZ                                    	@56
	??1HorizMicroScroll@@QAE@XZ                                 	@57
	??1NumEdit@@UAE@XZ                                          	@58
	??1OwnerDrawComboBox@@UAE@XZ                                	@59
	??1OwnerDrawListBox@@UAE@XZ                                 	@60
	??1OwnerDrawListBoxEx@@UAE@XZ                               	@61
	??1SpinControl@@QAE@XZ                                      	@62
	??1SpinEdit@@UAE@XZ                                         	@63
	??1VertMicroScroll@@QAE@XZ                                  	@64
	??4CBmpButton@@QAEAAV0@ABV0@@Z                              	@65
	??4CCoordEdit@CCoordPairEdit@@QAEAAV01@ABV01@@Z             	@66
	??4CHelpText@@QAEAAV0@ABV0@@Z                               	@67
	??4CInPlaceCombo@@QAEAAV0@ABV0@@Z                           	@349
	??4CManageUndoRedo@@QAEAAV0@ABV0@@Z                         	@68
	??4CPropertySheetExt@@QAEAAV0@ABV0@@Z                       	@69
	??4CSelIdentItem@@QAEAAV0@ABV0@@Z                           	@70
	??4CSelIdentList@@QAEAAV0@ABV0@@Z                           	@71
	??4CSelIdentListView@@QAEAAV0@ABV0@@Z                       	@72
	??4CSelIdentListViewWindow@@QAEAAV0@ABV0@@Z                 	@350
	??4DoubleNumEdit@@QAEAAV0@ABV0@@Z                           	@73
	??4HorizMicroScroll@@QAEAAV0@ABV0@@Z                        	@74
	??4NumEdit@@QAEAAV0@ABV0@@Z                                 	@75
	??4OwnerDrawComboBox@@QAEAAV0@ABV0@@Z                       	@76
	??4OwnerDrawListBox@@QAEAAV0@ABV0@@Z                        	@77
	??4OwnerDrawListBoxEx@@QAEAAV0@ABV0@@Z                      	@78
	??4SpinControl@@QAEAAV0@ABV0@@Z                             	@79
	??4SpinEdit@@QAEAAV0@ABV0@@Z                                	@80
	??4VertMicroScroll@@QAEAAV0@ABV0@@Z                         	@81
	??8CPropertyName@@QAEHAAV0@@Z                               	@82
	??BCInPlaceCombo@@QAEPAVComboBox@@XZ                        	@351
	??CCSelIdentListViewWindow@@QAEPAVCSelIdentListView@@XZ     	@352
	??_7CCoordEdit@CCoordPairEdit@@6B@                          	@83
	??_7CCoordPairEdit@@6B@                                     	@84
	??_7CInPlaceCombo@@6B@                                      	@353
	??_7CPropertySheetExt@@6B@                                  	@85
	??_7CSelIdentListView@@6B@                                  	@354
	??_7CSelIdentListViewWindow@@6B@                            	@355
	??_7DoubleNumEdit@@6B@                                      	@86
	??_7NumEdit@@6B@                                            	@87
	??_7OwnerDrawComboBox@@6B@                                  	@88
	??_7OwnerDrawListBox@@6B@                                   	@89
	??_7OwnerDrawListBoxEx@@6B@                                 	@90
	??_7SpinEdit@@6B@                                           	@91
	??_ECBmpButton@@QAEPAXI@Z                                   	@92
	??_ECCoordEdit@CCoordPairEdit@@UAEPAXI@Z                    	@93
	??_ECCoordPairEdit@@QAEPAXI@Z                               	@94
	??_ECHelpText@@QAEPAXI@Z                                    	@95
	??_ECInPlaceCombo@@UAEPAXI@Z                                	@356
	??_ECManageUndoRedo@@QAEPAXI@Z                              	@96
	??_ECPropertySheetExt@@UAEPAXI@Z                            	@97
	??_ECSelIdentList@@QAEPAXI@Z                                	@98
	??_ECSelIdentListView@@QAEPAXI@Z                            	@99
	??_ECSelIdentListViewWindow@@UAEPAXI@Z                      	@357
	??_EDoubleNumEdit@@UAEPAXI@Z                                	@100
	??_EHorizMicroScroll@@QAEPAXI@Z                             	@101
	??_ENumEdit@@UAEPAXI@Z                                      	@102
	??_EOwnerDrawComboBox@@UAEPAXI@Z                            	@103
	??_EOwnerDrawListBox@@UAEPAXI@Z                             	@104
	??_EOwnerDrawListBoxEx@@UAEPAXI@Z                           	@105
	??_ESpinControl@@QAEPAXI@Z                                  	@106
	??_ESpinEdit@@UAEPAXI@Z                                     	@107
	??_EVertMicroScroll@@QAEPAXI@Z                              	@108
	??_GCBmpButton@@QAEPAXI@Z                                   	@109
	??_GCCoordEdit@CCoordPairEdit@@UAEPAXI@Z                    	@110
	??_GCCoordPairEdit@@QAEPAXI@Z                               	@111
	??_GCHelpText@@QAEPAXI@Z                                    	@112
	??_GCInPlaceCombo@@UAEPAXI@Z                                	@358
	??_GCManageUndoRedo@@QAEPAXI@Z                              	@113
	??_GCPropertySheetExt@@UAEPAXI@Z                            	@114
	??_GCSelIdentList@@QAEPAXI@Z                                	@115
	??_GCSelIdentListView@@QAEPAXI@Z                            	@116
	??_GCSelIdentListViewWindow@@UAEPAXI@Z                      	@359
	??_GDoubleNumEdit@@UAEPAXI@Z                                	@117
	??_GHorizMicroScroll@@QAEPAXI@Z                             	@118
	??_GNumEdit@@UAEPAXI@Z                                      	@119
	??_GOwnerDrawComboBox@@UAEPAXI@Z                            	@120
	??_GOwnerDrawListBox@@UAEPAXI@Z                             	@121
	??_GOwnerDrawListBoxEx@@UAEPAXI@Z                           	@122
	??_GSpinControl@@QAEPAXI@Z                                  	@123
	??_GSpinEdit@@UAEPAXI@Z                                     	@124
	??_GVertMicroScroll@@QAEPAXI@Z                              	@125
	?Activate@OwnerDrawComboBox@@MAEXVEvent@@@Z                 	@126
	?Activate@OwnerDrawListBox@@MAEXVEvent@@@Z                  	@127
	?AddItem@OwnerDrawComboBox@@QAEJPAXH@Z                      	@128
	?AddItem@OwnerDrawListBox@@QAEJPAXH@Z                       	@129
	?AddUndo@CManageUndoRedo@@QAEJPAUIUnknown@@@Z               	@130
	?AutoLoad@CBmpButton@@QAEHPAVResourceFile@@@Z               	@131
	?BeginUndoLevel@CManageUndoRedo@@QAEJPAUIUnknown@@@Z        	@132
	?BeginUndoLevel@CManageUndoRedo@@QAEJPBD@Z                  	@133
	?CalcRotatedSize@@YGHHHAAUtagGRADIENT@@HAAH1@Z              	@134
	?CancelUndoLevel@CManageUndoRedo@@QAEJH@Z                   	@135
	?ChangeSelected@OwnerDrawListBoxEx@@QAEHHH@Z                	@136
	?ChangeSelected@OwnerDrawListBoxEx@@QAEHVRange@@H@Z         	@137
	?ChangeSelectedAll@CSelIdentListView@@QAEHH@Z               	@138
	?ClassFromIdent@@YAJKPADH@Z                                 	@139
	?ClearSelected@OwnerDrawListBoxEx@@QAEHXZ                   	@140
	?CmpEntries@@YGHJJJ@Z                                       	@141
	?Compare@@YAHAAVCPropertyName@@0@Z                          	@142
	?CompareItem@OwnerDrawComboBox@@MAEHVOwnerDrawEvt@@PAX1@Z   	@143
	?CopyToEdit@SpinControl@@QAEXXZ                             	@144
	?CopyToSpin@SpinControl@@QAEXXZ                             	@145
	?Create@CInPlaceCombo@@QAEHHHAAV?$list@V?$os_basic_string@DVos_char_traits_char@@V?$allocator@D@@@@@@H@Z	@360
	?CreateInstance@CHelpText@@SAPAV1@PAVDialogWindow@@VResID@@H@Z	@146
	?CreateInstance@CManageUndoRedo@@SAPAV1@H@Z                 	@147
	?CreateInstance@CSelIdentList@@SAPAV1@PAVDialogWindow@@VResID@@@Z	@148
	?DataObjectCreateInstance@@YAJPAUIUnknown@@ABU_GUID@@PAPAX@Z	@149
	?DecodeEntry@CSelIdentList@@AAEHFAAJAAF@Z                   	@150
	?DecodeEntry@CSelIdentListView@@QAEHHAAJAAF@Z               	@151
	?DelItem@OwnerDrawComboBox@@QAEJH@Z                         	@152
	?DelItem@OwnerDrawListBox@@QAEJH@Z                          	@153
	?DeleteItem@OwnerDrawComboBox@@MAEHVDeleteItemEvt@@@Z       	@154
	?Disable@SpinControl@@QAEXXZ                                	@155
	?Dispatch@CInPlaceCombo@@MAEJVEvent@@@Z                     	@361
	?Dispatch@CSelIdentListViewWindow@@MAEJVEvent@@@Z           	@362
	?Dispatch@OwnerDrawComboBox@@MAEJVEvent@@@Z                 	@156
	?Dispatch@OwnerDrawListBox@@MAEJVEvent@@@Z                  	@157
	?DrawEntireItem@CSelIdentListViewWindow@@UAEHVDrawItemEvt@@@Z	@363
	?DrawEntireItem@OwnerDrawComboBox@@MAEHVDrawItemEvt@@@Z     	@158
	?DrawItem@CBmpButton@@QAEHVDrawItemEvt@@@Z                  	@159
	?DrawItemFocus@CSelIdentListViewWindow@@UAEHVDrawItemEvt@@@Z	@364
	?DrawItemFocus@OwnerDrawComboBox@@MAEHVDrawItemEvt@@@Z      	@160
	?DrawItemSelect@CSelIdentListViewWindow@@UAEHVDrawItemEvt@@@Z	@365
	?DrawItemSelect@OwnerDrawComboBox@@MAEHVDrawItemEvt@@@Z     	@161
	?Enable@SpinControl@@QAEXXZ                                 	@162
	?EnableDragDrop@OwnerDrawListBoxEx@@QAEHH@Z                 	@163
	?EndUndoLevel@CManageUndoRedo@@QAEJXZ                       	@164
	?EveryDelete@CManageUndoRedo@@QAEXXZ                        	@165
	?Expose@CSelIdentListViewWindow@@MAEXVExposeEvt@@@Z         	@366
	?FFreeListboxExtents@@YAHPAUHWND__@@@Z                      	@166
	?FInit@CBmpButton@@QAEHXZ                                   	@167
	?FInit@CCheckTreeView@@QAEHXZ                               	@168
	?FInit@CHelpText@@QAEHH@Z                                   	@169
	?FInit@CManageUndoRedo@@IAEHH@Z                             	@170
	?FInit@CSelIdentList@@QAEHXZ                                	@171
	?FInitListboxExtents@@YAHPAUHWND__@@@Z                      	@172
	?FindItem@OwnerDrawComboBox@@QAEJPAX@Z                      	@173
	?FindItem@OwnerDrawListBox@@QAEJPAX@Z                       	@174
	?FindString@CCheckTreeView@@QAEPAU_TREEITEM@@PBD@Z          	@175
	?FitColumn@CSelIdentListView@@QAEXH@Z                       	@176
	?FocusChange@CCoordEdit@CCoordPairEdit@@MAEXVFocusChangeEvt@@@Z	@177
	?FocusChange@CInPlaceCombo@@MAEXVFocusChangeEvt@@@Z         	@367
	?FocusChange@CSelIdentListViewWindow@@MAEXVFocusChangeEvt@@@Z	@368
	?FocusChange@DoubleNumEdit@@MAEXVFocusChangeEvt@@@Z         	@178
	?FocusChange@NumEdit@@MAEXVFocusChangeEvt@@@Z               	@179
	?FocusChange@OwnerDrawListBoxEx@@MAEXVFocusChangeEvt@@@Z    	@180
	?GetAspectRatio@PrinterPars@@QAE?AVPoint@@XZ                	@181
	?GetCaretIndex@OwnerDrawListBoxEx@@QAEHXZ                   	@182
	?GetCheckState@CCheckTreeView@@QAEIPAU_TREEITEM@@@Z         	@183
	?GetColor@HorizMicroScroll@@QAE?AVColor@@W4MSColorDef@@@Z   	@184
	?GetColor@VertMicroScroll@@QAE?AVColor@@W4MSColorDef@@@Z    	@185
	?GetColumnCount@CSelIdentListView@@QAEHXZ                   	@186
	?GetComboBox@CInPlaceCombo@@QAEPAVComboBox@@XZ              	@369
	?GetCurrPos@HorizMicroScroll@@QAEIXZ                        	@187
	?GetCurrPos@VertMicroScroll@@QAEIXZ                         	@188
	?GetDescription@CSelIdentListView@@QAEHHPADH@Z              	@189
	?GetDotsPerMM@PrinterPars@@QAE?AVDoublePair@@XZ             	@190
	?GetEditControl@NumEdit@@QAEPAVSingleLineEdit@@XZ           	@191
	?GetEnumLONGData@@YAJPAUIDataObject@@ABU_GUID@@PAPAX@Z      	@192
	?GetEnumLONGData@@YAJPAUIDataObject@@PAPAV?$IEnum@J@@@Z     	@193
	?GetFileVersionInfoA@CVersionBind@@QAEHPADKKPAX@Z           	@194
	?GetFileVersionInfoSizeA@CVersionBind@@QAEKPADPAK@Z         	@195
	?GetFirstIdent@CSelIdentList@@QAEHAAJAAF@Z                  	@196
	?GetFirstIdent@CSelIdentListView@@QAEHAAJAAF@Z              	@197
	?GetFirstIdentEx@CSelIdentList@@QAEHAAJAAFAAH@Z             	@198
	?GetFirstIdentEx@CSelIdentListView@@QAEHAAJAAFAAH@Z         	@199
	?GetFirstIdentInList@CSelIdentListView@@QAEHAAJAAF@Z        	@200
	?GetFirstIdentInListEx@CSelIdentListView@@QAEHAAJAAFAAH@Z   	@201
	?GetFirstInList@CSelIdentListView@@QAEHXZ                   	@202
	?GetFirstSelected@CSelIdentListView@@QAEHXZ                 	@203
	?GetFirstSelected@OwnerDrawListBoxEx@@QAEHXZ                	@204
	?GetFullName@CPropertyName@@QAEHAAVstring@@@Z               	@205
	?GetFullName@CPropertyName@@QAEHPADG@Z                      	@206
	?GetHWNDData@@YAJPAUIDataObject@@PAPAUHWND__@@@Z            	@207
	?GetHandle@HorizMicroScroll@@IAEPAUHWND__@@XZ               	@208
	?GetHandle@OwnerDrawComboBox@@IAEPAUHWND__@@XZ              	@209
	?GetHandle@OwnerDrawListBox@@IAEPAUHWND__@@XZ               	@210
	?GetHandle@VertMicroScroll@@IAEPAUHWND__@@XZ                	@211
	?GetInvertRange@HorizMicroScroll@@QAEHXZ                    	@212
	?GetInvertRange@VertMicroScroll@@QAEHXZ                     	@213
	?GetItem@OwnerDrawComboBox@@QAEPAXH@Z                       	@214
	?GetItem@OwnerDrawListBox@@QAEPAXH@Z                        	@215
	?GetItemFocus@CSelIdentListView@@QAEHXZ                     	@216
	?GetLastInList@CSelIdentListView@@QAEHXZ                    	@217
	?GetLastSelected@CSelIdentListView@@QAEHXZ                  	@218
	?GetListCtrl@CSelIdentListViewWindow@@QAEPAVCSelIdentListView@@XZ	@370
	?GetMargins@DoubleNumEdit@@QAEHAAN0@Z                       	@219
	?GetNextIdent@CSelIdentList@@QAEHAAJAAF@Z                   	@220
	?GetNextIdent@CSelIdentListView@@QAEHAAJAAF@Z               	@221
	?GetNextIdentEx@CSelIdentList@@QAEHAAJAAFAAH@Z              	@222
	?GetNextIdentEx@CSelIdentListView@@QAEHAAJAAFAAH@Z          	@223
	?GetNextIdentInList@CSelIdentListView@@QAEHAAJAAF@Z         	@224
	?GetNextIdentInListEx@CSelIdentListView@@QAEHAAJAAFAAH@Z    	@225
	?GetNextInList@CSelIdentListView@@QAEHXZ                    	@226
	?GetNextRedoDesc@CManageUndoRedo@@QAEKPAPAD@Z               	@227
	?GetNextSelected@CSelIdentListView@@QAEHXZ                  	@228
	?GetNextSelected@OwnerDrawListBoxEx@@QAEHXZ                 	@229
	?GetNextUndoDesc@CManageUndoRedo@@QAEKPAPAD@Z               	@230
	?GetNoSelected@OwnerDrawListBoxEx@@QAEHXZ                   	@231
	?GetOTyp@CSelIdentList@@AAEFF@Z                             	@232
	?GetPageSize@PrinterPars@@QAE?AVDimension@@XZ               	@233
	?GetPegScroll@HorizMicroScroll@@QAEHXZ                      	@234
	?GetPegScroll@VertMicroScroll@@QAEHXZ                       	@235
	?GetPrevInList@CSelIdentListView@@QAEHXZ                    	@236
	?GetPrevSelected@CSelIdentListView@@QAEHXZ                  	@237
	?GetRedoList@CManageUndoRedo@@QAEJPAPAUIEnumUnknown@@@Z     	@238
	?GetScrollRange@HorizMicroScroll@@QAE?AVRange@@XZ           	@239
	?GetScrollRange@VertMicroScroll@@QAE?AVRange@@XZ            	@240
	?GetSelection@OwnerDrawListBoxEx@@QAEHF@Z                   	@241
	?GetStyle@CSelIdentListViewWindow@@IAEKXZ                   	@371
	?GetTargetDevice@PrinterPars@@QBEPAUtagDVTARGETDEVICE@@XZ   	@242
	?GetText@NumEdit@@QAEXPADI@Z                                	@243
	?GetTextLen@NumEdit@@QAEHXZ                                 	@244
	?GetUndoList@CManageUndoRedo@@QAEJPAPAUIEnumUnknown@@@Z     	@245
	?GetValue@DoubleNumEdit@@QAEHAAN@Z                          	@246
	?GetValue@NumEdit@@QAEHPAH@Z                                	@247
	?GetValue@SpinControl@@QAEFXZ                               	@248
	?GetValues@CCoordPairEdit@@QAEHAAN0H@Z                      	@249
	?GetVariantData@@YAJPAUIDataObject@@PBUtagFORMATETC@@PAVCComVariant@@@Z	@250
	?Handle@OwnerDrawListBoxEx@@QAEPAUHWND__@@G@Z               	@251
	?HideSpin@SpinControl@@QAEXXZ                               	@252
	?HideStateImage@CCheckTreeView@@QAEXPAU_TREEITEM@@@Z        	@253
	?IdentFromClass@@YAJPBDPAKH@Z                               	@254
	?IndexFromPoint@OwnerDrawListBoxEx@@QAEHVPoint@@PAH@Z       	@255
	?InitControl@CSelIdentListView@@QAEHKHP6AKJK@ZP6GHJJJ@ZK@Z  	@256
	?InitFromData@PrinterPars@@QAEHPAUtagDVTARGETDEVICE@@@Z     	@257
	?InitFromDefaultPrinter@PrinterPars@@QAEHXZ                 	@258
	?InsertColumns@CSelIdentListView@@UAEHH@Z                   	@372
	?InsertColumns@CSelIdentListViewWindow@@UAEHH@Z             	@373
	?IsItemSelected@CSelIdentListView@@QAEHH@Z                  	@259
	?Justify@@YAJPAUHDC__@@0PBDPAUtagPOINT@@PAUtagRECT@@W4AlignType@@HPAFF@Z	@374
	?KeyDown@CInPlaceCombo@@MAEXVKeyEvt@@@Z                     	@375
	?KeyDown@DoubleNumEdit@@MAEXVKeyEvt@@@Z                     	@261
	?KeyDown@NumEdit@@MAEXVKeyEvt@@@Z                           	@262
	?LoadBitmaps@CBmpButton@@QAEHVResID@@000@Z                  	@263
	?LoadExtPageFromRegistry@CPropertySheetExt@@IAEJPAUHKEY__@@PBD1PAUIDataObject@@PBU_ITEMIDLIST@@@Z	@264
	?LoadExtPagesFromRegistry@CPropertySheetExt@@QAEJPAUHKEY__@@PBD1PAUIDataObject@@PBU_ITEMIDLIST@@@Z	@265
	?LocControl@OwnerDrawComboBox@@QAEPAVComboBox@@XZ           	@266
	?LocControl@OwnerDrawListBox@@QAEPAVListBox@@XZ             	@267
	?LocCtrl@OwnerDrawListBoxEx@@QAEPAVMultiSelListBox@@XZ      	@268
	?MeasureItem@OwnerDrawComboBox@@MAEHVMeasureItemEvt@@@Z     	@269
	?MouseButtonDn@OwnerDrawListBoxEx@@MAEXVMouseEvt@@@Z        	@270
	?MouseButtonUp@OwnerDrawListBoxEx@@MAEXVMouseEvt@@@Z        	@271
	?MouseDrag@OwnerDrawListBoxEx@@MAEXVMouseEvt@@@Z            	@272
	?ObjPropCreateInstance@@YAJPAUIUnknown@@ABU_GUID@@1PAPAX@Z  	@273
	?OnCloseup@CInPlaceCombo@@QAEXXZ                            	@376
	?OnDeleteAllItems@CSelIdentListView@@QAEXXZ                 	@274
	?OnDeleteItem@CSelIdentListView@@QAEXPAU_NM_LISTVIEW@@@Z    	@275
	?PActCreateInstance@@YAJPBDABU_GUID@@PAPAX@Z                	@276
	?PaletteChange@OwnerDrawComboBox@@MAEXVPaletteChangeEvt@@@Z 	@277
	?PaletteChange@OwnerDrawListBox@@MAEXVPaletteChangeEvt@@@Z  	@278
	?PiCreateInstance@@YAJABU_GUID@@PAPAX@Z                     	@279
	?PostValidate@NumEdit@@MAEHH@Z                              	@280
	?PostValidate@SpinEdit@@UAEHH@Z                             	@281
	?PreTranslateMsg@CInPlaceCombo@@MAEHPAUtagMSG@@@Z           	@377
	?Redo@CManageUndoRedo@@QAEJJ@Z                              	@282
	?Register@CExtReg@@QAEHXZ                                   	@283
	?RegisterPropertyActions@@YAJP6AHPAUIClassProperty@@PBDK@ZK@Z	@284
	?RepaintSelectedItems@CSelIdentListViewWindow@@IAEXXZ       	@378
	?ResetListboxExtents@@YAXPAUHWND__@@@Z                      	@285
	?RotateBitmap@@YGPAUHBITMAP__@@PAUHDC__@@PAU1@UtagGRADIENT@@HPAJ3@Z	@286
	?RunPropertyActionSequence@@YAJPAUHWND__@@PBDPAUtagCALPCLSID@@PAUIProgressIndicator@@PAUIDataObject@@PAPAU4@@Z	@287
	?RunPropertyActionSequence@@YAJPAUHWND__@@PBDPAUtagCALPCSTR@@PAUIProgressIndicator@@PAUIDataObject@@PAPAU4@@Z	@288
	?SelectIdent@CSelIdentList@@QAEHJFH@Z                       	@289
	?SelectIdent@CSelIdentListView@@QAEHJFH@Z                   	@290
	?SelectItem@CSelIdentListView@@QAEXHH@Z                     	@291
	?SelectItemFocus@CSelIdentListView@@QAEXHH@Z                	@292
	?SetCaretIndex@OwnerDrawListBoxEx@@QAEHHH@Z                 	@293
	?SetCheckState@CCheckTreeView@@QAEXPAU_TREEITEM@@I@Z        	@294
	?SetColor@HorizMicroScroll@@QAE?AVColor@@W4MSColorDef@@V2@@Z	@295
	?SetColor@VertMicroScroll@@QAE?AVColor@@W4MSColorDef@@V2@@Z 	@296
	?SetCurrPos@HorizMicroScroll@@QAEII@Z                       	@297
	?SetCurrPos@VertMicroScroll@@QAEII@Z                        	@298
	?SetEnumLONGData@@YAJPAV?$IEnum@J@@PAUIDataObject@@@Z       	@299
	?SetGroup@CPropertyName@@QAEHPBD@Z                          	@300
	?SetHWNDData@@YAJPAUHWND__@@PAUIDataObject@@@Z              	@301
	?SetHelpText@CHelpText@@QAEXVResID@@@Z                      	@302
	?SetHelpTextV@CHelpText@@QAAXVResID@@ZZ                     	@303
	?SetHighlightType@CSelIdentListViewWindow@@QAE?AW4EHighlight@1@W421@@Z	@379
	?SetHorizontalExtent@CInPlaceCombo@@QAEXI@Z                 	@380
	?SetInvertRange@HorizMicroScroll@@QAEHH@Z                   	@304
	?SetInvertRange@VertMicroScroll@@QAEHH@Z                    	@305
	?SetItem@OwnerDrawComboBox@@QAEJPAXH@Z                      	@306
	?SetItem@OwnerDrawListBox@@QAEJPAXH@Z                       	@307
	?SetItemHeight@CInPlaceCombo@@QAEHHI@Z                      	@381
	?SetMargins@DoubleNumEdit@@QAEXNN@Z                         	@308
	?SetModified@NumEdit@@QAEXH@Z                               	@309
	?SetName@CPropertyName@@QAEHPBD@Z                           	@310
	?SetNumEditMode@NumEdit@@QAE?AW4NumEditMode@1@W421@@Z       	@311
	?SetPegScroll@HorizMicroScroll@@QAEHH@Z                     	@312
	?SetPegScroll@VertMicroScroll@@QAEHH@Z                      	@313
	?SetRange@SpinControl@@QAE?AVRange@@V2@@Z                   	@314
	?SetRange@SpinEdit@@QAE?AVRange@@V2@@Z                      	@315
	?SetRedraw@CSelIdentListView@@QAEXH@Z                       	@316
	?SetScrollRange@HorizMicroScroll@@QAE?AVRange@@V2@@Z        	@317
	?SetScrollRange@VertMicroScroll@@QAE?AVRange@@V2@@Z         	@318
	?SetStyle@NumEdit@@QAEXK@Z                                  	@319
	?SetSubGroup@CPropertyName@@QAEHPBD@Z                       	@320
	?SetText@NumEdit@@QAEXPBD@Z                                 	@321
	?SetTextLimit@NumEdit@@QAEXI@Z                              	@322
	?SetType@CPropertyName@@QAEHW4tagPROPTYPE@@@Z               	@323
	?SetUp@PrinterPars@@QAEHXZ                                  	@324
	?SetValue@DoubleNumEdit@@QAEXN@Z                            	@325
	?SetValue@NumEdit@@QAEXH@Z                                  	@326
	?SetValue@SpinControl@@QAEFF@Z                              	@327
	?SetValues@CCoordPairEdit@@QAEHNN@Z                         	@328
	?SetVariantData@@YAJAAVCComVariant@@PAUIDataObject@@PBUtagFORMATETC@@@Z	@329
	?ShowSpin@SpinControl@@QAEXXZ                               	@330
	?SizeToContent@CBmpButton@@QAEXXZ                           	@331
	?SupportsSelfRegister@CExtReg@@QAEHXZ                       	@332
	?ToggleCheckMark@CCheckTreeView@@QAEHPAU_TREEITEM@@@Z       	@333
	?Undo@CManageUndoRedo@@QAEJJ@Z                              	@334
	?UndoCreateInstance@@YAJABU_GUID@@PAPAX@Z                   	@335
	?Unregister@CExtReg@@QAEHXZ                                 	@336
	?UpdateImage@CSelIdentListView@@QAEHH@Z                     	@337
	?Validate@CCoordPairEdit@@MAEHXZ                            	@338
	?VerQueryValueA@CVersionBind@@QAEHQAXPADPAPAXPAI@Z          	@339
	?WAddExtentEntry@@YAGPAUHWND__@@PBD@Z                       	@340
	?WRemoveExtentEntry@@YAGPAUHWND__@@PBD@Z                    	@341
	?isModified@NumEdit@@QAEHXZ                                 	@342
	?isModified@SpinControl@@QAEHXZ                             	@343
	?isModified@SpinEdit@@QAEHXZ                                	@382
	DllCanUnloadNow                                             	@2	PRIVATE
	DllGetClassObject                                           	@1	PRIVATE
	DllRegisterServer                                           	@3	PRIVATE
	DllUnregisterServer                                         	@4	PRIVATE
	InitTrias03                                                 	@383
