// $Header: $
// Copyright© 1998-2000 TRiAS GmbH Potsdam, All rights reserved
// Created: 14.09.2000 21:21:48 
//
// This file was generated by the TRiASDB Data Server Wizard V1.02.103 (#HK000729)
//
// @doc
// @module TRiASMIObjectsCollection.h | Declaration of the <c CTRiASMIObjectsCollection> class

#if !defined(_TRIASMIOBJECTSCOLLECTION_H__429413B3_D83E_49B1_933F_A097A2547882__INCLUDED_)
#define _TRIASMIOBJECTSCOLLECTION_H__429413B3_D83E_49B1_933F_A097A2547882__INCLUDED_

#if _MSC_VER >= 1000
#pragma once
#endif // _MSC_VER >= 1000

// Header include diagnostics
#if defined(_TRIAS_DBG_HEADER_DIAGNOSTICS)
#pragma message(__TIME__": include " __FILE__ )
#endif

#include "resource.h"       // main symbols

/////////////////////////////////////////////////////////////////////////////
// CTRiASMIObjectsCollection
class ATL_NO_VTABLE CTRiASMIObjectsCollection : 
	public CComObjectRootEx<CComObjectThreadModel>,
	public CComCoClass<CTRiASMIObjectsCollection, &CLSID_TRiASMIObjectsCollection>,
	public CErrSupport<CTRiASMIObjectsCollection, &IID_ITRiASObjectsCollection>,
	public ITRiASObjectsCollectionCallback
{
public:
	CTRiASMIObjectsCollection()
	{
	}

	_ATLX_DEBUG_OBJECTCOUNT_IMPL(CTRiASMIObjectsCollection)

	DECLARE_REGISTRY_RESOURCEID(IDR_TRIASMIOBJECTSCOLLECTION_RGS)
	DECLARE_AGGREGATE_EX_SUPPORT();

	BEGIN_COM_MAP(CTRiASMIObjectsCollection)
		COM_INTERFACE_ENTRY(ITRiASObjectsCollectionCallback)
		COM_INTERFACE_ENTRY(ISupportErrorInfo)
		COM_INTERFACE_ENTRY_THIS()

	// durch aggregiertes Objekt implementierte Interfaces
		COM_INTERFACE_ENTRY_AGGREGATE_EX(IID_ITRiASObjectsCollection, m_BaseUnk.p)
		COM_INTERFACE_ENTRY_AGGREGATE_EX(IID_ITRiASBase, m_BaseUnk.p)
		COM_INTERFACE_ENTRY_AGGREGATE_EX(IID_IDispatch, m_BaseUnk.p)
		COM_INTERFACE_ENTRY_AGGREGATE_BLIND(m_BaseUnk.p)		// alles andere nicht gesondert behandeln
	END_COM_MAP()

	DECLARE_GET_CONTROLLING_UNKNOWN()
	DECLARE_PROTECT_FINAL_CONSTRUCT()
	HRESULT FinalConstruct()
	{
		RETURN_FAILED_HRESULT(m_BaseUnk.CreateInstance (CLSID_TRiASObjectsCollection, CLSCTX_ALL, GetControllingUnknown()));

	WTRiASObjectsCollection BaseObj;

		RETURN_FAILED_HRESULT(m_BaseUnk -> QueryInterface(BaseObj.ppi()));
		return BaseObj -> putref_ObjectsCollectionCallback(this);
	}
	void FinalRelease()
	{
		m_BaseUnk.Assign(NULL);
	}

// ISupportsErrorInfo
	STDMETHOD(InterfaceSupportsErrorInfo)(REFIID riid);

// ITRiASObjectsCollectionCallback
public:
	STDMETHOD(get_DefaultType)(BSTR *pbstrType);
	STDMETHOD(OnCreate)(VARIANT NameOrHandle, BSTR Type, OBJECTSCOLLECTIONTYPE rgType, ITRiASObjects **ppIObjs);
	STDMETHOD(OnDelete)(VARIANT vWhich);
	STDMETHOD(OnFinalRelease)();

#if defined(_READ_WRITE)
protected:
	HRESULT CreateObject (VARIANT NameOrHandle, DWORD dwType, const CLSID *pClsId, ITRiASObjects **ppIObjs);
#endif // defined(_READ_WRITE)

private:
	WUnknown m_BaseUnk;					// aggregiertes Objekt
};

#endif // !defined(_TRIASMIOBJECTSCOLLECTION_H__429413B3_D83E_49B1_933F_A097A2547882__INCLUDED_)
