// $Header: $
// Copyright© 1999-2000 TRiAS GmbH Potsdam, All rights reserved
// Created: 14.09.2000 21:21:48
//
// This file was generated by the TRiASDB Data Server Wizard V1.02.103 (#HK000729)
//
// THIS CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT WARRANTY OF ANY 
// KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
// IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A PARTICULAR 
// PURPOSE.
//
// @doc
// @module Version.h | Versionen dieses Modules

#if !defined(_VERSION_H__23904906_32FC_4258_AD33_2F0E06A7A994__INCLUDED_)
#define _VERSION_H__23904906_32FC_4258_AD33_2F0E06A7A994__INCLUDED_

#if _MSC_VER >= 1000
#pragma once
#endif // _MSC_VER >= 1000

// VersionsInfo des DataServers
#define TRIASMI_VERSION	"1"
#define TRIASMI_RELEASE	"00"
#define TRIASMI_BUILD		"056"

// VersionsInfo der TRiASMIDatabase
#define TRIASMI_VERSION_MAJOR	1
#define TRIASMI_VERSION_MINOR	00

#endif // !defined(_VERSION_H__23904906_32FC_4258_AD33_2F0E06A7A994__INCLUDED_)
