//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by TriasDB.rc
//
#define IDR_MESSAGETABLE                1
#define IDR_MSG407                      1
#define IDR_MSG00407                    1
#define IDS_PROJNAME                    100
#define IDS_CATIDDESC                   101
#define IDR_TRIASPROJECT                102
#define IDS_DBENGINE_DESC               102
#define IDR_TRIASVIEW                   103
#define IDS_NONAME                      103
#define IDR_TRIASVIEWS                  104
#define IDS_OPENCOPYTEXT                104
#define IDR_TRIASCLASSES                105
#define IDS_OPENROCAPTION               105
#define IDR_TRIASVIEWITEMS              105
#define IDR_TRIASCLASS                  106
#define IDS_ISREADONLY                  106
#define IDR_TRIASVIEWITEM               106
#define IDR_TRIASOBJECTS                107
#define IDS_USEDBYOTHERS                107
#define IDR_TRIASOBJECT                 108
#define IDS_SESSIONEND                  108
#define IDR_TRIASFEATURES               109
#define IDS_SESSIONENDCAP               109
#define IDR_TRIASFEATURE                110
#define IDS_SAVEPROJECTCAP              110
#define IDR_TRIASRELATIONS              111
#define IDS_CHANGEDBYOTHERS             111
#define IDR_TRIASRELATION               112
#define IDS_DBISCOPY                    112
#define IDR_TRIASPROJECTS               113
#define BUCHICON1                       113
#define IDS_OPENPROJECTCAP              113
#define IDI_BUCHICON1                   113
#define IDR_TRIASDBENGINE               114
#define IDS_COULDOPENONLYONE            114
#define BUCHICON2                       115
#define IDS_ADVDESCTEXT                 115
#define IDI_BUCHICON2                   115
#define IDS_TRIASCONNECTION_DESC        116
#define IDS_SHAREVIOLATIONCOPYTEXT      116
#define IDR_TRIASCONNECTION             117
#define IDS_GEOMETRYFEATURE             117
#define IDR_TRIASCONNECTIONS            118
#define IDS_BROKENLINK                  118
#define IDR_TRIASDATABASE               119
#define IDS_OBJECTCOUNT_DESC            119
#define IDR_TRIASCOMPATIBLEDATABASE     120
#define IDS_OBJECTCOUNT_TEXT            120
#define IDR_TRIASPROPERTY               121
#define IDS_OBJECTALLOCS_DESC           121
#define IDR_TRIASPROPERTIES             122
#define IDS_OBJECTALLOCS_TEXT           122
#define IDR_TRIASDBPROPERTYSUPPORT      123
#define IDS_OBJECTFREES_DESC            123
#define IDS_OBJECTFREES_TEXT            124
#define IDS_OBJECTCOUNTS_DESC           125
#define IDR_TRIASDATASERVERREGENTRIES   126
#define IDS_OBJECTCOUNTS_TEXT           126
#define IDR_TRIASDATASERVERREGENTRY     127
#define IDS_DUMMY                       127
#define IDR_TRIASSIMPLEOBJECTS          128
#define IDS_NONAME_CNT                  128
#define IDS_BROKENLINKDIR               129
#define IDR_OPENWIZPROPEXT              130
#define IDS_COULDNOTREOPENCONNECTION    130
#define IDR_TRIASOBJECTHANDLEMAP        131
#define IDS_BROKENCONNECTION            131
#define IDR_TRIASOBJECTSCOLLECTION      132
#define IDS_COULDNOTRECONNECT           132
#define IDR_TRIASSIMPLEOBJECT           135
#define IDR_TRIASSIMPLEFEATURE          137
#define IDR_TRIASSIMPLEFEATURES         138
#define IDR_DATABASEFEATUREMAP          140
#define IDR_TRIASGUIDFEATURE            151
#define IDR_TRIASOBJECTSOPERATIONS      152
#define IDR_TRIASSIMPLEOBJECTSCOLLECTION 155
#define IDR_CONNECTIONMONIKER           157
#define IDR_OLEDOCUMENTWRAPPER          158
#define IDR_TRIASCONNECTIONFILTERS      159
#define IDR_TRIASCONNECTIONFILTER       160
#define IDC_COMPATIBLE_WITH_V2          202
#define IDC_DATABASE_TEMPLATE           203
#define IDC_COMPATIBLE_WITH_V4          203
#define IDC_COMPRESS_STREAMS            204
#define IDC_COMPATIBLE_210              205
#define IDR_DBD014                      209
#define IDR_DBD015                      210
#define IDR_DBDOLD                      211
#define IDC_YESALL                      211
#define IDR_PBDOLD                      212
#define IDC_NOALL                       212
#define IDR_PBD011                      213
#define IDC_PROMPT                      213
#define IDR_DBDRIW                      217
#define IDC_PROMPT_STATIC               218
#define IDI_PROJECT                     223
#define IDR_TRIASVARIANTPROPERTY        229
#define IDR_TRIASOBJECTSHANDLEMAP       234
#define IDR_DBD017                      235
#define IDR_DBD018                      236
#define IDR_TRIASFEATUREHANDLEMAP       237
#define IDR_TRIASSIMPLEGEOFEATURE       238
#define IDR_TRIASSIMPLEGEOFEATURES      239
#define IDR_GENOBJECTMAP                240
#define IDR_TRIASAUTOSAVEPROPERTY       246
#define IDR_TRIASDATABASEONSTG          253
#define IDR_TEMPLATEWIZPROPEXT          255
#define IDR_PBD012                      256
#define IDR_TRIASGENERICHANDLEMAP       257
#define IDR_PBD013                      257
#define IDR_METADATAMAP_RGS             258
#define IDD_MESSAGEBOXEX                262
#define IDI_ICON_QUESTION               263
#define IDR_DBD019                      264
#define IDC_SELECTCOORDSYSTEM           1000
#define ID_DBDTEMPLATE                  5000
#define IDS_DATABASENOTOPEN             10000
#define IDS_INVALIDPARAMETER            10001
#define IDS_DBERROR                     10002
#define IDS_COULDNOTOPEN                10003
#define IDS_ALREADYOPENED               10004
#define IDS_DBENGINENOTSTARTED          10005
#define IDC_TEMPLATE_DESCRIPTION        22037
#define IDC_CREATENEW_BMP               22038
#define IDC_DEZIMAL                     22043
#define IDC_HEXADEZ                     22044
#define IDC_COMPATIBILITYMODE           22048
#define IDC_DESCTEXT                    22050
#define IDC_ADVANCEDDESC                22061
#define IDB_CREATENEW                   22141
#define IDD_CREATENEWWIZARD_PARAMS      22159
#define IDD_CREATENEWWIZARD_TEMPLATE    22160
#define IDD_MESSAGEBOXEXCANCEL          22161

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        265
#define _APS_NEXT_COMMAND_VALUE         32768
#define _APS_NEXT_CONTROL_VALUE         219
#define _APS_NEXT_SYMED_VALUE           161
#endif
#endif
