#	@ECHO === MAKE WITH MSDEV %T3PROJECT% /OUT $(T3LOGDIR)\%T3LOGFILE% /MAKE %T3CONFIG% $(T3BUILDOPTIONS)
#	@%T3MSDEV% %T3PROJECT% /OUT $(T3LOGDIR)\%T3LOGFILE% /MAKE %T3CONFIG% $(T3BUILDOPTIONS)
	@ECHO === MAKE WITH MSDEV %T3PROJECT% /OUT $(T3LOGDIR)\%T3LOGFILE% /MAKE %T3CONFIG% $(T3BUILDOPTIONS)
	@%T3MSDEV% %T3PROJECT% /OUT $(T3LOGDIR)\%T3LOGFILE% /MAKE %T3CONFIG% $(T3BUILDOPTIONS)