#
# VC++ makefile to build the MITAB library and test programs
#

default:
	cd cpl
	nmake -f makefile.vc
	cd ..\ogr
	nmake -f makefile.vc
	cd ..\mitab
	nmake -f makefile.vc

clean:
	cd cpl
	nmake -f makefile.vc clean
	cd ..\ogr
	nmake -f makefile.vc clean
	cd ..\mitab
	nmake -f makefile.vc clean
