//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by DBASEEXT.RC
//
#define IDM_SHOWDBASE                   1
#define IDM_SHOW_AL                     101
#define IDM_STORE_AL                    102
#define IDM_CHANGE_AL                   103
#define IDM_CREATE_ALIAS_FILE           104
#define IDM_SET_ALIAS_FILE              105
#define IDM_CHANGE_ALIAS_FILE           106
#define IDM_AKT_ALIAS_FILE              107
#define IDS_DBASEMENUITEM               1000
#define IDS_OBJPROPFUNC                 1001
#define IDS_INDEX_CAPTION               1002
#define IDS_ONE_INDEX                   1003
#define IDS_OTHER_INDEX                 1004
#define IDS_INDEX_EXT                   1005
#define IDS_ALIAS_SPEC                  1006
#define IDS_ALIAS_SEL_CAPTION           1007
#define IDD_MEMO                        2000
#define IDE_MEMO                        2001
#define IDS_EMPTYMEMO                   2002
#define IDD_DBF                         2003
#define IDL_ROW                         2004
#define IDL_COLUMN                      2005
#define IDM_DBF                         2006
#define IDM_ROWCOL                      2007
#define IDM_COPY                        2008
#define IDM_FIRSTENTRY                  2010
#define IDM_LASTENTRY                   2011
#define ID_TOOLBARS72                   2012
#define ID_TOOLBARS96                   2013
#define ID_TOOLBARS120                  2014
#define ID_ROWGIZMOBAR                  2015
#define IDM_FIRSTROW                    2016
#define IDM_LASTROW                     2017
#define ID_SEPARATOR1                   2018
#define ID_SEPARATOR2                   2019
#define IDM_FIRSTSCROLL                 2020
#define IDM_BIGLEFTSCROLL               2021
#define IDM_ONELEFTSCROLL               2022
#define IDM_ONERIGHTSCROLL              2023
#define IDM_BIGRIGHTSCROLL              2024
#define IDM_LASTSCROLL                  2025
#define IDB_ROW                         2026
#define IDS_ZEILENTEXT                  2027
#define ID_COLGIZMOBAR                  2028
#define IDM_FIRSTCOL                    2029
#define IDM_LASTCOL                     2030
#define IDB_COLUMN                      2031
#define IDM_PREVFIELD                   2032
#define IDM_NEXTFIELD                   2033
#define ID_SEPARATOR3                   2034
#define ID_SEPARATOR4                   2035
#define ID_SEPARATOR5                   2036
#define IDC_FIELDNAMES                  2037
#define IDS_SPALTENTEXT                 2038
#define IDS_DBASEOPFHELP                2039
#define IDS_CLIPOPTION                  2040
#define IDS_LONGCLASSNAME               2041
#define IDS_DBF_EXT                     2042
#define IDS_DBASEOPF                    2043
#define IDS_DBASEKEY                    2044
#define IDS_SYSTEM_ERROR                2045
#define IDS_BAD_FORMAT                  2046
#define IDS_GROUP_NAME                  2047
#define IDS_EDIT_NOT_FOUND              2048
#define IDS_GEN_ERROR                   2049
#define IDS_LOAD_EDIT_CAPTION           2010
#define IDM_VDBASE_HELP                 2511
#define IDM_CREATE_INDEX                2512
#define IDM_REL                         2600

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        108
#define _APS_NEXT_COMMAND_VALUE         108
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           108
#endif
#endif
