T3PROJECT=TERRTRK

!IF defined(MASTERMAKE)
!INCLUDE $(MASTERMAKE)
!ELSE
$(TRIASDIR_D)\$(T3PROJECT)D.dll :
	SET T3PROJECT=$(T3PROJECT).dsp
	SET T3CONFIG="$(T3PROJECT) - Win32 Debug"
	SET T3LOGFILE=$(T3PROJECT).log
!INCLUDE C:\MAKE\MkMSDEV.mak	

$(TRIASDIR_R)\$(T3PROJECT).dll :
	SET T3PROJECT=$(T3PROJECT).dsp
	SET T3CONFIG="$(T3PROJECT) - Win32 Release"
	SET T3LOGFILE=$(T3PROJECT).log
!INCLUDE C:\MAKE\MkMSDEV.mak	
!ENDIF
