/* $Header:   G:/cv.win/pvcs/commonvu/src/appstrt2.cxv   3.0   25 Mar 1992 15:23:10   RONAN  $
 *
 *	A P P S T A R T  . C X X
 *
 *  Copyright (c) 1992 Trischford Limited 
 *  ( A wholly owned subsidary of Computer Associates International, Inc)
 *  All Rights Reserved
 *
 *	Version 3.1			Nov 1992
 *
 *	Mods Log:
 *	0.0	ferg	05oct88	Milestone	2 .. Beta 2 ship date.
 *	0.1	ferg	11oct88	Presentation Manager Integration.
 *	0.2 jk		29nov88 ------ Milestone 2A. Beta 2A ship date. ------
 *	0.3 jk		02dec88 Fast Compile defines added.
 *  1.0	rs		29mar89 -------Release 1.0 ship date ----------------
 *  1.1	rs		07jul89 -------Release 1.0a ship date ---------------
 */
#include "tfrmlib.hxx"

void	App::  Start	(const int, const char*[])
{
	App::Start();
}	// End of "App" FUNCTION "Start"

