# Makefile zur Erstellung von TRiAS - TRSABiS

$(TRIASDIR_D)\TRSABiSd.ext :
	SET T3PROJECT=TRSABiS.dsp
	SET T3CONFIG="TRSABIS - Win32 Debug"
	SET T3LOGFILE=TRSABiS.log
!INCLUDE C:\MAKE\MkMSDEV.mak	

$(TRIASDIR_R)\TRSABiS.ext :
	SET T3PROJECT=TRSABiS.dsp
	SET T3CONFIG="TRSABIS - Win32 Release MinSize"
	SET T3LOGFILE=TRSABiS.log
!INCLUDE C:\MAKE\MkMSDEV.mak	
