// TestPerfMon.idl : IDL source for TestPerfMon.dll
//

// This file will be processed by the MIDL tool to
// produce the type library (TestPerfMon.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

[
	uuid(46745290-9CBA-11D2-9F09-006008447800),
	version(1.0),
	helpstring("TestPerfMon 1.0 Type Library")
]
library TESTPERFMONLib
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

};
