//  Copyright (c) 1992 Trischford Limited 
//  ( A wholly owned subsidary of Computer Associates International, Inc)
//  All Rights Reserved
//
//	Version 3.1			Nov 1992

#ifndef _CVRESID_H
#define _CV_RESID_H

#define ID_CVHELP		0xFFFF
#define ID_CVHELPON		0xFFFE
#define ID_CVHELPOFF		0xFFFD
#define ID_FIRSTCVHELPID 	0xFFFD

#define ID_MDISETMENU		0xFFFC
#define ID_FIRSTSYSTEMID 	0xFFFC

#define ID_DEBUGBANNER		0x900
#define ID_BETABANNER		0x901

#endif

