//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Trias323.RC
//
#define VER_DEBUG                       0
#define IDS_GLOBALUNDOLIST              1
#define IDR_TYPELIB                     1
#define IDR_REGISTRYHELPER              1
#define IDS_GLOBALREDOLIST              2
#define IDS_UNDOCREATEFEATURE           3
#define IDS_UNDOEDITFEATURE             4
#define IDS_UNDODELETEFEATURE           5
#define IDS_UNDODELETETEXT              6
#define IDS_UNDOCREATETEXT              7
#define IDS_UNDODELETERELATION          8
#define IDS_UNDOCREATERELATION          9
#define IDS_DELETEOBJHWND               10
#define IDS_UNDODELETEOBJECT            11
#define IDS_UNDOMODIFYOBJECT            12
#define IDS_FILETEMPLATE                13
#define IDS_UNDOCREATEPBDDATA           14
#define IDS_UNDOCREATEPBDDATA2          15
#define IDS_UNDOCREATEPBDDATA3          16
#define IDS_UNDOCREATEPBDDATA4          17
#define IDS_UNDODELETEPBDDATA           18
#define IDS_UNDODELETEPBDDATA2          19
#define IDS_UNDODELETEPBDDATA3          20
#define IDS_UNDODELETEPBDDATA4          21
#define IDS_UNDOEDITPBDDATA             22
#define IDS_UNDOEDITPBDDATA2            23
#define IDS_UNDOEDITPBDDATA3            24
#define IDS_UNDOEDITPBDDATA4            25
#define IDS_HEADERIDENT                 26
#define IDS_HEADERDESC                  27
#define IDS_UNDOVISINFO                 28
#define IDS_UNDOMODIDENT                29
#define IDS_GENERRORCAP                 30
#define IDS_ADDERROR                    31
#define IDS_QUERYCONTINUE               32
#define IDS_PROPINFO_IDENTOTYP          33
#define IDS_HELPDESC_IDENTOTYP          34
#define IDS_PROPGROUPNAME               35
#define IDS_PROPINFO_CLASSIFYOBJ        35
#define IDS_PROPINFO_MODIDENT           36
#define IDS_HELPDESC_MODIDENT           37
#define IDS_UNDOMODIDENTS               38
#define IDS_PROPINFO_OBJWND             39
#define IDS_HELPDESC_OBJWND             40
#define IDS_HELPDESC_PROPSEQUENCE       41
#define IDS_PROPINFO_PROPSEQUENCE       42
#define IDS_ENUMOBJECTSBYNMUMBER        43
#define IDS_PROPINFO_ORWNDDEST          44
#define IDS_HELPDESC_ORWNDDEST          45
#define IDS_NEWOBJCAPTION               46
#define IDS_TEXTSEARCHENGINE_DESC       47
#define IDS_REGISTRAR_DESC              48
#define IDS_NOT_IN_MAP                  49
#define IDS_UNEXPECTED_EOS              50
#define IDS_VALUE_SET_FAILED            51
#define IDS_RECURSE_DELETE_FAILED       52
#define IDS_EXPECTING_EQUAL             53
#define IDS_CREATE_KEY_FAILED           54
#define IDS_DELETE_KEY_FAILED           55
#define IDS_OPEN_KEY_FAILED             56
#define IDS_CLOSE_KEY_FAILED            57
#define IDS_UNABLE_TO_COERCE            58
#define IDS_BAD_HKEY                    59
#define IDS_MISSING_OPENKEY_TOKEN       60
#define IDS_CONVERT_FAILED              61
#define IDS_TYPE_NOT_SUPPORTED          62
#define IDS_COULD_NOT_CONCAT            63
#define IDS_COMPOUND_KEY                64
#define IDS_INVALID_MAPKEY              65
#define IDS_UNSUPPORTED_VT              66
#define IDS_VALUE_GET_FAILED            67
#define IDS_VALUE_TOO_LARGE             68
#define IDS_MISSING_VALUE_DELIMETER     69
#define IDS_DATA_NOT_BYTE_ALIGNED       70
#define IDS_UNDOCREATEOBJECT            71
#define IDS_NOOBJECTSFOUND              72
#define IDS_PROPINFO_DELOBJECT          73
#define IDS_HELPDESC_DELOBJECT          74
#define IDS_DELOBJECTRESULT             75
#define IDS_DELOBJECTSTATUS             76
#define IDS_PROPINFO_CREATETEXT         77
#define IDS_HELPDESC_CREATETEXT         78
#define IDS_REPLACEOBJHWND              79
#define IDS_ADDTOOBJHWND                80
#define IDS_HELPDESC_CLASSIFYOBJ        81
#define IDS_NOVALUE                     82
#define IDS_PROPINFO_IMPORTDATA         83
#define IDS_HELPDESC_IMPORTDATA         84
#define IDS_IMPORTFMTDLGCAP             85
#define IDS_NOIMPORTFILTERS             86
#define IDS_IMPORTNOMULTISEL            87
#define IDS_GENTEXTPROPACT_DESC         88
#define IDS_HELPDESC_GENTEXTPROPACT     89
#define IDS_NODEPOBJPROP                90
#define IDS_SCRIPTPROPACT_DESC          90
#define IDS_SCRIPTPROPACT_HELPDESC      91
#define IDS_STANDARDSTATUSTEXT          92
#define IDD_STATUSDLG                   101
#define IDB_SELALLCLASSES               101
#define ID_ANYCHAR                      101
#define IDT_FILE                        102
#define ID_CHARINRANGE                  102
#define ID_CHARNOTINRANGE               103
#define IDB_PLFT_SMALL                  104
#define ID_BEGINOFTEXT                  104
#define IDB_PLFT_LARGE                  105
#define IDD_SELECTIDS_WIZ               105
#define ID_LINEEND                      105
#define IDD_OBJECTROP_WIZ               106
#define IDB_PLFT_SMALL1                 106
#define IDD_SELECTREL_WIZ               107
#define ID_OR                           107
#define IDD_SELECTOBJWND_WIZ            108
#define ID_ZEROORMORE                   108
#define IDT_TIME                        109
#define IDD_DESTOBJWND_WIZ              109
#define IDR_TEXTSEARCHENGINE            109
#define ID_ONEORMORE                    109
#define IDD_MODIFYIDS_WIZ               110
#define IDR_PROPINFO_IDENTOTYP          110
#define IDD_TEXTSEARCHENGINE_CFG        111
#define IDR_PROPINFO_MODIDENT           111
#define ID_WORDBOUNDARY                 111
#define IDR_PROPINFO_OBJWND             112
#define IDD_TEXTSEARCHENGINE_CFG_WIN32S 112
#define ID_WITHINWORD                   112
#define IDR_PROPINFO_PROPSEQUENCE       113
#define IDD_SELECT_OBJPROPS             113
#define ID_WORDBEGIN                    113
#define IDR_PROPINFO_ORWNDDEST          114
#define IDD_STATUSDLG_AVI               114
#define ID_WORDEND                      114
#define IDR_ENUMOBJECTSBYNMUMBER        115
#define ID_BEGINOFLINE                  115
#define IDD_CREATETEXTS_WIZ             115
#define IDI_DEINSTALL                   116
#define ID_ENDOFLINE                    116
#define IDD_IMPORT_WIZ                  116
#define IDB_ARROW_RIGHT                 117
#define IDB_ARROW_RIGHT_SEL             118
#define IDR_REGEXPR                     118
#define IDB_ARROW_RIGHT_DISABLED        119
#define IDB_OBJPROPTYPES                119
#define ID_ZEROORONE                    119
#define IDB_ARROW_RIGHT_FOCUS           120
#define ID_GROUPTOKENS                  120
#define IDB_ARROW_DOWN                  121
#define IDB_ARROW_DOWN_DISABLED         122
#define IDB_ARROW_DOWN_FOCUS            123
#define IDB_ARROW_DOWN_SEL              124
#define IDR_PROGRESSINDICATOR_RGS       128
#define IDR_MULTIPI_RGS                 130
#define IDR_PROPINFO_DELOBJECT          131
#define IDR_PROPINFO_CREATETEXT_RGS     132
#define IDB_CHECKMARKS_NT               133
#define IDB_CHECKMARKS_40               134
#define IDR_REGISTEREXT_RGS             135
#define IDR_REGISTRY                    136
#define IDR_PROPINFO_CLASSIFYBYOBJPROP  137
#define IDR_PROPINFO_IMPORTDATA         140
#define IDR_GENTEXTPROPACT              142
#define IDR_SCRIPTPROPACT               143
#define IDR_SCRIPT_COPYOBJECTS          145
#define IDR_OBJEKTEDOPPELN              147
#define IDR_SCRIPT_UNIONOBJECTS         148
#define IDR_OBJEKTEVEREINIGEN           150
#define IDR_FAKETRIASLOCKFEATURE        151
#define QUERYFIELDDLG                   162
#define IDPB_STATUS                     1000
#define IDT_PERCENT                     1001
#define IDC_LISTDESTIDENTS              1001
#define IDT_FILENAME                    1002
#define IDC_ADDTOVIEW                   1002
#define IDC_LISTIDENTS                  1003
#define IDC_DEFINENEW                   1003
#define IDT_OBJECTNUMBER                1004
#define IDC_ACTIVATED                   1004
#define IDT_TIMETEXT                    1005
#define IDC_OBJPROPS                    1005
#define IDC_OBJPROPERTY                 1005
#define IDC_FINDWHAT                    1007
#define IDC_EQUAL                       1008
#define IDC_INSERT_REGEXPR              1008
#define IDC_EXISTS                      1009
#define IDC_SELECT_OBJPROP              1009
#define IDC_CAPITAL                     1010
#define IDC_LISTRELATIONS               1011
#define IDC_FULLMATCH                   1011
#define IDC_LISTOBJWND                  1012
#define IDC_USEREGEXPR                  1012
#define IDC_SELECTALL                   1013
#define IDC_FUZZYMATCH                  1013
#define IDC_ALLOBJECTS                  1014
#define IDC_SELECTEDOBJECTS             1015
#define IDC_CREATENEWOBJWND             1016
#define IDC_SELECTOBJWND                1017
#define IDC_ANIMATE                     1017
#define IDC_RETAINSELECTION             1018
#define IDC_SELECTNEW                   1019
#define IDC_PARTIALMATCH                1019
#define IDC_BEGINOFTEXT                 1020
#define IDC_EXISTSONLY                  1021
#define IDT_SEARCH                      1022
#define IDC_OBJECTPROPS                 1024
#define IDC_CREATEDEPENDEND             1025
#define IDC_DONOTMOVE                   1028
#define IDC_IMPORTGEOMETRY              1028
#define IDC_DELETE                      1029
#define IDC_IMPORTFEATURES              1029
#define IDC_REPLACE                     1030
#define IDC_IMPORTRELATIONS             1030
#define IDC_OPTIONSELECT                1031
#define IDC_IMPORTVISUALISATION         1031
#define IDC_NEGATE                      1032
#define IDB_CONFIG                      1032
#define IDC_CLASSIFYALL                 1033
#define IDC_DYNAMICLABEL                1034
#define IDC_IMPORTFORMATS               1035
#define IDC_IMPORTFILES                 1036
#define IDC_SELECTIMPORTFILES           1037
#define IDC_FROMOBJPROP                 1038
#define IDC_IMPORTANSIOEM               1039
#define IDC_DIRECTINPUT                 1039
#define IDC_ROTATEFORLINES              1040
#define IDC_DIRECTTEXTLIST              1041
#define IDC_NOTEXISTANT                 1042
#define IDC_DELETETARGETOBJECT          1043
#define IDC_CHECK_SELECTIDENT           1044
#define IDC_STATIC_SELECTIDENT          1045
#define IDC_COORDSYS                    1060
#define IDS_OBJPROPFTEXT                1326
#define IDS_OBJPROPPUNKTOBJSH           1413
#define IDS_OBJPROPKANTENOBJSH          1414
#define IDS_OBJPROPFLAECHENOBJSH        1415
#define IDS_OBJPROPTEXTOBJSH            1416
#define IDS_OBJPROPKOMPLEXOBJSH         1417
#define IDS_OBJPROPUNKNOWNOBJSH         1418
#define IDS_OBJPROPOBJTYPSHORT          1419
#define IDS_OBJPROPTYPHELPSHORT         1420
#define IDM_MCODEFORMAT                 1422
#define IDCB_USEFORALL                  1840
#define IDE_FIELDTEXT                   1841
#define IDR_COPY_AVI                    2000
#define IDR_MOVE_AVI                    2001
#define IDR_DELETE_AVI                  2002
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        152
#define _APS_NEXT_COMMAND_VALUE         121
#define _APS_NEXT_CONTROL_VALUE         1046
#define _APS_NEXT_SYMED_VALUE           106
#endif
#endif
