// Definition der Parameter für ASCIMP.EXT ------------------------------------
// File: INPUT.H

#if !defined(_INPUT_H)
#define _INPUT_H

// Feldgrößen -----------------------------------------------------------------
#define MAXGI	100000
#define MAXINZ	5000
#define MAXMI	5000

// Standardwerte --------------------------------------------------------------
#define DEFAULT_EPS	2

#endif // _INPUT_H
