# Makefile für CustomTargets in Module ASCIMP.EXT -----------------------------

!include "$(TRIASINCLUDE)/triasver.mak"

# Generierungsdatum (yymmdd) und Version
DATE=040523
VERSION = 1
RELEASE = 00
BUILD = 069

COPYRIGHT = HK$(DATE)

PNAME = $(TRIAS_PNAME)
PADDRESS = $(TRIAS_PADDRESS)

STUB = rights
RIGHTS = $(STUB).exe
REPLACE = ersetz
NAME = ascimp
DEF = $(NAME).def
LEXFLAGS = -s -l
YACCFLAGS = -Dytab.h -C$*.cpp -n -s

ASM = masm
ASMF = /D?PLM=0 /D?WIN=1
LINK = link16.exe
YACC = c:/bin/tools/pcyacc
LEX = c:/bin/tools/pclex

# ------------------------------------------------------------------------------
all:	ascparsy.cpp ascparsl.cpp

ascparsl.cpp:	ascpars.lx ytab.h ascpars.h
	$(LEX) $(LEXFLAGS) ascpars.lx
	@del ascparsl.cpp
	@ren ascpars.c ascparsl.cpp

ascparsy.cpp ytab.h:	ascpars.y
	$(YACC) $(YACCFLAGS) ascpars.y

# Generieren der Versionsinfo's -----------------------------------------------
# CopyrightEintraege Generieren 
new:
	@del $(NAME).rcv
	@del $(DEF)
	@del version.h

formake:	$(DEF) $(NAME).rcv version.h

# Personalisierungsinformation
$(NAME).rcv:	$(NAME)v.tpl makefile
	$(REPLACE) \
		$(VERSION) \
		$(RELEASE) \
		$(BUILD) \
		$(COPYRIGHT) \
		$(PNAME) \
		$(PADDRESS) \
		$(TRIAS_VERSION) \
		$(TRIAS_RELEASE) \
		$(COMPANYNAME) \
			$(NAME)v.tpl $(NAME).rcv

$(DEF):		$(NAME).tpl makefile
	$(REPLACE) \
		$(VERSION) \
		$(RELEASE) \
		$(BUILD) \
		$(COPYRIGHT) \
			$(NAME).tpl $(DEF)

version.h:	version.tpl makefile
	$(REPLACE) \
		$(VERSION) \
		$(RELEASE) \
			version.tpl version.h
