//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by LineTools.rc
//
#define IDM_CODECHECK                   1
#define IDM_CODECHECKMULTI              2
#define IDM_CHECKGEOMETRIE              3
#define IDM_LINECHECK                   4
#define IDM_CLASSIFY                    5
#define IDM_CLASSIFYWINDOW              6
#define IDS_PROJNAME                    100
#define IDS_LONGCLASSNAME               101
#define IDR_MENU1                       102
#define IDR_MENU2                       103
#define IDR_CCODESTAT                   105
#define IDS_DESCRIPTION_CCODESTAT       106
#define IDR_CODELINE                    108
#define IDS_DESCRIPTION_CODELINE        109
#define IDR_CODECHECK                   112
#define IDS_DESCRIPTION_CODECHECK       113
#define IDR_CLSFYBYCODE                 114
#define IDS_DESCRIPTION_CLSFYBYCODE     115
#define IDC_DUPLGEOMETRY                201
#define IDC_DUPLICATEKEY                202
#define IDC_NOKEY                       203
#define IDC_SYNTAXERROR                 204
#define IDC_ALLOFERRORS                 205
#define IDC_OTHERFEATURE                206
#define IDC_CONTROLCODE                 220
#define IDC_CONTROLERROR                223
#define IDC_UNDVERKNUEPFUNG             225
#define IDC_ODERVERKNUEPFUNG            226
#define IDC_ERRBESCHREIBUNG             227
#define IDC_MULTIGEOMETRY               228
#define IDC_CONTROLORIGINAL             229
#define IDC_CHECKFIRSTCTRL              230
#define IDC_CHECKFEATURE                231
#define IDC_CHECKINTERN                 232
#define IDC_LINEDESCRIPTION             233
#define IDC_LINEGCSCONTROL              234
#define IDC_AREACONSTRUCTION            235
#define IDC_LINECONSTRUCTIOMN           236
#define IDC_LINECONSTRUCTION            236
#define IDC_HELPCONSTRUCTION            237
#define IDC_GCOIDENT                    238
#define IDC_SELECTCAPTION               239
#define IDC_ERRORSTATIST                240
#define IDS_MENUENTRY                   20104
#define IDS_ORMENUENTRY                 20105
#define IDS_SHOWXMLERROR_CAP            20106
#define IDS_NOXMLDOMPARSER              20107
#define IDS_CODECHECKDATA               20108
#define IDS_CODECHECKCAP                20109
#define IDS_ORCODECHECKCAP              20110
#define IDS_NOWORKING                   20111
#define IDS_OBJECTGCSCODE               20112
#define IDS_DBUSERNAME                  20113
#define IDS_GCOERRORCODE                20114
#define IDS_CODECHECKMULTICAP           20119
#define IDS_ORCODECHECKMULTICAP         20120
#define IDS_CHECKGEOMETRIECAP           20121
#define IDS_ORCHECKGEOMETRIECAP         20122
#define IDS_CODECHECKXML                20123
#define IDS_ORCODECHECKXML              20124
#define IDS_CHECKGEOMETRIEXML           20125
#define IDS_ORCHECKGEOMETRIEXML         20126
#define IDS_CODECHECKMULTIXML           20127
#define IDS_ORCODECHECKMULTIXML         20128
#define IDS_LINKFEATURE                 20129
#define IDS_ERRORCODEFEATURE            20130
#define IDS_LINKFEATUREKEY              20131
#define IDS_ERRORCODEFEATUREKEY         20132
#define IDS_GCAVORSPANN                 20133
#define IDS_GCOCODE                     20134
#define IDS_GCOCODEKEY                  20135
#define IDS_PROJECTLAYER                20136
#define IDS_UNDBESCHREIBUNG             20137
#define IDS_CODEWIDERSPRUCH             20138
#define IDS_ODERBESCHREIBUNG            20139
#define IDS_ERRORKEY01                  20140
#define IDS_ERRORKEY02                  20141
#define IDS_ERRORKEY03                  20142
#define IDS_ERRORKEY04                  20143
#define IDS_ERRORKEY05                  20144
#define IDS_ERRORKEY06                  20145
#define IDS_ERRORCODESTRING             20146
#define IDS_GCORIGINAL                  20147
#define IDS_GCORIGINALKEY               20148
#define IDS_LINEFEATBEMA                20149
#define IDS_LINEFEATBEMD                20150
#define IDS_LINECHECKCAP                20151
#define IDS_ORLINECHECKCAP              20152
#define IDS_LINECHECKXML                20153
#define IDS_ORLINECHECKXML              20154
#define IDS_HELPNOTCTRL                 20155
#define IDS_HELPFEATURE                 20156
#define IDS_CLASSIFYCAP                 20158
#define IDS_ORCLASSIFYCAP               20159
#define IDS_CLASSIFYXML                 20160
#define IDS_ORCLASSIFYXML               20161
#define IDD_CODECHECK_OPTIONS           21104
#define IDD_CCODESTAT_OPTIONS           21105
#define IDD_CODELINE_OPTIONS            21106
#define IDD_CLSFYBYCODE_OPTIONS         21107
#define IDS_HELPINTERN                  21157
#define IDS_CLASSIFYWINDOWXML           21158
#define IDS_ORCLASSIFYWINDOWXML         21159
#define IDS_CLASSIFYWINDOWCAP           21160
#define IDS_ORCLASSIFYWINDOWCAP         21161
#define IDS_HELPAREACTRL                21162
#define IDS_HELPLINECTRL                21163
#define IDS_TESTUNREF                   21164
#define IDS_LINECAPTION                 21165
#define IDS_MULTICAPTION                21166
#define IDS_HELPLINEAREACTRL            21167
#define IDS_HELPLINELINECTRL            21168
#define IDS_HELPMULTIAREACTRL           21169
#define IDS_HELPMULTILINECTRL           21170
#define IDS_ERRORLINE                   21171
#define IDS_HEADERLINE                  21172
#define IDS_EXITLINE                    21173

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        219
#define _APS_NEXT_COMMAND_VALUE         32774
#define _APS_NEXT_CONTROL_VALUE         241
#define _APS_NEXT_SYMED_VALUE           118
#endif
#endif
