# Makefile.src
# Copyright (c) 1997, Regents of the University of California
# $Header: /usr/local/devel/GiST/libgist/src/libbtree/Makefile.src,v 1.3 2000/03/15 00:24:08 mashah Exp $

SRCS += $(LIBBTREEDIR)/gist_btree.cc

ifeq (${AMDB},true)
SRCS += $(LIBBTREEDIR)/amdb_btree.cc
endif
