//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Geoedit.rc
//
#define IDM_VERTEXMOD                   10
#define IDM_VERTEXADD                   11
#define IDM_VERTEXDEL                   12
#define IDM_LINEELONG                   13
#define IDM_OBJECTROT                   14
#define IDM_LINEPART                    15
#define IDM_OBJECTPART                  16
#define IDM_OBJECTCUT                   17
#define IDM_ISLANDADD                   18
#define IDM_ISLANDDEL                   19
#define IDM_RECHTWINKL                  20
#define IDM_COMMONBORDER                21
#define IDM_OBJECTDEL                   22
#define IDM_LINETOAREA                  23
#define IDM_AREATOLINE                  24
#define IDR_COMMONBORDER                103
#define IDR_ENUMOBJEKTGEOMETRIE         120
#define IDR_DRAGMULTILINE               121
#define IDR_TOPICALOBJECTS              122
#define IDR_NEWPOINT                    123
#define IDR_NEWLINE                     124
#define IDR_NEWAREA                     125
#define IDR_OBJECTMOVE                  126
#define IDR_OBJECTMODIFY                127
#define IDR_VERTEXMOVE                  128
#define IDR_VERTEXADD                   129
#define IDR_LINEELONGATION              130
#define IDR_AREAPARTITION               131
#define IDR_ISLANDADD                   132
#define IDR_MAKERECTANGULAR             133
#define IDR_DESIGNING                   134
#define IDR_RESTRICTLINE                135
#define IDR_RESTRICTCURSOR              136
#define IDB_TOOLBAREDIT                 200
#define IDB_TOOLBARDESIGN               201
#define IDC_CUREDIT                     202
#define IDC_CURVERTEX                   203
#define IDC_CURLINE                     204
#define IDC_CURDELETE                   205
#define IDC_CURINSIDE                   206
#define IDC_CURGRAB                     207
#define IDB_COMM                        222
#define IDB_COMM_SEL                    223
#define IDB_COMM_FOCUS                  224
#define IDB_COMM_DISABLED               225
#define IDB_CIRC                        226
#define IDB_CIRC_SEL                    227
#define IDB_CIRC_FOCUS                  228
#define IDB_CIRC_DISABLED               229
#define IDB_CLOS                        230
#define IDB_CLOS_SEL                    231
#define IDB_CLOS_FOCUS                  232
#define IDB_CLOS_DISABLED               233
#define IDB_DELE                        234
#define IDB_DELE_SEL                    235
#define IDB_DELE_FOCUS                  236
#define IDB_DELE_DISABLED               237
#define IDR_POINTMODMENUE               300
#define IDR_LINEMODMENUE                301
#define IDR_AREAMODMENUE                302
#define IDD_SINGLEDESIGNING             1000
#define IDR_STRECKE                     1001
#define IDR_GERADE                      1002
#define IDR_KREIS                       1003
#define IDR_ANGLE90                     1004
#define IDR_ANGLEFREE                   1005
#define IDE_ANGLE                       1006
#define IDT_DISTANCE                    1007
#define IDE_DISTANCE                    1008
#define IDD_FIXPOINTS                   1010
#define IDR_END2                        1011
#define IDR_END1                        1012
#define IDR_MIDDLE                      1013
#define IDR_MOUSECLICK                  1014
#define IDT_RWK                         1015
#define IDT_HWK                         1016
#define IDT_RW1                         1017
#define IDT_HW1                         1018
#define IDT_RW2                         1019
#define IDT_HW2                         1020
#define IDT_RWM                         1021
#define IDT_HWM                         1022
#define IDB_CONTINUE                    1100
#define IDB_ISLAND                      1101
#define IDD_EDITBASE                    1200
#define IDL_IDENTIFIKATOR               1201
#define IDT_OPTIONEN                    1202
#define IDP_BORDER                      1203
#define IDB_CLOSE                       1204
#define IDT_CLOSE                       1205
#define IDB_CIRCLE                      1206
#define IDT_CIRCLE                      1207
#define IDB_COMMONBORDER                1208
#define IDT_COMMONBORDER                1209
#define IDD_COORDMODIFY                 1300
#define IDE_XKOORD                      1301
#define IDE_YKOORD                      1302
#define IDB_DELETE                      1303
#define IDT_DELETE                      1304
#define IDD_MINIEDIT                    1400
#define IDS_LONGCLASSNAME               2000
#define IDS_UMARKGROESSE                2001
#define IDS_OMARKGROESSE                2002
#define IDS_MARKCOLOR                   2003
#define IDS_MARKCOLORBEGIN              2004
#define IDS_MARKCOLOREND                2005
#define IDS_MARKBOUNDTHICK              2006
#define IDS_SELFTOUCH                   2007
#define IDS_DESIGNMODE                  2008
#define IDS_GEOREIN                     2009
#define IDS_NOGEOREIN                   2010
#define IDS_NOOBJOPER                   2011
#define IDS_GEOFEHLERTEST               2012
#define IDS_EDITBASECAP                 2013
#define IDS_EDITCOORDCAP                2014
#define IDS_NEWPOINT                    2015
#define IDS_NEWLINE                     2016
#define IDS_NEWAREA                     2017
#define IDS_CAPTLINEELONG               2018
#define IDS_CAPTLINESELON               2019
#define IDS_CAPTISLANDADD               2020
#define IDS_MODVERTICES                 2021
#define IDS_ADDVERTEX                   2022
#define IDS_ADDVERTICES                 2023
#define IDS_DELOBJECTS                  2024
#define IDS_VERTICESMOD                 2025
#define IDS_VERTEXADD                   2026
#define IDS_VERTICESADD                 2027
#define IDS_VERTICESDEL                 2028
#define IDS_OBJECTSROT                  2029
#define IDS_LINEPART                    2030
#define IDS_LINESPART                   2031
#define IDS_LINEELONG                   2032
#define IDS_LINESELONG                  2033
#define IDS_RECHTWINKL                  2034
#define IDS_CLEARSELFTOUCH              2035
#define IDS_ISLANDSADD                  2036
#define IDS_ISLANDSDEL                  2037
#define IDS_OBJECTSDEL                  2038
#define IDS_UNDOVERTICESMOVE            2039
#define IDS_UNDOVERTICESDEL             2040
#define IDS_UNDOOBJECTSROT              2041
#define IDS_UNDORECTANGULAR             2042
#define IDS_UNDOOBJECTSDRAGDROP         2043
#define IDS_UNDOISLANDSADD              2044
#define IDS_UNDOISLANDSDEL              2045
#define IDS_UNDOOBJECTSCUT              2046
#define IDS_UNDOCOMMONBORDER            2047
#define IDS_DRAGVERTEX                  2048
#define IDS_STATKOORDMOD                2049
#define IDS_STATVERTDELETE              2050
#define IDS_STATVERTADD                 2051
#define IDS_STATLINIETEIL               2052
#define IDS_STATLINIEVERL               2053
#define IDS_STATOBJDREHEN               2054
#define IDS_STATOBJPART                 2055
#define IDS_STATOBJCUT                  2056
#define IDS_STATADDINSEL                2057
#define IDS_STATSUBINSEL                2058
#define IDS_STATRECHTWINKL              2059
#define IDS_MOVEDOBJECTS                2060
#define IDS_DESIGNCAP                   2061
#define IDS_SINGLEDESIGNCAP             2062
#define IDS_DOUBLEDESIGNCAP             2063
#define IDS_FIXPOINTSCAP                2064
#define IDS_BEARB_OBJEKT                2065
#define IDS_DELETE_STATUS               2066
#define IDS_STATOBJDELETE               2067
#define IDS_STATABBRUCH                 2068
#define IDS_CUREDIT                     2069
#define IDS_CURVERTEXMOVE               2070
#define IDS_CURVERTEXADD                2071
#define IDS_CURVERTEXDEL                2072
#define IDS_CUROBJECTMOVE               2073
#define IDS_SPEICHERN                   2074
#define IDS_CONTBUTTON                  2075
#define IDS_ISLBUTTON                   2076
#define IDS_INMARKER                    2077
#define IDS_AKTSTRECKE                  2078
#define IDS_GESAMTLAENGE                2079
#define IDS_URSPRLAENGE                 2080
#define IDS_AKTINSEL                    2081
#define IDS_GESAMTINHALT                2082
#define IDS_FLTEILEN                    2083
#define IDS_SPLITBUTTON                 2084
#define IDS_NOTEILUNG                   2085
#define IDS_PARTIALLINES                2086
#define IDS_PARTIALAREAS                2087
#define IDS_OBJOPERERR                  2088
#define IDS_GEOFEHLERMOD                2089
#define IDS_NOCOMBORDER1                2090
#define IDS_NOCOMBORDER2                2091
#define IDS_NEWOBJTYPE                  2092
#define IDS_DELISLAND                   2093
#define IDS_NOSTORAGE                   2094
#define IDS_LINEATVERTEX                2095
#define IDS_LENGTH                      2096
#define IDS_RADIUS                      2097
#define IDS_OUTSECTPOINT                2098
#define IDS_INOUTSECTPOINT              2099
#define IDS_NOSECTPOINT                 2100
#define IDS_LEFT                        2101
#define IDS_RIGHT                       2102
#define IDS_TOP                         2103
#define IDS_BOTTOM                      2104
#define IDS_LINETOAREA                  2105
#define IDS_STATLINETOAREA              2106
#define IDS_LINESTOAREA                 2107
#define IDS_AREATOLINE                  2108
#define IDS_STATAREATOLINE              2109
#define IDS_NOSELFCLEANINGPOSSIBLE      2110
#define IDS_GEOFEHLER                   2111
#define IDS_LINETOAREA_CAP              2112
#define IDS_LINETOAREA_WARNING          2113
#define IDS_NEWITEM                     2114
#define IDS_OBJECTNOTUNIQUE             2115
#define IDS_NOSOURCEOBJECT				2116
#define IDS_NOTSAMECONTOUR              2117
#define IDS_KEYBOARDINPUT				2118
#define IDS_WERKZEUGETOOLBAR            2200
#define IDS_DESIGNTOOLCAPTION           2201
#define ID_TOOL_PUNKTEDIT               2202
#define ID_TOOL_LINIENEDIT              2203
#define ID_TOOL_FLAECHENEDIT            2204
#define ID_TOOL_MODIFYOBJ               2205
#define ID_TOOL_MOVEOBJ                 2206
#define ID_TOOL_DESIGN                  2207
#define ID_TOOL_DESIGNSTOP              2208
#define IDS_ROMODE                      2209
#define IDS_NOTSUPPORTED                2300
#define IDS_NOGEOOBJECTS                2301
#define IDS_LINETOAREA_UNDO             2302
#define IDS_AREATOLINE_UNDO             2303
#define IDB_APPLY                       0x3021
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        245
#define _APS_NEXT_COMMAND_VALUE         40013
#define _APS_NEXT_CONTROL_VALUE         1032
#define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
