//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Statist.rc
//
#define IDR_UNITSOFMEASURE              102
#define IDD_POPUPTREECTRL               103
#define IDR_STATISTICOBJECTPROPERTY     106
#define IDD_MATHOP_CONFIG               107
#define IDR_SELECTSTATISTVALUE          109
#define IDB_OBJPROPTYPES                119
#define IDR_OBJEKTCONTAINER             120
#define IDB_ARROW                       125
#define IDR_UNITSOFMEASUREPP            133
#define IDB_CHECKMARKS                  134
#define IDR_STATISTVALUE                137
#define IDB_PROJECTVALUEPAGECTRL        139
#define IDR_PROJECTVALUEPAGECTRL        140
#define IDB_ORWNDVALUEPAGECTRL          140
#define IDD_PROJECTVALUEPAGECTRL        141
#define IDR_ENUMCOORDSYSTEMNAMES        144
#define IDR_SIMPLESTATISTICS            201
#define IDC_OBJECTPROPERTY              201
#define IDR_MESHGENERATION              202
#define IDC_EVALRELATION                203
#define IDD_POPUPTREEDLG                204
#define IDC_CONVEXHULL                  205
#define IDC_OBJPROPERTIES               206
#define IDC_VORONOI                     206
#define IDC_STATISTVALUES               207
#define IDC_DELAUNAY                    207
#define IDR_OBJPROPTREE                 207
#define IDC_LABEL                       207
#define IDC_OPERATION                   208
#define IDC_POPUPTREE                   208
#define IDC_UNIT_OF_LENGTH              209
#define IDB_STATFUNCS                   209
#define IDC_AUTO_SELECT                 210
#define IDC_SELECT_UNITS                211
#define IDC_UNIT_OF_AREA                212
#define IDB_CUSTOMIZEOBJPROP            212
#define IDC_STATIC_UNITS                215
#define IDC_STATIC_OPTIONS              216
#define IDR_STATFUNC                    216
#define IDC_STATIC_DESC                 217
#define IDC_APPENDUNITS                 219
#define IDB_STATVALUES                  219
#define IDC_STATIC_AREA                 220
#define IDR_HOURGLASS                   220
#define IDC_STATIC_LENGTH               221
#define IDC_CURSOR1                     221
#define IDC_PLUS                        222
#define IDC_MINUS                       223
#define IDC_MULTIPLY                    224
#define IDC_DIVIDE                      225
#define IDC_EDIT1                       226
#define IDI_HOURGLASS                   226
#define IDC_POINTS                      227
#define IDC_LINES                       228
#define IDC_AREAS                       229
#define IDC_TEXTS                       230
#define IDR_REGISTRY1                   230
#define IDC_OBJPROPERTY_FIRST           231
#define IDR_ORWNDVALUEPAGECTRL          231
#define IDC_SELECT_OBJPROP_FIRST        232
#define IDR_OBJECTCOUNTINORWND          232
#define IDC_DESC_OPERATION              233
#define IDR_OBJECTCOUNTINORWNDCLASS     233
#define IDC_OBJPROPTREE                 234
#define IDC_STATISTPROPTREE             235
#define IDC_OBJPROP2                    235
#define IDC_STATIC_DELIMITER            236
#define IDC_OBJPROP1                    237
#define IDC_INVERTVALUE                 238
#define IDC_CUSTOMIZE                   240
#define IDC_NOMODULES                   244
#define IDC_VALUESFRAME                 245
#define IDC_VALUES                      246
#define ID_CUSTOMIZE                    1000
#define IDC_OBJPROPERTY                 1005
#define IDC_STATISTVALUE                1006
#define IDC_OBJPROPERTY_SECOND          1006
#define IDC_SELECT_OBJPROP              1009
#define IDC_SELECT_STATISTVALUE         1010
#define IDC_SELECT_OBJPROP_SECOND       1010
#define IDC_STATIC_CATEGORIES           22075
#define IDC_CATEGORIES                  22077
#define IDD_PROJECTVALUES               22203
#define ID_STANDARD_OVERVIEW            22215
#define IDI_STATISTICS                  22233
#define IDB_DELAUNAY                    24643
#define IDS_PROJNAME                    24700
#define IDB_ARROW_DOWN                  24700
#define IDS_LONGCLASSNAME               24701
#define IDB_ARROW_DOWN_DISABLED         24701
#define IDS_COUNTLINEPOINTS_NAME        24702
#define IDB_ARROW_DOWN_FOCUS            24702
#define IDS_COUNTLINEPOINTS_HELP        24703
#define IDB_ARROW_DOWN_SEL              24703
#define IDS_COORDX_NAME                 24704
#define IDS_COORDY_NAME                 24705
#define IDS_POINTCOORDX_HELP            24706
#define IDS_POINTCOORDY_HELP            24707
#define IDS_OBJPROP_GROUPNAME           24708
#define IDS_OP_NAME_STATISTICOBJECTPROPERTY 24709
#define IDS_OP_DESCRIPTION_STATISTICOBJECTPROPERTY 24710
#define IDS_DESCRIPTION_SELECTSTATISTVALUE 24711
#define IDS_COORDCENTREX_NAME           24712
#define IDS_COORDCENTREY_NAME           24713
#define IDS_CENTRECOORDX_HELP           24714
#define IDS_CENTRECOORDY_HELP           24715
#define IDS_OP_NAME_LENGTHOFLINE        24716
#define IDS_OP_DESCRIPTION_LENGTHOFLINE 24717
#define IDS_OP_NAME_COUNTAREAISLAND     24718
#define IDS_OP_DESCRIPTION_COUNTAREAISLAND 24719
#define IDS_OP_NAME_SIMPLEAREAFRAME     24720
#define IDS_OP_DESCRIPTION_SIMPLEAREAFRAME 24721
#define IDS_OP_NAME_FULLAREAFRAME       24722
#define IDS_OP_DESCRIPTION_FULLAREAFRAME 24723
#define IDS_OP_NAME_SUPERFICIALCONTENTS 24724
#define IDS_OP_DESCRIPTION_SUPERFICIALCONTENTS 24725
#define IDS_OP_NAME_OBJEKTCONTAINER     24726
#define IDS_CONTAINERMINX_NAME          24726
#define IDS_OP_DESCRIPTION_OBJEKTCONTAINER 24727
#define IDS_CONTAINERMINX_HELP          24727
#define IDS_CONTAINERMAXX_NAME          24728
#define IDS_CONTAINERMAXX_HELP          24729
#define IDS_CONTAINERMINY_NAME          24730
#define IDS_CONTAINERMINY_HELP          24731
#define IDS_CONTAINERMAXY_NAME          24732
#define IDS_CONTAINERMAXY_HELP          24733
#define IDS_OP_NAME_SIMPLEAREARADIUS    24734
#define IDS_OP_DESCRIPTION_SIMPLEAREARADIUS 24735
#define IDS_DESCRIPTION_MESHGENERATION  24736
#define IDS_UNIQUEIDENT_CONVEXHULL      24737
#define IDS_UNITOFLENGTH                24738
#define IDS_UNITOFAREA                  24739
#define IDD_MESHGENERATION_OPTIONS      24740
#define IDS_APPENDUNITS                 24740
#define IDD_SELECTSTATISTVALUE_OPTIONS  24741
#define IDS_OP_NAME_MATHOPERATIONPROPERTY 24741
#define IDI_STATIST                     24742
#define IDS_OP_DESCRIPTION_MATHOPERATIONPROPERTY 24742
#define IDD_UNITSOFMEASURE              24743
#define IDS_MATHOPADD                   24743
#define IDB_CONEXHULL                   24744
#define IDS_MATHOPSUBTRACT              24744
#define IDB_VORONOI                     24745
#define IDS_MATHOPMULTIPLY              24745
#define IDS_MATHOPDIVIDE                24746
#define IDB_STATVALUES_MASK             24746
#define IDS_CONFIG_OBJPROP              24747
#define IDS_UNIT_OF_LENGTH              24748
#define IDS_UNIT_OF_AREA                24749
#define IDS_DESC_CONVEXHULL             24750
#define IDS_DESC_VORONOI                24751
#define IDS_DESC_DELAUNAY               24752
#define IDS_STATISTCOUNT_NAME           24753
#define IDS_STATISTCOUNT_DESC           24754
#define IDS_STATISTCOUNTNOTNULL_NAME    24755
#define IDS_STATISTCOUNTNOTNULL_DESC    24756
#define IDS_STATISTSUM_NAME             24757
#define IDS_STATISTSUM_DESC             24758
#define IDS_STATISTARITHAVERAGE_NAME    24759
#define IDS_STATISTARITHAVERAGE_DESC    24760
#define IDS_STATISTGEOMAVERAGE_NAME     24761
#define IDS_STATISTGEOMAVERAGE_DESC     24762
#define IDS_STATISTMEDIAN_NAME          24763
#define IDS_STATISTMEDIAN_DESC          24764
#define IDS_STATISTMINVALUE_NAME        24765
#define IDS_STATISTMINVALUE_DESC        24766
#define IDS_STATISTMAXVALUE_NAME        24767
#define IDS_STATISTMAXVALUE_DESC        24768
#define IDS_STATISTRANGE_NAME           24769
#define IDS_STATISTRANGE_DESC           24770
#define IDS_STATISTDEVIATION_NAME       24771
#define IDS_STATISTDEVIATION_DESC       24772
#define IDS_STATISTVARIANCE_NAME        24773
#define IDS_STATISTVARIANCE_DESC        24774
#define IDS_CATIDDESC                   24775
#define IDS_CATIDDESC_STATVALUE         24775
#define IDS_SELECT_OBJPROP              24776
#define IDS_SELECT_STATFUNC             24777
#define IDS_OBJPROP1                    24778
#define IDS_OBJPROP2                    24779
#define IDS_PROJECTVALUES               24780
#define IDS_STATISTVALUEHDRNAME         24781
#define IDS_STATISTVALUEHDRVALUE        24782
#define IDS_CATIDDESC_STATVALUESCONTAINER 24783
#define IDS_WERKZEUGETOOLBAR            24784
#define IDS_STATISTICS_ON               24785
#define IDS_LOADING                     24786
#define IDS_CUMULATION                  24787
#define IDS_WORKSPACEROOT_INIT          24788
#define IDS_WORKSPACEROOT               24789
#define IDS_OBJECTCOUNTINCLASS          24790
#define IDS_OBJECTCOUNTINCLASS_DESC     24791
#define IDR_OBJECTCOUNTINCLASS          24792
#define IDS_POINTCOUNT                  24792
#define IDR_OBJECTCOUNTINDATASOURCE     24793
#define IDS_LINECOUNT                   24793
#define IDS_AREACOUNT                   24794
#define IDS_TEXTCOUNT                   24795
#define IDS_WORKSPACEROOT_ONE           24796
#define ID_TOOL_STATISTICS              32768
#define ID_BUTTON32770                  32770
#define ID_BUTTON32771                  32771
#define ID_BUTTON32772                  32772

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        234
#define _APS_NEXT_COMMAND_VALUE         24794
#define _APS_NEXT_CONTROL_VALUE         248
#define _APS_NEXT_SYMED_VALUE           145
#endif
#endif
