///////////////////////////////////////////////////////////////////////////
// @doc 
// @module COMTreeItem.h | Schnittstelle für die Klasse CCOMTreeItem.
// @end

#if !defined(_COMTREEITEM_H__3460D3E7_62C9_11D2_9EDE_006008447800__INCLUDED_)
#define _COMTREEITEM_H__3460D3E7_62C9_11D2_9EDE_006008447800__INCLUDED_

#if _MSC_VER >= 1000
#pragma once
#endif // _MSC_VER >= 1000

/*
  *****************************************************
  * Copyright:
  *   Datenmanagement- & Präsentationssysteme
  *   Weimarer Str. 1B
  *   D-98693 Ilmenau
  *   GERMANY
  *****************************************************
  * Module: Header, Klasse COMTreeItem: 
  *		Container für Informationen zu einem COM-Objekt
  *
  * Function: Klasse, welche alle Informationen zu 
  *		einem COM-Objekt aufnimmt, das in das 
  *		TreeControl des Dialogs CStdCtrlDlg eingefügt 
  *		wird
  *****************************************************
  * Created:        28.07.98  TWI
  * Last modified:  24.08.98  TWI   
  *****************************************************
  * Automated generated by D&P Documenter
  * DV: 1.0 *** FV: 1.0 *** Last documented: 25.08.98
  *****************************************************
*/

//////////////////////////////////////////////////////////////////////

#define MAXOBJNAMELENGTH	_MAX_PATH

union HBITMAPICON {
	HBITMAP hBmp;
	HICON hIcon;
};

class CCOMTreeItem : public CObject  
{

public:
	// public-Attribute
	unsigned long	m_id;			// Objekt-ID (für Identifizierung in einer Liste)
	WUnknown		m_Unk;			// Ptr auf IUnknown des COM-Objektes
	CString			m_name;			// Bezeichner des COM-Objektes im Baum
	unsigned long	m_parentId;		// ID des Parent des COM-Objektes im Baum
	WUnknown		m_ParentUnk;	// Ptr auf IUnknown des Parent des COM-Objektes im Baum
	
	bool			m_fIsIcon;
	HBITMAPICON		m_hBmpColl;		// Bitmap/Icon Handle collapsed
	HBITMAPICON		m_hBmpExp;		// Bitmap/Icon Handle expanded

	int				m_imageIndex;
	int				m_imageIndexExp;

	HTREEITEM		m_hItem;		// Handle auf das Item des COM-Objektes
	BOOL			m_selected;		// Ist das Item selektiert?
	BOOL			m_expanded;		// Ist das Item aufgeklappt?
	BOOL			m_HasChildren;	// Hat dieses Objekt Children im Baum?

// Copy-Konstruktor
    CCOMTreeItem(const CCOMTreeItem &cti);

// Zuweisungsoperator
	CCOMTreeItem &operator=(const CCOMTreeItem &cti);

	HRESULT Save(LPSTREAM pStm);
	HRESULT Load(LPSTREAM pStm);

	// Standard-Konstruktor
	CCOMTreeItem();
	// Destruktor
	virtual ~CCOMTreeItem();
};

#endif // !defined(_COMTREEITEM_H__3460D3E7_62C9_11D2_9EDE_006008447800__INCLUDED_)
