# Generated automatically from Makefile.in by configure.
# Makefile.in generated automatically by automake 1.4 from Makefile.am

# Copyright (C) 1994, 1995-8, 1999 Free Software Foundation, Inc.
# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.


SHELL = /bin/sh

srcdir = .
top_srcdir = ..
prefix = /usr/local
exec_prefix = ${prefix}

bindir = ${exec_prefix}/bin
sbindir = ${exec_prefix}/sbin
libexecdir = ${exec_prefix}/libexec
datadir = ${prefix}/share
sysconfdir = ${prefix}/etc
sharedstatedir = ${prefix}/com
localstatedir = ${prefix}/var
libdir = ${exec_prefix}/lib
infodir = ${prefix}/info
mandir = ${prefix}/man
includedir = ${prefix}/include
oldincludedir = /usr/include

DESTDIR =

pkgdatadir = $(datadir)/goose
pkglibdir = $(libdir)/goose
pkgincludedir = $(includedir)/goose

top_builddir = ..

ACLOCAL = //d/triasdev.mvc/statist/goose/missing aclocal
AUTOCONF = //d/triasdev.mvc/statist/goose/missing autoconf
AUTOMAKE = //d/triasdev.mvc/statist/goose/missing automake
AUTOHEADER = //d/triasdev.mvc/statist/goose/missing autoheader

INSTALL = //d/cygnus/CYGWIN~1/H-I586~1/bin/install -c
INSTALL_PROGRAM = ${INSTALL} $(AM_INSTALL_PROGRAM_FLAGS)
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_SCRIPT = ${INSTALL_PROGRAM}
transform = s,x,x,

NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
build_alias = i686-pc-cygwin32
build_triplet = i686-pc-cygwin32
host_alias = i686-pc-cygwin32
host_triplet = i686-pc-cygwin32
target_alias = i686-pc-cygwin32
target_triplet = i686-pc-cygwin32
AS = as
BUILD_GUILE = no
CC = gcc
CPP = gcc -E
CURSES_LIB = 
CXX = c++
CXXCPP = c++ -E
DLLTOOL = dlltool
GLIB_CFLAGS = 
GLIB_CONFIG = no
GLIB_LIBS = 
GOOSE_AGE = 0
GOOSE_CURRENT = 10
GOOSE_MAJOR_VERSION = 0
GOOSE_MICRO_VERSION = 10
GOOSE_MINOR_VERSION = 0
GOOSE_REVISION = 0
GOOSE_VERSION = 0.0.10
GUILEGOOSE_AGE = 0
GUILEGOOSE_CURRENT = 0
GUILEGOOSE_REVISION = 0
GUILE_INCS = 
GUILE_LIBS = 
LD = //d/cygnus/CYGWIN~1/H-I586~1/i586-cygwin32/bin/ld.exe
LIBTOOL = $(SHELL) $(top_builddir)/libtool
LN_S = ln -s
MAINT = #
MAKEINFO = makeinfo
NM = //d/cygnus/CYGWIN~1/H-I586~1/bin/nm -B
PACKAGE = goose
QTTHREADS_LIB = 
RANLIB = ranlib
READLINE_LIB = -lreadline
TERMCAP_LIB = -ltermcap
VERSION = 0.0.10

INCLUDES =  	$(GLIB_CFLAGS) 	-I$(top_srcdir)/src/specfns 	-I$(top_srcdir)/src/util 	-I$(top_srcdir)/src/linear 	-I$(top_srcdir)/src/containers 	-I$(top_srcdir)/src/stats 	-I$(includedir)	


LDADD =  	$(GLIB_LIBS) 	$(top_builddir)/src/specfns/libgoose-specfns.la 	$(top_builddir)/src/util/libgoose-util.la 	$(top_builddir)/src/linear/libgoose-linear.la 	$(top_builddir)/src/containers/libgoose-containers.la 	$(top_builddir)/src/stats/libgoose-stats.la


EXTRA_DIST = runtests.pl README

noinst_PROGRAMS =  	test_A001 	test_A002 	test_B001 	test_B002 	test_B003 	test_B004 	test_B005 	test_B006 	test_E001 	test_E002 	test_E003 	test_E004 	test_G001 	test_H001


test_A001_SOURCES = test_A001.cpp
test_A002_SOURCES = test_A002.cpp
test_B001_SOURCES = test_B001.cpp
test_B002_SOURCES = test_B002.cpp
test_B003_SOURCES = test_B003.cpp
test_B004_SOURCES = test_B004.cpp
test_B005_SOURCES = test_B005.cpp
test_B006_SOURCES = test_B006.cpp
test_E001_SOURCES = test_E001.cpp
test_E002_SOURCES = test_E002.cpp
test_E003_SOURCES = test_E003.cpp
test_E004_SOURCES = test_E004.cpp
test_G001_SOURCES = test_G001.cpp
test_H001_SOURCES = test_H001.cpp
mkinstalldirs = $(SHELL) $(top_srcdir)/mkinstalldirs
CONFIG_HEADER = ../config.h
CONFIG_CLEAN_FILES = 
PROGRAMS =  $(noinst_PROGRAMS)


DEFS = -DHAVE_CONFIG_H -I. -I$(srcdir) -I..
CPPFLAGS = 
LDFLAGS = 
LIBS = -lm 
test_A001_OBJECTS =  test_A001.o
test_A001_LDADD = $(LDADD)
test_A001_DEPENDENCIES =  \
$(top_builddir)/src/specfns/libgoose-specfns.la \
$(top_builddir)/src/util/libgoose-util.la \
$(top_builddir)/src/linear/libgoose-linear.la \
$(top_builddir)/src/containers/libgoose-containers.la \
$(top_builddir)/src/stats/libgoose-stats.la
test_A001_LDFLAGS = 
test_A002_OBJECTS =  test_A002.o
test_A002_LDADD = $(LDADD)
test_A002_DEPENDENCIES =  \
$(top_builddir)/src/specfns/libgoose-specfns.la \
$(top_builddir)/src/util/libgoose-util.la \
$(top_builddir)/src/linear/libgoose-linear.la \
$(top_builddir)/src/containers/libgoose-containers.la \
$(top_builddir)/src/stats/libgoose-stats.la
test_A002_LDFLAGS = 
test_B001_OBJECTS =  test_B001.o
test_B001_LDADD = $(LDADD)
test_B001_DEPENDENCIES =  \
$(top_builddir)/src/specfns/libgoose-specfns.la \
$(top_builddir)/src/util/libgoose-util.la \
$(top_builddir)/src/linear/libgoose-linear.la \
$(top_builddir)/src/containers/libgoose-containers.la \
$(top_builddir)/src/stats/libgoose-stats.la
test_B001_LDFLAGS = 
test_B002_OBJECTS =  test_B002.o
test_B002_LDADD = $(LDADD)
test_B002_DEPENDENCIES =  \
$(top_builddir)/src/specfns/libgoose-specfns.la \
$(top_builddir)/src/util/libgoose-util.la \
$(top_builddir)/src/linear/libgoose-linear.la \
$(top_builddir)/src/containers/libgoose-containers.la \
$(top_builddir)/src/stats/libgoose-stats.la
test_B002_LDFLAGS = 
test_B003_OBJECTS =  test_B003.o
test_B003_LDADD = $(LDADD)
test_B003_DEPENDENCIES =  \
$(top_builddir)/src/specfns/libgoose-specfns.la \
$(top_builddir)/src/util/libgoose-util.la \
$(top_builddir)/src/linear/libgoose-linear.la \
$(top_builddir)/src/containers/libgoose-containers.la \
$(top_builddir)/src/stats/libgoose-stats.la
test_B003_LDFLAGS = 
test_B004_OBJECTS =  test_B004.o
test_B004_LDADD = $(LDADD)
test_B004_DEPENDENCIES =  \
$(top_builddir)/src/specfns/libgoose-specfns.la \
$(top_builddir)/src/util/libgoose-util.la \
$(top_builddir)/src/linear/libgoose-linear.la \
$(top_builddir)/src/containers/libgoose-containers.la \
$(top_builddir)/src/stats/libgoose-stats.la
test_B004_LDFLAGS = 
test_B005_OBJECTS =  test_B005.o
test_B005_LDADD = $(LDADD)
test_B005_DEPENDENCIES =  \
$(top_builddir)/src/specfns/libgoose-specfns.la \
$(top_builddir)/src/util/libgoose-util.la \
$(top_builddir)/src/linear/libgoose-linear.la \
$(top_builddir)/src/containers/libgoose-containers.la \
$(top_builddir)/src/stats/libgoose-stats.la
test_B005_LDFLAGS = 
test_B006_OBJECTS =  test_B006.o
test_B006_LDADD = $(LDADD)
test_B006_DEPENDENCIES =  \
$(top_builddir)/src/specfns/libgoose-specfns.la \
$(top_builddir)/src/util/libgoose-util.la \
$(top_builddir)/src/linear/libgoose-linear.la \
$(top_builddir)/src/containers/libgoose-containers.la \
$(top_builddir)/src/stats/libgoose-stats.la
test_B006_LDFLAGS = 
test_E001_OBJECTS =  test_E001.o
test_E001_LDADD = $(LDADD)
test_E001_DEPENDENCIES =  \
$(top_builddir)/src/specfns/libgoose-specfns.la \
$(top_builddir)/src/util/libgoose-util.la \
$(top_builddir)/src/linear/libgoose-linear.la \
$(top_builddir)/src/containers/libgoose-containers.la \
$(top_builddir)/src/stats/libgoose-stats.la
test_E001_LDFLAGS = 
test_E002_OBJECTS =  test_E002.o
test_E002_LDADD = $(LDADD)
test_E002_DEPENDENCIES =  \
$(top_builddir)/src/specfns/libgoose-specfns.la \
$(top_builddir)/src/util/libgoose-util.la \
$(top_builddir)/src/linear/libgoose-linear.la \
$(top_builddir)/src/containers/libgoose-containers.la \
$(top_builddir)/src/stats/libgoose-stats.la
test_E002_LDFLAGS = 
test_E003_OBJECTS =  test_E003.o
test_E003_LDADD = $(LDADD)
test_E003_DEPENDENCIES =  \
$(top_builddir)/src/specfns/libgoose-specfns.la \
$(top_builddir)/src/util/libgoose-util.la \
$(top_builddir)/src/linear/libgoose-linear.la \
$(top_builddir)/src/containers/libgoose-containers.la \
$(top_builddir)/src/stats/libgoose-stats.la
test_E003_LDFLAGS = 
test_E004_OBJECTS =  test_E004.o
test_E004_LDADD = $(LDADD)
test_E004_DEPENDENCIES =  \
$(top_builddir)/src/specfns/libgoose-specfns.la \
$(top_builddir)/src/util/libgoose-util.la \
$(top_builddir)/src/linear/libgoose-linear.la \
$(top_builddir)/src/containers/libgoose-containers.la \
$(top_builddir)/src/stats/libgoose-stats.la
test_E004_LDFLAGS = 
test_G001_OBJECTS =  test_G001.o
test_G001_LDADD = $(LDADD)
test_G001_DEPENDENCIES =  \
$(top_builddir)/src/specfns/libgoose-specfns.la \
$(top_builddir)/src/util/libgoose-util.la \
$(top_builddir)/src/linear/libgoose-linear.la \
$(top_builddir)/src/containers/libgoose-containers.la \
$(top_builddir)/src/stats/libgoose-stats.la
test_G001_LDFLAGS = 
test_H001_OBJECTS =  test_H001.o
test_H001_LDADD = $(LDADD)
test_H001_DEPENDENCIES =  \
$(top_builddir)/src/specfns/libgoose-specfns.la \
$(top_builddir)/src/util/libgoose-util.la \
$(top_builddir)/src/linear/libgoose-linear.la \
$(top_builddir)/src/containers/libgoose-containers.la \
$(top_builddir)/src/stats/libgoose-stats.la
test_H001_LDFLAGS = 
CXXFLAGS = -g -O2 -D_INCLUDE_POSIX_SOURCE -ansi -pedantic -Wall
CXXCOMPILE = $(CXX) $(DEFS) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS)
LTCXXCOMPILE = $(LIBTOOL) --mode=compile $(CXX) $(DEFS) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS)
CXXLD = $(CXX)
CXXLINK = $(LIBTOOL) --mode=link $(CXXLD) $(AM_CXXFLAGS) $(CXXFLAGS) $(LDFLAGS) -o $@
DIST_COMMON =  README Makefile.am Makefile.in


DISTFILES = $(DIST_COMMON) $(SOURCES) $(HEADERS) $(TEXINFOS) $(EXTRA_DIST)

TAR = tar
GZIP_ENV = --best
SOURCES = $(test_A001_SOURCES) $(test_A002_SOURCES) $(test_B001_SOURCES) $(test_B002_SOURCES) $(test_B003_SOURCES) $(test_B004_SOURCES) $(test_B005_SOURCES) $(test_B006_SOURCES) $(test_E001_SOURCES) $(test_E002_SOURCES) $(test_E003_SOURCES) $(test_E004_SOURCES) $(test_G001_SOURCES) $(test_H001_SOURCES)
OBJECTS = $(test_A001_OBJECTS) $(test_A002_OBJECTS) $(test_B001_OBJECTS) $(test_B002_OBJECTS) $(test_B003_OBJECTS) $(test_B004_OBJECTS) $(test_B005_OBJECTS) $(test_B006_OBJECTS) $(test_E001_OBJECTS) $(test_E002_OBJECTS) $(test_E003_OBJECTS) $(test_E004_OBJECTS) $(test_G001_OBJECTS) $(test_H001_OBJECTS)

all: all-redirect
.SUFFIXES:
.SUFFIXES: .S .c .cpp .lo .o .s
$(srcdir)/Makefile.in: # Makefile.am $(top_srcdir)/configure.in $(ACLOCAL_M4) 
	cd $(top_srcdir) && $(AUTOMAKE) --gnu --include-deps test/Makefile

Makefile: $(srcdir)/Makefile.in  $(top_builddir)/config.status
	cd $(top_builddir) \
	  && CONFIG_FILES=$(subdir)/$@ CONFIG_HEADERS= $(SHELL) ./config.status


mostlyclean-noinstPROGRAMS:

clean-noinstPROGRAMS:
	-test -z "$(noinst_PROGRAMS)" || rm -f $(noinst_PROGRAMS)

distclean-noinstPROGRAMS:

maintainer-clean-noinstPROGRAMS:

.c.o:
	$(COMPILE) -c $<

.s.o:
	$(COMPILE) -c $<

.S.o:
	$(COMPILE) -c $<

mostlyclean-compile:
	-rm -f *.o core *.core

clean-compile:

distclean-compile:
	-rm -f *.tab.c

maintainer-clean-compile:

.c.lo:
	$(LIBTOOL) --mode=compile $(COMPILE) -c $<

.s.lo:
	$(LIBTOOL) --mode=compile $(COMPILE) -c $<

.S.lo:
	$(LIBTOOL) --mode=compile $(COMPILE) -c $<

mostlyclean-libtool:
	-rm -f *.lo

clean-libtool:
	-rm -rf .libs _libs

distclean-libtool:

maintainer-clean-libtool:

test_A001: $(test_A001_OBJECTS) $(test_A001_DEPENDENCIES)
	@rm -f test_A001
	$(CXXLINK) $(test_A001_LDFLAGS) $(test_A001_OBJECTS) $(test_A001_LDADD) $(LIBS)

test_A002: $(test_A002_OBJECTS) $(test_A002_DEPENDENCIES)
	@rm -f test_A002
	$(CXXLINK) $(test_A002_LDFLAGS) $(test_A002_OBJECTS) $(test_A002_LDADD) $(LIBS)

test_B001: $(test_B001_OBJECTS) $(test_B001_DEPENDENCIES)
	@rm -f test_B001
	$(CXXLINK) $(test_B001_LDFLAGS) $(test_B001_OBJECTS) $(test_B001_LDADD) $(LIBS)

test_B002: $(test_B002_OBJECTS) $(test_B002_DEPENDENCIES)
	@rm -f test_B002
	$(CXXLINK) $(test_B002_LDFLAGS) $(test_B002_OBJECTS) $(test_B002_LDADD) $(LIBS)

test_B003: $(test_B003_OBJECTS) $(test_B003_DEPENDENCIES)
	@rm -f test_B003
	$(CXXLINK) $(test_B003_LDFLAGS) $(test_B003_OBJECTS) $(test_B003_LDADD) $(LIBS)

test_B004: $(test_B004_OBJECTS) $(test_B004_DEPENDENCIES)
	@rm -f test_B004
	$(CXXLINK) $(test_B004_LDFLAGS) $(test_B004_OBJECTS) $(test_B004_LDADD) $(LIBS)

test_B005: $(test_B005_OBJECTS) $(test_B005_DEPENDENCIES)
	@rm -f test_B005
	$(CXXLINK) $(test_B005_LDFLAGS) $(test_B005_OBJECTS) $(test_B005_LDADD) $(LIBS)

test_B006: $(test_B006_OBJECTS) $(test_B006_DEPENDENCIES)
	@rm -f test_B006
	$(CXXLINK) $(test_B006_LDFLAGS) $(test_B006_OBJECTS) $(test_B006_LDADD) $(LIBS)

test_E001: $(test_E001_OBJECTS) $(test_E001_DEPENDENCIES)
	@rm -f test_E001
	$(CXXLINK) $(test_E001_LDFLAGS) $(test_E001_OBJECTS) $(test_E001_LDADD) $(LIBS)

test_E002: $(test_E002_OBJECTS) $(test_E002_DEPENDENCIES)
	@rm -f test_E002
	$(CXXLINK) $(test_E002_LDFLAGS) $(test_E002_OBJECTS) $(test_E002_LDADD) $(LIBS)

test_E003: $(test_E003_OBJECTS) $(test_E003_DEPENDENCIES)
	@rm -f test_E003
	$(CXXLINK) $(test_E003_LDFLAGS) $(test_E003_OBJECTS) $(test_E003_LDADD) $(LIBS)

test_E004: $(test_E004_OBJECTS) $(test_E004_DEPENDENCIES)
	@rm -f test_E004
	$(CXXLINK) $(test_E004_LDFLAGS) $(test_E004_OBJECTS) $(test_E004_LDADD) $(LIBS)

test_G001: $(test_G001_OBJECTS) $(test_G001_DEPENDENCIES)
	@rm -f test_G001
	$(CXXLINK) $(test_G001_LDFLAGS) $(test_G001_OBJECTS) $(test_G001_LDADD) $(LIBS)

test_H001: $(test_H001_OBJECTS) $(test_H001_DEPENDENCIES)
	@rm -f test_H001
	$(CXXLINK) $(test_H001_LDFLAGS) $(test_H001_OBJECTS) $(test_H001_LDADD) $(LIBS)
.cpp.o:
	$(CXXCOMPILE) -c $<
.cpp.lo:
	$(LTCXXCOMPILE) -c $<

tags: TAGS

ID: $(HEADERS) $(SOURCES) $(LISP)
	list='$(SOURCES) $(HEADERS)'; \
	unique=`for i in $$list; do echo $$i; done | \
	  awk '    { files[$$0] = 1; } \
	       END { for (i in files) print i; }'`; \
	here=`pwd` && cd $(srcdir) \
	  && mkid -f$$here/ID $$unique $(LISP)

TAGS:  $(HEADERS) $(SOURCES)  $(TAGS_DEPENDENCIES) $(LISP)
	tags=; \
	here=`pwd`; \
	list='$(SOURCES) $(HEADERS)'; \
	unique=`for i in $$list; do echo $$i; done | \
	  awk '    { files[$$0] = 1; } \
	       END { for (i in files) print i; }'`; \
	test -z "$(ETAGS_ARGS)$$unique$(LISP)$$tags" \
	  || (cd $(srcdir) && etags $(ETAGS_ARGS) $$tags  $$unique $(LISP) -o $$here/TAGS)

mostlyclean-tags:

clean-tags:

distclean-tags:
	-rm -f TAGS ID

maintainer-clean-tags:

distdir = $(top_builddir)/$(PACKAGE)-$(VERSION)/$(subdir)

subdir = test

distdir: $(DISTFILES)
	@for file in $(DISTFILES); do \
	  d=$(srcdir); \
	  if test -d $$d/$$file; then \
	    cp -pr $$/$$file $(distdir)/$$file; \
	  else \
	    test -f $(distdir)/$$file \
	    || ln $$d/$$file $(distdir)/$$file 2> /dev/null \
	    || cp -p $$d/$$file $(distdir)/$$file || :; \
	  fi; \
	done
test_A001.o: test_A001.cpp ../config.h ../src/linear/gala.h \
	../src/util/RCMatrix.h ../src/util/RCArray.h
test_A002.o: test_A002.cpp ../config.h ../src/util/zdouble.h
test_B001.o: test_B001.cpp ../src/specfns/specfns.h \
	../src/specfns/specfns_protos.h
test_B002.o: test_B002.cpp ../src/specfns/specfns.h \
	../src/specfns/specfns_protos.h
test_B003.o: test_B003.cpp ../src/specfns/specfns.h \
	../src/specfns/specfns_protos.h
test_B004.o: test_B004.cpp ../src/specfns/specfns.h \
	../src/specfns/specfns_protos.h
test_B005.o: test_B005.cpp ../src/specfns/specfns.h \
	../src/specfns/specfns_protos.h
test_B006.o: test_B006.cpp ../src/specfns/specfns.h \
	../src/specfns/specfns_protos.h
test_E001.o: test_E001.cpp ../config.h ../src/stats/descriptive.h \
	../src/containers/RealSet.h ../src/util/stringtools.h \
	../src/util/RCArray.h ../src/util/Permutation.h \
	../src/util/Random.h ../src/util/Exception.h \
	../src/containers/DataSet.h ../src/util/DataConverter.h
test_E002.o: test_E002.cpp ../config.h ../src/containers/HoleSet.h \
	../src/util/DataConverter.h ../src/containers/DataSet.h \
	../src/util/Random.h ../src/containers/RealSet.h \
	../src/util/stringtools.h ../src/util/RCArray.h \
	../src/util/Permutation.h ../src/util/Exception.h
test_E003.o: test_E003.cpp ../src/containers/DateSet.h \
	../src/util/RCArray.h ../src/util/Permutation.h \
	../src/util/Random.h ../src/util/Exception.h \
	../src/containers/DataSet.h ../src/util/DataConverter.h
test_E004.o: test_E004.cpp ../src/containers/AsciiImport.h \
	../src/containers/DataSet.h ../src/util/Random.h \
	../src/util/DataConverter.h ../src/util/stringtools.h \
	../src/containers/ColumnDivider.h \
	../src/containers/AsciiReader.h ../src/util/WarningController.h \
	../src/util/Exception.h ../src/util/Progress.h \
	../src/containers/RealSet.h ../src/util/RCArray.h \
	../src/util/Permutation.h
test_G001.o: test_G001.cpp ../src/util/Random.h \
	../src/containers/RealSet.h ../src/util/stringtools.h \
	../src/util/RCArray.h ../src/util/Permutation.h \
	../src/util/Exception.h ../src/containers/DataSet.h \
	../src/util/DataConverter.h ../src/stats/LinearRegression.h \
	../src/util/ConfInt.h
test_H001.o: test_H001.cpp ../src/util/Random.h \
	../src/containers/RealSet.h ../src/util/stringtools.h \
	../src/util/RCArray.h ../src/util/Permutation.h \
	../src/util/Exception.h ../src/containers/DataSet.h \
	../src/util/DataConverter.h ../src/stats/bootstrap.h

info-am:
info: info-am
dvi-am:
dvi: dvi-am
check-am: all-am
check: check-am
installcheck-am:
installcheck: installcheck-am
install-exec-am:
install-exec: install-exec-am

install-data-am:
install-data: install-data-am

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am
install: install-am
uninstall-am:
uninstall: uninstall-am
all-am: Makefile $(PROGRAMS)
all-redirect: all-am
install-strip:
	$(MAKE) $(AM_MAKEFLAGS) AM_INSTALL_PROGRAM_FLAGS=-s install
installdirs:


mostlyclean-generic:

clean-generic:

distclean-generic:
	-rm -f Makefile $(CONFIG_CLEAN_FILES)
	-rm -f config.cache config.log stamp-h stamp-h[0-9]*

maintainer-clean-generic:
mostlyclean-am:  mostlyclean-noinstPROGRAMS mostlyclean-compile \
		mostlyclean-libtool mostlyclean-tags \
		mostlyclean-generic

mostlyclean: mostlyclean-am

clean-am:  clean-noinstPROGRAMS clean-compile clean-libtool clean-tags \
		clean-generic mostlyclean-am

clean: clean-am

distclean-am:  distclean-noinstPROGRAMS distclean-compile \
		distclean-libtool distclean-tags distclean-generic \
		clean-am
	-rm -f libtool

distclean: distclean-am

maintainer-clean-am:  maintainer-clean-noinstPROGRAMS \
		maintainer-clean-compile maintainer-clean-libtool \
		maintainer-clean-tags maintainer-clean-generic \
		distclean-am
	@echo "This command is intended for maintainers to use;"
	@echo "it deletes files that may require special tools to rebuild."

maintainer-clean: maintainer-clean-am

.PHONY: mostlyclean-noinstPROGRAMS distclean-noinstPROGRAMS \
clean-noinstPROGRAMS maintainer-clean-noinstPROGRAMS \
mostlyclean-compile distclean-compile clean-compile \
maintainer-clean-compile mostlyclean-libtool distclean-libtool \
clean-libtool maintainer-clean-libtool tags mostlyclean-tags \
distclean-tags clean-tags maintainer-clean-tags distdir info-am info \
dvi-am dvi check check-am installcheck-am installcheck install-exec-am \
install-exec install-data-am install-data install-am install \
uninstall-am uninstall all-redirect all-am all installdirs \
mostlyclean-generic distclean-generic clean-generic \
maintainer-clean-generic clean mostlyclean distclean maintainer-clean


# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
