//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by KOMPLEXR.RC
//
#define IDM_EXTABOUT                    1
#define IDM_START                       2
#define IDM_PARAM                       3
#define IDM_EDIT                        4
#define IDM_STAND                       5
#define EXTENSIONMENU                   100
#define DEFIDABOUT                      102
#define DEFIDICON                       103
#define ABOUTICON                       104
#define IDT_COMMENT                     106
#define IDD_RECHERCHESTATUS             107
#define IDT_GROUPTEXT                   109
#define IDS_DQLEXTENSION                110
#define IDS_DQLFILTERSPEC               111
#define IDS_NOCOMMENT                   112
#define IDS_DQLSUBDIRECT                113
#define IDS_DUMMY                       114
#define IDS_SCRIPTKEY                   115
#define IDS_PFADSECTION                 116
#define IDS_OBJLISTCAPTION              120
#define IDS_DBASESECTION                121
#define IDS_COMMENT                     130
#define IDB_UNIQUEKEY                   131
#define IDB_ENTRYEXPR                   132
#define IDR_LIST                        133
#define IDR_CLASSIFY                    134
#define IDE_COMMENT                     135
#define IDB_HELP                        137
#define IDB_MODIFY                      138
#define IDT_DBASEDATEI                  139
#define IDB_SELECTFILE                  140
#define DATEI                           141
#define SCRIPT_TEMPLATE                 142
#define IDS_KEYFLAG                     143
#define IDS_GROUPLINE                   145
#define IDS_KEYLINE                     146
#define IDS_REPORTONLIST                147
#define IDS_REPORTONCLASS               148
#define IDC_EXPRESSIONLIST              149
#define IDS_EXPRLINE                    150
#define IDS_REPORTLINE                  151
#define IDS_CLIPOPTION                  152
#define IDS_EXPRSECTION                 153
#define IDS_EXPRENTRY                   154
#define IDS_UNBENANNT                   155
#define IDS_ERRORCAPTION                156
#define IDS_SYNTAXERROR                 157
#define IDS_DBASESPEC                   158
#define IDS_KEINEDATEI                  159
#define IDS_ALIASSECTION                161
#define IDS_INIEXTENSION                162
#define IDD_ALIASSELECT                 163
#define IDL_ALIASSELECT                 164
#define IDB_OKALIASSELECT               165
#define IDB_ABBRALIASSELECT             166
#define IDS_GEN_ERROR                   166
#define IDB_HELPALIASSELECT             167
#define IDD_STANDSCRIPT                 168
#define IDG_EXPORTSTATUS                169
#define IDB_CONNECTEXPR                 170
#define IDS_REDKEYLINE                  171
#define KE_RECHERCHE                    499
#define KE_READY                        500
#define KE_START                        501
#define KE_PARSE                        502
#define KE_PARAM                        503
#define KE_CLOSE                        504
#define KE_READY_NOW                    505
#define EDIT_CLOSE                      506
#define EDIT_SENT_HANDLE                507
#define EDIT_GET_HANDLE                 508
#define KE_GET_HANDLE                   509
#define KE_SENT_HANDLE                  510
#define EDIT_CAN                        511
#define KE_SENT_VERSION                 512
#define EDIT_GET_VERSION                513
#define IDS_LONGCLASSNAME               1184

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        101
#define _APS_NEXT_COMMAND_VALUE         101
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           110
#endif
#endif
